### ISSUE TITLE
Fail to load module script:Expected a JavaScript module script but the server responded with a MIME type of "text/plain".Strict MIME type checking is enforced for module script per HTML spec.

### ISSUE THREAD

**Issue by caesarding07** [caddyserver/caddy#4734] opened 2022-04-27 10:33 UTC
Windows 11
Node  v16.14.2
Vue 3.2.25
Vite 2.9.5
---
while I use the caddy to get my static file up and just run the HelloWorld, it catches an error that is like this
```
Fail to load module script:Expected a JavaScript module script but the server responded with a MIME type of "text/plain".Strict MIME type checking is enforced for module script per HTML spec.
```
what's more, I also try it with Nginx, and it run ok.

**Comment by mohammed90** [comment] 2022-04-27 10:44
Thank you for the report/question! Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by caesarding07** [comment] 2022-04-27 11:30
## 1. Environment

### 1a. Operating system and version

```
Windows 11  22H2 22598.1
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
v2.4.6 h1:HGkGICFGvyrodcqOOclHKfvJC0qTU7vny/7FhYp9hNw=
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)
After I run `caddy file-server`,the browser catch a error like this:
```
Fail to load module script:Expected a JavaScript module script but the server responded with a MIME type of "text/plain".Strict MIME type checking is enforced for module script per HTML spec
```

### 2b. Why it's a bug (if it's not obvious)
it can run ok if i use nginx。



### 2c. Log output

 nothing terminal output or logs here

### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)

I see the js Content-Type  is text/plain while text/javascript is right.

**Comment by francislavoie** [comment] 2022-04-27 13:00
You didn't give us the information we need.

What file are you trying to serve? Give an example request with `curl -v` and its output.

**Comment by caesarding07** [comment] 2022-04-27 13:03
I have solve it. I add `header /*.js Content-Type text/javascript` into the Caddyfile.
However,I still think it is a bug of caddy. Because I can get it up on my Mac normally while catch error on the windows.😁😁😁
The Last but not least, I'm so sorry that you may not understand what i taking about because of my poor Engish.

**Comment by francislavoie** [comment] 2022-04-27 13:07
We have no evidence of a bug. This works fine for us.

It's probably a misconfiguration in your environment. Go pulls mime type mappings from the operating system, so if it's not correctly set on your system, then it won't serve the right content type.

I'm guessing you might be running into this: https://github.com/golang/go/issues/32350, there's an old workaround repo: https://github.com/zekroTJA/go-win-mime-fix

**Closed by francislavoie** 2022-04-27 13:08 UTC
Labels: needs info

**Comment by caesarding07** [comment] 2022-04-27 13:12
> 
Sorry, I just want to use caddy serve the Vue template which is built by  Vite.It's a HelloWorld. I would show you the photo if you 
dont understand me.

This is the error the browse catch!
![](https://cdn.jsdelivr.net/gh/caesarding07/images/picgo20220427210740.png)

This is the page I what to serve!
![](https://cdn.jsdelivr.net/gh/caesarding07/images/picgo20220427210850.png)

By the way, I can serve the page correctlly on my Mac.

**Comment by caesarding07** [comment] 2022-04-27 13:13
> Go pulls mime type mappings from the operating system, so if it's not correctly set on your system, then it won't serve the right content type.

Maybe you are right,I havent install the go on my Windows.I will tyr it! Thank you so much!💕💕💕💕

**Comment by francislavoie** [comment] 2022-04-27 13:41
This does not have to do with installing Go on your Windows machine.

Caddy is written with Go, and it uses Go's stdlib mime-types implementation.

If your Windows machine isn't correctly configured to map `*.js` to `text/javascript`, then Caddy won't serve that mime type.
