### ISSUE TITLE
caddy tls client_auth domain supported, ip not?

### ISSUE THREAD

**Issue by Orefa** [caddyserver/caddy#5771] opened 2023-08-21 00:46 UTC
## IP configuration is incorrect
Caddyfile
```
{
    #default_sni 127.0.0.1
    servers {
        strict_sni_host insecure_off
    }
}

127.0.0.1 {
  tls internal {
    client_auth {
      mode require_and_verify
      trusted_ca_cert_file root.crt
    }
  }
  handle_path / {
    respond "{http.request.tls.client.serial}"
  }
}
```
```cmd
E:\caddytest>curl --cert hxf.p12 -k --pass password https://127.0.0.1/
{http.request.tls.client.serial}
```
## Domain configuration is correct

Caddyfile

```
{
    #default_sni 127.0.0.1
    servers {
		strict_sni_host insecure_off
	}
}

localhost {
  tls internal {
    client_auth {
      mode require_and_verify
      trusted_ca_cert_file root.crt
    }
  }
  handle_path / {
    respond "{http.request.tls.client.serial}"
  }
}
```
```
E:\caddytest>curl --cert hxf.p12 -k --pass password https://localhost/
96050935782879187808286284401262872399223282886
```

## It is also incorrect if default_sni is configured

```
{
    default_sni 127.0.0.1
    servers {
        strict_sni_host insecure_off
    }
}

127.0.0.1 {
  tls internal {
    client_auth {
      mode require_and_verify
      trusted_ca_cert_file root.crt
    }
  }
  handle_path / {
    respond "{http.request.tls.client.serial}"
  }
}
192.168.1.100 {
  handle_path / {
    respond "{http.request.tls.client.serial}"
  }
}
```
correct:

```
E:\caddytest>curl --cert client.p12 -k --pass password https://127.0.0.1/
96050935782879187808286284401262872399223282886
```

incorrect:

```
E:\caddytest>curl  -k --pass password https://192.168.1.100/
curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_CERT_UNKNOWN (0x80090327) - 处理证书时，出现了一个未知错误。
```

Why does 192.168.1.100 require a client certificate?

```
E:\caddytest>curl --cert client.p12 -k --pass password https://192.168.1.100/
96050935782879187808286284401262872399223282886
```

**Comment by francislavoie** [comment] 2023-08-21 01:23
Thanks for opening an issue! We'll look into this.

It's not immediately clear to us what is going on, so we'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by mholt** [comment] 2023-09-07 23:09
I'm just now seeing that the original post was edited with more details (edits don't trigger notifications). I'll take a look at this soon.

**Comment by mohammed90** [comment] 2024-01-28 20:11
Hi, @Orefa! Can you please share more details per the template? It's hard to decipher your post. Please ensure you enable [`debug` mode](https://caddyserver.com/docs/caddyfile/options#debug) for more details in the logs.

**Comment by Orefa** [comment] 2024-01-29 00:00
test file:  https://github.com/Orefa/Caddybug

Compile the (any) latest version of caddy
> My system is Windows 10.
```
caddy run
```
access：https://10.15.105.123/ It is normal for this access to ask for credentials,

access: https://127.0.0.1/ 
Why would you ask for a certificate?  `tls: client didn't provide a certificate`

console:
```
2024/01/28 23:32:59.104 DEBUG   events  event   {"name": "tls_get_certificate", "id": "126cc591-95c7-4a10-b66f-5a1a971e1502", "origin": "tls", "data": {"client_hello":{"CipherSuites":[2570,4865,4866,4867,49195,49199,49196,49200,52393,52392,49171,49172,156,157,47,53],"ServerName":"","SupportedCurves":[27242,29,23,24],"SupportedPoints":"AA==","SignatureSchemes":[1027,2052,1025,1283,2053,1281,2054,1537],"SupportedProtos":["h2","http/1.1"],"SupportedVersions":[51914,772,771],"RemoteAddr":{"IP":"127.0.0.1","Port":35095,"Zone":""},"LocalAddr":{"IP":"127.0.0.1","Port":443,"Zone":""}}}}
2024/01/28 23:32:59.104 DEBUG   tls.handshake   choosing certificate    {"identifier": "127.0.0.1", "num_choices": 1}
2024/01/28 23:32:59.105 DEBUG   tls.handshake   default certificate selection results   {"identifier": "127.0.0.1", "subjects": ["127.0.0.1"], "managed": true, "issuer_key": "local", "hash": "a8602983c58c5ac1fd3190a0d4e051570513ea771896dd086b1a37b8fd86171f"}
2024/01/28 23:32:59.105 DEBUG   tls.handshake   matched certificate in cache    {"remote_ip": "127.0.0.1", "remote_port": "35095", "subjects": ["127.0.0.1"], "managed": true, "expiration": "2024/01/29 11:24:13.000", "hash": "a8602983c58c5ac1fd3190a0d4e051570513ea771896dd086b1a37b8fd86171f"}
2024/01/28 23:32:59.109 DEBUG   http.stdlib     http: TLS handshake error from 127.0.0.1:35095: EOF
2024/01/28 23:32:59.116 DEBUG   events  event   {"name": "tls_get_certificate", "id": "137d4124-60da-4b7e-9f37-0cd2ecb3d3e1", "origin": "tls", "data": {"client_hello":{"CipherSuites":[39578,4865,4866,4867,49195,49199,49196,49200,52393,52392,49171,49172,156,157,47,53],"ServerName":"","SupportedCurves":[31354,29,23,24],"SupportedPoints":"AA==","SignatureSchemes":[1027,2052,1025,1283,2053,1281,2054,1537],"SupportedProtos":["h2","http/1.1"],"SupportedVersions":[2570,772,771],"RemoteAddr":{"IP":"127.0.0.1","Port":35096,"Zone":""},"LocalAddr":{"IP":"127.0.0.1","Port":443,"Zone":""}}}}
2024/01/28 23:32:59.117 DEBUG   tls.handshake   choosing certificate    {"identifier": "127.0.0.1", "num_choices": 1}
2024/01/28 23:32:59.118 DEBUG   tls.handshake   default certificate selection results   {"identifier": "127.0.0.1", "subjects": ["127.0.0.1"], "managed": true, "issuer_key": "local", "hash": "a8602983c58c5ac1fd3190a0d4e051570513ea771896dd086b1a37b8fd86171f"}
2024/01/28 23:32:59.118 DEBUG   tls.handshake   matched certificate in cache    {"remote_ip": "127.0.0.1", "remote_port": "35096", "subjects": ["127.0.0.1"], "managed": true, "expiration": "2024/01/29 11:24:13.000", "hash": "a8602983c58c5ac1fd3190a0d4e051570513ea771896dd086b1a37b8fd86171f"}
2024/01/28 23:32:59.120 DEBUG   http.stdlib     http: TLS handshake error from 127.0.0.1:35096: EOF
2024/01/28 23:32:59.128 DEBUG   events  event   {"name": "tls_get_certificate", "id": "00db511a-5f1e-4adc-980c-9627da7b1cd8", "origin": "tls", "data": {"client_hello":{"CipherSuites":[14906,4865,4866,4867,49195,49199,49196,49200,52393,52392,49171,49172,156,157,47,53],"ServerName":"","SupportedCurves":[35466,29,23,24],"SupportedPoints":"AA==","SignatureSchemes":[1027,2052,1025,1283,2053,1281,2054,1537],"SupportedProtos":["h2","http/1.1"],"SupportedVersions":[6682,772,771],"RemoteAddr":{"IP":"127.0.0.1","Port":35097,"Zone":""},"LocalAddr":{"IP":"127.0.0.1","Port":443,"Zone":""}}}}
2024/01/28 23:32:59.128 DEBUG   tls.handshake   choosing certificate    {"identifier": "127.0.0.1", "num_choices": 1}
2024/01/28 23:32:59.129 DEBUG   tls.handshake   default certificate selection results   {"identifier": "127.0.0.1", "subjects": ["127.0.0.1"], "managed": true, "issuer_key": "local", "hash": "a8602983c58c5ac1fd3190a0d4e051570513ea771896dd086b1a37b8fd86171f"}
2024/01/28 23:32:59.129 DEBUG   tls.handshake   matched certificate in cache    {"remote_ip": "127.0.0.1", "remote_port": "35097", "subjects": ["127.0.0.1"], "managed": true, "expiration": "2024/01/29 11:24:13.000", "hash": "a8602983c58c5ac1fd3190a0d4e051570513ea771896dd086b1a37b8fd86171f"}
2024/01/28 23:32:59.131 DEBUG   http.stdlib     http: TLS handshake error from 127.0.0.1:35097: tls: client didn't provide a certificate
2024/01/28 23:33:00.157 DEBUG   events  event   {"name": "tls_get_certificate", "id": "f565cef1-3e4b-4ee9-bb37-1e8f333d75f9", "origin": "tls", "data": {"client_hello":{"CipherSuites":[31354,4865,4866,4867,49195,49199,49196,49200,52393,52392,49171,49172,156,157,47,53],"ServerName":"","SupportedCurves":[64250,29,23,24],"SupportedPoints":"AA==","SignatureSchemes":[1027,2052,1025,1283,2053,1281,2054,1537],"SupportedProtos":["h2","http/1.1"],"SupportedVersions":[10794,772,771],"RemoteAddr":{"IP":"127.0.0.1","Port":35098,"Zone":""},"LocalAddr":{"IP":"127.0.0.1","Port":443,"Zone":""}}}}
2024/01/28 23:33:00.157 DEBUG   tls.handshake   choosing certificate    {"identifier": "127.0.0.1", "num_choices": 1}
2024/01/28 23:33:00.158 DEBUG   tls.handshake   default certificate selection results   {"identifier": "127.0.0.1", "subjects": ["127.0.0.1"], "managed": true, "issuer_key": "local", "hash": "a8602983c58c5ac1fd3190a0d4e051570513ea771896dd086b1a37b8fd86171f"}
2024/01/28 23:33:00.165 DEBUG   tls.handshake   matched certificate in cache    {"remote_ip": "127.0.0.1", "remote_port": "35098", "subjects": ["127.0.0.1"], "managed": true, "expiration": "2024/01/29 11:24:13.000", "hash": "a8602983c58c5ac1fd3190a0d4e051570513ea771896dd086b1a37b8fd86171f"}
2024/01/28 23:33:00.172 DEBUG   http.stdlib     http: TLS handshake error from 127.0.0.1:35098: tls: client didn't provide a certificate
```

**Comment by mohammed90** [comment] 2024-01-30 09:16
I understand your issue. The default check for when to check for client authentication is based on the SNI. The SNI is not sent by clients on connections with IP addresses, even if the connection is on HTTPS. This is per the [protocol spec](https://datatracker.ietf.org/doc/html/rfc6066#section-3).

>    Literal IPv4 and IPv6 addresses are not permitted in "HostName".

This is why it works when you used a domain name (SNI is sent), and that's why it requests for certificate on the other IP address when you used `default_sni` (caddy assumes the default SNI because it's not in available in the request). 

The solution could be tricky. Here are the options I'm thinking of:
- Simplest: use domain names instead
- Medium: Switch to JSON config, configure different `listen` addresses (which have to be specific), and configure different `default_sni` for each server.

There's a discussion to add `local_ip` as connection policy matcher (#6074), which might help with your use case. However, this use case is very atypical, which is why we didn't include it at first and why nobody else has ever requested it before. Why are you using IP addresses instead of domain names? What's the use case? What's your setup?

**Comment by Orefa** [comment] 2024-01-30 23:43
Through the domain names is no problem, switch to json configuration has a little complexity, the service is published in the LAN, not configured DNS, some clients can not modify the host file, also can not modify the local dns configuration. :joy:

**Comment by mholt** [comment] 2024-04-15 17:14
Thanks for looking into this Mohammed. I think I'm now up to speed with your assessment.

I'd be interested in pursuing your PR #6074 and maybe making the Caddyfile smart enough to use it when an IP is used as the site address. :thinking: I'm not sure that needs to go in 2.8 since we need to be careful with this enhancement but since IPs aren't in the ServerName, there's definitely some improvements we could make.

**Comment by mohammed90** [comment] 2024-04-15 18:02
> maybe making the Caddyfile smart enough to use it when an IP is used as the site address. 🤔 I'm not sure that needs to go in 2.8 since we need to be careful with this enhancement but since IPs aren't in the ServerName

Yeah, let's keep this extra-smarty part for later 😄

**Comment by mholt** [comment] 2024-04-17 18:35
With the `local_ip` matcher now merged, I think the TLS connection policy can now be used when configured with JSON.

To enable this with the Caddyfile, the Caddyfile adapter has to be smart enough to know to use that matcher instead of the `sni` matcher. The code here could be updated:

https://github.com/caddyserver/caddy/blob/3efda6fb3a0622cfb591f3ff904c37f171f6fe89/caddyconfig/httpcaddyfile/httptype.go#L696-L700

Instead of using `sni` for all the hostnames, filter out the IPs and put them in the `local_ip` matcher, and the domains in `sni`.

Pull requests welcomed!

**Closed by mholt** 2024-04-17 18:35 UTC
Labels: help wanted :sos:, feature :gear:
