### ISSUE TITLE
{ and } Stripped From Request Path

### ISSUE THREAD

**Issue by 0xbzho** [caddyserver/caddy#4027] opened 2021-02-17 17:49 UTC
If I issue a GET with a path of `/foo%7Bbar%7Dglark` Caddy sees it as `/fooglark`. This means that when using the file_server module, requests for files with these characters in the path fail. It works fine on Nginx for the same document root.

Sample log:

`{"level":"debug","ts":1613583834.7168345,"logger":"http.handlers.file_server","msg":"sanitized path join","site_root":"/data/redacted/static/current/","request_path":"/fooglark","result":"/data/redacted/static/current/fooglark"}`

for

`curl "https://redacted/foo%7Bbar%7Dglark"`.

**Comment by mholt** [comment] 2021-02-17 18:31
Thanks for opening an issue! We'll look into this.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Instructions -- please heed otherwise we cannot help you (help us help you!)

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by 0xbzho** [comment] 2021-02-17 20:23
## 1. Environment

### 1a. Operating system and version

Debian testing. 

### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
v2.3.0 h1:fnrqJLa3G5vfxcxmOH/+kJOcunPLhSBnjgIvjXV/QTA=
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
go1.16rc1 linux/amd64
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)

Text between curly braces, i.e. { and }, is stripped, along with the braces from the request path before the file_server module sees it. Accordingly, valid URLs are 404.

### 2b. Why it's a bug (if it's not obvious)

These characters are valid in a filename and, when URLencoded, valid in a URL.

### 2c. Log output

When running file_server as a module with debug enabled:

```
{"level":"debug","ts":1613583834.7168345,"logger":"http.handlers.file_server","msg":"sanitized path join","site_root":"/data/redacted/static/current/","request_path":"/fooglark","result":"/data/redacted/static/current/fooglark"} 
```

When recreating the bug using `caddy file-server`:

```
2021/02/17 20:12:20.412	ERROR	http.log.access	handled request	{"request": {"remote_addr": "127.0.0.1:43716", "proto": "HTTP/1.1", "method": "GET", "host": "127.0.0.1", "uri": "/two%7Bcurly%7Dbraces", "headers": {"User-Agent": ["curl/7.74.0"], "Accept": ["*/*"]}}, "common_log": "127.0.0.1 - - [17/Feb/2021:20:12:20 +0000] \"GET /two%7Bcurly%7Dbraces HTTP/1.1\" 404 0", "duration": 0.000435343, "size": 0, "status": 404, "resp_headers": {"Server": ["Caddy"]}}
```

### 2d. Workaround(s)

Rename the files, I guess. Ideally, Caddy wouldn't butcher the request path.

## 3. Tutorial (minimal steps to reproduce the bug)

```
$ cd /tmp
$ mkdir dir
$ echo foo > dir/two{curly}braces
$ echo foo > dir/twocurlybraces
$ echo foo > dir/two{curlybraces
$ echo foo > dir/twocurly}braces
$ ./caddy_linux_amd64 file-server -access-log -root /tmp/dir
# In another terminal:
$ curl --verbose http://127.0.0.1/twocurlybraces
*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET /twocurlybraces HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 4
< Etag: "qoow404"
< Last-Modified: Wed, 17 Feb 2021 20:12:00 GMT
< Server: Caddy
< Date: Wed, 17 Feb 2021 20:12:57 GMT
< 
foo
* Connection #0 to host 127.0.0.1 left intact
* 
$ curl --verbose http://127.0.0.1/two%7Bcurlybraces
*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET /two%7Bcurlybraces HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 4
< Etag: "qoow444"
< Last-Modified: Wed, 17 Feb 2021 20:12:04 GMT
< Server: Caddy
< Date: Wed, 17 Feb 2021 20:12:24 GMT
< 
foo
* Connection #0 to host 127.0.0.1 left intact

$ curl --verbose http://127.0.0.1/twocurly%7Dbraces
*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET /twocurly%7Dbraces HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 4
< Etag: "qoow8l4"
< Last-Modified: Wed, 17 Feb 2021 20:14:45 GMT
< Server: Caddy
< Date: Wed, 17 Feb 2021 20:14:58 GMT
< 
foo
* Connection #0 to host 127.0.0.1 left intact

$ curl --verbose http://127.0.0.1/two%7Bcurly%7Dbraces
*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET /two%7Bcurly%7Dbraces HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Server: Caddy
< Date: Wed, 17 Feb 2021 20:13:40 GMT
< Content-Length: 0
< 
* Connection #0 to host 127.0.0.1 left intact
```

The 404 has the log:

```
2021/02/17 20:12:20.412	ERROR	http.log.access	handled request	{"request": {"remote_addr": "127.0.0.1:43716", "proto": "HTTP/1.1", "method": "GET", "host": "127.0.0.1", "uri": "/two%7Bcurly%7Dbraces", "headers": {"User-Agent": ["curl/7.74.0"], "Accept": ["*/*"]}}, "common_log": "127.0.0.1 - - [17/Feb/2021:20:12:20 +0000] \"GET /two%7Bcurly%7Dbraces HTTP/1.1\" 404 0", "duration": 0.000435343, "size": 0, "status": 404, "resp_headers": {"Server": ["Caddy"]}}
```

**Comment by francislavoie** [comment] 2021-02-18 01:02
It might be possible that this was fixed by https://github.com/caddyserver/caddy/commit/88a38bd00d386457aec71696a386449d3bcf8990. Could you try v2.4.0-beta.1 to verify? Thanks!

**Comment by 0xbzho** [comment] 2021-02-18 01:42
Unfortunately, not. Using v2.4.0-beta.1 h1:Ed/tIaN3p6z8M3pEiXWJL/T8JmCqV62FrSJCHKquW/I= I see the same results as previously.

**Comment by rozekey** [comment] 2021-02-18 20:38
> If I issue a GET with a path of `/foo%7Bbar%7Dglark` Caddy sees it as `/fooglark`. This means that when using the file_server module, requests for files with these characters in the path fail. It works fine on Nginx for the same document root.
> 
> Sample log:
> 
> `{"level":"debug","ts":1613583834.7168345,"logger":"http.handlers.file_server","msg":"sanitized path join","site_root":"/data/redacted/static/current/","request_path":"/fooglark","result":"/data/redacted/static/current/fooglark"}`
> 
> for
> 
> `curl "https://redacted/foo%7Bbar%7Dglark"`.

**Comment by francislavoie** [comment] 2021-02-28 20:40
I'm pretty sure the fix would be to use `ReplaceKnown` instead here:

https://github.com/caddyserver/caddy/blob/ec309c6d52fdfce0431a1303a49f28c3f546176a/modules/caddyhttp/fileserver/staticfiles.go#L141

@mholt what usecase is there for running the replacer on the request path anyways? I can't think of a good reason for running replacers on request inputs.

**Comment by mholt** [comment] 2021-03-01 16:49
@francislavoie ... That is a good point. I am not sure why I put that in there. We can probably just remove that line!

**Comment by mholt** [comment] 2021-03-01 20:49
@0xbzho Thanks so much for the great tutorial to reproduce the bug, and @francislavoie for the idea. Took only about 3 mintues to reproduce and fix. Wish more bug reports were this helpful. :)

**Closed** 2021-03-01 20:49 UTC
Labels: bug
