### ISSUE TITLE
http.request.tls.client.* placeholder broken for Caddy 2.6.3+

### ISSUE THREAD

**Issue by desirevolution** [caddyserver/caddy#5551] opened 2023-05-22 18:53 UTC
Let me first say thanks for this  awesome product !  The bug I am about  to "complain" is rather a first world problem^^

I am using following matcher to decide whenever I am on a "safe" client (with installed client certificate) or some "public" machine (fallback to Authelia):

```
        @missing_mTLS_cert {
                expression {tls_client_subject} == null
        }
        
        forward_auth @missing_mTLS_cert ... {
                ....
        }        
```

Everything was working fine until 2.6.3 .. Starting from this version it become unstable.. Now even with a valid certificate it randomly fails (placeholder not set (?)). forcing me to login with Authelia ...

Thanks!

**Comment by mholt** [comment] 2023-05-22 19:40
Thanks for opening an issue! We'll look into this.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Instructions -- please heed otherwise we cannot help you (help us help you!)

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222) Please enable debug and access logs.
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by francislavoie** [comment] 2023-05-22 21:38
Please try v2.7.0-beta.1, we've made a lot of changes since 2.6.4, some of which may have already fixed it.

**Comment by desirevolution** [comment] 2023-05-23 07:51
Unfortunately v2.7.0-beta-1 is behaving the same way ... But I succeeded to fix my problem just by disabling HTTP/3 protocol. Maybe this gives you a more specific hint regarding the problem?

@mholt besides Caddy specific data... would you also need a test client certificate as part of the report ? (I can't provide you with my private one ...) 

Thanks anyway for your support!

**Comment by mholt** [comment] 2023-05-23 14:25
Huh, that's interesting. Apparently this is NOT null then, when it should be? https://github.com/caddyserver/caddy/blob/cee4441cb1d485b38d728168a315cda5641d84fb/modules/caddyhttp/replacer.go#LL428C17-L428C17

I don't think there's any need to send me your private key :grimacing: But when I get a chance I'll try to reproduce this. Or if someone beats me to it, that'd be faster probably :)

**Comment by francislavoie** [comment] 2023-05-23 20:54
Looking at the diff between 2.6.2 and 2.6.3, I don't see what could have possibly broken it. See https://github.com/caddyserver/caddy/compare/v2.6.2...v2.6.3

**Comment by desirevolution** [comment] 2023-05-24 10:18
My config (simplified):
```
{
        auto_https off
        https_port 443
        servers :443 {
                protocols h1 h2 h3
        }
}

(log_setup) {
        log {
                output stdout
                format json
                level DEBUG
        }
}


(missing_mTLS_cert) {
        @missing_mTLS_cert {
                expression {tls_client_subject} == null
        }
}

(ssl_setup) {
        import missing_mTLS_cert
        tls ./fullchain.cer ./server.key {
                alpn http/1.1
                client_auth {
                        mode verify_if_given
                        trusted_ca_cert_file ./client.crt
                }
        }
        forward_auth @missing_mTLS_cert 192.168.0.60:9091 {
                uri /api/verify?rd=https://authelia.server
                copy_headers Remote-User Remote-Groups Remote-Name Remote-Email
        }
        encode gzip
}

authelia.server {
        reverse_proxy 192.168.60.60:9091
}

server:443 {
        import log_setup
        import ssl_setup
        header subject {http.request.tls.client.subject}
        header issuer {http.request.tls.client.issuer}
        reverse_proxy http://192.168.0.60:1234
}
```
I was testing it against some simple website.
First request returns the headers correctly (probably because its still http1.1?) but afterwards with http3 requests i only see  placeholder strings "{http.request.tls.client....}" returned.

**Comment by mholt** [comment] 2023-05-25 20:51
Is `header subject {http.request.tls.client.subject}` broken as well as `expression {tls_client_subject} == null` ? If so, then I would definitely double-check to verify that the client is or is not, in fact, providing a client certificate. If the client doesn't provide a certificate then those fields won't be replaced, and your expression would evaluate to true.

(Maybe that's a bug. What do you think @francislavoie  -- should those placeholders always be "recognized" even when the client doesn't provide a cert?)

**Comment by francislavoie** [comment] 2023-05-25 21:06
> but afterwards with http3 requests i only see placeholder strings "{http.request.tls.client....}" returned.

Hmm. So you're saying it seems broken for H3 requests but it works fine for H1/H2? Okay. Are you sure it worked with H3 with prior versions? I'm trying to understand what you're actually describing as broken and when.

**Comment by desirevolution** [comment] 2023-05-26 04:49
@francislavoie You are right! I don't see any http3 requests when testing with 2.6.2.

![2 6 2](https://github.com/caddyserver/caddy/assets/128931875/37c25492-95f1-4764-8cf3-c279207546a2)

The behavior changed with 2.6.3+

![2 7 0 b](https://github.com/caddyserver/caddy/assets/128931875/0ee08521-6fb9-438f-96e6-8a645665f4bb)
(302 is the Authelia redirection)

**Comment by desirevolution** [comment] 2023-05-26 05:16
One more ..  After changing "mode verify_if_given" to "mode require_and_verify"  for 2.6.3+ 
![2 7 0 b_require](https://github.com/caddyserver/caddy/assets/128931875/f16985cc-d688-4d34-87bb-8006c21ba58d)
(both headers are always set in response)

**Comment by mholt** [comment] 2023-05-26 14:57
So maybe the client is only sending it if required?

Can you use a different, simpler client (like `curl`) to verify this behavior?

(Sorry I still haven't gotten around to reproducing it on my machine. Been busy...)

**Comment by desirevolution** [comment] 2023-05-28 05:56
Sorry for the delayed response. And yes,  I can reproduce it with curl:

`curl --cert ....  https://server --next  https://server`

First call works as expected, second one produces the described effect.

**Comment by mholt** [comment] 2023-05-28 18:44
Thanks!

> First call works as expected, second one produces the described effect.

As in, you run the command twice, and the problem only manifests the second time?

**Comment by desirevolution** [comment] 2023-05-29 06:36
sorry, wrong wording from my side .. I was using "--next" to simulate the behavior I observed while testing it with the browser.  Curl is sending the GET request twice but without closing/reopening the connection between the calls.

**Comment by francislavoie** [comment] 2023-05-29 07:05
I see... so it sounds like the TLS connection state isn't carried over to the next request for some reason. :thinking:

Please turn on the `debug` global option in your Caddyfile, and make sure to enable the `log` directive in the relevant site (for access logs), then make those two requests again. What do you see in the logs?

**Comment by francislavoie** [comment] 2023-06-18 16:03
@desirevolution we still need some more information here to be sure about what course of action to take to solve this issue.

**Comment by henryreed** [comment] 2023-07-30 01:20
ALCON,

I am having the same issue where Caddy v2.6.4 only sometimes passes the client certificate to the backend server (in my case, Keycloak, but it shouldn't matter whether it's Keycloak, Authelia, or Authentik). Note that this issue only occurs if H3 is enabled _and_ `verify_if_given` is used. If `require_and_verify` is used, this issue doesn't occur. Below is my Caddyfile

```
{
    log {
        level debug
    }
    servers {
        protocols h1 h2 h3
    }
}

(client_auth) {
    tls {
        client_auth {
            mode verify_if_given
            trusted_ca_cert_file /certs/ca/root_ca.crt
            trusted_ca_cert_file /certs/ca/intermediate_ca.crt
        }
    }
}

keycloak.secure.local {
    import client_auth
    reverse_proxy 127.0.0.1:8080 {
        header_up SSL_CLIENT_CERT {http.request.tls.client.certificate_pem}
    }
}
```

Attached [here](https://github.com/caddyserver/caddy/files/12208326/Caddy.Sanitized.Log) is my debug log. Note that I removed the following from the logs, do let me know if it is an issue:

1. The client certificate itself has been removed. All instances that contain certificate data have been replaced with "[CERT_DATA]"
2. Any references to the server certificate. I can't release this at this time, but if it's required I'll stand up a separate environment with releasable server certificate data.

Another difference is I cannot recreate the issue with curl. It seems to only occur with browsers (Firefox, Chrome) and only _sometimes_. I know this is unhelpful. I will also try the latest alpha version, as well, and comment here.

**Comment by mholt** [comment] 2023-07-30 03:50
@henryreed The behavior you're describing sounds like quirks in browsers, which aren't uncommon especially when it comes to HTTP/3. They do weird things with connections and caches and such. I'm glad you tried it with curl, I think that goes to show the browsers are doing something funky.

**Comment by henryreed** [comment] 2023-07-30 05:28
@mholt Do you think the issue potential issue with go-quik that @francislavoie mentioned above has anything to do with this? If so, I am willing to test more, and maybe even work on a set of docker-compose files complete with certificate generation and so on for you all to test with. Obviously, doing this would cut into my free time, so if you think that's highly unlikely and it's a browser specific problem unassociated with Caddy, then I'd say it's fair to close the issue as won't fix or unapplicable.

**Comment by mholt** [comment] 2023-07-31 20:30
@henryreed I'm not sure tbh. I keep coming back to it working with curl. So if it works with curl, which doesn't do any fancy tricks, it sounds like a fancy trick has a bug in the browser. Just my $0.02. It's up to you how you want to spend your time: if you really want the cause narrowed down, it might be worth the time to see if it's a bug in Caddy or a dependency, versus a browser. Either way, you could make progress and if it's a bug in a browser, you can report it to the browser. If it's a bug in a Caddy dependency, you can report it to the dependency. Or if it's a bug in our code we can fix it :)

**Comment by henryreed** [comment] 2023-08-01 15:15
@mholt  I was able to recreate the issue with curl. Attached [here](https://github.com/caddyserver/caddy/files/12231223/Caddy_Sanitized_2.log) are the logs (sanitized in the same way as before). Here is the curl command:

```
curl --cert test-user.crt --key test-user.key https://keycloak.secure.local --next https://keycloak.secure.local/admin/
```

My Caddyfile is identical as in my previous message. Let me know how I can help you find the root cause for this bug.

**Comment by henryreed** [comment] 2023-08-01 16:20
I just tested this with 2.7.0-beta.2. The issue now occurs even if HTTP3 is disabled. Attached [here](https://github.com/caddyserver/caddy/files/12231823/Caddy_Sanitized_3.log) are the logs, sanitized in the same way as before, for 2.7.0-beta.2. The curl command is identical to the command above.

**Comment by mholt** [comment] 2023-08-01 17:55
Thanks for digging further -- I'll look into it soon; maybe after 2.7 release.

**Comment by mholt** [comment] 2023-08-03 19:09
@henryreed I made some time to generate a root, sign a cert, and use them with your config to try to reproduce the issue.

A self-contained config based on yours:

```
{
	log {
		level debug
	}
}

(client_auth) {
	tls {
		client_auth {
			mode verify_if_given
			trusted_ca_cert_file /home/matt/Downloads/rootCACert.pem
		}
	}
}

localhost {
	import client_auth
	reverse_proxy 127.0.0.1:8080 {
		header_up SSL_CLIENT_CERT {http.request.tls.client.certificate_der_base64}
	}
}

:8080 {
	respond "Client cert: {header.SSL_CLIENT_CERT}"
}
```

Notice that I've changed the placeholder to `{http.request.tls.client.certificate_der_base64}` to get a value valid for headers. I also removed the `protocols` line because that is the default value anyway.

Then running your curl command:

```
$ curl --cert cert.crt --key cert.key https://localhost --next https://localhost
Client cert: MIIDETCCAfkCFF5asgeh9Umey6UFLdeqLOCjvqHCMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwHhcNMjMwODAzMTkwMTUyWhcNMjQxMjE1MTkwMTUyWjBFMQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3c20iN8fZt3eBn+ILESOTJow/CaQU5FP689x0+w4GALxlMrLBpsHVoT1VO/z3MYRtuVbSuCJO+IMoA6ySXijDMdkVGkoUkhlTuBjLJso2pxT1dSs/bII0L4IhhfFNniDcI7Zji6GtCyR1RlBD4z+C/Wzskmzmcq1C7AoFeLCoovGtjIuUFhz9P145b3U4M4q4ysCKZ8XNS4sfT0rulet+2NGHBc7+6WznCjAP3lkv/3sw9npiFyW2Kw55DlDYZH/Juq7tkibgGS+ShWKLQdVP3zbQ6eY/7o0yi4aC5pNtpI0zRsk8TDNmgc9n4640jfN+LT6ovduckTu2dh15cZGiQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQApGx6XdU+TGEyQyNaH4ylP3VPHG/kawOcA4Svxaw0kiwQlqR04fZkilh25ruS1whnWMNSNVZXAWu6dfk5t5LSse0B4t0hXfNHtTSEzBU8q84+EoLk1tkqjOyDkXCvAiQ2eNehtTZvgmFyDrrh3BVsBYlhHnBxaIQGxuj3V4nDyjs1PMAddeiNJReCjWKFgzccto6i8bNkXwl5RKR7LvMciDt9QXV7JEWZS4kxfCH0uSTJzQoAe0Ch+faCRBAH2Iz5WjbeHzAxFXCI5w22T1z3QRhOF+gMgYTJsx3FmXAD9SmhZcVzuEHZ+SeNlk/ik7C+OhE3+vYpsu/VZmYNQgUpRClient cert: {http.request.tls.client.certificate_der_base64}
```

This all looks as expected. The extra `Client cert: {http.request.tls.client.certificate_der_base64}` at the end is normal because of the `--next https://localhost` request which makes a second request without client auth.

**Comment by henryreed** [comment] 2023-08-04 17:49
> Notice that I've changed the placeholder to {http.request.tls.client.certificate_der_base64} to get a value valid for headers. 

Yeah long story, I used a mod by someone in a different issue to get around this since Caddy doesn't wrap certs in escape characters--it was unrelated to the issue so I didn't want to bog down my already-wordy paragraphs with extraneous details.

> The extra Client cert: {http.request.tls.client.certificate_der_base64} at the end is normal because of the --next https://localhost request which makes a second request without client auth.

This is a lack of an understanding of how curl processes the `--next` request on my side then.

Let's put a pin in this for now. I will do more testing on my side and see if I can recreate the issue I am having in the web browsers I tested with curl, instead. The workaround for now is to disable HTTP3, which allows users to successfully use require_and_verify. I will also see if this behavior occurs with other web servers (Nginx, Apache, etc.) to see if it's an issue that is only related to web browsers.

I think the issue should be left as open with needs info. I will update as soon as I can, likely after Hacker Summer Camp. Sorry for the delays on my end.

**Comment by danielmunoz** [comment] 2023-09-29 15:37
Dear all:

Thank you for this thread. For me, the issue is that I was using `{http.request.tls.client.certificate}` instead of `{http.request.tls.client.certificate_der_base64}`.

So thank you for your time, @mholt 

Greetings and best wishes!

**Comment by francislavoie** [comment] 2023-10-14 08:06
I'm not sure I understand what's broken here at this point. Is there anything actionable? :thinking:

**Comment by henryreed** [comment] 2023-10-31 03:59
Francis and Matt, my sincere apologies for ghosting you. I haven't had much breathing room the past few months.

I don't believe the issue has been fixed. Even if that base64 certificate option is used, the behavior should remain the same. Let me try to set some time aside to try to replicate this with `curl`, since browsers aren't supported. If anyone else wants to take a crack at it, please do.

**Comment by mholt** [comment] 2024-01-25 19:41
@henryreed No worries, I'm obviously woefully behind on my backlog as well.

Did you get a chance to try replicating with curl?

**Comment by henryreed** [comment] 2024-01-25 19:43
@mholt 

:( I have not. Let me try to work this sometime this week. Sorry again for the delay.

**Comment by mholt** [comment] 2024-01-25 20:05
No rush :)

**Comment by henryreed** [comment] 2024-01-27 09:27
Hi folks, I got very good progress and I am able to consistently replicate the issue with Curl and Caddy 2.7.6. Thanks to @francislavoie for linking to HTTP3 version of Curl in the thread [here](https://caddy.community/t/caddy-not-using-http3/19555/2). 

It seems the issue always occurs in HTTP3/QUIC. It does not occur over HTTP1 or HTTP2. Previously, I stated "[i]t seems to only occur with browsers (Firefox, Chrome) and only sometimes." This is false, wrong and absolute misinformation. The only reason why it occurs "sometimes" is because Firefox and Chrome tend to switch between HTTP2 and HTTP3 seemingly in a random fashion. I'm not quite sure what gets them to switch between the two, but I reckon that's out of scope of this issue.

I can confirm that this behavior is always consistent, given the variables below. 

Given the following Caddyfile:

```
{
    log {
        level debug
    }
}

(client_auth) {
    tls {
        dns cloudflare [SECRET REDACTED]
        client_auth {
            mode verify_if_given
            trusted_ca_cert_file /intermediate.crt
        }
    }
}

caddytest.homelab.memetichenry.com {
    import client_auth
    bind 10.12.180.18
    reverse_proxy 127.0.0.1:5000 {
        header_up tls-client-certificate {http.request.tls.client.certificate_der_base64}
        header_up soundness-check are-you-still-there
    }
}
```

and the following Docker Compose file:


```yml
services:
  caddy:
    build: Cloudflare_Caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:Z
      - ./certs/intermediate.crt:/intermediate.crt:Z
      - ./caddy_data:/data:Z
      - ./caddy_config:/config:Z
    network_mode: "host"
    restart: unless-stopped
```

Where "Cloudflare_Caddy" is simply Caddy with the official Cloudflare module, the following curl command:

```
curl -E ./client.crt --key ./client.key -vs -D/dev/stdout --http3 https://caddytest.homelab.memetichenry.com
```

Will always generate the following reverse proxy request, taken from the Caddy log:

```json
{
  "level": "debug",
  "ts": 1706345885.550976,
  "logger": "http.handlers.reverse_proxy",
  "msg": "upstream roundtrip",
  "upstream": "127.0.0.1:5000",
  "duration": 0.00240038,
  "request": {
    "remote_ip": "10.12.180.2",
    "remote_port": "39728",
    "client_ip": "10.12.180.2",
    "proto": "HTTP/3.0",
    "method": "GET",
    "host": "caddytest.homelab.memetichenry.com",
    "uri": "/",
    "headers": {
      "X-Forwarded-For": [
        "10.12.180.2"
      ],
      "X-Forwarded-Proto": [
        "https"
      ],
      "X-Forwarded-Host": [
        "caddytest.homelab.memetichenry.com"
      ],
      "Tls-Client-Certificate": [
        "{http.request.tls.client.certificate_der_base64}"
      ],
      "Soundness-Check": [
        "are-you-still-there"
      ],
      "User-Agent": [
        "curl/8.2.1-DEV"
      ],
      "Accept": [
        "*/*"
      ]
    },
    "tls": {
      "resumed": false,
      "version": 772,
      "cipher_suite": 4867,
      "proto": "h3",
      "server_name": "caddytest.homelab.memetichenry.com"
    }
  },
  "headers": {
    "Server": [
      "Werkzeug/3.0.1 Python/3.9.18"
    ],
    "Date": [
      "Sat, 27 Jan 2024 08:58:05 GMT"
    ],
    "Content-Type": [
      "application/json"
    ],
    "Content-Length": [
      "552"
    ]
  },
  "status": 200
}
```

I used a simple Python program written by ChatGPT to send back the HTTP headers, and I can confirm they match the log (meaning the client certificate is never passed to backend).

If, however, you disable HTTP3 via `servers{protocols h1 h2}`, the client certificate is passed normally:

```json
{
  "level": "debug",
  "ts": 1706346834.37273,
  "logger": "http.handlers.reverse_proxy",
  "msg": "upstream roundtrip",
  "upstream": "127.0.0.1:5000",
  "duration": 0.002871964,
  "request": {
    "remote_ip": "10.12.180.2",
    "remote_port": "45112",
    "client_ip": "10.12.180.2",
    "proto": "HTTP/2.0",
    "method": "GET",
    "host": "caddytest.homelab.memetichenry.com",
    "uri": "/",
    "headers": {
      "Accept": [
        "*/*"
      ],
      "Soundness-Check": [
        "are-you-still-there"
      ],
      "Tls-Client-Certificate": [
        "MIIByzCCAXKgAwIBAgIRANKDWKTP49v869jRCdFzmw0wCgYIKoZIzj0EAwIwKjEoMCYGA1UEAxMfQ2FkZHkgQ2xpZW50IENBIEludGVybWVkaWF0ZSBDQTAeFw0yNDAxMjYxOTIzMTZaFw00NDAxMjYxOTIzMTZaMBcxFTATBgNVBAMTDENhZGR5IENsaWVudDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGFabTn1YK+af8aONdSGO6X7zfzx+kq15N0U33Q6iEl/Y7WNiX2PnU43RapRvepLH+uQbct/JoFDZYWIUAc+jeqjgYswgYgwDgYDVR0PAQH/BAQDAgeAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNVHQ4EFgQURXgJ57eglfL2YD63w++Y3k0ZeU4wHwYDVR0jBBgwFoAU5SOl0DJU/th60T+B7kpijKJLBtwwFwYDVR0RBBAwDoIMQ2FkZHkgQ2xpZW50MAoGCCqGSM49BAMCA0cAMEQCIAm1JC6gJDR2qWUWAHWfcFUB96mcVdmO4lJMd+U3TtByAiBHRGtADANutoSpcrGj1me4/ef1ltex4zbZZK9unJBWlg=="
      ],
      "X-Forwarded-For": [
        "10.12.180.2"
      ],
      "X-Forwarded-Proto": [
        "https"
      ],
      "X-Forwarded-Host": [
        "caddytest.homelab.memetichenry.com"
      ],
      "User-Agent": [
        "curl/8.2.1-DEV"
      ]
    },
    "tls": {
      "resumed": false,
      "version": 772,
      "cipher_suite": 4867,
      "proto": "h2",
      "server_name": "caddytest.homelab.memetichenry.com",
      "client_common_name": "Caddy Client",
      "client_serial": "279819867913103031473390418487099497229"
    }
  },
  "headers": {
    "Content-Type": [
      "application/json"
    ],
    "Content-Length": [
      "1124"
    ],
    "Server": [
      "Werkzeug/3.0.1 Python/3.9.18"
    ],
    "Date": [
      "Sat, 27 Jan 2024 09:13:54 GMT"
    ]
  },
  "status": 200
}
```

Attached here [certificates.zip](https://github.com/caddyserver/caddy/files/14071812/certificates.zip) are the intermediate CA, client certificate and associated key files for ease of testing. The file client.p12 is provided in case either of you want to test a web browser, both Chrome and Firefox only support P12 files to the best of my knowledge. The certificate keys are plaintext. The certificates and associated keys were generated with the following commands, using Smallstep CLI: 

```bash
step-cli certificate create --insecure --no-password --not-after=175320h --profile=root-ca "Caddy Client CA Root CA" root.crt root.key
step-cli certificate create --insecure --no-password --not-after=175320h --profile=
intermediate-ca --ca ./root.crt --ca-key ./root.key "Caddy Client CA Intermediate CA" intermediate.crt intermediate.key 
step-cli certificate create --insecure --no-password --not-after=175320h --profile=leaf --ca ./intermediate.crt --ca-key ./intermediate.key "Caddy Client" client.crt client.key
step-cli certificate p12 --insecure --no-password client.p12 client.crt client.key
```
Please let me know if you need any more information, and again, my apologies for the wait.

**Comment by mholt** [comment] 2024-03-01 16:58
Thanks for the details! I'll try to circle back to this soon! Got just about 80 notifications in my backlog still... :sweat_smile:

**Comment by mholt** [comment] 2024-04-15 15:03
@henryreed Finally had a chance to set up as you described, thanks for providing the cert/key files to test with.

Maybe something got fixed in the latest quic-go update because now I see the cert passed through:

```
$ curl -E ./client.crt --key ./client.key -vs -D/dev/stdout --http3 https://localhost
* Host localhost:443 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:443...
* QUIC cipher selection: TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_CCM_SHA256
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
*  subjectAltName: host "localhost" matched cert's "localhost"
* Verified certificate just fine
* Connected to localhost (::1) port 443
* using HTTP/3
* [HTTP/3] [0] OPENED stream for https://localhost/
* [HTTP/3] [0] [:method: GET]
* [HTTP/3] [0] [:scheme: https]
* [HTTP/3] [0] [:authority: localhost]
* [HTTP/3] [0] [:path: /]
* [HTTP/3] [0] [user-agent: curl/8.7.1]
* [HTTP/3] [0] [accept: */*]
> GET / HTTP/3
> Host: localhost
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/3 200 
< date: Mon, 15 Apr 2024 14:58:43 GMT
< content-length: 0
< server: Caddy
< server: Caddy
< 
* Connection #0 to host localhost left intact
```


With log:

```
2024/04/15 14:58:43.184 DEBUG   http.handlers.reverse_proxy     upstream roundtrip      {"upstream": "127.0.0.1:5000", "duration": 0.00122472, "request": {"remote_ip": "::1", "remote_port": "32774", "client_ip": "::1", "proto": "HTTP/3.0", "method": "GET", "host": "localhost", "uri": "/", "headers": {"Soundness-Check": ["are-you-still-there"], "Tls-Client-Certificate": ["MIIByzCCAXKgAwIBAgIRANKDWKTP49v869jRCdFzmw0wCgYIKoZIzj0EAwIwKjEoMCYGA1UEAxMfQ2FkZHkgQ2xpZW50IENBIEludGVybWVkaWF0ZSBDQTAeFw0yNDAxMjYxOTIzMTZaFw00NDAxMjYxOTIzMTZaMBcxFTATBgNVBAMTDENhZGR5IENsaWVudDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGFabTn1YK+af8aONdSGO6X7zfzx+kq15N0U33Q6iEl/Y7WNiX2PnU43RapRvepLH+uQbct/JoFDZYWIUAc+jeqjgYswgYgwDgYDVR0PAQH/BAQDAgeAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNVHQ4EFgQURXgJ57eglfL2YD63w++Y3k0ZeU4wHwYDVR0jBBgwFoAU5SOl0DJU/th60T+B7kpijKJLBtwwFwYDVR0RBBAwDoIMQ2FkZHkgQ2xpZW50MAoGCCqGSM49BAMCA0cAMEQCIAm1JC6gJDR2qWUWAHWfcFUB96mcVdmO4lJMd+U3TtByAiBHRGtADANutoSpcrGj1me4/ef1ltex4zbZZK9unJBWlg=="], "User-Agent": ["curl/8.7.1"], "Accept": ["*/*"], "X-Forwarded-For": ["::1"], "X-Forwarded-Proto": ["https"], "X-Forwarded-Host": ["localhost"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "h3", "server_name": "localhost", "client_common_name": "Caddy Client", "client_serial": "279819867913103031473390418487099497229"}}, "headers": {"Server": ["Caddy"], "Date": ["Mon, 15 Apr 2024 14:58:43 GMT"], "Content-Length": ["0"]}, "status": 200}
```

So it is definitely working over HTTP/3.

I'll close the issue since it seems to be working, but feel free to continue discussion if needed.

**Closed by mholt** 2024-04-15 15:03 UTC
Labels: bug :lady_beetle:, deferred :alarm_clock:, needs info :mailbox_with_no_mail:

**Comment by henryreed** [comment] 2024-04-18 07:40
I'm unable to replicate this. Just to confirm, are we using some version of Caddy other than 2.7.6? E.g., given this Dockerfile, should I get the same version of Quic as you?

```Dockerfile
FROM caddy:builder AS builder

RUN xcaddy build --with github.com/caddy-dns/cloudflare

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

**Comment by henryreed** [comment] 2024-05-30 05:03
Confirming this still impacts `2.8.0`. Just a thought: if this isn't something Caddy can support then perhaps Caddy can disable HTTP3 if the `verify_if_given` directive is used.

**Comment by mholt** [comment] 2024-06-04 21:19
I believe it's _supposed_ to... soon-ish?
