### ISSUE TITLE
segmentation violation in bufio.go

### ISSUE THREAD

**Issue by corny** [caddyserver/caddy#3713] opened 2020-09-07 09:43 UTC
Caddy 2.1.1 crashed on Linux/amd64:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4b8a26]
goroutine 2087214 [running]:
bufio.(*Writer).Flush(0x0, 0x17e3d35, 0x19)
        bufio/bufio.go:585 +0x26
net/http.(*expectContinueReader).Read(0xc000dec1a0, 0xc000760700, 0x6a6, 0x6a6, 0x150ac00, 0xc000324201, 0xc000760700)
        net/http/server.go:890 +0x153
io.(*LimitedReader).Read(0xc000dec4e0, 0xc000760700, 0x6a6, 0x6a6, 0x0, 0xc000dc8800, 0x40a798)
        io/io.go:451 +0x63
io.copyBuffer(0x1abbf60, 0xc0007641a0, 0x1ab9a00, 0xc000dec4e0, 0xc000760700, 0x6a6, 0x6a6, 0x4fe779e3, 0xc00052f505, 0xc000dc8880)
        io/io.go:405 +0x122
io.Copy(...)
        io/io.go:364
net.genericReadFrom(0x1ab9c00, 0xc000ef8068, 0x1ab9a00, 0xc000dec4e0, 0x0, 0x0, 0x1720400)
        net/net.go:626 +0x9a
net.(*TCPConn).readFrom(0xc000ef8068, 0x1ab9a00, 0xc000dec4e0, 0xc000dc89f0, 0x40aa5a, 0x15ade00)
        net/tcpsock_posix.go:54 +0xe2
net.(*TCPConn).ReadFrom(0xc000ef8068, 0x1ab9a00, 0xc000dec4e0, 0x7f986989d378, 0xc000ef8068, 0xc000dc8a01)
        net/tcpsock.go:103 +0x4d
io.copyBuffer(0x1ab9c00, 0xc000ef8068, 0x1ab9a00, 0xc000dec4e0, 0x0, 0x0, 0x0, 0x161eee0, 0x203001, 0x7f986989d358)
        io/io.go:391 +0x2fc
io.Copy(...)
        io/io.go:364
net/http.persistConnWriter.ReadFrom(0xc0007ab440, 0x1ab9a00, 0xc000dec4e0, 0x7f986989d358, 0xc0007ab440, 0x1)
        net/http/transport.go:1672 +0x85
bufio.(*Writer).ReadFrom(0xc00060b200, 0x1ab9a00, 0xc000dec4e0, 0x7f986989d338, 0xc00060b200, 0x1)
        bufio/bufio.go:714 +0x357
io.copyBuffer(0x1ab58e0, 0xc00060b200, 0x1ab9a00, 0xc000dec4e0, 0x0, 0x0, 0x0, 0xc000dc8c40, 0x40d1e8, 0x20)
        io/io.go:391 +0x2fc
io.Copy(...)
        io/io.go:364
net/http.(*transferWriter).doBodyCopy(0xc000dad180, 0x1ab58e0, 0xc00060b200, 0x1ab9a00, 0xc000dec4e0, 0x15adf01, 0x1000000dc8cc8, 0x1000200000002)
        net/http/transfer.go:400 +0x6a
net/http.(*transferWriter).writeBody(0xc000dad180, 0x1ab58e0, 0xc00060b200, 0x2, 0x2)
        net/http/transfer.go:359 +0x6e5
net/http.(*Request).write(0xc0005a9a00, 0x1ab58e0, 0xc00060b200, 0x0, 0x0, 0xc000dec480, 0x0, 0x0)
        net/http/request.go:685 +0x6cf
net/http.(*persistConn).writeLoop(0xc0007ab440)
        net/http/transport.go:2280 +0x1c1
created by net/http.(*Transport).dialConn
        net/http/transport.go:1648 +0xc7b
```

**Comment by mholt** [comment] 2020-09-07 11:55
That's in the Go standard lib. What is the full log output: before, after, and also what triggered it?

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by mholt** [comment] 2020-11-24 23:43
Closing due to inactivity

**Closed by mholt** 2020-11-24 23:43 UTC
Labels: needs info
