### ISSUE TITLE
v2: caddy file-server on routes not on base root. lack of documentation?

### ISSUE THREAD

**Issue by neuronflow** [caddyserver/caddy#3033] opened 2020-02-10 21:21 UTC
Hi maybe this is just a case of me not understanding the still sparse documentation...I run a server, normally it should only return "let the neurons flow!".

Despite of that it should return two different static websites under the routes /hello and /green both of them access the same node/express api under /api with http post requests. 

I cannot get the file servers to run. I can get a file server to run at the base root / with the example from the documentation but not for subroutes like in my case.

Also on a side note...is my node/express sufficiently protected with this config or should I add further things to the configuration?

```
localhost:8080 {
    respond "let the neurons flow!"
}

localhost:8080/api* {
    reverse_proxy /api* localhost:3020
}

localhost:8080/hello* {
    root hello
    file_server
}

localhost:8080/green* {
    root green
    file_server
}
```

**Comment by mholt** [comment] 2020-02-10 22:12
Thanks for opening an issue! We'll look into this.

First, I noticed that you can simplify this line: `reverse_proxy /api* localhost:3020` to `reverse_proxy localhost:3020` since that site is only for requests with a path of `/api*` anyway.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by neuronflow** [comment] 2020-02-10 23:50
## 1. Environment

### 1a. Operating system and version

```
OSX 10.15.3
Ubuntu 18.04
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
v2.0.0-beta.13 h1:QL0JAepFvLVtOatABqniuDRQ4HmtvWuuSWZW24qVVtk=
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
prebuilt
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)
I expect two file servers to spawn



### 2b. Why it's a bug (if it's not obvious)

file servers are not reachable


### 2c. Log output

be aware that the code I used was for reproduction purposes so the log output will not fit 1:1
```
2020/02/10 23:04:37 [INFO][cache:0xc000674be0] Stopped certificate maintenance routine
2020/02/10 22:04:37.527 INFO    autosaved config        {"file": "/Users/meow/Library/Application Support/Caddy/autosave.json"}
2020/02/10 22:04:37.527 INFO    admin.api       load complete
meow@meow-rmbp brats_starz % 2020/02/10 22:04:38.030    INFO    admin   stopped previous server
caddy reload
2020/02/10 22:05:27.142 INFO    using adjacent Caddyfile
2020/02/10 22:05:27.146 INFO    admin.api       received request        {"method": "POST", "uri": "/load", "remote_addr": "127.0.0.1:59596", "headers": {"Accept-Encoding":["gzip"],"Content-Length":["1015"],"Content-Type":["application/json"],"Origin":["localhost:2019"],"User-Agent":["Go-http-client/1.1"]}}
2020/02/10 22:05:27.146 INFO    admin   admin endpoint started  {"address": "localhost:2019", "enforce_origin": false, "origins": ["localhost:2019"]}
2020/02/10 23:05:27 [INFO][cache:0xc000208050] Started certificate maintenance routine
2020/02/10 23:05:27 [INFO][cache:0xc000674eb0] Stopped certificate maintenance routine
2020/02/10 22:05:27.150 INFO    autosaved config        {"file": "/Users/meow/Library/Application Support/Caddy/autosave.json"}
2020/02/10 22:05:27.150 INFO    admin.api       load complete
meow@meow-rmbp brats_starz % 2020/02/10 22:05:27.650    INFO    admin   stopped previous server
caddy reload
```



### 2d. Workaround(s)

I will go for a more distributed architecture now...serve my apps with nginx and use caddy as the reverse proxy


### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)
see initial post

**Comment by mholt** [comment] 2020-02-11 00:11
Thanks, but, what exactly is not working? You say "I cannot get the file servers to run." but what does that mean? Is there a request that is failing that you expect should succeed? Can you please be more specific? The bug template is a lot of work, yes, but the point of it is to help drill down to what the problem is. Many people debug their own issues just while filling out the bug report thoroughly.

**Comment by neuronflow** [comment] 2020-02-11 00:27
When I access the page I get a 404.

I found another workaround in the meantime:

`localhost:8080/hello* {
    redir localhost:8081
}




localhost:8081 {
    root * dist
    file_server browse {
    }
}`

**Comment by neuronflow** [comment] 2020-02-11 00:34
wrote you an email on your gmail adress :)
happy to do a screen sharing to diagnose the bug.

**Comment by mholt** [comment] 2020-02-11 01:58
I got your email, but I can only dedicate personal time to fixing issues, as our current funding situation doesn't give me much extra time except for accomplishing development goals, unfortunately.

> When I access the page I get a 404.

Which page? What is your request, exactly? If anyone is going to experience the same issue, we need to know exactly what steps to take.

**Comment by neuronflow** [comment] 2020-02-11 08:36
To summarize:
`localhost:8080/hello` and `localhost:8080/green`
both lead to 404 when trying to spawn file servers like this:

```

localhost:8080/hello* {
    root hello
    file_server
}

localhost:8080/green* {
    root green
    file_server
}
```

but mapping them to individual.ports on base route works.

```

localhost:8081 {
    root hello
    file_server
}

localhost:8082 {
    root green
    file_server
}
```

**Comment by mholt** [comment] 2020-02-11 16:43
Thanks, that's more specific, but still not quite enough. Since you are running a file server, there are more variables at play. What is in your `hello` and `green` folders? I ask because your config works for me.  Are you sure you have a file at /hello/index.html? (A request to `/hello` will get redirected to `/hello/` if there is an index file there.)

**Closed** 2020-02-23 22:24 UTC

**Comment by Master-Y0da** [comment] 2021-05-07 02:58
@neuronflow did you get a solution ?... I'm facing similar error...

    :80 {
    root * /var/www/html
    file_server
    }
     :80/administracion/* {
     uri strip_prefix /administracion
     root * /var/www/html/smiled-front/dist
     file_server
    }

:80 working fine...but :80/administracion getting 404 error on console...spend almost a day trying to make this work.

**Comment by francislavoie** [comment] 2021-05-07 03:17
@Master-Y0da Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
