### ISSUE TITLE
Symlinks showing as files not directories when using browse

### ISSUE THREAD

**Issue by VioletLovesJasmine** [caddyserver/caddy#3838] opened 2020-11-01 18:00 UTC
This issue appears to be very similar to a previous [issue](https://github.com/caddyserver/caddy/issues/1660) with v1. My webroot is on a high-speed SSD, while large media files are stored on a separate raid array. I used symlinks to symlink specific directories on the raid array to the webroot, so they can be browsed. Caddy v1 was fine with this arrangement, but v2 displays the symlinks as files rather than as links to directories as v1 did.

I'm using v2.2.0
Let me know if you need any more information 👍

![Screenshot 2020-11-01 at 17 42 41](https://user-images.githubusercontent.com/19542026/97810465-f3a9c500-1c6b-11eb-8880-cf00f6f540f7.png)

**Comment by francislavoie** [comment] 2020-11-01 18:42
Hmm. I think https://github.com/caddyserver/caddy/commit/b95b87381a282e1fe57295d145b71645d7801f07 might have broken it, specifically the change to `sanitizedPathJoin`. I didn't realize that would have an effect.

Could you try with Caddy v2.1.1 to confirm that it worked in that release?

**Comment by VioletLovesJasmine** [comment] 2020-11-01 20:44
Nope. Sorry
![Screenshot 2020-11-01 at 20 40 11](https://user-images.githubusercontent.com/19542026/97814972-e8ae5f00-1c82-11eb-93cf-be5a1011a6aa.png)

**Comment by VioletLovesJasmine** [comment] 2020-11-01 20:48
Yes, that seems to have fixed it

**Comment by francislavoie** [comment] 2020-11-01 21:15
Okay, thanks. We'll look into it.

**Comment by gdhameeja** [comment] 2020-11-04 09:35
Can I work on this? Although I don't have the background that seems related to this bug, could I give it a go?

**Comment by francislavoie** [comment] 2020-11-04 09:50
Absolutely! Go for it 😄

**Comment by gmerrall** [comment] 2020-11-15 08:07
> Could you try with Caddy v2.1.1 to confirm that it worked in that release?

I've rolled back to v2.1.1 (arm64) and the issue is still occurring for me as per the original supplied screenshot. I'm running it in the container so it's no big drama for me to roll back through 2.1.0 and 2.0 to see if it occurs in those versions as well.

**Comment by mholt** [comment] 2020-11-24 19:25
The problem is we were transforming the root path (evaluating its placeholders) at the beginning of the file server's ServeHTTP, but we didn't reuse it later in browse, instead referring to the original fsrv.Root variable. Should be fixed now. (Works for me.)

**Closed** 2020-11-24 19:24 UTC
Labels: bug
