### ISSUE TITLE
stopping current admin endpoint	{"error": "shutting down admin server: context deadline exceeded"}

### ISSUE THREAD

**Issue by Jokcy** [caddyserver/caddy#2978] opened 2020-01-16 08:02 UTC
system: macos
caddy version: caddy2-beta12

I use caddy start to start caddy, then use `POST /load` to update the config. My config is here:
```json
{
  "apps": {
    "http": {
      "servers": {
        "client-local.test.api": {
          "listen": [":8088"],
          "routes": [
            {
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "handler": "rewrite",
                          "uri": "/{http.matchers.path_regexp.api.1}"
                        },
                        {
                          "handler": "reverse_proxy",
                          "transport": {
                            "protocol": "http",
                            "read_buffer_size": 4096
                          },
                          "upstreams": [{ "dial": "localhost:8080" }]
                        }
                      ],
                      "match": [
                        {
                          "path_regexp": {
                            "name": "api",
                            "pattern": "^/api/(.*)$"
                          }
                        }
                      ]
                    }
                  ]
                }
              ],
              "match": [{ "host": ["localhost", "127.0.0.1"] }]
            }
          ]
        },
        "client.test.com": {
          "listen": [":80"],
          "routes": [
            {
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "handler": "rewrite",
                          "uri": "{http.matchers.path_regexp.api.1}"
                        },
                        {
                          "handler": "reverse_proxy",
                          "transport": {
                            "protocol": "http",
                            "read_buffer_size": 4096
                          },
                          "upstreams": [{ "dial": "localhost:8080" }]
                        }
                      ],
                      "match": [
                        {
                          "path_regexp": {
                            "name": "api",
                            "pattern": "^/api/(.*)$"
                          }
                        }
                      ]
                    },
                    {
                      "handle": [
                        {
                          "handler": "reverse_proxy",
                          "transport": {
                            "protocol": "http",
                            "read_buffer_size": 4096
                          },
                          "upstreams": [{ "dial": "localhost:3000" }]
                        }
                      ],
                      "match": [{ "path": ["/"] }]
                    }
                  ]
                }
              ],
              "match": [{ "host": ["client.test.com"] }]
            }
          ]
        }
      }
    }
  }
}

```

The no matter what change I do to the config, I `POST /load` again, caddy will throw error:

```
ERROR	admin	stopping current admin endpoint	{"error": "shutting down admin server: context deadline exceeded"}
```

Then caddy dead, I can't even `caddy stop` it.

**Comment by mholt** [comment] 2020-01-16 16:58
Thanks for opening an issue! We'll look into this.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Closed** 2020-03-16 04:17 UTC
