### ISSUE TITLE
Caddy is unable to reverse proxy http/2 streams

### ISSUE THREAD

**Issue by figassis** [caddyserver/caddy#3938] opened 2020-12-27 09:36 UTC
I placed caddy in front of a kubernetes api server and noticed that `kubectl logs -f pod` simply hangs and then times out saying `Unable to connect to the server: unexpected EOF`.

I then tried using curl to reach the API, and got:
```bash
curl -v -k -XGET  -H "Authorization: Bearer token" -H "Accept: application/json, */*" 'https://server/api/v1/namespaces/namespace/pods/pod/log?follow=true'
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying ip...
* TCP_NODELAY set
* Connected to server (ip) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=server
*  start date: Dec 18 09:19:48 2020 GMT
*  expire date: Mar 18 09:19:48 2021 GMT
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fc3b7003c00)
> GET /api/v1/namespaces/namespace/pods/pod/log?follow=true HTTP/2
> Host: server
> User-Agent: curl/7.54.0
> Authorization: Bearer token
> Accept: application/json, */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* Unexpected EOF
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (56) Unexpected EOF
```

This all works if I replace caddy with haproxy acting as a tcp reverse proxy. To clarify, I'm using the following config, which proxies self signed upstream servers, but also provides a valid LE cert to the client. I think somewhere in the process of terminating the upstream and repackaging the response in the valid cert, we're losing the ability to provide a stream to the client, but really, I have no idea, that's a guess:

```
fqdn:80, fqdn:443 {
	log
    encode gzip
    reverse_proxy {$NODE1}:6443 {$NODE2}:6443 {$NODE3}:6443 {
        health_path    /
        health_interval 10s
        health_timeout  3s
        health_status   401
        header_up X-Forwarded-Proto https
        transport http {
            tls
            tls_insecure_skip_verify
        }
    }
}
```

**Comment by francislavoie** [comment] 2020-12-27 14:21
Thanks for opening an issue! We'll look into this.

It's not immediately clear to us what is going on, so we'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by figassis** [comment] 2020-12-27 22:08
I'm running caddy on docker using caddy:2.1.1, and most of my environment is dockerized so it would not really be accurate to provide details away from this.

## 1. Environment

### 1a. Operating system and version

```
Host OS: Ubuntu 20.04
Docker CE version: 20.10.1
Caddy Image: caddy:2.1.1
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
Official Caddy Image: caddy:2.1.1
From Dockerfile: https://github.com/caddyserver/caddy/releases/download/v2.1.1/caddy_2.1.1_linux_amd64.tar.gz
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
I didn't build from source, please see version above
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)
Configuring Caddy as a reverse https proxy for a https kubernetes api server works with regular commands like `kubectl get pods`, but results in a timeout when doing `kubectl logs -f pod`.

When debugging with `kubectl -v=9 logs -f pod` and executing the resulting curl request, I get the output in the comment [above](https://github.com/caddyserver/caddy/issues/3938#issue-775006645).

I have removed hostnames and IPs because for now I've replaced caddy with a working haproxy setup.



### 2b. Why it's a bug (if it's not obvious)
Because the `kubectl logs -f pod` command seems to respond with an http/2 stream and I believe Caddy is not handling the tls termination from the upstream server, the client, or both while maintaining the stream.



### 2c. Log output

```
caddy returns a 200 response on the request, then hangs. I will update with actual logs as soon as I redeploy caddy.
```



### 2d. Workaround(s)
I replaced caddy with haproxy in http mode with an ACME sidecar container and it works fine.



### 2e. Relevant links


## 3. Tutorial (minimal steps to reproduce the bug)
Configure caddy with the following files and point it to any https enabled kubernetes api server.
Replace backend-server with your actual api server, and domain.com with your test domain.

docker-compose.yaml
```
version: "2"
services:
  caddy:
    image: caddy:2.1.1
    container_name: caddy
    restart: always
    volumes:
      - /etc/caddy:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"
```

Caddyfile
```
{
    acme_ca https://acme-v02.api.letsencrypt.org/directory
    email   admin@domain.com
    auto_https disable_redirects
    admin off
}

api.domain.com:80, api.domain.com:443 {
	log
    encode gzip
    reverse_proxy backend-server:6443 {
        health_path    /
        health_interval 10s
        health_timeout  3s
        health_status   401
        header_up X-Forwarded-Proto https
        transport http {
            tls
            tls_insecure_skip_verify
        }
    }
}
```

**Comment by francislavoie** [comment] 2020-12-28 02:48
Please try with `caddy:2.3.0-rc.1`, there have been many changes since that may have fixed it.

**Comment by mholt** [comment] 2020-12-28 21:47
If it still doesn't work with the latest version, I'd be interested in seeing the HTTP requests/responses in detail, especially between Caddy and the backend. (That would be faster than me learning kubernetes and setting up a cluster just to repro this issue...)

**Comment by francislavoie** [comment] 2021-01-24 19:52
I'm going to close this due to inactivity.

**Closed by francislavoie** 2021-01-24 19:52 UTC
Labels: needs info

**Comment by sidwebworks** [comment] 2025-02-22 13:56
@francislavoie I think I am still facing the same issue - what information do you need? please let me know
