### ISSUE TITLE
acme_server directive errors on arm

### ISSUE THREAD

**Issue by ViViDboarder** [caddyserver/caddy#3847] opened 2020-11-04 18:58 UTC
I've just validated that a very simple Caddyfile adding an acme server fails when executed on an ARM Linux device (Raspberry Pi 2 and 4), but appears fine on my Darwin device. This is reproduced with Docker and the binaries for version 2.1.1 and 2.2.1.

Example Caddyfile
```
{
    local_certs
    debug
}

acme.localhost {
    acme_server
}
```

Validating with `caddy validate` on ARM yields
```
2020/11/04 18:53:31.910	INFO	using adjacent Caddyfile
2020/11/04 18:53:31.914	INFO	tls.cache.maintenance	started background certificate maintenance	{"cache": "0x246f810"}
2020/11/04 18:53:31.917	INFO	http	server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS	{"server_name": "srv0", "https_port": 443}
2020/11/04 18:53:31.917	INFO	http	enabling automatic HTTP->HTTPS redirects	{"server_name": "srv0"}
2020/11/04 18:53:31.917	INFO	tls	setting internal issuer for automation policy that has only internal subjects but no issuer configured	{"subjects": ["acme.localhost"]}
2020/11/04 18:53:31.946	INFO	tls.cache.maintenance	stopped background certificate maintenance	{"cache": "0x246f810"}
validate: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'acme_server': provision http.handlers.acme_server: initializing certificate authority: Error opening database of Type badger with source /home/username/.local/share/caddy/acme_server/db: error opening Badger database: Unable to mmap RDWR log file: invalid argument
```

On my macOS it yields
```
2020/11/04 18:54:54.824	INFO	using adjacent Caddyfile
2020/11/04 18:54:54.838	INFO	tls.cache.maintenance	started background certificate maintenance	{"cache": "0xc000473030"}
2020/11/04 18:54:54.855	INFO	http	server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS	{"server_name": "srv0", "https_port": 443}
2020/11/04 18:54:54.855	INFO	http	enabling automatic HTTP->HTTPS redirects	{"server_name": "srv0"}
2020/11/04 18:54:54.855	INFO	tls	setting internal issuer for automation policy that has only internal subjects but no issuer configured	{"subjects": ["acme.localhost"]}
2020/11/04 18:54:54.924	INFO	tls.cache.maintenance	stopped background certificate maintenance	{"cache": "0xc000473030"}
Valid configuration
```

**Comment by francislavoie** [comment] 2020-11-04 19:44
Interesting. Well it's an issue with https://github.com/dgraph-io/badger but it's likely something already solved upstream, and that we need to get the dependency updated. But it's an indirect dependency, I think by the `smallstep` libs.

**Comment by ViViDboarder** [comment] 2020-11-04 19:54
I'm in the process of trying to run tests for https://github.com/smallstep/certificates, which seems to be the module using Badger, on my Raspberry Pi 4 now to see if it's reproducible there.

**Comment by ViViDboarder** [comment] 2020-11-04 20:01
I also just looked at the Database docs for [smallstep/certificates](https://github.com/smallstep/certificates/blob/c1e6c0285a423397d76e3b64cca21d7425aaef37/docs/database.md) and found that there appears to be a setting that allows different badger versions and writing to `FileIO` vs `MemoryMap`.

So that's another thing I can try to play with.

**Comment by ViViDboarder** [comment] 2020-11-04 20:19
Good news! Simply switching to `FileIO` works. I'm not sure of the implications of switching default will be.

**Comment by ViViDboarder** [comment] 2020-11-04 22:19
Some more research. Here's the upstream issue: smallstep/certificates#211. Here's the issue upstream of that: dgraph-io/badger#246

There the fix does appear to be to use `FileIO`.

I also found smallstep/cli#256 where they discuss fixing an identical error with the the `smallstep` cli. They said it was fixed there, but I can't quite tell where the fix was or what they did. It could have been switching to `FileIO`, however I don't know exactly.

Any thoughts on switching to `FileIO` or making it a non-default configuration option for `acme_server`?

**Comment by ViViDboarder** [comment] 2020-11-04 23:58
I've got a branch working that I can submit soon that adds an optional argument to `acme_server` that disables `MemoryMap` and uses `FileIO`. For now I've called it `acme_server no_mem_map`. Open to other naming or conventions. This seems concise, but another option would be to use a block and a subdirective such as `badger_file_loading_mode` that accepts either `"FileIO"` or `"MemoryMap"`, however that is directly exposing a value that is going through 2 dependencies rather than abstracting it. I don't think that the directive name or values will be intuitive to a user.

**Comment by francislavoie** [comment] 2020-11-05 00:11
I think it being a subdirective would be better, like this:

```
acme_server {
	no_memory_map
}
```

But it should be marked as a likely temporary solution, because I think badger v2 shouldn't have this problem. I reached out to the smallstep guys and they believe that's the case, I think. But the problem is badger v1 and v2 aren't compatible, so if we were to switch which version is used by Caddy, it would fail to load the v1 version of the database on startup.

**Comment by ViViDboarder** [comment] 2020-11-05 00:31
Ah. I tried BadgerV2 and it didn't work, but I think that's because it doesn't auto update the state.

I've added `no_memory_map` and `use_badgerv2` as subdirectives now and they both work! So if someone has an existing state they are trying to migrate, they can enable `no_memory_map`. If they are starting from scratch, they can do `use_badgerv2`.

**Closed** 2020-11-23 20:03 UTC
Labels: upstream
