### ISSUE TITLE
Using special characters instead of punycode gives hard-to-decrypt errors

### ISSUE THREAD

**Issue by iverks** [caddyserver/caddy#6673] opened 2024-11-01 23:16 UTC
If a domain name has special characters, it's translated into punycode (e.g. `å.no` -> `xn--5ca.no`). When setting up caddy on servers that use this, you need to use the translated version (as per my experience so far).

The "failure mode" for using the wrong caddyfile is a 200 response with an empty body. At the very least it would be good to reject caddyfiles with these mistakes with a helpful error. 

### Wrong

```Caddyfile
å.no {
    respond "Hello world"
}

```

### Correct

```Caddyfile
xn--5ca.no {
    respond "Hello world"
}

```

**Comment by mholt** [comment] 2024-11-02 02:44
You can use UTF-8 in domain names as in the first Caddyfile. What is the problem, exactly?

**Comment by iverks** [comment] 2024-11-02 19:24
For me it does not work. I get a 200 response with an empty body for the first file, and the correct response for the second file.

**Comment by mholt** [comment] 2024-11-04 17:48
Ah, sorry, this has been fixed but more recently than I thought: https://github.com/caddyserver/caddy/commit/99dcdf7e426f0dcbdffe510f241ae8a4fd5a56e6

(You can try the latest beta, I'm actually hoping to cut a new version today.)

Will close this but feel free to continue discussion if necessary!

**Comment by mholt** [comment] 2024-11-04 17:49
Duplicate of #6404

**Closed by mholt** 2024-11-04 17:48 UTC
