### ISSUE TITLE
v2: panic loading certificat in 2.0 beta 17

### ISSUE THREAD

**Issue by aitva** [caddyserver/caddy#3150] opened 2020-03-15 12:59 UTC
I just tried Caddy v2.0.0-beta.17 but I was hit by a panic. It seems to be caused by certificat migration:

```
Mar 14 12:03:59 app systemd[1]: Started Caddy HTTP/2 web server.
Mar 14 12:03:59 app caddy[23726]: 2020/03/14 11:03:59.211#011#033[34mINFO#033[0m#011using provided configuration#011{"config_file": "/etc/caddy/Caddyfile", "config_adapter": "caddyfile"}
Mar 14 12:03:59 app caddy[23726]: 2020/03/14 11:03:59.229#011#033[34mINFO#033[0m#011admin#011admin endpoint started#011{"address": "localhost:2019", "enforce_origin": false, "origins": ["localhost:2019"]}
Mar 14 12:03:59 app caddy[23726]: 2020/03/14 12:03:59 [INFO][cache:0xc0000eed70] Started certificate maintenance routine
Mar 14 12:03:59 app caddy[23726]: 2020/03/14 11:03:59.234#011#033[33mWARN#033[0m#011tls.automigrate#011certificate storage path has changed; attempting one-time auto-migration#011{"old_folder": "/etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites", "new_folder": "/etc/ssl/caddy/certificates/acme-v02.api.letsencrypt.org-directory", "details": "https://github.com/caddyserver/caddy/issues/2955"}
Mar 14 12:03:59 app caddy[23726]: 2020/03/14 11:03:59.234#011#033[34mINFO#033[0m#011tls.automigrate#011moving certificate assets#011{"ca": "acme-v02.api.letsencrypt.org", "site": "redacted", "destination": "/etc/ssl/caddy/certificates/acme-v02.api.letsencrypt.org-directory/redacted"}
Mar 14 12:03:59 app caddy[23726]: 2020/03/14 11:03:59.235#011#033[34mINFO#033[0m#011tls.automigrate#011moving certificate assets#011{"ca": "acme-v02.api.letsencrypt.org", "site": "redacted", "destination": "/etc/ssl/caddy/certificates/acme-v02.api.letsencrypt.org-directory/redacted"}
Mar 14 12:03:59 app caddy[23726]: 2020/03/14 11:03:59.235#011#033[34mINFO#033[0m#011tls.automigrate#011moving certificate assets#011{"ca": "acme-v02.api.letsencrypt.org", "site": "redacted", "destination": "/etc/ssl/caddy/certificates/acme-v02.api.letsencrypt.org-directory/redacted"}
Mar 14 12:03:59 app caddy[23726]: 2020/03/14 11:03:59.236#011#033[34mINFO#033[0m#011tls.automigrate#011moving certificate assets#011{"ca": "acme-v02.api.letsencrypt.org", "site": "redacted", "destination": "/etc/ssl/caddy/certificates/acme-v02.api.letsencrypt.org-directory/redacted"}
Mar 14 12:03:59 app caddy[23726]: 2020/03/14 11:03:59.236#011#033[34mINFO#033[0m#011tls.automigrate#011moving certificate assets#011{"ca": "acme-v02.api.letsencrypt.org", "site": "redacted", "destination": "/etc/ssl/caddy/certificates/acme-v02.api.letsencrypt.org-directory/redacted"}
Mar 14 12:03:59 app caddy[23726]: 2020/03/14 11:03:59.237#011#033[34mINFO#033[0m#011http#011server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS#011{"server_name": "srv0", "https_port": 443}
Mar 14 12:03:59 app caddy[23726]: 2020/03/14 11:03:59.237#011#033[34mINFO#033[0m#011http#011enabling automatic HTTP->HTTPS redirects#011{"server_name": "srv0"}
Mar 14 12:03:59 app caddy[23726]: 2020/03/14 11:03:59.249#011#033[34mINFO#033[0m#011tls#011cleaned up storage units
Mar 14 12:03:59 app caddy[23726]: 2020/03/14 11:03:59.250#011#033[34mINFO#033[0m#011http#011enabling automatic TLS certificate management#011{"domains": ["redacted", "redacted", "redacted", "redacted", "redacted"]}
Mar 14 12:04:00 app caddy[23726]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 14 12:04:00 app caddy[23726]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8b3396]
Mar 14 12:04:00 app caddy[23726]: goroutine 1 [running]:
Mar 14 12:04:00 app caddy[23726]: github.com/caddyserver/certmagic.(*Config).loadCertResource(0xc000354c60, 0xc00047e8b0, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Mar 14 12:04:00 app caddy[23726]: #011/Users/matt/go/pkg/mod/github.com/caddyserver/certmagic@v0.10.2/crypto.go:161 +0x76
Mar 14 12:04:00 app caddy[23726]: github.com/caddyserver/certmagic.(*Config).loadManagedCertificate(0xc000354c60, 0xc00047e8b0, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Mar 14 12:04:00 app caddy[23726]: #011/Users/matt/go/pkg/mod/github.com/caddyserver/certmagic@v0.10.2/certificates.go:129 +0x7b
Mar 14 12:04:00 app caddy[23726]: github.com/caddyserver/certmagic.(*Config).CacheManagedCertificate(0xc000354c60, 0xc00047e8b0, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Mar 14 12:04:00 app caddy[23726]: #011/Users/matt/go/pkg/mod/github.com/caddyserver/certmagic@v0.10.2/certificates.go:117 +0x7b
Mar 14 12:04:00 app caddy[23726]: github.com/caddyserver/certmagic.(*Config).manageOne(0xc000354c60, 0x17199c0, 0xc0003735c0, 0xc00047e8b0, 0xe, 0xffffffffffffff01, 0x0, 0x0)
Mar 14 12:04:00 app caddy[23726]: #011/Users/matt/go/pkg/mod/github.com/caddyserver/certmagic@v0.10.2/config.go:300 +0x98
Mar 14 12:04:00 app caddy[23726]: github.com/caddyserver/certmagic.(*Config).manageAll(0xc000354c60, 0x17199c0, 0xc0003735c0, 0xc0005d3030, 0x1, 0x1, 0x1, 0x0, 0x0)
Mar 14 12:04:00 app caddy[23726]: #011/Users/matt/go/pkg/mod/github.com/caddyserver/certmagic@v0.10.2/config.go:289 +0x1ec
Mar 14 12:04:00 app caddy[23726]: github.com/caddyserver/certmagic.(*Config).ManageAsync(...)
Mar 14 12:04:00 app caddy[23726]: #011/Users/matt/go/pkg/mod/github.com/caddyserver/certmagic@v0.10.2/config.go:271
Mar 14 12:04:00 app caddy[23726]: github.com/caddyserver/caddy/v2/modules/caddytls.(*TLS).Manage(0xc0000b6c80, 0xc0000eee10, 0x5, 0x5, 0x1, 0x1)
Mar 14 12:04:00 app caddy[23726]: #011/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.17/modules/caddytls/tls.go:259 +0x382
Mar 14 12:04:00 app caddy[23726]: github.com/caddyserver/caddy/v2/modules/caddyhttp.(*App).automaticHTTPSPhase2(0xc00019a5b0, 0xc000186e08, 0x1)
Mar 14 12:04:00 app caddy[23726]: #011/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.17/modules/caddyhttp/autohttps.go:513 +0x1f5
Mar 14 12:04:00 app caddy[23726]: github.com/caddyserver/caddy/v2/modules/caddyhttp.(*App).Start(0xc00019a5b0, 0x0, 0x0)
Mar 14 12:04:00 app caddy[23726]: #011/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.17/modules/caddyhttp/caddyhttp.go:320 +0x10eb
Mar 14 12:04:00 app caddy[23726]: github.com/caddyserver/caddy/v2.run.func4(0xc0000eea00, 0x17199c0, 0xc0003735c0)
Mar 14 12:04:00 app caddy[23726]: #011/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.17/caddy.go:406 +0xfa
Mar 14 12:04:00 app caddy[23726]: github.com/caddyserver/caddy/v2.run(0xc0000eea00, 0x801, 0x0, 0x0)
Mar 14 12:04:00 app caddy[23726]: #011/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.17/caddy.go:422 +0x2c2
Mar 14 12:04:00 app caddy[23726]: github.com/caddyserver/caddy/v2.unsyncedDecodeAndRun(0xc000132400, 0x8b7, 0x900, 0x7, 0xc0000f06c0)
Mar 14 12:04:00 app caddy[23726]: #011/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.17/caddy.go:249 +0xf7
Mar 14 12:04:00 app caddy[23726]: github.com/caddyserver/caddy/v2.changeConfig(0x1438780, 0x4, 0x14425a3, 0x7, 0xc000130900, 0x8b7, 0x900, 0x1, 0x0, 0x0)
Mar 14 12:04:00 app caddy[23726]: #011/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.17/caddy.go:156 +0x4bb
Mar 14 12:04:00 app caddy[23726]: github.com/caddyserver/caddy/v2.Load(...)
Mar 14 12:04:00 app caddy[23726]: #011/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.17/caddy.go:102
Mar 14 12:04:00 app caddy[23726]: github.com/caddyserver/caddy/v2/cmd.cmdRun(0xc000098600, 0x0, 0x0, 0x0)
Mar 14 12:04:00 app caddy[23726]: #011/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.17/cmd/commandfuncs.go:187 +0x360
Mar 14 12:04:00 app caddy[23726]: github.com/caddyserver/caddy/v2/cmd.Main()
Mar 14 12:04:00 app caddy[23726]: #011/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.17/cmd/main.go:72 +0x23e
Mar 14 12:04:00 app caddy[23726]: main.main()
Mar 14 12:04:00 app caddy[23726]: #011/Users/matt/Downloads/Downloads/caddytest/main.go:37 +0x20
Mar 14 12:04:00 app systemd[1]: caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 14 12:04:00 app systemd[1]: caddy.service: Unit entered failed state.
Mar 14 12:04:00 app systemd[1]: caddy.service: Failed with result 'exit-code'.
```

I was previously on v2.0.0-beta10 and here is my Caddyfile:

```
{
    storage file_system {
        root /etc/ssl/caddy
    }
}

site1.example.com {
    tls redacted@example.com
    reverse_proxy /* localhost:9002
}
site2.exampe.com {
    reverse_proxy /* localhost:9000
}
site3.example.com {
    reverse_proxy /* localhost:9001
}
site4.example.com {
    reverse_proxy /* localhost:9003
    basicauth /* {
        admin <redacted>
    }
}

site5.example.com {
    redir / /site1/ temporary
    reverse_proxy /site2/* localhost:8080
    reverse_proxy /site1/* localhost:8081
    reverse_proxy /site3/* localhost:8082
    reverse_proxy /site4/* localhost:8083
    basicauth /site4/* {
        admin <redacted>
    }
}
```

**Comment by mholt** [comment] 2020-03-15 14:54
Thanks for opening an issue! I am looking into this, but unfortunately I am not able to reproduce the panic with the given config.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: **Please do not redact any information as you did in your original post.**

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by mholt** [comment] 2020-03-15 15:25
Actually, after trying a few more things, I made some headway on this bug anyway.

@aitva Can you please pull commit https://github.com/caddyserver/caddy/commit/115b877e1a83527e4b5e1bf33bb2d9b62f3f3059 and try again?

**Comment by aitva** [comment] 2020-03-15 17:37
Thank you for your quick response. I have just tried 115b877 and the panic is gone. 🎉

**Comment by mholt** [comment] 2020-03-15 17:38
Excellent, thank you for confirming!

**Closed** 2020-03-15 17:38 UTC
Labels: bug, needs info, v2
