### ISSUE TITLE
Broken handling of --listen in combination with --domain

### ISSUE THREAD

**Issue by larsks** [caddyserver/caddy#6059] opened 2024-01-24 13:28 UTC
I want to start an HTTPS fileserver on 127.0.0.1:8443. I tried:

```
caddy file-server -d fs.internal -l 127.0.0.1:8443
```

But this fails with:

```
2024/01/24 13:24:18.370 WARN    admin   admin endpoint disabled
2024/01/24 13:24:18.371 INFO    http.auto_https enabling automatic HTTP->HTTPS redirects        {"server_name": "static"}
2024/01/24 13:24:18.371 INFO    tls.cache.maintenance   started background certificate maintenance      {"cache": "0xc00057f700"}
2024/01/24 13:24:18.371 INFO    [INFO][FileStorage:/home/larsks/.local/share/caddy] Lock for 'storage_clean' is stale (created: 2024-01-24 08:23:44.147168988 -0500 EST, last update: 2024-01-24 08:23:44.147168988 -0500 EST); removing then retrying: /home/larsks/.local/share/caddy/locks/storage_clean.lock
2024/01/24 13:24:18.371 INFO    tls.cache.maintenance   stopped background certificate maintenance      {"cache": "0xc00057f700"}
Error: loading new config: http app module: start: listening on 127.0.0.1:80: listen tcp 127.0.0.1:80: bind: permission denied
```

This doesn't make any sense; caddy is attempting to bind to port 80 even though I've explicited requested that it listen on `127.0.0.1:8443`. There doesn't appear to be any mechanism available to specify the socket configuration (listening address and port) separately from the domain configuration. If I add `fs.internal` to `/etc/hosts`, this works:

```
caddy -l fs.internal:8443
```

...but that requires `root` access, which is silly.

It should be possible to provide domain name information to caddy separate from the socket configuration.

**Comment by francislavoie** [comment] 2024-01-24 13:39
That's correct. When you specify a domain, you're implicitly telling Caddy "I want HTTPS". Caddy's "Automatic HTTPS" feature enables HTTP->HTTPS redirects in addition to ACME automation, so it listens on port 80 for HTTP unless told not to.

I don't think our `file-server` command has a flag to disable Automatic HTTPS right now though, that could/should be added.

For now, I recommend using a Caddyfile config which is more expressive and without limits.

**Comment by larsks** [comment] 2024-01-24 13:40
> That's correct. When you specify a domain, you're implicitly telling Caddy "I want HTTPS".

Yes, I know. As I mentioned, my goal was to start an HTTPS file-server. I don't want to disable automatic HTTPS; I want it to work but I want the socket configuration to be independent.

**Comment by francislavoie** [comment] 2024-01-24 13:42
Well, "Automatic HTTPS" includes listening on the HTTP port. Unless that's turned off, it will always do that. That's the point of that feature. If you don't want it to listen on the HTTP port, then you need to turn that off. With the Caddyfile, that's done with the `auto_https off` global option or with `auto_https disable_redirects` to only turn off the HTTP->HTTPS redirect (but keep solving ACME HTTP challenges).

**Comment by mholt** [comment] 2024-01-24 15:18
The problem is most clients still try HTTP by default. If/when they all switch to HTTPS first, then we can more easily eliminate the HTTP->HTTPS redirects. But not having those will break a majority of sites still.

**Comment by mholt** [comment] 2024-04-17 18:32
Closing, since I don't think there's anything actionable here at the moment. The command is working as intended, and the desired behavior is more advanced which can be attained by a line or two of configuration in the Caddyfile (`auto_https off` for example).

**Closed by mholt** 2024-04-17 18:32 UTC
Labels: discussion :speech_balloon:
