### ISSUE TITLE
Deriving mime type inconsistent with Go 1.17

### ISSUE THREAD

**Issue by cubic3d** [caddyserver/caddy#4287] opened 2021-08-17 22:48 UTC
Looks like Go 1.17 changed the source for mime types (https://github.com/golang/go/issues/46013) it's no longer sources from `mailcap` using `/etc/mime.types` but from the Shared MIME-Info Database at `/usr/share/mime/`.

So if I use the official build from current version `2.4.3` and request a file from `localhost/file.ign` I get the correct header `Content-Type: application/vnd.coreos.ignition+json`. Building the same version with xcaddy with Go 1.17 will not set a content type because `application/vnd.coreos.ignition+json` is not part of the shared database on my system it looks like. More popular types like `text/plain` work fine.

Is there a way to make the lookup more consistent and remove the external dependency? Maybe embedding mime types in the Caddy binary?

**Comment by francislavoie** [comment] 2021-08-17 23:07
Hmm. No, Caddy doesn't have anything built-in for overriding MIME types right now.

I think you should open an issue upstream to report this problem, since this is a regression that they introduced.

I would expect that if no MIME type is found in your shared DB, then it should fallback to `/etc/mime.types` 🤔

The specific PR that made the change is https://github.com/golang/go/pull/45271

**Comment by francislavoie** [comment] 2021-08-17 23:11
You may also want to consider asking https://gitlab.freedesktop.org/xdg/shared-mime-info to add that mime type to the database.

**Comment by mholt** [comment] 2022-03-03 18:15
Think I'm going to close this, as it seems that having the MIME db properly installed on the system should resolve the issue; not really a Caddy bug. Thanks!

**Closed by mholt** 2022-03-03 18:15 UTC
Labels: bug, upstream
