### ISSUE TITLE
Redirects after reverse proxying seem to redirect to the host before reverse proxying.

### ISSUE THREAD

**Issue by Summpot** [caddyserver/caddy#5787] opened 2023-08-27 07:43 UTC
```
:9000 {
	redir / /hello
	handle /hello {
		respond "world"
	}
}

:9001 {
	handle_path /hi {
		reverse_proxy :9000 {
			header_up Host {upstream_hostport}
		}
	}
}
```
localhost:9001/hi will redirect to localhost:9001/hello .
I'm not sure if this is a bug or a design, but I really didn't find a workaround. btw with or without `header_up Host {upstream_hostport}` doesn't redirect correctly.

**Comment by mohammed90** [comment] 2023-08-27 08:46
Thanks for your question, and we're thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

**Closed** 2023-08-27 08:46 UTC
Labels: question :grey_question:

**Comment by francislavoie** [comment] 2023-08-27 09:21
That's working as intended. I don't understand your goal so as @mohammed90 said please open a topic on the forums and explain in more detail what you're trying to achieve.

**Comment by Summpot** [comment] 2023-08-27 09:42
I'd prefer this to be a feature request as opposed to a question, as you guys wrote in the documentation for handle_path, matching and removing the url's prefix is a very common use case, the only practical use case I can think of is reverse proxying the matched request to another address, but redirecting to the original url of the reverse proxy after removing the url's path prefix is usually doesn't make sense. So I think it's important to provide a convenient way to properly handle redirects after reverse proxying, or at least provide a solution in an obvious place in the documentation (e.g. in the handle_path documentation).

**Comment by francislavoie** [comment] 2023-08-27 22:34
We still have no idea what you're trying to achieve. Please fill out the help topic template on the forums.
