### ISSUE TITLE
[feature request] ignore dotfiles by default when parsing drop-in configuration

### ISSUE THREAD

**Issue by IceCodeNew** [caddyserver/caddy#5295] opened 2023-01-10 11:46 UTC
here is the error log:
```
root@xxxxxx:~/git/private_proxy_config# docker logs -f caddy
{"level":"info","ts":1673350699.8861008,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
Error: adapting config using caddyfile: /etc/caddy/Caddyfile:39 - Error during parsing: Could not read tokens while importing /etc/caddy/sites-enabled/.gitkeep: EOF

root@xxxxxx:~/git/private_proxy_config# file caddy/sites-enabled/.gitkeep
caddy/sites-enabled/.gitkeep: empty
```

---

I was trying to git-ops my caddy configuration. Some machines do not need the drop-in configuration while others do.
I decide to put an empty file in the `sites-enabled` sub-dir so it would be tracked by git.

**Comment by francislavoie** [comment] 2023-01-10 16:03
Ignoring dot files by default seems like a good idea, when the `*` is a sole path segment.

The empty files part is a duplicate of https://github.com/caddyserver/caddy/issues/5180

I'm thinking we can probably change it from an error to a warning. Silently ignoring empty files seems not ideal.

**Comment by francislavoie** [comment] 2023-01-10 18:22
Which is why I suggest a warning as a middle-ground/compromise. It'll make it work for situations where users expect it to work, and still put up yellow flags in cases where it's probably a mistake.

**Comment by mholt** [comment] 2023-01-10 18:25
I'm probably OK with a warning.

**Comment by IceCodeNew** [comment] 2023-01-11 03:06
> I'm so on the fence about empty config files. They are nearly always an error, except for a few times they aren't. It feels wrong to start a server that is missing configuration that is expected.

How about ignoring dotfiles by default? I found you are making a point here, I agree that ignoring the empty config files is not a good idea.

**Closed** 2023-01-21 17:22 UTC
Labels: bug :lady_beetle:, good first issue :baby_chick:
