### ISSUE TITLE
add-package persistence for upgrading with distribution releases

### ISSUE THREAD

**Issue by max312** [caddyserver/caddy#5975] opened 2023-12-12 22:04 UTC
Referencing: https://github.com/caddyserver/dist/issues/106

Maybe this could be relevant here?
Like adding a "cache" file to save packages added by add-package command.

**Comment by francislavoie** [comment] 2023-12-12 22:10
Duplicate of https://github.com/caddyserver/dist/issues/106

**Closed by francislavoie** 2023-12-12 22:10 UTC
