### ISSUE TITLE
Intermittent “panic: runtime error: invalid memory address or nil pointer dereference”

### ISSUE THREAD

**Issue by palant** [caddyserver/caddy#6286] opened 2024-05-01 07:47 UTC
I’m running caddy for comparison in some static web server benchmarks. While it normally works well, this run failed due  to a Caddy crash: https://github.com/static-web-server/static-web-server/actions/runs/8905267421/job/24455725366?pr=375#step:16:34

```
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6f08aa]

goroutine 4734 [running]:
net/http.(*persistConn).closeLocked(0xc001c31c20, {0xab7540, 0xc000062c70})
	/opt/hostedtoolcache/go/1.20.8/x64/src/net/http/transport.go:2732 +0x12a
net/http.(*persistConn).close(0xc000a235b8?, {0xab7540?, 0xc000062c70?})
	/opt/hostedtoolcache/go/1.20.8/x64/src/net/http/transport.go:2717 +0xb0
net/http.(*persistConn).readLoop.func1()
	/opt/hostedtoolcache/go/1.20.8/x64/src/net/http/transport.go:2075 +0x2d
panic({0x944040, 0xe2e080})
	/opt/hostedtoolcache/go/1.20.8/x64/src/runtime/panic.go:884 +0x213
net/http.(*persistConn).Read(0xc001c31c20, {0xc00243e000?, 0x405cab?, 0x60?})
	/opt/hostedtoolcache/go/1.20.8/x64/src/net/http/transport.go:1943 +0x42
bufio.(*Reader).fill(0xc002215aa0)
	/opt/hostedtoolcache/go/1.20.8/x64/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).Peek(0xc002215aa0, 0x1)
	/opt/hostedtoolcache/go/1.20.8/x64/src/bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc001c31c20)
	/opt/hostedtoolcache/go/1.20.8/x64/src/net/http/transport.go:2107 +0x1ac
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.20.8/x64/src/net/http/transport.go:1765 +0x16ea
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6f08aa]

goroutine 4769 [running]:
net/http.(*persistConn).closeLocked(0xc002619c20, {0xab7540, 0xc000062c70})
	/opt/hostedtoolcache/go/1.20.8/x64/src/net/http/transport.go:2732 +0x12a
net/http.(*persistConn).close(0xc0026dbd38?, {0xab7540?, 0xc000062c70?})
	/opt/hostedtoolcache/go/1.20.8/x64/src/net/http/transport.go:2717 +0xb0
net/http.(*persistConn).readLoop.func1()
	/opt/hostedtoolcache/go/1.20.8/x64/src/net/http/transport.go:2075 +0x2d
panic({0x944040, 0xe2e080})
	/opt/hostedtoolcache/go/1.20.8/x64/src/runtime/panic.go:884 +0x213
net/http.(*persistConn).Read(0xc002619c20, {0xc00236d000?, 0x405cab?, 0x60?})
	/opt/hostedtoolcache/go/1.20.8/x64/src/net/http/transport.go:1943 +0x42
bufio.(*Reader).fill(0xc002362300)
	/opt/hostedtoolcache/go/1.20.8/x64/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).Peek(0xc002362300, 0x1)
	/opt/hostedtoolcache/go/1.20.8/x64/src/bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc002619c20)
	/opt/hostedtoolcache/go/1.20.8/x64/src/net/http/transport.go:2107 +0x1ac
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.20.8/x64/src/net/http/transport.go:1765 +0x16ea
Error: Process completed with exit code 2.
```

This run used pre-compiled Caddy 2.7.6 from Gihub releases. It was benchmarking [listing of this directory](https://github.com/static-web-server/benchmarks-setup/tree/v0.2/testroot) with [vegeta](https://github.com/tsenart/vegeta/). The [configuration file](https://github.com/static-web-server/benchmarks-setup/blob/v0.2/config/Caddyfile) is minimal:

```
http://localhost:8080 {
  root * /home/runner/work/static-web-server/static-web-server/benchmarks-setup/testroot
  file_server browse {
    precompressed gzip
  }
  encode {
    gzip
    minimum_length 100
  }
}
```

**Comment by francislavoie** [comment] 2024-05-01 08:08
That's weird. The stack trace is entirely within Go stdlib code, so I have no idea where to start with this.

Anyway, can you try with `v2.8.0-beta.1` instead?

**Comment by palant** [comment] 2024-05-01 08:21
This should be possible, even though running benchmarks against a pre-release version might not be the best idea. Given that the issue is intermittent, I’m not sure this would accomplish much however. We’ve had a few dozen successful runs before this crash happened. So it would take quite some time to learn whether `v2.8.0-beta.1` is affected.

**Comment by francislavoie** [comment] 2024-05-01 08:26
Okay.

Well, I think I'll close this for now because we don't have any actionable information here, but we can reopen if you manage to find a way to replicate it (ideally with the latest version, because it may have been fixed in one way or another since then).

**Closed by francislavoie** 2024-05-01 08:26 UTC

**Comment by mholt** [comment] 2024-05-01 14:48
Interesting... possibly a bug in Go?

Does the bug occur if you remove the `encode` directive?

**Comment by palant** [comment] 2024-05-01 16:56
> Does the bug occur if you remove the `encode` directive?

Given that I’ve seen this crash exactly once so far – I have no idea. I’ve only added Caddy to the benchmarks two days ago.

**Comment by mholt** [comment] 2024-05-01 21:45
Thanks for reporting it nonetheless. I'm curious if you see it again, esp. without `encode` there! (And if you don't see it, I'd also like to know that.) Best: a deterministic way to reproduce this (can be difficult, I know).

We'll leave this closed for now since it doesn't seem to indicate a bug in Caddy itself, but I'd definitely be curious if you have more information later!
