### ISSUE TITLE
APT Update: Cloudsmith 402 Payment required error

### ISSUE THREAD

**Issue by hundehausen** [caddyserver/caddy#6212] opened 2024-04-03 11:11 UTC
When running `apt update`

I get:

```
E: Failed to fetch https://dl.cloudsmith.io/public/caddy/stable/deb/debian/dists/any-version/InRelease  402  Payment Required [IP: 3.160.150.99 443]
E: The repository 'https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease' is no longer signed.
```

**Comment by syedtaqi95** [comment] 2024-04-03 11:44
+1, just got the same error when updating caddy using apt on Ubuntu 22.04.

**Comment by mohammed90** [comment] 2024-04-03 12:35
Duplicate of caddyserver/dist#115.

> Seems like cloudsmith want some cash https://cloudsmith.com/pricing

Cloudsmith generously offers us (Caddy) an extended bandwidth quota as part of their OSS support. Unfortunately, our apt repo was abused by being used in CI, which consumed all of our quota in **3 days**. We're grateful for Cloudsmith.

Let's move the conversation to the other ticket.

**Closed by mohammed90** 2024-04-03 12:35 UTC
