### ISSUE TITLE
ACME `"provisioner  not found"` when accessing directory and using local certs

### ISSUE THREAD

**Issue by ViViDboarder** [caddyserver/caddy#5929] opened 2023-11-06 21:39 UTC
I'm trying to run Caddy as an internal ACME CA. When I try to curl `/acme/local/directory`, I get the following response `{"type":"notFound","detail":"resource not found","message":"provisioner  not found"}`. I've created a bare bones test Caddyfile to reproduce the issue.

Here is my Caddyfile:
```Caddyfile
{
    local_certs
}

localhost

acme_server
```
After this, I try to curl using the following:
```bash
$ curl --insecure https://localhost:443/acme/local/directory
```
The response is then `{"type":"notFound","detail":"resource not found","message":"provisioner  not found"}`.

I'm expecting the ACME directory for the cert.

**Comment by francislavoie** [comment] 2023-11-06 21:43
Duplicate of https://github.com/caddyserver/caddy/issues/5911. Sorry, 2.7.5 broke it. You can use 2.7.4 for the time being, or build from `master` until we cut a release.

**Closed by francislavoie** 2023-11-06 21:43 UTC

**Comment by ViViDboarder** [comment] 2023-11-06 22:23
I _swear_ I searched for this before submitting (and doing all my debugging). Anyway, thanks for pointing me to the tag. 👍
