### ISSUE TITLE
Curly brackets in file- and directory names returns a 404

### ISSUE THREAD

**Issue by ngitzarak** [caddyserver/caddy#4044] opened 2021-02-28 19:20 UTC
Can anyone explain to me why a request for a file or directory with { curly brackets } in its name fails with a 404?

**Comment by Mohammed90** [comment] 2021-02-28 20:09
Duplicate of #4027

**Closed by Mohammed90** 2021-02-28 20:09 UTC
Labels: duplicate

**Comment by mholt** [comment] 2021-03-01 20:50
(Fixed! https://github.com/caddyserver/caddy/commit/5bf0a55df499e189424103d87d93960395d3172f)
