### ISSUE TITLE
500 Error Occurs When Accessing a Simple txt2html-Converted 'u-boot/README' via Caddy Server

### ISSUE THREAD

**Issue by 911gt3** [caddyserver/caddy#5778] opened 2023-08-24 11:20 UTC
I encountered a 500 error when accessing 'u-boot/README' after setting up a cgit service using Caddy (v2.7.4). Later, I generated a static page 'README.html' using the following commands:

```bash
wget https://github.com/u-boot/u-boot/raw/master/README
wget https://git.zx2c4.com/cgit/plain/filters/html-converters/txt2html
chmod +x txt2html
cat README | ./txt2html > README.html
```

When accessing this generated page using a browser, I still face the same issue. Caddy reports an error with following log:
```log
"logger":"http.log.error","msg":"template: /README.html:798: unexpected \",\" in operand"
```

I tested the generated 'README.html' using another HTTP server and did not encounter such an issue.

**Comment by mohammed90** [comment] 2023-08-24 12:44
Thanks for your question, and we're thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

**Closed** 2023-08-24 12:44 UTC
Labels: question :grey_question:

**Comment by 911gt3** [comment] 2023-08-24 13:39
Thanks for your response.  I am inclined to consider this as an issue rather than a question. You might want to consider testing based on my description to see if you can reproduce the 500 error that I encountered.

**Comment by steffenbusch** [comment] 2023-08-24 13:48
The error message you have received indicates an issue with the [template](https://caddyserver.com/docs/caddyfile/directives/templates#templates) functionality.

These templates use `{{` and `}}` by default to indicate that a template specific instruction follows. For example `{{env "HOSTNAME"}}` will be dynamically replaced in the generated HTML with the HOSTNAME environment variable.

In the README.md you've mentioned, there are such template delimiters such as:
```
		 CFG_SYS_I2C_BUSES	{{0, {I2C_NULL_HOP}}, \
```

You might to either disable the `template` directive for that files where also README.html is in or HTML escape them with:

* `{` -> `&lcub;`
* `}` -> `&rcub;`

Hope this helps.

**Comment by mholt** [comment] 2023-08-24 13:58
Thanks for opening an issue! We'll look into this.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_ **using the latest version of Caddy.** This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

This should be the latest version of Caddy:

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Instructions -- please heed otherwise we cannot help you (help us help you!)

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222) Please enable debug and access logs.
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by 911gt3** [comment] 2023-08-24 14:21
Thanks for your help. I resolved the question by removing 'templates' from Caddyfile. This was indeed my mistake, and I apologize for any inconvenience caused.

**Comment by steffenbusch** [comment] 2023-08-24 15:05
I'm glad that the issue was solved.
I'm a Caddy newbie, and it takes some time to get into it, but I ❤️ the documentation and the examples provided as well as the help provided on the [Caddy Forum](https://caddy.community/).
