### ISSUE TITLE
Log config does not update on reload

### ISSUE THREAD

**Issue by ranisalt** [caddyserver/caddy#3411] opened 2020-05-14 02:30 UTC
I created a server and, to test, set logging to log to stdout. I then decided to move the log to a file, replacing `log stdout` with
```
log {
  output file /var/log/access.log
}
```

However issuing `caddy reload` will not pick this change, it even reports that no changes were made. It will only pick after a full restart.

### 1a. Operating system and version
Debian 9

### 1b. Caddy version (run `caddy version` or paste commit SHA)
v2.0.0 h1:pQSaIJGFluFvu8KDGDODV8u4/QRED/OPyIR+MWYYse8=

### 1c. Go version (if building Caddy from source; run `go version`)
go version go1.14.2 linux/amd64

### 2a. What happens (briefly explain what is wrong)
I change the log file path and reload the server (`caddy reload`) and the log output is not changed, it still logs to the old configured file

### 2c. Log output
Not really useful...

### 2d. Workaround(s)
Restart the server

## 3. Tutorial (minimal steps to reproduce the bug)
1. Create a Caddyfile and configure the log directive with any dest
```
output file /path/to/log
```
2. Start Caddy
3. Replace `/path/to/log` with anything else
4. Reload Caddy

**Comment by mholt** [comment] 2020-05-14 03:10
Thanks for opening an issue! We'll look into this.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by ranisalt** [comment] 2020-05-14 03:56
I appended the additional info to the OP

**Comment by francislavoie** [comment] 2020-05-14 04:45
> 2. Start Caddy

How are you starting Caddy? Are you using a service?

If you run `curl localhost:2019/config/`, what do you see?

**Comment by ranisalt** [comment] 2020-05-14 04:53
I am running it inside a Docker container, using the `caddy` image.



> If you run `curl localhost:2019/config/`, what do you see?

```
{"apps":{"http":{"servers":{"srv0":{"listen":[":443"],"logs":{"logger_names":{"[redacted]":"log0"}},"routes":[{"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"reverse_proxy","upstreams":[{"dial":"[redacted]"}]}]}]}],"match":[{"host":["[redacted]"]}],"terminal":true},{"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"vars","root":"/app/www1"}]},{"handle":[{"handler":"rewrite","uri":"{http.matchers.file.relative}"}],"match":[{"file":{"try_files":["{http.request.uri.path}","index.html"]}}]}]}],"match":[{"host":["[redacted]"]}],"terminal":true},{"handle":[{"handler":"subroute","routes":[{"group":"group4","handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"rewrite","strip_path_prefix":"/api"},{"handler":"reverse_proxy","upstreams":[{"dial":"[redacted]"}]}]}]}],"match":[{"path":["/api/*"]}]},{"group":"group4","handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"vars","root":"/app/www2"}]},{"handle":[{"handler":"rewrite","uri":"{http.matchers.file.relative}"}],"match":[{"file":{"try_files":["{http.request.uri.path}","/index.html"]}}]},{"handle":[{"handler":"file_server","hide":["/etc/caddy/Caddyfile"]}]}]}]}]}],"match":[{"host":["[redacted]"]}],"terminal":true}],"tls_connection_policies":[{"match":{"sni":["[redacted]"]}},{"match":{"sni":["[redacted]"]}},{"match":{"sni":["[redacted]"]}},{}]}}},"tls":{"automation":{"policies":[{"issuer":{"ca":"https://acme-staging-v02.api.letsencrypt.org/directory","challenges":{"dns":{"provider":{"api_token":"[redacted]","name":"cloudflare"}}},"email":"[redacted]","module":"acme"},"subjects":["[redacted]","[redacted]","[redacted]"]},{"issuer":{"ca":"https://acme-staging-v02.api.letsencrypt.org/directory","email":"[redacted]","module":"acme"}}]}}},"logging":{"logs":{"default":{"level":"DEBUG"},"log0":{"encoder":{"format":"logfmt"},"include":["http.log.access.log0"],"level":"DEBUG","writer":{"filename":"/var/log/api.access.log","output":"file"}}}}}
```

**Comment by francislavoie** [comment] 2020-05-14 05:01
Right at the end, I'm already seeing `"filename":"/var/log/api.access.log"`.

Looks like it's already running with that config.

What does your docker run command or docker-compose config look like?

There's still a lack of information here, we can't reproduce this issue without clear, exact steps.

**Closed** 2020-05-14 05:01 UTC
Labels: needs info

**Comment by mholt** [comment] 2020-05-14 18:29
Yeah, seems to be working here with the instructions provided; and it appears that the config change did take place -- so, if you can show that there is a bug in Caddy, please provide more specific information and we'll take a look.

**Comment by ranisalt** [comment] 2020-05-19 18:17
The thing is if I change the `log` line to anything else and reload the server, this change is not picked up.

So, if I change it to
```
output file /var/log/anything.log
```
And `caddy reload`, the next request to `/config/` will still return
```
"filename":"/var/log/api.access.log"
```
A full restart is required to change this.

**Comment by mholt** [comment] 2020-05-19 18:25
@ranisalt What do the logs show when you do the reload?

**Comment by ranisalt** [comment] 2020-05-19 18:54
```
May 19 20:53:21 docker[5393]: {"level":"info","ts":1589914401.7030447,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
May 19 20:53:21 docker[882]: {"level":"info","ts":1589914401.7079124,"logger":"admin.api","msg":"received request","method":"POST","host":"localhost:2019","uri":"/load","remote_addr":"127.0.0.1:40942","headers":{"Accept-Encoding":["gzip"],"Content-Length":["3105"],"Content-Type":["application/json"],"Origin":["localhost:2019"],"User-Agent":["Go-http-client/1.1"]}}
May 19 20:53:21 docker[882]: {"level":"info","ts":1589914401.7107785,"logger":"admin.api","msg":"config is unchanged"}
May 19 20:53:21 docker[882]: {"level":"info","ts":1589914401.7109783,"logger":"admin.api","msg":"load complete"}
```

**Comment by francislavoie** [comment] 2020-05-19 20:20
Interesting. Thanks for following up on that. What were you using to edit the file then?

**Comment by ranisalt** [comment] 2020-05-19 20:20
I am using vim with the default configuration for Debian 9.

**Comment by mholt** [comment] 2020-05-19 20:24
Ah, interesting. Glad that Caddy's log can help expose an infrastructure quirk/bug!

**Comment by francislavoie** [comment] 2020-05-19 20:26
Okay I think we'll consider whether it makes sense to change the recommended volume path in our docker docs to `/etc/caddy` instead. :+1:
