### ISSUE TITLE
no information found to solve challenge for identifier

### ISSUE THREAD

**Issue by indy-singh** [caddyserver/caddy#5684] opened 2023-08-04 07:08 UTC
Hi,

Not sure what is going on, but Caddy blew up. I installed Caddy on `Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-78-generic x86_64)` using [these instructions](https://caddyserver.com/docs/install#debian-ubuntu-raspbian)

<details>
  <summary>StackTrace</summary>
  
```log
2023/08/02 22:38:59.770 INFO    using adjacent Caddyfile
2023/08/02 22:38:59.772 INFO    admin   admin endpoint started  {"address": "localhost:2019", "enforce_origin": false, "origins": ["//localhost:2019", "//[::1]:2019", "//127.0.0.1:2019"]}
2023/08/02 22:38:59.772 INFO    http.auto_https server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS {"server_name": "srv0", "https_port": 443}
2023/08/02 22:38:59.772 INFO    http.auto_https enabling automatic HTTP->HTTPS redirects        {"server_name": "srv0"}
2023/08/02 22:38:59.773 INFO    http    enabling HTTP/3 listener        {"addr": ":443"}
2023/08/02 22:38:59.773 INFO    http.log        server running  {"name": "srv0", "protocols": ["h1", "h2", "h3"]}
2023/08/02 22:38:59.774 INFO    http.log        server running  {"name": "remaining_auto_https_redirects", "protocols": ["h1", "h2", "h3"]}
2023/08/02 22:38:59.774 INFO    http    enabling automatic TLS certificate management   {"domains": ["hooks.s3dedupe.com", "api.s3dedupe.com", "s3dedupe.com"]}
2023/08/02 22:38:59.776 INFO    autosaved config (load with --resume flag)      {"file": "/root/.config/caddy/autosave.json"}
2023/08/02 22:38:59.776 INFO    serving initial configuration
2023/08/02 22:38:59.776 INFO    tls.cache.maintenance   started background certificate maintenance      {"cache": "0xc000300a00"}
2023/08/02 22:38:59.776 INFO    tls     cleaning storage unit   {"description": "FileStorage:/root/.local/share/caddy"}
2023/08/02 22:38:59.777 INFO    tls     finished cleaning storage units
2023/08/03 13:15:28.768 ERROR   tls     tls-alpn challenge      {"remote_addr": "47.242.57.127:32128", "server_name": "s3dedupe.com", "error": "no information found to solve challenge for identifier: s3dedupe.com"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x903750]

goroutine 2289 [running]:
github.com/caddyserver/certmagic.(*Config).getCertDuringHandshake(0xc000464820, {0x1f0bbe8, 0xc0000420d8}, _, _)
        github.com/caddyserver/certmagic@v0.19.1/handshake.go:378 +0x1390
github.com/caddyserver/certmagic.(*Config).GetCertificateWithContext(0xc000464820, {0x1f0bbe8, 0xc0000420d8}, 0xc000464750)
        github.com/caddyserver/certmagic@v0.19.1/handshake.go:84 +0xbff
github.com/caddyserver/certmagic.(*Config).GetCertificate(0xc00067efc0?, 0xc0002e0290?)
        github.com/caddyserver/certmagic@v0.19.1/handshake.go:50 +0x2a
github.com/caddyserver/caddy/v2/modules/caddytls.(*ConnectionPolicy).buildStandardTLSConfig.func1(0xc000464750)
        github.com/caddyserver/caddy/v2@v2.7.0/modules/caddytls/connpolicy.go:232 +0x14f
github.com/quic-go/qtls-go1-20.(*config).getCertificate(0xc000446480, 0xc000464750)
        github.com/quic-go/qtls-go1-20@v0.3.0/common.go:1086 +0x42
github.com/quic-go/qtls-go1-20.(*serverHandshakeStateTLS13).pickCertificate(0xc000521be8)
        github.com/quic-go/qtls-go1-20@v0.3.0/handshake_server_tls13.go:415 +0x66
github.com/quic-go/qtls-go1-20.(*serverHandshakeStateTLS13).handshake(0xc000521be8)
        github.com/quic-go/qtls-go1-20@v0.3.0/handshake_server_tls13.go:60 +0x53
github.com/quic-go/qtls-go1-20.(*Conn).serverHandshake(0xc00032a700, {0x1f0bbb0, 0xc000448280})
        github.com/quic-go/qtls-go1-20@v0.3.0/handshake_server.go:53 +0x188
github.com/quic-go/qtls-go1-20.(*Conn).handshakeContext(0xc00032a700, {0x1f0bc58, 0xc00064e990})
        github.com/quic-go/qtls-go1-20@v0.3.0/conn.go:1540 +0x3ce
github.com/quic-go/qtls-go1-20.(*Conn).HandshakeContext(0xc0004617d0?, {0x1f0bc58?, 0xc00064e990?})
        github.com/quic-go/qtls-go1-20@v0.3.0/conn.go:1480 +0x25
created by github.com/quic-go/qtls-go1-20.(*QUICConn).Start
        github.com/quic-go/qtls-go1-20@v0.3.0/quic.go:179 +0xcf
root@drop-001:~# ./run-caddy.sh
2023/08/04 06:46:19.112 INFO    using adjacent Caddyfile
2023/08/04 06:46:19.119 INFO    admin   admin endpoint started  {"address": "localhost:2019", "enforce_origin": false, "origins": ["//localhost:2019", "//[::1]:2019", "//127.0.0.1:2019"]}
2023/08/04 06:46:19.120 INFO    http.auto_https server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS {"server_name": "srv0", "https_port": 443}
2023/08/04 06:46:19.121 INFO    http.auto_https enabling automatic HTTP->HTTPS redirects        {"server_name": "srv0"}
2023/08/04 06:46:19.122 INFO    tls.cache.maintenance   started background certificate maintenance      {"cache": "0xc000464e80"}
2023/08/04 06:46:19.124 INFO    http    enabling HTTP/3 listener        {"addr": ":443"}
2023/08/04 06:46:19.125 INFO    http.log        server running  {"name": "srv0", "protocols": ["h1", "h2", "h3"]}
2023/08/04 06:46:19.125 INFO    http.log        server running  {"name": "remaining_auto_https_redirects", "protocols": ["h1", "h2", "h3"]}
2023/08/04 06:46:19.125 INFO    http    enabling automatic TLS certificate management   {"domains": ["hooks.s3dedupe.com", "api.s3dedupe.com", "s3dedupe.com"]}
2023/08/04 06:46:19.130 INFO    autosaved config (load with --resume flag)      {"file": "/root/.config/caddy/autosave.json"}
2023/08/04 06:46:19.130 INFO    serving initial configuration
2023/08/04 06:46:19.131 INFO    tls     cleaning storage unit   {"description": "FileStorage:/root/.local/share/caddy"}
2023/08/04 06:46:19.134 INFO    tls     finished cleaning storage units
```
</details>

Caddy version:- `v2.7.0 h1:ZrAwnBzZ/FBoNw+WBlF2HER8oEs/O7c20ku6nbWFqco=`

<details>
  <summary>caddy build-info</summary>
  
```
root@drop-001:~# caddy build-info
go      go1.20.6
path    command-line-arguments
dep     filippo.io/edwards25519 v1.0.0  h1:0wAIcmJUqRdI8IJ/3eGi5/HwXZWPujYXXlkrQogz0Ek=
dep     github.com/AndreasBriese/bbloom v0.0.0-20190825152654-46b345b51c96      h1:cTp8I5+VIoKjsnZuH8vjyaysT/ses3EvZeaV/1UkF2M=
dep     github.com/BurntSushi/toml      v1.3.2  h1:o7IhLm0Msx3BaB+n3Ag7L8EVlByGnpq14C4YWiu/gL8=
dep     github.com/Masterminds/goutils  v1.1.1  h1:5nUrii3FMTL5diU80unEVvNevw1nH4+ZV4DSLVJLSYI=
dep     github.com/Masterminds/semver/v3        v3.2.0  h1:3MEsd0SM6jqZojhjLWWeBY+Kcjy9i6MQAeY7YgDP83g=
dep     github.com/Masterminds/sprig/v3 v3.2.3  h1:eL2fZNezLomi0uOLqjQoN6BfsDD+fyLtgbJMAj9n6YA=
dep     github.com/alecthomas/chroma/v2 v2.7.0  h1:hm1rY6c/Ob4eGclpQ7X/A3yhqBOZNUTk9q+yhyLIViI=
dep     github.com/antlr/antlr4/runtime/Go/antlr/v4     v4.0.0-20230305170008-8188dc5388df      h1:7RFfzj4SSt6nnvCPbCqijJi1nWCd+TqAT3bYCStRC18=
dep     github.com/aryann/difflib       v0.0.0-20210328193216-ff5ff6dc229b      h1:uUXgbcPDK3KpW29o4iy7GtuappbWT0l5NaMo9H9pJDw=
dep     github.com/beorn7/perks v1.0.1  h1:VlbKKnNfV8bJzeqoa4cOKqO6bYr3WgKZxO8Z16+hsOM=
dep     github.com/caddyserver/caddy/v2 v2.7.0  h1:ZrAwnBzZ/FBoNw+WBlF2HER8oEs/O7c20ku6nbWFqco=
dep     github.com/caddyserver/certmagic        v0.19.1 h1:4jyOYm2DHvQI8YM0sk6qm62Gl5XznHxiMBMWjMTlQkw=
dep     github.com/cenkalti/backoff/v4  v4.2.1  h1:y4OZtCnogmCPw98Zjyt5a6+QwPLGkiQsYW5oUqylYbM=
dep     github.com/cespare/xxhash       v1.1.0  h1:a6HrQnmkObjyL+Gs60czilIUGqrzKutQD6XZog3p+ko=
dep     github.com/cespare/xxhash/v2    v2.2.0  h1:DC2CZ1Ep5Y4k3ZQ899DldepgrayRUGE6BBZ/cd9Cj44=
dep     github.com/chzyer/readline      v1.5.1  h1:upd/6fQk4src78LMRzh5vItIt361/o4uq553V8B5sGI=
dep     github.com/cpuguy83/go-md2man/v2        v2.0.2  h1:p1EgwI/C7NhT0JmVkwCD2ZBK8j4aeHQX2pMHHBfMQ6w=
dep     github.com/dgraph-io/badger     v1.6.2  h1:mNw0qs90GVgGGWylh0umH5iag1j6n/PeJtNvL6KY/x8=
dep     github.com/dgraph-io/badger/v2  v2.2007.4       h1:TRWBQg8UrlUhaFdco01nO2uXwzKS7zd+HVdwV/GHc4o=
dep     github.com/dgraph-io/ristretto  v0.1.0  h1:Jv3CGQHp9OjuMBSne1485aDpUkTKEcUqF+jm/LuerPI=
dep     github.com/dgryski/go-farm      v0.0.0-20200201041132-a6ae2369ad13      h1:fAjc9m62+UWV/WAFKLNi6ZS0675eEUC9y3AlwSbQu1Y=
dep     github.com/dlclark/regexp2      v1.7.0  h1:7lJfhqlPssTb1WQx4yvTHN0uElPEv52sbaECrAQxjAo=
dep     github.com/dustin/go-humanize   v1.0.1  h1:GzkhY7T5VNhEkwH0PVJgjz+fX1rhBrR7pRT3mDkpeCY=
dep     github.com/felixge/httpsnoop    v1.0.3  h1:s/nj+GCswXYzN5v2DpNMuMQYe+0DDwt5WVCU6CWBdXk=
dep     github.com/fxamacker/cbor/v2    v2.4.0  h1:ri0ArlOR+5XunOP8CRUowT0pSJOwhW098ZCUyskZD88=
dep     github.com/go-chi/chi   v4.1.2+incompatible     h1:fGFk2Gmi/YKXk0OmGfBh0WgmN3XB8lVnEyNz34tQRec=
dep     github.com/go-kit/kit   v0.10.0 h1:dXFJfIHVvUcpSgDOV+Ne6t7jXri8Tfv2uOLHUZ2XNuo=
dep     github.com/go-logfmt/logfmt     v0.5.1  h1:otpy5pqBCBZ1ng9RQ0dPu4PN7ba75Y/aA+UpowDyNVA=
dep     github.com/go-logr/logr v1.2.4  h1:g01GSCwiDw2xSZfjJ2/T9M+S6pFdcNtFYsp+Y43HYDQ=
dep     github.com/go-logr/stdr v1.2.2  h1:hSWxHoqTgW2S2qGc0LTAI563KZ5YKYRhT3MFKZMbjag=
dep     github.com/go-sql-driver/mysql  v1.7.0  h1:ueSltNNllEqE3qcWBTD0iQd3IpL/6U+mJxLkazJ7YPc=
dep     github.com/golang/glog  v1.1.0  h1:/d3pCKDPWNnvIWe0vVUpNP32qc8U3PDVxySP/y360qE=
dep     github.com/golang/protobuf      v1.5.3  h1:KhyjKVUg7Usr/dYsdSqoFveMYd5ko72D+zANwlG1mmg=
dep     github.com/golang/snappy        v0.0.4  h1:yAGX7huGHXlcLOEtBnF4w7FQwA26wojNCwOYAEhLjQM=
dep     github.com/google/cel-go        v0.15.1 h1:iTgVZor2x9okXtmTrqO8cg4uvqIeaBcWhXtruaWFMYQ=
dep     github.com/google/certificate-transparency-go   v1.1.4  h1:hCyXHDbtqlr/lMXU0D4WgbalXL0Zk4dSWWMbPV8VrqY=
dep     github.com/google/go-tpm        v0.3.3  h1:P/ZFNBZYXRxc+z7i5uyd8VP7MaDteuLZInzrH2idRGo=
dep     github.com/google/go-tspi       v0.3.0  h1:ADtq8RKfP+jrTyIWIZDIYcKOMecRqNJFOew2IT0Inus=
dep     github.com/google/uuid  v1.3.0  h1:t6JiXgmwXMjEs8VusXIJk2BXHsn+wx8BZdTaoZ5fu7I=
dep     github.com/grpc-ecosystem/grpc-gateway/v2       v2.7.0  h1:BZHcxBETFHIdVyhyEfOvn/RdU/QGdLI4y34qQGjGWO0=
dep     github.com/huandu/xstrings      v1.3.3  h1:/Gcsuc1x8JVbJ9/rlye4xZnVAbEkGauT8lbebqcQws4=
dep     github.com/imdario/mergo        v0.3.12 h1:b6R2BslTbIEToALKP7LxUvijTsNI9TAe80pLWN2g/HU=
dep     github.com/jackc/chunkreader/v2 v2.0.1  h1:i+RDz65UE+mmpjTfyz0MoVTnzeYxroil2G82ki7MGG8=
dep     github.com/jackc/pgconn v1.14.0 h1:vrbA9Ud87g6JdFWkHTJXppVce58qPIdP7N8y0Ml/A7Q=
dep     github.com/jackc/pgio   v1.0.0  h1:g12B9UwVnzGhueNavwioyEEpAmqMe1E/BN9ES+8ovkE=
dep     github.com/jackc/pgpassfile     v1.0.0  h1:/6Hmqy13Ss2zCq62VdNG8tM1wchn8zjSGOBJ6icpsIM=
dep     github.com/jackc/pgproto3/v2    v2.3.2  h1:7eY55bdBeCz1F2fTzSz69QC+pG46jYq9/jtSPiJ5nn0=
dep     github.com/jackc/pgservicefile  v0.0.0-20221227161230-091c0ba34f0a      h1:bbPeKD0xmW/Y25WS6cokEszi5g+S0QxI/d45PkRi7Nk=
dep     github.com/jackc/pgtype v1.14.0 h1:y+xUdabmyMkJLyApYuPj38mW+aAIqCe5uuBB51rH3Vw=
dep     github.com/jackc/pgx/v4 v4.18.0 h1:Ltaa1ePvc7msFGALnCrqKJVEByu/qYh5jJBYcDtAno4=
dep     github.com/klauspost/compress   v1.16.7 h1:2mk3MPGNzKyxErAw8YaohYh69+pa4sIQSC0fPGCFR9I=
dep     github.com/klauspost/cpuid/v2   v2.2.5  h1:0E5MSMDEoAulmXNFquVs//DdoomxaoTY1kUhbc/qbZg=
dep     github.com/libdns/libdns        v0.2.1  h1:Wu59T7wSHRgtA0cfxC+n1c/e+O3upJGWytknkmFEDis=
dep     github.com/manifoldco/promptui  v0.9.0  h1:3V4HzJk1TtXW1MTZMP7mdlwbBpIinw3HztaIlYthEiA=
dep     github.com/mastercactapus/proxyprotocol v0.0.4  h1:qSY75IZF30ZqIU9iW1ip3I7gTnm8wRAnGWqPxCBVgq0=
dep     github.com/mattn/go-colorable   v0.1.8  h1:c1ghPdyEDarC70ftn0y+A/Ee++9zz8ljHG1b13eJ0s8=
dep     github.com/mattn/go-isatty      v0.0.16 h1:bq3VjFmv/sOjHtdEhmkEV4x1AJtvUvOJ2PFAZ5+peKQ=
dep     github.com/matttproud/golang_protobuf_extensions        v1.0.1  h1:4hp9jkHxhMHkqkrB3Ix0jegS5sx/RkqARlsWZ6pIwiU=
dep     github.com/mgutz/ansi   v0.0.0-20200706080929-d51e80ef957d      h1:5PJl274Y63IEHC+7izoQE9x6ikvDFZS2mDVS3drnohI=
dep     github.com/mholt/acmez  v1.2.0  h1:1hhLxSgY5FvH5HCnGUuwbKY2VQVo8IU7rxXKSnZ7F30=
dep     github.com/micromdm/scep/v2     v2.1.0  h1:2fS9Rla7qRR266hvUoEauBJ7J6FhgssEiq2OkSKXmaU=
dep     github.com/miekg/dns    v1.1.55 h1:GoQ4hpsj0nFLYe+bWiCToyrBEJXkQfOOIvFGFy0lEgo=
dep     github.com/mitchellh/copystructure      v1.2.0  h1:vpKXTN4ewci03Vljg/q9QvCGUDttBOGBIa15WveJJGw=
dep     github.com/mitchellh/go-ps      v1.0.0  h1:i6ampVEEF4wQFF+bkYfwYgY+F/uYJDktmvLPf7qIgjc=
dep     github.com/mitchellh/reflectwalk        v1.0.2  h1:G2LzWKi524PWgd3mLHV8Y5k7s6XUvT0Gef6zxSIeXaQ=
dep     github.com/pkg/errors   v0.9.1  h1:FEBLx1zS214owpjy7qsBeixbURkuhQAwrK5UwLGTwt4=
dep     github.com/prometheus/client_golang     v1.14.0 h1:nJdhIvne2eSX/XRAFV9PcvFFRbrjbcTUj0VP62TMhnw=
dep     github.com/prometheus/client_model      v0.3.0  h1:UBgGFHqYdG/TPFD1B1ogZywDqEkwp3fBMvqdiQ7Xew4=
dep     github.com/prometheus/common    v0.37.0 h1:ccBbHCgIiT9uSoFY0vX8H3zsNR5eLt17/RQLUvn8pXE=
dep     github.com/prometheus/procfs    v0.8.0  h1:ODq8ZFEaYeCaZOJlZZdJA2AbQR98dSHSM1KW/You5mo=
dep     github.com/quic-go/qpack        v0.4.0  h1:Cr9BXA1sQS2SmDUWjSofMPNKmvF6IiIfDRmgU0w1ZCo=
dep     github.com/quic-go/qtls-go1-20  v0.3.0  h1:NrCXmDl8BddZwO67vlvEpBTwT89bJfKYygxv4HQvuDk=
dep     github.com/quic-go/quic-go      v0.37.1 h1:M+mcsFq9KoxVjCetIwH65TvusW1UdRBc6zmxI6pkeD0=
dep     github.com/rs/xid       v1.5.0  h1:mKX4bl4iPYJtEIxp6CYiUuLQ/8DYMoz0PUdtGgMFRVc=
dep     github.com/russross/blackfriday/v2      v2.1.0  h1:JIOH55/0cWyOuilr9/qlrm0BSXldqnqwMsf35Ld67mk=
dep     github.com/shopspring/decimal   v1.2.0  h1:abSATXmQEYyShuxI4/vyW3tV1MrKAJzCZ/0zLUXYbsQ=
dep     github.com/shurcooL/sanitized_anchor_name       v1.0.0  h1:PdmoCO6wvbs+7yrJyMORt4/BmY5IYyJwS/kOiWx8mHo=
dep     github.com/sirupsen/logrus      v1.9.3  h1:dueUQJ1C2q9oE3F7wvmSGAaVtTmUizReu6fjN8uqzbQ=
dep     github.com/slackhq/nebula       v1.6.1  h1:/OCTR3abj0Sbf2nGoLUrdDXImrCv0ZVFpVPP5qa0DsM=
dep     github.com/smallstep/certificates       v0.24.3-rc.5    h1:l9N7NmFqW5it5UcDtbyZ4CrrvYYiHRM7Dj7Mk+YC1Io=
dep     github.com/smallstep/go-attestation     v0.4.4-0.20230509120429-e17291421738    h1:h+cZgVniTaE0uuRMdxTThLaJeuxsv4aas6oStz6f5VQ=
dep     github.com/smallstep/nosql      v0.6.0  h1:ur7ysI8s9st0cMXnTvB8tA3+x5Eifmkb6hl4uqNV5jc=
dep     github.com/smallstep/truststore v0.12.1 h1:guLUKkc1UlsXeS3t6BuVMa4leOOpdiv02PCRTiy1WdY=
dep     github.com/spf13/cast   v1.4.1  h1:s0hze+J0196ZfEMTs80N7UlFt0BDuQ7Q+JDnHiMWKdA=
dep     github.com/spf13/cobra  v1.7.0  h1:hyqWnYt1ZQShIddO5kBpj3vu05/++x6tJ6dg8EC572I=
dep     github.com/spf13/pflag  v1.0.5  h1:iy+VFUOCP1a+8yFto/drg2CJ5u0yRoB7fZw3DKv/JXA=
dep     github.com/stoewer/go-strcase   v1.2.0  h1:Z2iHWqGXH00XYgqDmNgQbIBxf3wrNq0F3feEy0ainaU=
dep     github.com/tailscale/tscert     v0.0.0-20230509043813-4e9cb4f2b4ad      h1:JEOo9j4RzDPBJFTU9YZ/QPkLtfV8+6PbZFFOSUx5VP4=
dep     github.com/urfave/cli   v1.22.14        h1:ebbhrRiGK2i4naQJr+1Xj92HXZCrK7MsyTS/ob3HnAk=
dep     github.com/x448/float16 v0.8.4  h1:qLwI1I70+NjRFUR3zs1JPUCgaCXSh3SW62uAKT1mSBM=
dep     github.com/yuin/goldmark        v1.5.5  h1:IJznPe8wOzfIKETmMkd06F8nXkmlhaHqFRM9l1hAGsU=
dep     github.com/yuin/goldmark-highlighting/v2        v2.0.0-20230729083705-37449abec8cc      h1:+IAOyRda+RLrxa1WC7umKOZRsGq4QrFFMYApOeHzQwQ=
dep     github.com/zeebo/blake3 v0.2.3  h1:TFoLXsjeXqRNFxSbk35Dk4YtszE/MQQGK10BH4ptoTg=
dep     go.etcd.io/bbolt        v1.3.7  h1:j+zJOnnEjF/kyHlDDgGnVL/AIqIJPq8UoB2GSNfkUfQ=
dep     go.mozilla.org/pkcs7    v0.0.0-20210826202110-33d05740a352      h1:CCriYyAfq1Br1aIYettdHZTy8mBTIPo7We18TuO/bak=
dep     go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp   v0.42.0 h1:pginetY7+onl4qN1vl0xW/V/v6OBZ0vVdH+esuJgvmM=
dep     go.opentelemetry.io/contrib/propagators/autoprop        v0.42.0 h1:s2RzYOAqHVgG23q8fPWYChobUoZM6rJZ98EnylJr66w=
dep     go.opentelemetry.io/contrib/propagators/aws     v1.17.0 h1:IX8d7l2uRw61BlmZBOTQFaK+y22j6vytMVTs9wFrO+c=
dep     go.opentelemetry.io/contrib/propagators/b3      v1.17.0 h1:ImOVvHnku8jijXqkwCSyYKRDt2YrnGXD4BbhcpfbfJo=
dep     go.opentelemetry.io/contrib/propagators/jaeger  v1.17.0 h1:Zbpbmwav32Ea5jSotpmkWEl3a6Xvd4tw/3xxGO1i05Y=
dep     go.opentelemetry.io/contrib/propagators/ot      v1.17.0 h1:ufo2Vsz8l76eI47jFjuVyjyB3Ae2DmfiCV/o6Vc8ii0=
dep     go.opentelemetry.io/otel        v1.16.0 h1:Z7GVAX/UkAXPKsy94IU+i6thsQS4nb7LviLpnaNeW8s=
dep     go.opentelemetry.io/otel/exporters/otlp/internal/retry  v1.16.0 h1:t4ZwRPU+emrcvM2e9DHd0Fsf0JTPVcbfa/BhTDF03d0=
dep     go.opentelemetry.io/otel/exporters/otlp/otlptrace       v1.16.0 h1:cbsD4cUcviQGXdw8+bo5x2wazq10SKz8hEbtCRPcU78=
dep     go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.16.0 h1:TVQp/bboR4mhZSav+MdgXB8FaRho1RC8UwVn3T0vjVc=
dep     go.opentelemetry.io/otel/metric v1.16.0 h1:RbrpwVG1Hfv85LgnZ7+txXioPDoh6EdbZHo26Q3hqOo=
dep     go.opentelemetry.io/otel/sdk    v1.16.0 h1:Z1Ok1YsijYL0CSJpHt4cS3wDDh7p572grzNrBMiMWgE=
dep     go.opentelemetry.io/otel/trace  v1.16.0 h1:8JRpaObFoW0pxuVPapkgH8UhHQj+bJW8jJsCZEu5MQs=
dep     go.opentelemetry.io/proto/otlp  v0.19.0 h1:IVN6GR+mhC4s5yfcTbmzHYODqvWAp3ZedA2SJPI1Nnw=
dep     go.step.sm/cli-utils    v0.8.0  h1:b/Tc1/m3YuQq+u3ghTFP7Dz5zUekZj6GUmd5pCvkEXQ=
dep     go.step.sm/crypto       v0.33.0 h1:fP8awo6YkZ0/rrLhzbHYA3U8g24VnWEebZRnGwUobRo=
dep     go.step.sm/linkedca     v0.20.0 h1:bH41rvyDm3nSSJ5xgGsKUZOpzJcq5x2zacMIeqtq9oI=
dep     go.uber.org/multierr    v1.11.0 h1:blXXJkSxSSfBVBlC76pxqeO+LN3aDfLQo+309xJstO0=
dep     go.uber.org/zap v1.25.0 h1:4Hvk6GtkucQ790dqmj7l1eEnRdKm3k3ZUrUMS2d5+5c=
dep     golang.org/x/crypto     v0.11.0 h1:6Ewdq3tDic1mg5xRO4milcWCfMVQhI4NkqWWvqejpuA=
dep     golang.org/x/exp        v0.0.0-20230310171629-522b1b587ee0      h1:LGJsf5LRplCck6jUCH3dBL2dmycNruWNF5xugkSlfXw=
dep     golang.org/x/net        v0.12.0 h1:cfawfvKITfUsFCeJIHJrbSxpeu/E81khclypR0GVT50=
dep     golang.org/x/sync       v0.3.0  h1:ftCYgMx6zT/asHUrPw8BLLscYtGznsLAnjq5RH9P66E=
dep     golang.org/x/sys        v0.10.0 h1:SqMFp9UcQJZa+pmYuAKjd9xq1f0j5rLcDIk0mj4qAsA=
dep     golang.org/x/term       v0.10.0 h1:3R7pNqamzBraeqj/Tj8qt1aQ2HpmlC+Cx/qL/7hn4/c=
dep     golang.org/x/text       v0.11.0 h1:LAntKIrcmeSKERyiOh0XMV39LXS8IE9UL2yP7+f5ij4=
dep     google.golang.org/genproto      v0.0.0-20230706204954-ccb25ca9f130      h1:Au6te5hbKUV8pIYWHqOUZ1pva5qK/rwbIhoXEUB9Lu8=
dep     google.golang.org/genproto/googleapis/api       v0.0.0-20230706204954-ccb25ca9f130      h1:XVeBY8d/FaK4848myy41HBqnDwvxeV3zMZhwN1TvAMU=
dep     google.golang.org/genproto/googleapis/rpc       v0.0.0-20230711160842-782d3b101e98      h1:bVf09lpb+OJbByTj913DRJioFFAjf/ZGxEz7MajTp2U=
dep     google.golang.org/grpc  v1.56.2 h1:fVRFRnXvU+x6C4IlHZewvJOVHoOv1TUuQyoRsYnB4bI=
dep     google.golang.org/protobuf      v1.31.0 h1:g0LDEJHgrBl9N9r17Ru3sqWhkIx2NB67okBHPwC7hs8=
dep     gopkg.in/natefinch/lumberjack.v2        v2.2.1  h1:bBRl1b0OH9s/DuPhuXpNl+VtCaJXFZ5/uEFST95x9zc=
dep     gopkg.in/square/go-jose.v2      v2.6.0  h1:NGk74WTnPKBNUhNzQX7PYcTLUjoq7mzKk2OKbvwk2iI=
dep     gopkg.in/yaml.v3        v3.0.1  h1:fxVm/GzAzEWqLHuvctI91KS9hhNmmWOoWu0XTYJS7CA=
build   -buildmode=exe
build   -compiler=gc
build   -trimpath=true
build   CGO_ENABLED=0
build   GOARCH=amd64
build   GOOS=linux
build   GOAMD64=v1
```
</details>

Caddyfile:-

```
s3dedupe.com {
	respond "I am alive"
}

api.s3dedupe.com {
	respond "I too, am alive!"
}

hooks.s3dedupe.com {
	reverse_proxy localhost:9000
}
```

I will caveat all of that with it is _entirely_ possible that I've done something wrong here, I'm very much green when it comes to running things on Linux. I've tried to include all the necessary information. But from a layman point of view it looks like Caddy blew up trying to serve a request from `47.242.57.127:32128`.

If you need more info, please say so :)

Cheers,
Indy

**Comment by francislavoie** [comment] 2023-08-04 15:47
Duplicate of https://github.com/caddyserver/caddy/issues/5680, we're working on it.

**Closed by francislavoie** 2023-08-04 15:47 UTC

**Comment by guotie** [comment] 2024-04-24 02:35
have you solved this problem?
