### ISSUE TITLE
Caddy 2.1.1 cannot get TLS certificate

### ISSUE THREAD

**Issue by strategist922** [caddyserver/caddy#3555] opened 2020-07-07 06:30 UTC
My Caddy version is "v2.1.1 h1:X9k1+ehZPYYrSqBvf/ocUgdLSRIuiNiMo7CvyGUQKeA="
OS: Ubuntu 20.04 LTS (GNU/Linux 5.4.0-40-generic x86_64)
I encountered this issue for tree days.....
May I know how to resolve this issue?
Error message get from "systemctl status caddy"as following:

caddy.service - Caddy
Loaded: loaded (/lib/systemd/system/caddy.service; enabled; vendor preset: enabled)
Active: active (running) since Tue 2020-07-07 10:27:53 CST; 3h 53min ago
Docs: https://caddyserver.com/docs/
Main PID: 603 (caddy)
Tasks: 8 (limit: 1074)
Memory: 50.6M
CGroup: /system.slice/caddy.service
└─603 /usr/bin/caddy run --environ --config /etc/caddy/Caddyfile
Jul 07 13:28:36 localhost caddy[603]: 2020/07/07 13:28:36 [INFO] retry due to: acme: error: 400 :: POST :: https://acme-staging-v02.api.letsencrypt.org/acm>
Jul 07 13:28:37 localhost caddy[603]: 2020/07/07 13:28:37 [ERROR] acme: error: 400 :: POST :: https://acme-staging-v02.api.letsencrypt.org/acme/new-order :>
Jul 07 13:28:37 localhost caddy[603]: 2020/07/07 13:28:37 [ERROR] acme: error: 400 :: POST :: https://acme-staging-v02.api.letsencrypt.org/acme/new-order :>
Jul 07 13:28:39 localhost caddy[603]: 2020/07/07 13:28:39 [INFO] [timeouts] acme: Obtaining bundled SAN certificate given a CSR
Jul 07 13:28:39 localhost caddy[603]: 2020/07/07 13:28:39 [INFO] [none] acme: Obtaining bundled SAN certificate given a CSR
Jul 07 13:28:39 localhost caddy[603]: 2020/07/07 13:28:39 [ERROR] acme: error: 400 :: POST :: https://acme-staging-v02.api.letsencrypt.org/acme/new-order :>
Jul 07 13:28:39 localhost caddy[603]: 2020/07/07 13:28:39 [ERROR] acme: error: 400 :: POST :: https://acme-staging-v02.api.letsencrypt.org/acme/new-order :>
Jul 07 13:28:41 localhost caddy[603]: 2020/07/07 13:28:41 [ERROR] attempt 11: [timeouts] Obtain: [timeouts] acme: error: 400 :: POST :: https://acme-stagin>
Jul 07 13:28:41 localhost caddy[603]: 2020/07/07 13:28:41 [ERROR] attempt 11: [none] Obtain: [none] acme: error: 400 :: POST :: https://acme-staging-v02.ap>
Jul 07 13:42:47 localhost caddy[603]: 2020/07/07 13:42:47 http: TLS handshake error from 209.17.97.90:54942: no certificate available for 'myhostnome.....'

Thanks in advance.

**Comment by mholt** [comment] 2020-07-07 15:58
Thanks for opening an issue! We'll look into this.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by strategist922** [comment] 2020-07-09 03:20
## 1. Environment

### 1a. Operating system and version

```
Ubuntu 20.04 LTS (GNU/Linux 5.4.0-40-generic x86_64)
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
v2.1.1 h1:X9k1+ehZPYYrSqBvf/ocUgdLSRIuiNiMo7CvyGUQKeA=
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
install Caddy using apt install caddy
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)

Cannot get TLS certificate for more than 5 days

### 2b. Why it's a bug (if it's not obvious)

Cannot get TLS certificate for more than 5 days

### 2c. Log output

```
root@localhost:~# systemctl status caddy
● caddy.service - Caddy
     Loaded: loaded (/lib/systemd/system/caddy.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2020-07-07 10:27:53 CST; 2 days ago
       Docs: https://caddyserver.com/docs/
   Main PID: 603 (caddy)
      Tasks: 8 (limit: 1074)
     Memory: 37.4M
     CGroup: /system.slice/caddy.service
             └─603 /usr/bin/caddy run --environ --config /etc/caddy/Caddyfile

Jul 09 10:29:14 localhost caddy[603]: 2020/07/09 10:29:14 [INFO] [timeouts] acme: Obtaining bundled SAN certificate given a CSR
Jul 09 10:29:14 localhost caddy[603]: 2020/07/09 10:29:14 [ERROR] acme: error: 400 :: POST :: https://acme-staging-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:p>
Jul 09 10:29:14 localhost caddy[603]: 2020/07/09 10:29:14 [INFO] [none] acme: Obtaining bundled SAN certificate given a CSR
Jul 09 10:29:14 localhost caddy[603]: 2020/07/09 10:29:14 [ERROR] acme: error: 400 :: POST :: https://acme-staging-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:p>
Jul 09 10:29:16 localhost caddy[603]: 2020/07/09 10:29:16 [ERROR] attempt 19: [timeouts] Obtain: [timeouts] acme: error: 400 :: POST :: https://acme-staging-v02.api.le>
Jul 09 10:29:16 localhost caddy[603]: 2020/07/09 10:29:16 [ERROR] attempt 19: [none] Obtain: [none] acme: error: 400 :: POST :: https://acme-staging-v02.api.letsencryp>
Jul 09 10:36:01 localhost caddy[603]: 2020/07/09 10:36:01 http: TLS handshake error from 128.14.134.170:57288: no certificate available for 'MY VPS IP'
Jul 09 10:47:00 localhost caddy[603]: 2020/07/09 10:47:00 http: TLS handshake error from 94.242.54.22:22890: no certificate available for  'MY VPS IP'
Jul 09 10:47:06 localhost caddy[603]: 2020/07/09 10:47:06 http: TLS handshake error from 45.33.80.76:54920: no certificate available for 'MY VPS IP'
Jul 09 10:52:49 localhost caddy[603]: 2020/07/09 10:52:49 http: TLS handshake error from 176.58.124.134:35342: tls: first record does not look like a TLS handshake
```



### 2d. Workaround(s)

No workaround


### 2e. Relevant links

N/A

## 3. Tutorial (minimal steps to reproduce the bug)
Install Caddy by using apt install with following Caddyfile
===
example.com {
    encode gzip
    log {
         output file /var/log/caddy/access.log{
         }
    }
timeouts none
    reverse_proxy / https://www.baidu.com {
    }
    reverse_proxy /Fly 127.0.0.1:3128 {
    }
}

===

**Comment by mholt** [comment] 2020-07-09 03:23
Hi, thanks for posting more information. But your logs are truncated and so they are missing a lot of crucial information.

**Comment by mholt** [comment] 2020-07-09 06:07
I am not sure if you posted your Caddyfile correctly, either. Here is what you posted, formatted:

```
example.com {
	encode gzip
	log {
		output file /var/log/caddy/access.log{
	}
}

timeouts none

reverse_proxy / https://www.baidu.com {
}

reverse_proxy /Fly 127.0.0.1:3128 {
}

}
```

Clearly, this is not correct...

Anyway, will close the issue unless this is shown to be a bug in Caddy. If you have more questions about how to use Caddy, please ask in our forums: https://caddy.community

**Closed by mholt** 2020-07-09 06:07 UTC
Labels: needs info
