### ISSUE TITLE
[Feature Request] Certificate Renewal Post Hook

### ISSUE THREAD

**Issue by flixbi** [caddyserver/caddy#3774] opened 2020-10-03 11:45 UTC
I'm currently installing mailcow for our mailservice
and I'm thinking about how to handle the certificate renewal process corecctly.
I definetly want to use Caddy, because it runs perfectly and it's so easy to administrate.

So with Mailcow there is the possibility to use a [post hooks](https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/#optional-post-hook-script-for-non-mailcow-acme-clients) to apply new certificates.

So what do you think about an Hook implementation i.f.?

Maybe it's an useful feature for some other people too..

**Comment by francislavoie** [comment] 2020-10-03 20:04
I think this is a duplicate of https://github.com/caddyserver/caddy/issues/3643

**Closed by francislavoie** 2020-10-03 20:04 UTC
