### ISSUE TITLE
lb_policy cookie setting

### ISSUE THREAD

**Issue by krosoftware** [caddyserver/caddy#6535] opened 2024-08-22 13:42 UTC
Hello
I'm using Caddyfile like this:
```
:88 {
    reverse_proxy localhost:3000 localhost:3001 localhost:3002 {
      lb_policy cookie lb_mycookie
    }
}
```

and it works fine until same browsers are used. In that case, same session is used and cookie policy does not work correctly.
Any idea how to solve this, please?
Thanks!

**Comment by francislavoie** [comment] 2024-08-22 13:48
Thanks for opening an issue! We'll look into this.

It's not immediately clear to us what is going on, so we'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by krosoftware** [comment] 2024-08-23 08:11
I made additional tests (without Caddy), where I used the same scenario and even when I access the same port with the same browsers, I get a different sessionID. When I use Caddy, the sessionIDs are the same when I use the same browsers.
I can send 2 small exe files that I use as a web server. They are listening on ports 4000 and 4001 and everything is fine (also using Caddy) when the browsers are different, but when they are the same - I have the same session ID and both browsers open the same page.

**Comment by krosoftware** [comment] 2024-08-23 20:59
I created 4 servers and now it happens (sometimes) that browser Chrome take session from Edge..
I need always (for each client) different session. Of course, same client need to have always the same sessionID, but like said, different clients need to have always different one (even if they come from same IP and if they use same browser).
How to create Caddyfile for such case?
Currently, I have this one
```
:88 {
    reverse_proxy localhost:4000 localhost:4001 localhost:4002 {
      lb_policy cookie b2b1 {
        fallback first
      }
    }
    tls ..\pem.pem ..\key.key 
}

```
Thank you.

**Comment by francislavoie** [comment] 2024-08-23 21:29
`lb_policy cookie` with `fallback first` doesn't really make sense, it'll always pick the first upstream. It only makes sense if you enable active health checks and you specifically want to fallback to the 2nd if the first is down (and not spread the load between them).

I feel like you're confused about what the `cookie` policy does. The cookie is to remember which upstream was chosen after initial selection (i.e. `fallback random`, the default). It has nothing to do with authentication/sessions.

**Comment by krosoftware** [comment] 2024-08-24 05:44
You are absolutely right, I am not sure how to configure Caddyserver. I have 3 or 4 backgrounds and Caddyserver should redirect the new client to the least loaded server (regardless of IP address and/or browser, each client should be unique). 
The most logical choice is least_conn, however in that case, Caddyserver sends requests to all backends almost simultaneously. 

How to set Caddyserver to send a request to only one, least loaded backend?

**Comment by francislavoie** [comment] 2024-08-24 06:40
> Caddyserver sends requests to all backends almost simultaneously

Huh? No, each request goes to one upstream. Caddy doesn't multiply traffic.

The default policy `random` is sufficient to spread the load. The thing is least connections doesn't necessarily mean least load because each request is not equal in how much processing time they may take. So random is almost always a good enough approximation.

**Comment by krosoftware** [comment] 2024-08-24 15:53
Hello
in the attached image you can see an example where the server received requests from the same client at almost the same time on 2 backends (using "random"). How to configure Caddy server to distribute all current client traffic to only one backend?
Thank you so much for your help and support.
![server1](https://github.com/user-attachments/assets/394bc8b6-79c4-4411-8db3-1ae5ee0c85d4)

**Comment by steffenbusch** [comment] 2024-08-24 15:59
Your browser refresh click causes two requests:
One request is index.html and can be seen on top left and the other is favicon.ico on bottom left.

**Comment by francislavoie** [comment] 2024-08-24 16:11
Yeah there's no issue here. This is just two separate HTTP requests.

**Closed by francislavoie** 2024-08-24 16:11 UTC

**Comment by krosoftware** [comment] 2024-08-24 20:23
> Your browser refresh click causes two requests: One request is index.html and can be seen on top left and the other is favicon.ico on bottom left.

Yes, but I need all files on same server. It can be Javascript, CSS and other files and when all of them are distributed on different servers, it does not work, page is not displayed.
