### ISSUE TITLE
routes vs handle performance

### ISSUE THREAD

**Issue by WeidiDeng** [caddyserver/caddy#3738] opened 2020-09-20 08:23 UTC
I'm serving my website using caddy, I alse use it for [forward proxy](https://github.com/klzgrad/naiveproxy) for multiple users. First I add users in the handle array, when multiple users are using the server, forward proxy performance drop significantly. However, as I read the caddy json as compiled from Caddyfile, I realized official method is opening a subroute block, and add the forward proxy there. The performance went back to normal. I wonder whats the reason.

handle_path directive also compiles to subroute handle with one uri and remaining directive in the routes array.

**Comment by francislavoie** [comment] 2020-09-20 08:29
That's all a bit vague. Could you please elaborate and give specific examples? What configs are you trying? What kind of performance numbers are you seeing before/after?

**Comment by WeidiDeng** [comment] 2020-09-20 08:39
> That's all a bit vague. Could you please elaborate and give specific examples? What configs are you trying? What kind of performance numbers are you seeing before/after?

Originally I use this config, only app/http/routes array to save space.

```
"routes": [{
            "handle": [{
              "handler": "forward_proxy",
              "hide_ip": true,
              "hide_via": true,
              "auth_user": "user1",
              "auth_pass": "pass1",
              "probe_resistance": {"domain": "use a secret name or empty string here:0"}
            },
             {
              "handler": "forward_proxy",
              "hide_ip": true,
              "hide_via": true,
              "auth_user": "user2",
              "auth_pass": "pass2",
              "probe_resistance": {"domain": "use a secret name or empty string here:0"}
            }]
          }, {
            "match": [{"host": ["example.com", "www.example.com"]}],
            "handle": [{
              "handler": "file_server",
              "root": "/var/www/html"
            }],
            "terminal": true
          }]
```

When both users are using, connection comes to nearly stop, several kb per second. If only one user is using, performance is 1-1.5 mb per second.

Later I use this config, again only app/http/routes array

```
"routes": [{
            "handle": [{
              "handler": "forward_proxy",
              "hide_ip": true,
              "hide_via": true,
              "auth_user": "user1",
              "auth_pass": "pass1",
              "probe_resistance": {"domain": "use a secret name or empty string here:0"}
            }]
          },
          {
              "handle": [{
              "handler": "forward_proxy",
              "hide_ip": true,
              "hide_via": true,
              "auth_user": "user2",
              "auth_pass": "pass2",
              "probe_resistance": {"domain": "use a secret name or empty string here:0"}
           }]
          }
           , {
            "match": [{"host": ["example.com", "www.example.com"]}],
            "handle": [{
              "handler": "file_server",
              "root": "/var/www/html"
            }],
            "terminal": true
          }]
```

Performance become normal, 1-1.5 mb per second even both users are using.

**Comment by mholt** [comment] 2020-09-21 02:28
Thanks for opening an issue! We'll look into this.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Instructions -- please heed otherwise we cannot help you (help us help you!)

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by WeidiDeng** [comment] 2020-09-21 07:31
## 1. Environment

### 1a. Operating system and version

```
4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
v2.2.0-rc.3 h1:sCf7QCxI8l2/tvH2sJFtOC7cBAOWtB5w6XQPMPIWqqU= with [forward proxy plugin](https://github.com/klzgrad/forwardproxy)
```

Compilation steps

```
git clone -b naive https://github.com/klzgrad/forwardproxy
go get -u github.com/caddyserver/xcaddy/cmd/xcaddy
~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=$PWD/forwardproxy
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
go version go1.15.2 linux/amd64
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)

plugin config location in the array affects performance.


### 2b. Why it's a bug (if it's not obvious)

Even though it's a third party plugin, I wonder why the performance difference is huge. And official caddy compile Caddyfile directive to the second version, i.e, handlers in routes array instead of handle array

### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)

To setup testing environment is a bit involved, first I give the caddy.json I use.

First version

```
{"apps":{"http":{"servers":{"srv0":{"listen":[":443"],"routes":[{"handle":[{"handler":"forward_proxy","hide_ip":true,"hide_via":true,"auth_user":"u1","auth_pass":"p1","probe_resistance":{"domain":""}},{"handler":"forward_proxy","hide_ip":true,"hide_via":true,"auth_user":"u2","auth_pass":"p2","probe_resistance":{"domain":""}}]},{"match":[{"host":["example.com"]}],"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"file_server"}]}]}],"terminal":true}]}}}}}
```

Second version

```
{"apps":{"http":{"servers":{"srv0":{"listen":[":443"],"routes":[{"handle":[{"handler":"forward_proxy","hide_ip":true,"hide_via":true,"auth_user":"u1","auth_pass":"p1","probe_resistance":{"domain":""}}]},{"handle":[{"handler":"forward_proxy","hide_ip":true,"hide_via":true,"auth_user":"u2","auth_pass":"p2","probe_resistance":{"domain":""}}]},{"match":[{"host":["example.com"]}],"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"file_server"}]}]}],"terminal":true}]}}}}}
```

You also need (binary)[https://github.com/klzgrad/naiveproxy/releases/]

start 2 naive instances, each using the users, https://u1:p1@example.com, https://u2:p2@example.com, local proxy must be socks5.

Set up a tmux window, split in 2 panes.

In each pane, curl large files using different socks proxy.

Using the first version, connection speed is nearly zero.

Using the second version, connection speed is normal.

**Comment by mholt** [comment] 2020-09-21 18:52
Thanks for the info. I don't have a chance to try to reproduce it today; in the meantime: does this only happen with the forwardproxy handler? What if you use the simple [`"static_response"` handler](https://caddyserver.com/docs/modules/http.handlers.static_response) instead? And what do you mean by "connection speed" exactly?

First I'm interested in separating this from the handlers being used. Right now the bug report is framed as a problem with the performance of using multiple routes vs. combining them into the same route, but I'm not convinced right now that the specific handlers (and their configurations) aren't the problem.

**Comment by WeidiDeng** [comment] 2020-09-22 01:50
By connection speed I mean bytes transferred per second using the proxy.

I tested using builtin file server and gzip to serve local large file in /private/dir.

First is the Caddyfile and compiled json file

```
http://localhost:9090 {
        encode gzip
        root * /private/dir
        file_server
        bind localhost
}
```

Interestingly, the corresponding json file has handlers in handle array.

```
{"admin":{"disabled":true},"apps":{"http":{"servers":{"srv0":{"listen":["localhost:9090"],"routes":[{"match":[{"host":["localhost"]}],"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"vars","root":"/private/dir"},{"encodings":{"gzip":{}},"handler":"encode"},{"handler":"file_server","hide":["Caddyfile"]}]}]}],"terminal":true}],"automatic_https":{"skip":["localhost"]}}}},"tls":{"automation":{"policies":[{"subjects":["localhost"],"issuer":{"challenges":{"bind_host":"localhost"},"module":"acme"}}]}}}}
```

I hand crafted this json from above one.

```
{"admin":{"disabled":true},"apps":{"http":{"servers":{"srv0":{"listen":["localhost:9090"],"routes":[{"match":[{"host":["localhost"]}],"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"vars","root":"/private/dir"}]},{"handle":[{"encodings":{"gzip":{}},"handler":"encode"}]},{"handle":[{"handler":"file_server","hide":["Caddyfile"]}]}]}],"terminal":true}],"automatic_https":{"skip":["localhost"]}}}},"tls":{"automation":{"policies":[{"subjects":["localhost"],"issuer":{"challenges":{"bind_host":"localhost"},"module":"acme"}}]}}}}
```

Using 2 curl instances to download the 2.5 gb file to /dev/null simultaneously three times, average speed as shown by curl.

First test without compressed flag, each number is the average of the 2 curl instances' average speed

First json: 96.9 M, 97.05M, 99.05M
Second json: 115M, 110M, 114.5M

Nearly 10% improvement in performance.

Second test using compressed flag

First json: 56.3M, 54.5M, 56.15M
Second json: 54.4M, 54.45M, 56.4M

The difference is quite small, 2% slower. Given the the file is video file, I guess most time is spent on CPU instead of serving client.

**Comment by mholt** [comment] 2020-09-22 01:53
What about literally just a single `static_response` handler? I don't see why gzip, file_server, or vars handlers are relevant. If the discrepancy is due to the single route vs. multiple routes, then it shouldn't matter which handlers are used. I want to rule that out first.

Next time you run tests, open `http://localhost:2019/debug/pprof` and look at the memory and CPU profiles. You can also collect a profile during the tests, which will help us understand where the resources are being spent.

**Comment by WeidiDeng** [comment] 2020-09-22 01:57
But where to put the static_repsonse handler, a single one in routes or handle array is the same.

**Comment by mholt** [comment] 2020-09-22 02:01
How is that different from the forward proxy or the file server handlers?

**Comment by WeidiDeng** [comment] 2020-09-22 02:22
The problem with static reponse is that it's a [terminal handler](https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/staticresp.go#L103).

[forward proxy](https://github.com/klzgrad/forwardproxy/blob/naive/forwardproxy.go#L224), [encode](https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/encode/encode.go#L90), all perform in a middleware fashion, request flow down, response flow up.

**Comment by mholt** [comment] 2020-09-22 02:24
File server is also a terminal handler.

Forward proxy is only _conditionally_ a terminal handler. If it is proxying, it is terminal; there is a very specific condition which must be satisfied, as you linked to, in order to not be a terminal handler. But in your post you're saying that you _are_ proxying and getting slow speeds, but I am skeptical that the arrangement of routes is what is affecting proxy speeds.

**Comment by WeidiDeng** [comment] 2020-09-22 02:28
> File server is also a terminal handler.
> 
> Forward proxy is also a terminal handler, but only _conditionally_. If it is proxying, it is terminal; there is a very specific condition which must be satisfied, as you linked to, in order to not be a terminal handler. But in your post you're saying that you _are_ proxying and getting slow speeds, but I am skeptical that the arrangement of routes is what is affecting proxy speeds.

That's whats the matter, if only one user is using the proxy, only one terminal handler is active. If both users are using, one forward proxy is and is not a terminal handler.

**Comment by mholt** [comment] 2020-09-22 02:37
Hm, so only if two users are proxying at the same time, it is slow? But if you use the second config, and two users proxy at the same time, it is fast, right?

If you have a chance I'd be curious what the profiles say.

**Comment by WeidiDeng** [comment] 2020-09-22 06:12
I run the test, the first is using handle array, the second using routes array.

Curiously, when I first added the configuration through caddy reload, both are fast. It is only subsequent requests become way slower using the first json. Also, when I reload the second json, the speed is still slow, I have to stop the connection to make it fast.

[caddy_dump.zip](https://github.com/caddyserver/caddy/files/5259432/caddy_dump.zip)

The file suffix corresponds to the tests being run.

**Comment by francislavoie** [comment] 2021-08-23 06:10
We haven't had anyone else report a similar issue since, and we haven't gotten closer to having a clue what's going on here, so I'll close this as inactive. If new information is found, then it could be reopened.

**Comment by mholt** [comment] 2021-08-23 17:11
I don't think we're missing information, though; I just haven't had time myself to dive into the profile data. Someone else can, and until we know what's going on maybe we should leave it open so it doesn't get lost.

**Comment by francislavoie** [comment] 2022-03-23 02:38
Closing as inactive again, we haven't gotten around to taking a deeper look here, but also we haven't had any similar reports in the nearly two years since this was reported, so I'm pretty sure there's no actual problem here.

**Closed by francislavoie** 2022-03-23 02:39 UTC
Labels: help wanted, needs info
