### ISSUE TITLE
Geekflares HTTP/3 Tool doesn't show Caddy as HTTP/3 compatible

### ISSUE THREAD

**Issue by helmut72** [caddyserver/caddy#5122] opened 2022-10-05 20:31 UTC
[https://http3check.net](https://http3check.net) works:

* QUIC is not supported
* HTTP/3 is supported

I see HTTP/3 connections in Caddys log.

[https://geekflare.com/tools/http3-test](https://geekflare.com/tools/http3-test) doesn't work:

_"Couldn’t connect over HTTP/3. Take advantage of the latest protocol HTTP/3 for better performance."_

Only HTTP/1.1 and HTTP/2.0 connections in Caddys log.

Same with 2.5.2 when I have tested HTTP/3 some months ago. Now I thought to give it another try because HTTP/3 is enabled by default.

**Comment by mholt** [comment] 2022-10-05 21:08
- [Geekflare is broken](https://caddy.community/t/http-3-not-working/15651/3?u=matt) (old draft spec probably)
- http3check.net is a LiteSpeed service. HTTP/3 is supported is all you need, QUIC is old draft versions that aren't standard.

Duplicate of #5069

**Closed by mholt** 2022-10-05 21:08 UTC
Labels: duplicate, invalid

**Comment by helmut72** [comment] 2022-10-05 23:24
Ok, thank you to explain it. Sorry, I only searched for Geekflare in the issues and used http3check as an example that http3 works in Caddy. If I read 5069 I never opened another issue. Sorry.
