### ISSUE TITLE
README - Transparent image is not very well for dark theme

### ISSUE THREAD

**Issue by Semigradsky** [caddyserver/caddy#5245] opened 2022-12-11 13:25 UTC
![image](https://user-images.githubusercontent.com/1198848/206906237-f69ec4ab-46ec-45cc-b165-50a518135a41.png)

**Comment by IndeedNotJames** [comment] 2022-12-11 17:14
GitHub supports the `prefers-color-scheme` CSS media feature in `<picture>` HTML elements since a few months.

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to

https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/

Related: https://github.com/caddyserver/website/pull/232

**Comment by francislavoie** [comment] 2022-12-12 00:47
Duplicate of https://github.com/caddyserver/caddy/issues/4040

**Closed** 2022-12-12 00:48 UTC
