### ISSUE TITLE
False alarm on Firefox when 'Never remember history' is on

### ISSUE THREAD

**Issue by artus** [caddyserver/caddy#2697] opened 2019-08-08 15:17 UTC
I noticed on multiple devices that navigating to the 'mitm.watch' domain will report 'Mitm likely' when my browser (Firefox) is configured to never remember history. When I configure my browser to always remember history, the 'mitm.watch' reports that there is no Mitm attack happening.

Browser: Firefox Quantum 68.0.1 (64-bit)
Extensions: none

**Comment by mholt** [comment] 2019-08-08 15:27
Thanks for reporting this. Can you please submit the following information:

> To report a false positive, please file an issue with your real, unmodified User-Agent string, browser version, OS/platform details, the raw ClientHello bytes, and any other relevant build information.

Thanks

**Comment by artus** [comment] 2019-08-12 19:32
raw User-Agent string: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
Browser + version: Firefox Quantum 68.0.1 (64-bit)
OS: Windows 10 Pro 10.0.17763

**Comment by artus** [comment] 2019-08-12 19:34
Issue related to #2691

**Comment by Darkspirit** [comment] 2019-08-12 20:08
Yes, this is a duplicate of #2691.

**Closed** 2019-08-12 20:26 UTC
Labels: duplicate
