### ISSUE TITLE
Support for tcp/udp reverse proxy in Caddyfile

### ISSUE THREAD

**Issue by v-byte-cpu** [caddyserver/caddy#4193] opened 2021-06-06 07:31 UTC
First of all, I would like to thank you for such a wonderful project! It would be great if Caddy supported proxying udp packets and tcp connections like nginx `stream` directive by default. I found that https://github.com/mholt/caddy-l4 plugin already exists. Are there any plans to integrate this plugin into the main caddy distribution ?

**Comment by francislavoie** [comment] 2021-06-06 09:25
> Are there any plans to integrate this plugin into the main caddy distribution ?

No. Caddy is by design, an HTTP server.

Caddy's HTTP server does support UDP traffic in the form of QUIC though, FYI.

When Go gains support for HTTP/3 in its HTTP client module, the `reverse_proxy` handler still probably support it.

There's nothing actionable here, so I'll close this.

**Closed by francislavoie** 2021-06-06 09:26 UTC

**Comment by mholt** [comment] 2021-06-06 17:22
> No. Caddy is, by design, an HTTP server.

More like, Caddy is a server of servers. HTTP is built in by default because it's the server type that most people use. But technically, the HTTP server is no different from the TCP server -- it just comes bundled by default.

@v-byte-cpu 

>  Are there any plans to integrate this plugin into the main caddy distribution ?

Why do you need this?

**Comment by v-byte-cpu** [comment] 2021-06-06 20:41
I personally have a VPS server with HTTP, SMTP and IMAP servers deployed and for each of them I do TLS termination. Nginx is currently performing this function and I use `stream` directive to proxy to SMTP and IMAP servers. The relevant nginx config looks like this:

```
stream {
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_ciphers TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES256-GCM-SHA384;
	ssl_prefer_server_ciphers on;
	ssl_certificate  /tls/cert.pem;
	ssl_certificate_key  /tls/key.pem;
	ssl_dhparam  /tls/dhparam.pem;
	ssl_session_cache  shared:cool_cache:10m;
	ssl_session_timeout 10m;

	proxy_timeout 1m;
	server {
		listen 993 ssl;
		proxy_pass imap_server:993;
		proxy_protocol on;
	}
	server {
		listen 465 ssl;
		proxy_pass smtp_server:465;
	}
}
```

I really like Caddy HTTP server and would like to use it to perform TCP proxying as well.

**Comment by francislavoie** [comment] 2021-06-06 21:04
> I really like Caddy HTTP server and would like to use Caddy to perform TCP proxying as well.

You can just build Caddy with the `caddy-l4` plugin (either yourself, using `xcaddy`, or by using the build server at https://caddyserver.com/download).

It doesn't need to be a standard module for you to use it.

**Comment by v-byte-cpu** [comment] 2021-06-06 21:49
You're right, I'd rather rephrase: would like to use Caddy to perform TCP proxying as well out of the box.
> But technically, the HTTP server is no different from the TCP server -- it just comes bundled by default.

**Comment by francislavoie** [comment] 2021-06-06 23:59
We ship an official `builder` docker image variant you can use to build Caddy with plugins. It's super easy to use. See the docs on docker hub: https://hub.docker.com/_/caddy

**Comment by v-byte-cpu** [comment] 2021-06-07 16:51
Okay, thanks.

**Comment by bubnenkoff** [comment] 2024-02-15 07:26
I am voting for this future for caddy!

> When Go gains support for HTTP/3 in its HTTP client module
Is there any new about it?

**Comment by LZeugirdor** [comment] 2026-05-12 13:11
+1
