### ISSUE TITLE
Parsing caddyfile tokens for 'acme_dns': Wrong argument count or unexpected line ending

### ISSUE THREAD

**Issue by Mosney** [caddyserver/caddy#4122] opened 2021-04-18 18:19 UTC
### 1a. Operating system and version

```
Linux 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
```

### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
v2.3.0 h1:fnrqJLa3G5vfxcxmOH/+kJOcunPLhSBnjgIvjXV/QTA=
```

### 1c. Go version (if building Caddy from source; run `go version`)

```
Download from official site, ignore.
```

### 2a. What happens (briefly explain what is wrong)

Log says: Parsing caddyfile tokens for 'acme_dns': Wrong argument count or unexpected line ending 

### 2b. Why it's a bug (if it's not obvious)

Depend on [cadyyfile global options documents](https://caddyserver.com/docs/caddyfile/options#global-options), it can set an global tls config `acme_dns <provider>`, but not explain too much only `Configures the DNS challenge to use for all ACME transactions.`, then I check [automatic-https](https://caddyserver.com/docs/automatic-https#dns-challenge) documents, found  [Learn how to enable the DNS challenge for your provider at our wiki.](https://caddy.community/t/how-to-use-dns-provider-modules-in-caddy-2/8148) , give an example is:

> {
>     acme_dns cloudflare 1484053787dJQB8vP1q0yc5ZEBnH6JGS4d3mBmvIeMrnnxFi3WtJdF
> }

So I think global options `acme_dns <provider>` should like this.

### 2c. Log output

```
2021/04/18 18:57:53.553	INFO	using provided configuration	{"config_file": "/etc/caddy/Caddyfile.test", "config_adapter": ""}
run: adapting config using caddyfile: parsing caddyfile tokens for 'acme_dns': /etc/caddy/Caddyfile.test:6 - Error during parsing: Wrong argument count or unexpected line ending after 'REDACTED_API_Token'

```

### 2d. Workaround(s)

Delete API_Token only `acme_dns cloudflare ` left will be OK, but DNS challenge will not work cause lack of API Token.

## 3. Tutorial (minimal steps to reproduce the bug)

`/usr/bin/caddy run --config /etc/caddy/Caddyfile.test`

> Caddyfile.test
> ```
> {
>   storage file_system {
>     root /var/caddy.test
>   }
>   email master@DOMAIN.com
>   acme_dns cloudflare REDACTED_API_Token
>   cert_issuer zerossl
> }
> 
> 
> https://a.DOMAIN.com:8443 {
> reverse_proxy http://localhost:8989
> }
> ```

**Comment by mholt** [comment] 2021-04-18 18:39
Thanks for opening an issue! We'll look into this.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Instructions -- please heed otherwise we cannot help you (help us help you!)

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by Mosney** [comment] 2021-04-18 19:16
## 1. Environment

### 1a. Operating system and version

```
Linux 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
v2.3.0 h1:fnrqJLa3G5vfxcxmOH/+kJOcunPLhSBnjgIvjXV/QTA=
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
Download from official site, ignore.
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)

Log says: Parsing caddyfile tokens for 'acme_dns': Wrong argument count or unexpected line ending 


### 2b. Why it's a bug (if it's not obvious)

Depend on [cadyyfile global options documents](https://caddyserver.com/docs/caddyfile/options#global-options), it can set an global tls config `acme_dns <provider>`, but not explain too much only `Configures the DNS challenge to use for all ACME transactions.`, then I check [automatic-https](https://caddyserver.com/docs/automatic-https#dns-challenge) documents, found  [Learn how to enable the DNS challenge for your provider at our wiki.](https://caddy.community/t/how-to-use-dns-provider-modules-in-caddy-2/8148) , an cloudflare example is:

> {
>     acme_dns cloudflare 1484053787dJQB8vP1q0yc5ZEBnH6JGS4d3mBmvIeMrnnxFi3WtJdF
> }

So I think global options `acme_dns <provider>` should like this.


### 2c. Log output

```
2021/04/18 18:57:53.553	INFO	using provided configuration	{"config_file": "/etc/caddy/Caddyfile.test", "config_adapter": ""}
run: adapting config using caddyfile: parsing caddyfile tokens for 'acme_dns': /etc/caddy/Caddyfile.test:6 - Error during parsing: Wrong argument count or unexpected line ending after 'REDACTED_API_Token'

```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)

`/usr/bin/caddy run --config /etc/caddy/Caddyfile.test`

> Caddyfile.test
> ```
> {
>   storage file_system {
>     root /var/caddy.test
>   }
>   email master@DOMAIN.com
>   acme_dns cloudflare REDACTED_API_Token
>   cert_issuer zerossl
> }
> 
> 
> https://a.DOMAIN.com:8443 {
> reverse_proxy http://localhost:8989
> }
> ```

**Comment by Mosney** [comment] 2021-04-18 19:19
@mholt  I update this issue above, please check.

**Comment by francislavoie** [comment] 2021-04-18 19:52
The `acme_dns` global option is only functional since `v2.4.0-beta.1` unfortunately. There was a parsing bug in v2.3.0 preventing it from working correctly.

**Closed by francislavoie** 2021-04-18 19:52 UTC
Labels: needs info

**Comment by Mosney** [comment] 2021-04-18 20:31
All right, I do not see any notes in the documentation that these options are specific to a particular version.

**Comment by francislavoie** [comment] 2021-04-18 20:34
Yeah, we don't put versions information in the docs generally, we publish new docs along with stable version releases. The `acme_dns` option existed in `v2.3.0` but isn't functional (because bugs).

**Comment by Mosney** [comment] 2021-04-18 20:41
Haha, what coincidence. I just went to the website to download the latest bin file and found it's already `2.4.0-beta1`, looks that not "a stable version" 😄️

**Comment by francislavoie** [comment] 2021-04-18 21:19
It probably did that because you're using a plugin that specifies that version as a requirement.

**Comment by Mosney** [comment] 2021-04-19 17:44
Maybe, I try download caddy only, Windows-amd64 and Linux amd64, the version is 2.3.0, looks like add plugin will get a newer version.
