### ISSUE TITLE
Potential Memory Leak - total_inactive_file grows unbounded

### ISSUE THREAD

**Issue by michaelperel** [caddyserver/caddy#4124] opened 2021-04-20 13:51 UTC
**When running caddy as a reverse proxy via docker for a websocket server, according to `top`, ram that is consumed is never returned. This is especially apparent when doing a load test.**

System Info:
* Azure VM - Ubuntu 18.04
* docker version 20.10.6
* Any recent caddy image (tags: `alpine`, `latest`, `2`)

Here is a screenshot of `top` ~8 hours after performing a load test of 10,000 websocket connections for 10 minutes
![caddy_memory_leak](https://user-images.githubusercontent.com/10049607/115404549-6e837f80-a1bb-11eb-946f-d622197e310f.PNG)

Investigating it further, if you run ` cat /sys/fs/cgroup/memory/docker/<container hash>/memory.stat`, you can see that `total_inactive_file` accounts for the majority of the memory reported by `top`.
![inactive_file](https://user-images.githubusercontent.com/10049607/115405062-e6ea4080-a1bb-11eb-82fb-278dd5588c0d.PNG)

According to that screenshot, `total_inactive_file` grows to ~1.7gb.

If you run `docker stats`, which subtracts inactive files from the memory usage, it reports ~125 mb of memory used.

I am not a linux expert by any means, but after reading about `total_inactive_file`, it seems like this is part of a page cache that could be reclaimed by the system if it needed it.

Still, I am worried as it is the only container in my system that grows the inactive file count.

Is this something I should be worried about? Any insights as to why caddy grows like this, but the 10+ other containers (redis, databases, api servers, etc) I am using do not exhibit this behavior?

Thanks so much for providing caddy to the community. Auto HTTPS is invaluable, and I am hoping to use caddy as an nginx replacement in a variety of projects :)

**Comment by michaelperel** [comment] 2021-04-20 14:02
Here is my Caddyfile, in case it is relevant:
```
{$DOMAIN}

encode zstd gzip

route "/api/*" {
    reverse_proxy "api:{$API_PORT}"
}

reverse_proxy "server:{$FRONTEND_PORT}"
```

**Comment by mholt** [comment] 2021-04-20 14:36
I don't know what `total_inactive_file` is, but this is the first we've heard of a possible memory leak here. Open `localhost:2019/debug/pprof` and see what both the goroutine dump and heap profile show. Upload those reports here. Additionally, a profile during the load test would be helpful.

**Comment by francislavoie** [comment] 2021-04-20 15:15
Also, please try with the `2.4.0-beta.2-alpine` image which is the latest build, just in case it's already been fixed since v2.3.0

**Comment by michaelperel** [comment] 2021-04-21 12:15
@mholt I have uploaded the requested information to [this repo](https://github.com/michaelperel/caddy_pprof) because the output was too large to paste in a comment.

The files `goroutine_load_test` and `heap_load_test` occurred during a load test with a few thousand websocket connections sustained at the same time.

The files `goroutine_after` and `heap_after` are from a few minutes after the load test, where `docker stats` reports the memory usage has gone down, but `top` reports the memory still used (because `total_inactive_file` has grown)

@francislavoie I also tried using the new image, but the same behavior occurred.

I don't think this is specific to websocket connections as I did other tests where I flooded the reverse proxy without websockets and the same behavior occurred, so if you are interested in replicating, any standard setup with docker on linux should reproduce it.

**Comment by mholt** [comment] 2021-04-21 19:20
Thanks. Just took a quick glance with the time I have right now.

This might be a dumb question, but how sure are you that the client is closing the connections? Can we reproduce this behavior?

**Comment by michaelperel** [comment] 2021-04-22 03:13
@mholt The server closes the websocket connection, but the clients do not. 

The clients come from a script that generates load by creating thousands of websocket connections and periodically sending messages. The server is written in go using gorilla/websocket and reads messages. The server also communicates with the client via ping/pong messages to keep connections alive if the client hasn’t recently sent a message. 

When the load generating script ends, the ping pong messages will fail, and the server will close the connection. I am 100% confident that the server always calls close on the connection. 

I believe this test mimics when someone refreshes a webpage, closes their computer, or loses internet connection as we can’t always rely on the client/all browsers to gracefully close the connection. 

Is it required that a client close the connection for caddy to release resources?

Did something pop out to you in the heap/goroutine dump that may make it seem like connections aren’t closed?

Thanks so much for taking the time to investigate this issue! I really appreciate it.

**Comment by michaelperel** [comment] 2021-04-22 03:18
One other piece of information — if i inspect the process running caddy (lsof -p PID), I can see that after the test runs, there are no more outstanding socket connections. During the test, there are thousands of socket connections.

**Comment by simaotwx** [comment] 2021-04-22 14:20
Does this have to do with `MADV_FREE`?
See https://golang.org/doc/go1.16#runtime

This changed in Go 1.16 (2.3.0 is 1.15)

**Comment by mholt** [comment] 2021-04-22 21:06
Do you have something we can use to reproduce this (without Docker -- I don't have Docker)?

**Comment by michaelperel** [comment] 2021-04-23 15:31
@mholt I have just made a [minimal example without docker](https://github.com/michaelperel/caddy_test). The README contains the step by step examples necessary to run and recreate the problem.

**Comment by mholt** [comment] 2021-04-26 19:12
Thanks, will look at this as soon as I have a chance

**Comment by mholt** [comment] 2021-05-02 19:34
I just got it running, will investigate more this week hopefully. Thanks for the good test repo.

**Comment by mholt** [comment] 2021-05-04 23:07
I cannot find any leak.

Letting it run for 1-4 minutes seems like a leak, because resource usage is ramping up. But as connections time out and get closed, resources are deallocated.

I wired up the heck out of this thing for observation and let it run for over an hour, multiple times. (I also shortened the chat client's timeouts to 30s instead of 1m.) Here is one such run, and all were like this:

![Screenshot from 2021-05-04 13-35-44](https://user-images.githubusercontent.com/1128849/117080168-89e1a500-acfa-11eb-8ce0-d310937baab7.png)

The load program counted 100,000+ connections during these trials.

When looking at `localhost:2019/debug/pprof`, I can see allocations and goroutines both properly ramp up and then steady out when refreshing every few minutes. I also added lots of extra debug logs for the experiments and can see that all connections are closed properly, and buffers are returned to pools or cleaned up by the GC.

Both my system monitor and netdata also report steady memory and FD usage over time.

I am not sure what the metric you are looking at comes from exactly, but it might be an artifact of the container more than the Caddy process.

Going to close this as a non-issue, or at least not a Caddy issue, but feel free to continue the discussion as needed.

**Closed by mholt** 2021-05-04 23:07 UTC
Labels: needs info

**Comment by simaotwx** [comment] 2021-05-05 07:24
@michaelperel One thing you could try: reproduce your situation and then try to fill up RAM using a different application. If Go 1.15 `MADV_FREE` behavior is still active, the memory usage should go down as other applications need it. I have seen this happen on other Go apps as well. Also found this (not sure how much it helps, though): https://www.bwplotka.dev/2019/golang-memory-monitoring/

**Comment by mholt** [comment] 2021-05-05 09:26
That's true, sometimes resources are only returned as pressure increases, not always as soon as possible.

**Comment by michaelperel** [comment] 2021-05-05 14:39
@mholt Thanks for the in depth investigation into this issue. I feel confident in your analysis that there is no memory leak.

@simaotwx Thanks for your look into MADV_FREE, it describes the exact problem that I saw here (especially the part about `inactive_file` and how that affects reporting in `top`).

All of this seems inline with the idea that the memory reported is part of a cache that can be reclaimed (that is the description of `inactive_file` when I was researching initially)

I have done some tests, and the memory is reclaimed when memory pressure occurs from another application.

Sorry for opening an issue that seems to be Go related. This was an informative discussion for me, as I did not realize some of the gotchyas when monitoring Go apps in `top`.

**Comment by simaotwx** [comment] 2021-05-05 14:42
@michaelperel I'm glad it helped. No worries! It took me some digging to find this out, too. The issue should not be there with Caddy 2.4.0 anymore (if it's built with Go 1.16) as this changed in 1.16 to release memory back to the system quicker. Otherwise monitoring systems may falsely report high memory consumption even though it's perfectly normal.
