### ISSUE TITLE
grpc-web protocol error

### ISSUE THREAD

**Issue by tetra12** [caddyserver/caddy#5066] opened 2022-09-22 12:23 UTC
Hi ! This is a follow up of #3997 and #4896 

@mholt managed to implement a valid `grpc-web` back then, but later removed that branch and moved the whole `grpc-web` thing as a plugin [here](https://github.com/mholt/caddy-grpc-web)

I've been using that branch until recently, when I discovered it to be removed and some `Caddyfile` config drifts started to appear between `v2.5.2` and `v2.6.1`.

Afterwards, I [bumped](https://github.com/mholt/caddy-grpc-web/pull/1) that plugin and tried to use it. Now I'm getting the following error:
`{PROTOCOL_ERROR; received from peer] after Request.Body was written; define Request.GetBody to avoid this error"}`

The full error log:
```bash
caddy    | {"level":"debug","ts":1663845987.8254776,"logger":"http.handlers.file_server","msg":"opening file","filename":"/app/dist/index.html"}
caddy    | {"level":"debug","ts":1663845994.7414405,"logger":"http.handlers.rewrite","msg":"rewrote request","request":{"remote_ip":"172.21.0.1","remote_port":"46144","proto":"HTTP/1.1","method":"POST","host":"localhost","uri":"/gate/greeter.Greeter/SayHello","headers":{"X-Grpc-Web":["1"],"Sec-Fetch-Site":["same-origin"],"Accept-Language":["en-US,en;q=0.9"],"Connection":["keep-alive"],"Content-Length":["44"],"Content-Type":["application/grpc-web-text"],"Origin":["http://localhost"],"Accept-Encoding":["gzip, deflate, br"],"Accept":["application/grpc-web-text"],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Mode":["cors"],"Referer":["http://localhost/"],"Sec-Ch-Ua":["\"Chromium\";v=\"105\", \"Not)A;Brand\";v=\"8\""],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"],"Sec-Ch-Ua-Platform":["\"Linux\""],"Sec-Fetch-Dest":["empty"]}},"method":"POST","uri":"/greeter.Greeter/SayHello"}
caddy    | {"level":"debug","ts":1663845994.7415793,"logger":"http.handlers.reverse_proxy","msg":"selected upstream","dial":"192.168.1.93:50051","total_upstreams":1}
caddy    | {"level":"debug","ts":1663845994.7478976,"logger":"http.handlers.reverse_proxy","msg":"upstream roundtrip","upstream":"192.168.1.93:50051","duration":0.006246607,"request":{"remote_ip":"172.21.0.1","remote_port":"46144","proto":"HTTP/1.1","method":"POST","host":"localhost","uri":"/greeter.Greeter/SayHello","headers":{"Sec-Ch-Ua-Platform":["\"Linux\""],"Sec-Fetch-Dest":["empty"],"Content-Type":["application/grpc-web-text"],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Mode":["cors"],"X-Forwarded-For":["172.21.0.1"],"X-Forwarded-Host":["localhost"],"Sec-Ch-Ua":["\"Chromium\";v=\"105\", \"Not)A;Brand\";v=\"8\""],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"],"X-Grpc-Web":["1"],"Sec-Fetch-Site":["same-origin"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.9"],"Origin":["http://localhost"],"Accept":["application/grpc-web-text"],"Referer":["http://localhost/"],"X-Forwarded-Proto":["http"],"Content-Length":["44"]}},"error":"http2: Transport: cannot retry err [stream error: stream ID 3; PROTOCOL_ERROR; received from peer] after Request.Body was written; define Request.GetBody to avoid this error"}
caddy    | {"level":"error","ts":1663845994.7479832,"logger":"http.log.error","msg":"http2: Transport: cannot retry err [stream error: stream ID 3; PROTOCOL_ERROR; received from peer] after Request.Body was written; define Request.GetBody to avoid this error","request":{"remote_ip":"172.21.0.1","remote_port":"46144","proto":"HTTP/1.1","method":"POST","host":"localhost","uri":"/gate/greeter.Greeter/SayHello","headers":{"Accept-Language":["en-US,en;q=0.9"],"X-Grpc-Web":["1"],"Sec-Fetch-Site":["same-origin"],"Content-Type":["application/grpc-web-text"],"Origin":["http://localhost"],"Accept-Encoding":["gzip, deflate, br"],"Connection":["keep-alive"],"Content-Length":["44"],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Mode":["cors"],"Referer":["http://localhost/"],"Accept":["application/grpc-web-text"],"Sec-Ch-Ua-Platform":["\"Linux\""],"Sec-Fetch-Dest":["empty"],"Sec-Ch-Ua":["\"Chromium\";v=\"105\", \"Not)A;Brand\";v=\"8\""],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"]}},"duration":0.006603225,"status":502,"err_id":"h0e22mwvk","err_trace":"reverseproxy.statusError (reverseproxy.go:1271)"}
```

I built a debug project to show the issue. It implements both front and a backend and was built with  `Caddy master v2.6.1`.
The project is [here](https://github.com/tetra12/caddy-debug)

@mholt Could you pls take a look :eyes: I also think its a good idea to add this project in your CI pipeline :roll_eyes:

**Comment by mholt** [comment] 2022-09-22 20:04
@tetra12 Thanks for the report.

If you change `	protocols h1 h2 h2c` to `protocols h1 h2c`, does it work? (I don't imagine it will make a difference, since you're not using HTTPS anywhere in that config, but...)

If someone can take a look at this, that'd probably be faster. I'm working through a bit of a backlog after the 2.6 release.

**Comment by tetra12** [comment] 2022-09-23 12:09
@mholt  I can fix this on my own. How do I ran any integration test? :eyes: 

I'm currently trying to do `go test -v -run TestRespond` in the integration folder. My test fails [here](https://github.com/caddyserver/caddy/blob/eead00f54a4b5d55292b2dcf5f1ec462c79207ad/caddytest/caddytest.go#L260) complaining that Amin is not running :roll_eyes: How do I ran admin and launch any integration test ? :thinking:

**Comment by mholt** [comment] 2022-09-23 17:57
Oh... @mohammed90 pointed out to me that it's because I recently changed the default admin port (for the tests) to 2999 so it doesn't conflict with a real server running on the machine.

Any servers used in the tests that don't specify that alternate port in their config will have that error, I guess. We'll probably need to find a way to specify the admin port for those test servers.

**Comment by tetra12** [comment] 2022-09-23 18:43
So how do I run tests ? :roll_eyes:  Give me a short working example pls :pray:

**Comment by mholt** [comment] 2022-09-23 19:12
I will as soon as I get a chance, been a little busy with other things (sorry about that). I'll circle back to this soon!

Basically, find a way to add `"admin": "localhost:2999"` to the config for test servers.

**Comment by tetra12** [comment] 2022-09-23 19:25
As far as I see, it has already been set properly in master [here](https://github.com/caddyserver/caddy/blob/eead00f54a4b5d55292b2dcf5f1ec462c79207ad/caddytest/caddytest.go#L45). Okay take your time.

**Comment by mohammed90** [comment] 2022-09-23 19:32
> As far as I see, it has already been set properly in master [here](https://github.com/caddyserver/caddy/blob/eead00f54a4b5d55292b2dcf5f1ec462c79207ad/caddytest/caddytest.go#L45). Okay take your time.

This does not propagate to the server when it's **first** launched.

**Comment by tetra12** [comment] 2022-09-23 19:44
@mohammed90 I'm glad that you figured out a test issue. What's next?  :thinking:  I still need to run any integration test

**Comment by francislavoie** [comment] 2022-09-23 22:49
We know what the problem is, but fixing it is a whole other problem. That's what @mohammed90 is saying.

**Comment by mohammed90** [comment] 2022-09-24 19:03
@tetra12 The tests are fixed now. Go forth and do science!

**Comment by tetra12** [comment] 2022-09-25 11:26
@mohammed90 Yes, tests are working now, thank you! :+1: . Taking a lead to implement a proper GRPC support for Caddy :sunglasses:

**Comment by tetra12** [comment] 2022-09-26 10:29
Update

I digged a bit into this issue and found out two things :roll_eyes: :
1. Current issue needs a bit different `Caddyfile` config to make the plugin work, e.g like this:
```bash
http://localhost:5453 {
  grpc_web
  reverse_proxy h2c://localhost:50053
}
```
So an extra directive `grpc_web` needs to be added before every single call of `reverse_proxy`

2. While (1) fixes the issue in command line (calls are passed), browser calls are blocked by a strict `CORS` policy. The following `CORS` is set by default in a browser by my client: `Referrer Policy: strict-origin-when-cross-origin`. This yields in the traffic filtering and calls are timed out.

Envoy solves the CORS issue with an extra directive, like this:
```yaml
http_filters:
                  - name: envoy.filters.http.grpc_web
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
                  - name: envoy.filters.http.cors
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
```

Need to dig a bit more with CORS :eyes:

**Comment by mholt** [comment] 2022-09-26 15:13
@tetra12 Thanks for digging into this. But I'm not sure I understand fully your findings?

> So an extra directive grpc_web needs to be added before every single call of reverse_proxy

What do you mean by this, does `grpc_web` need to be specified more than once?

> Need to dig a bit more with CORS

As for CORS, they are just response headers, which you can manipulate with the `header` directive; and sounds orthogonal to GRPC (CORS must be obeyed regardless of GRPC).

By the way:

```
  route /gate/* {
      uri strip_prefix /gate
      reverse_proxy h2c://192.168.1.93:50051
  }
```

Any reason you're not using `handle_path` here instead? Then you can get rid of `uri strip_prefix /gate`. At least, you should be able to.

Were you able to get the config in the linked project to work, then?

**Closed** 2022-09-26 16:20 UTC
Labels: help wanted

**Comment by mohammed90** [comment] 2022-09-26 17:07
>> What do you mean by this, does grpc_web need to be specified more than once?
>
> I meant that the directive grpc_web must be specified per each route, which calls the reverse_proxy directive and before it 🙄

You can use the [`order` global option](https://caddyserver.com/docs/caddyfile/options#order) to say:

```
order grpc_gateway before reverse_proxy
```

You do that once in the global options part.

**Comment by tetra12** [comment] 2022-09-26 19:16
@mohammed90 Thanks ! Will do
