### ISSUE TITLE
fastcgi with more than 1 file extension causes error

### ISSUE THREAD

**Issue by iscraft** [caddyserver/caddy#1564] opened 2017-04-05 14:59 UTC
### 1. What version of Caddy are you running (`caddy -version`)?
windows7 & FreeBSD armv7
0.9.5

### 2. What are you trying to do?
add filetype .phtml on the fastcgi ext

### 3. What is your entire Caddyfile?
```
fastcgi / 127.0.0.1:9000 php {
ext .php .phtml
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

service caddy start
### 5. Please paste any relevant HTTP request(s) here.

php is runing;
but phtml not,only show source code

**Comment by abiosoft** [comment] 2017-04-05 15:26
I've been able to reproduce this.

**Comment by mholt** [comment] 2017-04-06 23:35
@abiosoft Thanks for checking it out! Can I assign you to this?

**Comment by abiosoft** [comment] 2017-04-07 05:49
Yeah you can.

**Comment by mhoIt** [comment] 2017-04-26 20:38
So what

**Comment by mholt** [comment] 2017-05-01 19:48
Hey @abiosoft do you want any help getting this resolved?

**Comment by abiosoft** [comment] 2017-05-01 20:40
Could there be any situation where `ext` and `split` can be different ? 
Since Caddy isn't splitting by regex, I don't think that is ever gonna happen.

**Comment by mholt** [comment] 2017-05-01 21:04
@abiosoft Great question. I'm not sure off-hand. Maybe someone else would have an example?

**Comment by francislavoie** [comment] 2017-05-01 22:27
If we find that `split` is never different than `ext`, then I think we might as well remove the arguments from `split` so that it just inherits them from `ext` if any.

There is an example in the docs that uses `split` without `ext` being set:
```Caddyfile
fastcgi / 127.0.0.1:9001 {
	split .html
}
```
But I think that was just meant as a configuration example and not a real-world usable case.

**Comment by abiosoft** [comment] 2017-05-01 23:54
I propose we simply remove/depreciate `split` while fixing this. This is the main blocker.

If that sounds fine, I can go ahead and finalize this.

**Comment by mholt** [comment] 2017-05-02 06:37
@abiosoft Great -- let's get a PR going and we can poll people to give their input. We should be "gentle" in this case by showing a warning when using the `split` subdirective, which is being deprecated, and if they need it, they should post an issue (link to Caddy issues). That way, they'll know to get in touch with us.

We can always add the split feature later if needed.

**Comment by slightfoot** [comment] 2017-05-04 18:30
@abiosoft I thought the split feature is there for separating the `PATH_INFO` and is unrelated to accepting cgi requests for specific file extensions. 
> [RFC3875: CGI Spec 1.1: Section 4.1.5](https://tools.ietf.org/html/rfc3875#section-4.1.5)

**Comment by slightfoot** [comment] 2017-05-04 18:39
Just took a quick look.. seems as though the `ext` fastcgi directive doesn't support multiple extensions.

https://github.com/mholt/caddy/blob/master/caddyhttp/fastcgi/fastcgi.go#L84
https://github.com/mholt/caddy/blob/master/caddyhttp/fastcgi/setup.go#L95

**Comment by abiosoft** [comment] 2017-05-04 19:04
Yes but in Caddy's case, I am yet to see when it is not same value as ext. e.g. in the php preset https://github.com/mholt/caddy/blob/master/caddyhttp/fastcgi/setup.go#L199
> @abiosoft I thought the split feature is there for separating the PATH_INFO and is unrelated to accepting cgi requests for specific file extensions.

Yes, which is why it breaks when more than one is specified.
> Just took a quick look.. seems as though the ext fastcgi directive doesn't support multiple extensions.

**Comment by slightfoot** [comment] 2017-05-04 19:45
@abiosoft In the past (on other web servers) I have used these separately. Extensions to detect and serve content and path_info to provide information on what to serve. So you have one say `php`file that serves lots of content. 

My remark was mainly aimed at the initial issue opened by @iscraft that he is trying to use multiple extensions and its it not working. caddy/issues/1564#issue-219613123 I thought that was the bug that was required to be fixed. The confusion might be caused because of the difference with the `ext` plugin vs. the `fastcgi` plugin. Ref: https://caddyserver.com/docs/ext

**Comment by mholt** [comment] 2017-05-04 19:49
@slightfoot 

> In the past (on other web servers) I have used these separately. Extensions to detect and serve content and PATH_INFO to provide information on what to serve. So you have one say phpfile that serves lots of content.

Can you share those lines of config so we can see how they're being used separately?

I realize that the separation of these two is slightly tangential, and it's probably best to focus on the original issue here; but they are related, and if one is blocking the other, let's knock out both (if needed).

**Comment by abiosoft** [comment] 2017-05-04 20:27
The direct fix to this issue is allow specifying multiple ext and split. Which is quite straightforward though a bit challenging on how to represent it in the config since an ext need to be attached to a split (I think).
```
ext .php .html
split .php .html
```
Just wondering why we need to specify same thing in two places.

**Comment by mholt** [comment] 2017-05-04 21:25
This is a good point. I'd be interested to know @slightfoot's use case where they are different.

**Comment by magikstm** [comment] 2018-03-26 16:38
I tested this issue and I reproduced it with Caddy 0.10.11 on Windows 7 x64.

I tested a workaround to make both work on my platform. I think it would work on other platforms too but it may need extra testing.

You could have two fastcgi directives.

Here's a minimal example on Windows:
```
on startup C:\caddysites\php\php-cgi.exe -b 6545 &
fastcgi / 127.0.0.1:6545 {
	ext .php
}
fastcgi / 127.0.0.1:6545 {
	ext .phtml
}
```

I tested a .php and .phtml page and both worked perfectly.

Is it a viable solution without having to change the code?

Maybe this limitation could be mentioned in the docs or a similar example could be added? https://caddyserver.com/docs/fastcgi

**Comment by abiosoft** [comment] 2018-03-26 17:04
I think I'll go ahead with the fix I had in mind back then which is to remove `split` and properly support multiple extensions. I haven't seen any specific case where `ext` and `split` have been different.

**Comment by tobya** [comment] 2018-11-11 10:33
@abiosoft Do you know if this was ever fixed?  Can we close this issue?

**Comment by tobya** [comment] 2019-02-16 20:45
@abiosoft  if split is removed, will the code still split eg.  Given the url

    https://exampl.com/pages/myfile.php/userid/docid/test

after the change will `$_SERVER['PATH_INFO']` still contain `/userid/docid/test` ?

If so I think we could go ahead, although I do like @magikstm workaround also.

If this is not the case we need to decide if we are happy breaking functionality.

**Comment by abiosoft** [comment] 2019-02-21 08:33
@tobya Yes it will. 
> after the change will `$_SERVER['PATH_INFO']` still contain `/userid/docid/test` ? Which is what it should contain at the moment.

**Comment by mholt** [comment] 2019-10-11 00:24
Can anyone verify whether this is still an issue with Caddy 2? (Caddy 2 is currently in beta on the v2 branch. See its readme and the wiki for full documentation.)

**Comment by tobya** [comment] 2019-10-11 08:45
I will try to test this.

**Comment by mholt** [comment] 2019-10-11 16:50
Thanks as always, Toby!

**Comment by tobya** [comment] 2019-10-12 07:04
I've looked at this in V2 and cant see how more than one extension can be specified, so this is still outstanding.  It seems necessary to be able to specify multiple extensions in these 2 places

````
"handle": [
                                {
                                  "handler": "reverse_proxy",
                                  "transport": {
                                    "protocol": "fastcgi",
                                    "split_path": ".phtml"
                                  },
                                  "upstreams": [
                                    {
                                      "dial": "localhost:4344"
                                    }
                                  ]
                                }
                              ],
````
and  (although I presume I can already here)
````
"match": [
                                {
                                  "path": [
                                    "*.phtml"
                                  ]
                                }
````

**Comment by mholt** [comment] 2019-10-12 18:06
I'm not even sure how you would split on more than one substring.

**Comment by tobya** [comment] 2019-10-12 18:54
Well we just need to allow multiple file ext for php files 
eg
> php, phtml, html

whatever someone wants really.  Then when a file is requested matching any of the exts we need to send file request to php and split on that extention

**Comment by mholt** [comment] 2019-10-12 18:56
So how about if `split_path` was a placeholder: `{http.request.uri.ext}` ? (Will have to make it, I think)

**Comment by mholt** [comment] 2020-03-22 13:49
v2 now supports trying multiple substrings for splitting the path, so I think this is fixed.

**Closed by mholt** 2020-03-22 13:49 UTC
Labels: bug
