### ISSUE TITLE
Reverse Proxy Not Working on 2.1.1

### ISSUE THREAD

**Issue by bestpaydeals** [caddyserver/caddy#3567] opened 2020-07-10 22:34 UTC
After I update Caddy from 2.0 to 2.1.1 my reverse proxy is not working. As for example the following code was working on 2.0:

```
reverse_proxy /wp-includes/* d37p4vovx82i8u.cloudfront.net:443
reverse_proxy /wp-content/* d37p4vovx82i8u.cloudfront.net:443
```
Now, its showing error and doesn't display the content anymore.

Is there anyway to resolve this? Or, am I wrong on this configuration as per the any new conf on latest release?

**Comment by mholt** [comment] 2020-07-10 22:49
Thanks for opening an issue! We'll look into this.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by bestpaydeals** [comment] 2020-07-11 00:27
## 1. Environment

### 1a. Operating system and version

```
Amazon Linux 2
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
2.1.1
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
N/A
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)

As checked on Chromium browser. All reverse proxied content cannot be found or displayed. As much as I remember there were 400 and or 500 errors.


### 2b. Why it's a bug (if it's not obvious)

Because same configuration was working on Caddy 2.0. And when I check the reverse proxied URLs directly they are all right and all contents displays on web browser correctly.


### 2c. Log output

```
Its hard to redo buggy things again on live traffic website. But, as far as I seen, there was no such 404, 410, However, following are my configuration as I can show:

```
mysite.com, www.mysite.com {
root * /var/www/html/bestpaydeals
import /etc/caddy/caddy_security.conf /* Also commented this and checked */
#reverse_proxy /wp-includes/* d37p4vovx82i8u.cloudfront.net:443 /* Now commented because not working */
#reverse_proxy /wp-content/* d37p4vovx82i8u.cloudfront.net:443 /* same */
php_fastcgi unix//var/opt/remi/php74/run/php-fpm/www.sock
encode zstd gzip
file_server
header Strict-Transport-Security max-age=15552000
@static {
file
path *.ico *.css *.js *.gif *.jpg *.jpeg *.png *.svg *.woff *.woff2
}
header @static Cache-Control max-age=15552000
log {
output file /var/log/caddy/access.log
format single_field common_log
}
@secure {
file
path *.sql *.bak *.zip *.tgz *.tar.gz
}
respond @secure 404
}
```
```



### 2d. Workaround(s)

Not working anyway!


### 2e. Relevant links

`https://d37p4vovx82i8u.cloudfront.net/wp-content/uploads/2020/07/perfect_keto_mct_oil_powder.jpg`


## 3. Tutorial (minimal steps to reproduce the bug)

As refer to 2e, paths on the folders /wp-content/* and /wp-includes/* are working. It was absolutely working on v2.0 until I updated to 2.1.1 and the bug appeared. I cleared up redis, WordPress and CloudFront Cache but bug appears. However, when I comment reverse proxy and reload caddy, everything is back to normal.

**Comment by mholt** [comment] 2020-07-11 01:24
Thanks. More to the point, how can we reproduce this?

> `https://d37p4vovx82i8u.cloudfront.net/wp-content/uploads/2020/07/perfect_keto_mct_oil_powder.jpg`

This works just fine.

I'll close the issue, but if you can show us how to reproduce this and prove that it's a bug, will be happy to reopen and fix it. (Or, even faster, since you are the only one able to reproduce the problem right now: figure out what the problem is then submit a patch. We'll be happy to help answer questions along the way, probably in our forum.)

**Closed by mholt** 2020-07-11 01:24 UTC
Labels: needs info

**Comment by mholt** [comment] 2020-07-11 01:57
@francislavoie pointed out to me that `d37p4vovx82i8u.cloudfront.net:443` might not enable TLS, you might need `https://d37p4vovx82i8u.cloudfront.net` instead. But, in any case, I don't think I have a firm grasp of the problem -- right now, with the given information, it could still be anything else too, like an AWS misconfiguration or something.

**Comment by bestpaydeals** [comment] 2020-07-12 14:14
On security policy I have kept TLSv1.2_2018 (recommended)

**Comment by bestpaydeals** [comment] 2020-07-12 14:19
No, I changed and tried on TLSv1 still the same issue.

**Comment by bestpaydeals** [comment] 2020-07-12 14:29
Now, I also tired pointing A and AAAA record to CloudFront and try browsing the website. It is working. So, there is no mistake it must be a bug in Caddy 2.1.1 or what else is there?

**Comment by mholt** [comment] 2020-07-12 19:08
Did you read my comment above?

**Comment by bestpaydeals** [comment] 2020-07-13 13:24
Yes that worked sory for all the troubles.
