### ISSUE TITLE
reverse_proxy loadbalance retry post request,Error:http: invalid Read on closed Body"

### ISSUE THREAD

**Issue by lonso** [caddyserver/caddy#5454] opened 2023-03-23 01:19 UTC
server1:  127.0.0.1:8001

server2: 127.0.0.1:8002

CaddyFIle:

`
:8000 {
    handle {
        reverse_proxy  {
            lb_policy random
            lb_retries 8
            lb_try_duration 10s
            lb_retry_match {
                method "GET"
            }
            to :8001 :8002
        }
    }
}
`

server2 shutdown,client to 127.0.0.1:8000, caddy retry to select upstream,but the log display Err: invalid Read on closed Body.

<img width="1600" alt="image" src="https://user-images.githubusercontent.com/5660818/227074055-e62d9ffb-90f7-468c-a454-ad721dc81b9c.png">

**Comment by francislavoie** [comment] 2023-03-23 02:08
Thanks for opening an issue! We'll look into this.

It's not immediately clear to us what is going on, so we'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by lonso** [comment] 2023-03-23 02:17
## 1. Environment

### 1a. Operating system and version

```
macOS 12.6
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
v2.6.1 h1:EDqo59TyYWhXQnfde93Mmv4FJfYe00dO60zMiEt+pzo=

```


### 1c. Go version (if building Caddy from source; run `go version`)

```
go version go1.18 darwin/amd64
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)

reverse_proxy upstreams want to load balance.if one server shutdown,we want request restry to other  enable server.


### 2b. Why it's a bug (if it's not obvious)

when we test use post request, restry failed, the error is http: invalid Read on closed Body


### 2c. Log output

```
{"upstream": ":8001", "duration": 0.001284789, "request": {"remote_ip": "127.0.0.1", "remote_port": "56145", "proto": "HTTP/1.1", "method": "POST", "host": "127.0.0.1:8000", "uri": "/ping", "headers": {"Cache-Control": ["no-cache"], "Sec-Fetch-Site": ["none"], "Accept-Language": ["en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,zh-TW;q=0.6"], "User-Agent": ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"], "Origin": ["chrome-extension://coohjcphdfgbiolnekdpbcijmhambjff"], "X-Forwarded-Proto": ["http"], "Content-Length": ["2"], "Content-Type": ["text/plain;charset=UTF-8"], "Sec-Fetch-Dest": ["empty"], "Sec-Ch-Ua-Mobile": ["?0"], "Accept-Encoding": ["gzip, deflate, br"], "Accept": ["*/*"], "X-Forwarded-For": ["127.0.0.1"], "Sec-Ch-Ua-Platform": ["\"macOS\""], "Sec-Fetch-Mode": ["cors"], "Sec-Ch-Ua": ["\"Google Chrome\";v=\"111\", \"Not(A:Brand\";v=\"8\", \"Chromium\";v=\"111\""], "X-Forwarded-Host": ["127.0.0.1:8000"]}}, "error": "readfrom tcp 127.0.0.1:56178->127.0.0.1:8001: http: invalid Read on closed Body"}
```

**Comment by francislavoie** [comment] 2023-03-23 02:28
Please try with the latest version, v2.6.4.

**Comment by WeidiDeng** [comment] 2023-03-24 02:55
Your Caddyfile is not formatted, and it doesn't allow `POST` body request retry.

```
:8000 {
	handle {
		reverse_proxy {
			lb_policy random
			lb_retries 8
			lb_try_duration 10s
			lb_retry_match {
				method "GET"
			}
			to :8001 :8002
		}
	}
}
```

And to allow `POST` requests retry, you have to buffer the request body. Which is a different setting.

**Closed by WeidiDeng** 2023-03-24 02:55 UTC
