### ISSUE TITLE
Windows Caddy version unknown

### ISSUE THREAD

**Issue by jungle-boogie** [caddyserver/caddy#2715] opened 2019-08-20 15:11 UTC
## 1. Which version of Caddy are you using (`caddy -version`)?
https://github.com/caddyserver/caddy/releases/tag/v1.0.3
https://github.com/caddyserver/caddy/releases/download/v1.0.3/caddy_v1.0.3_windows_amd64.zip
Windows 64bit

## 2. What are you trying to do?
Get version number of the Windows binary.

## 3. What is your Caddyfile?
(blank)

## 4. How did you run Caddy (give the full command and describe the execution environment)?
PS C:\Users\users\Downloads\caddy_v1.0.3_windows_amd64> .\caddy.exe -version
unknown

## 5. Please paste any relevant HTTP request(s) here.
(none)

## 6. What did you expect to see?
Caddy to return 1.0.3 or a hash from the release of 1.0.3

## 7. What did you see instead (give full error messages and/or log)?
`unknown` for the version number.

## 8. Why is this a bug, and how do you think this should be fixed?
This is a bug because the version number is known and previous builds of Caddy return the build number or a hash.

## 9. What are you doing to work around the problem in the meantime?
Opening a bug.

## 10. Please link to any related issues, pull requests, and/or discussion.
This is the only discussion I know of regarding Windows Caddy version number issues.

## Bonus: What do you use Caddy for? Why did you choose Caddy?
It runs on a Windows server and displays contents of a directory with `browse` so that photos can be seen without needing to map/mount a drive to the server.

**Comment by mholt** [comment] 2019-08-20 17:06
To clarify, is this from a Caddy binary you downloaded from the GitHub releases page you linked to, then?

**Comment by jungle-boogie** [comment] 2019-08-20 17:07
Yes, this link exactly: https://github.com/caddyserver/caddy/releases/download/v1.0.3/caddy_v1.0.3_windows_amd64.zip

**Comment by abbatis** [comment] 2019-10-17 20:51
Hi, why was this issue closed? I have the same issue, although on mac OS.

```$ caddy -version
unknown```

In PHP:
```[SERVER_SOFTWARE] => Caddy/unknown````

**Comment by mholt** [comment] 2019-10-17 20:56
@abbatis This issue was not closed. It is still open.

**Comment by imadphp** [comment] 2019-10-18 15:35
@mholt My bad 😄

**Comment by aaronraimist** [comment] 2019-11-08 03:35
Is this related to (or a duplicate of) #2584?

**Comment by mholt** [comment] 2019-11-08 04:47
Oh, yes it is. Thank you!

**Closed by mholt** 2019-11-08 04:47 UTC
