### ISSUE TITLE
Caddy does not take the correct certificate

### ISSUE THREAD

**Issue by alex1891** [caddyserver/caddy#3161] opened 2020-03-20 13:41 UTC
Hey guys,
I have a problem with some REST-Clients (for example yarc) or in my client-software-code when I try to send requests to my webserver behind my caddy (Version 1.3). I have set the common name to * because I have a embedded device with no hostname etc. 
When I do not set the TLS-property: "SSL_CTRL_SET_TLSEXT_HOSTNAME" in my code, the caddy proxy does not take the correct certificate and throws an error. 

In my opinion the wildcard * should mean: Caddy, take this certificate, it does not matter what the client is sending!

Best reguards
Alex

**Comment by mholt** [comment] 2020-03-20 13:42
Thanks for opening an issue! We'll look into this.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by mholt** [comment] 2020-03-23 20:52
Closing until there's more info

**Comment by alex1891** [comment] 2020-03-24 07:13
## 1. Environment

### 1a. Operating system and version
Ubuntu Core 18


### 1b. Caddy version (run `caddy version` or paste commit SHA)
1.0.4


### 1c. Go version (if building Caddy from source; run `go version`)
1.13


## 2. Description

### 2a. What happens (briefly explain what is wrong)
I have a problem with some REST-Clients (for example yarc) or in my client-software-code written in C++. When I try to send requests to my webserver behind my caddy. 

I have set the common name in my server certificate and the default-sni to * because I have a embedded device with no hostname etc.

When I do not set the TLS-property: "SSL_CTRL_SET_TLSEXT_HOSTNAME" in my code, the caddy proxy does not take the correct certificate and throws an error.


### 2b. Why it's a bug (if it's not obvious)

 my opinion the wildcard * should mean: Caddy, take this certificate, it does not matter what the client is sending.


### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)
Set the tls property SSL_CTRL_SET_TLSEXT_HOSTNAME, but not every REST-Client (e.g. YARC) does not support this.


### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)
Create
caddy --default-sni "*" -conf ./Caddyfile

**Comment by mholt** [comment] 2020-03-24 13:53
Thanks, but there's still not enough information here. What is your Caddyfile?

**Comment by alex1891** [comment] 2020-03-24 14:59
Hey, here is my "main-caddy-file"
`#Main configuration
#localhost:{$CADDY_PORT} # Dynamic port configuration
:80, :443

#Allow cors for all paths
cors / {
        origin *
        methods GET,POST,PUT,OPTIONS,DELETE,PATH
        allowed_headers Authorization,User-Agent,Keep-Alive,Origin,Accept,Content-Type
        exposed_headers ETag
}

#Redirect http to https
redir 301 {
        if {scheme} is http
        / https://{host}{uri}
}

import {$SNAP_DATA}/proxy_conf/apps/* # import all application specific Caddyfiles

# TLS/SSL specific configuration
tls {$SNAP_COMMON}/certs/caddy_cert.pem {$SNAP_COMMON}/private/caddy_privkey.pem`

and this a configuration that is imported:
`jwt {
    path /my-app/api
    publickey {$SNAP_COMMON}/publickey.pem
}`

**Comment by mholt** [comment] 2020-03-24 15:11
Awesome, thanks. One last thing I'll need is the command you used to generate the certificate so I can use the same one.

**Comment by alex1891** [comment] 2020-03-24 15:26
Here is the command:
`openssl req \
        -new \
        -newkey rsa:4096 \
        -days 365 \
        -nodes \
        -x509 \
        -subj "/C=DE/ST=Berlin/L=Berlin/O=My Company/CN=*/emailAddress=foo@bar.com" \
        -keyout $SNAP_DATA/proxy_conf/configs/caddy_privkey.pem \
        -out $SNAP_DATA/proxy_conf/configs/caddy_cert.pem `

**Comment by mholt** [comment] 2020-03-24 15:39
Oh, I found the problem. Wildcards in certificate names apply only to one label ([RFC 1034](https://tools.ietf.org/html/rfc1034#section-4.3.3)). So `*` matches hostnames like `localhost` but not `example.com`. But, most clients will reject catch-all certificates and TLD wildcards (`*.tld`) anyway. So if you want to match `foo.example.com` your wildcard cert would be for `*.example.com`.

**Closed by mholt** 2020-03-24 15:39 UTC
Labels: needs info, v1

**Comment by alex1891** [comment] 2020-03-24 15:45
As I mentioned I am working with an embedded device that does not have a domain or a hostname. So this does not work for me.

**Comment by mholt** [comment] 2020-03-24 15:47
I'm sorry to hear that. You'll have to make a certificate for the IP address instead, then.

**Comment by alex1891** [comment] 2020-03-24 18:17
The ip adress of device is not static - and upgrading to Caddy 2 is also no short-solution for us

**Comment by mholt** [comment] 2020-03-24 18:19
Well, I don't know what to tell you then. That's just how certificates work, it's not a Caddy issue.

**Comment by alex1891** [comment] 2020-03-24 18:22
in an older caddy version the CN wasn´t checked - in a newer version we have to use the wildcard or the real ip-adress or common name, otherwise a TLS-alert is thrown - maybe it would be a suitable way to have the possiblity to deactivate this behaviour.

**Comment by mholt** [comment] 2020-03-24 18:25
> in an older caddy version the CN wasn´t checked

By what? Please be more specific.
