### ISSUE TITLE
go get: /header_protector.go:131:8: cipher.SetCounter undefined

### ISSUE THREAD

**Issue by ddyok** [caddyserver/caddy#3081] opened 2020-02-26 01:05 UTC
I get this:

```
~$ go get github.com/caddyserver/caddy/caddy
# github.com/lucas-clemente/quic-go/internal/handshake
go/src/github.com/lucas-clemente/quic-go/internal/handshake/header_protector.go:131:8: cipher.SetCounter undefined (type *chacha20.Cipher has no field or method SetCounter)
# github.com/caddyserver/caddy/caddytls
go/src/github.com/caddyserver/caddy/caddytls/config.go:119:4: cannot use func literal (type func(certmagic.Certificate) (certmagic.Config, error)) as type certmagic.ConfigGetter in field value
go/src/github.com/caddyserver/caddy/caddytls/setup.go:135:19: config.Manager.Email undefined (type *certmagic.Config has no field or method Email)
go/src/github.com/caddyserver/caddy/caddytls/setup.go:153:19: config.Manager.CA undefined (type *certmagic.Config has no field or method CA)
go/src/github.com/caddyserver/caddy/caddytls/setup.go:160:19: config.Manager.KeyType undefined (type *certmagic.Config has no field or method KeyType)
go/src/github.com/caddyserver/caddy/caddytls/setup.go:257:19: config.Manager.DNSProvider undefined (type *certmagic.Config has no field or method DNSProvider)
go/src/github.com/caddyserver/caddy/caddytls/setup.go:361:27: config.Manager.KeyType undefined (type *certmagic.Config has no field or method KeyType)
go/src/github.com/caddyserver/caddy/caddytls/tls.go:80:42: not enough arguments in call to certmagic.NewDefault().RevokeCert
	have (string, bool)
	want (context.Context, string, bool)

```

**Comment by mholt** [comment] 2020-02-26 02:03
Probably some version mismatch somewhere. Make sure your version of Go is up-to-date, that you are using Go modules (and not GOPATH), etc etc.

Closing, since AFAIK this is not a bug in Caddy. Feel free to continue discussion, but please post more details about your environment and steps you've taken to get more help!

**Closed by mholt** 2020-02-26 02:03 UTC
