### ISSUE TITLE
http: invalid configuration: server 623ac93708d92b379582f3ad: listener address repeated: tcp/:443 (already claimed by server '623ac70258a9be37ad185243')

### ISSUE THREAD

**Issue by bookyo** [caddyserver/caddy#4656] opened 2022-03-23 07:58 UTC
when i use api create new host which binding 443 will cause this error:
```
{"level":"error","ts":1648019767.4574378,"logger":"admin.api","msg":"request error","error":"loading new config: loading http app module: http: invalid configuration: server 623ac93708d92b379582f3ad: listener address repeated: tcp/:443 (already claimed by server '623ac70258a9be37ad185243')","status_code":500}
```
first i post api http://localhost:2019/load to set a new json, host binding 443, and then i put http://localhost:2019/config/apps/http/servers/newserver' to create new server which binding 443, and will cause this error. why i cant set multe server binding 443 port?

**Comment by mohammed90** [comment] 2022-03-23 08:38
Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by bookyo** [comment] 2022-03-23 10:59
### 1a. Operating system and version

```
ubuntu 20.4
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
v2.4.6 h1:HGkGICFGvyrodcqOOclHKfvJC0qTU7vny/7FhYp9hNw=
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
no
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)

i write a admin panel, and use caddy manager domains, i found if binding same port when create new host, will cause:
```
listener address repeated: tcp/:443 (already claimed by server id)
```


### 2b. Why it's a bug (if it's not obvious)

if i use api create new host which binding same port,  it will work not cause error.


### 2c. Log output

```
2|caddyser | {"level":"error","ts":1648019767.4574378,"logger":"admin.api","msg":"request error","error":"loading new config: loading http app module: http: invalid configuration: server 623ac93708d92b379582f3ad: listener address repeated: tcp/:443 (already claimed by server '623ac70258a9be37ad185243')","status_code":500}

```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)
this is my code, logic is click button create new host, form post body: host, port, handler, root, upstream, and backend post http://localhost:2019/load reset or replaces the active configuration.
```
  const { host, port, handler, root, upstream } = req.body;
  const caddy = await Caddy.create({
    host,
    port,
    handler,
    root,
    upstream,
  });
  // const existsPortCaddy = await Caddy.findOne({port: port});
  // if(existsPortCaddy) {
  //   const existsHost = existsPortCaddy.host;
  //   const existsCaddyId = existsPortCaddy._id;
  //   const existsHostArr = existsHost.split('|');
  //   const hostArr = host.split('|');
  //   const newHostArr = [...hostArr, ...existsHostArr];
  //   let newServer = {};
  //   newServer = {
  //     listen: [":" + port],
  //     routes: [{
  //       match: [{
  //         host: newHostArr,
  //       }]
  //     }]
  //   }
  //   if (handler == 'file_server') {
  //     newServer.routes[0].handle = [{
  //       "handler": "vars",
  //       "root": root
  //     }, {
  //       "handler": "file_server",
  //       "hide": ["./Caddyfile"]
  //     }];
  //   } else {
  //     newServer.routes[0].handle = [{
  //       "handler": "reverse_proxy",
  //       "headers": {
  //         "request": {
  //           "set": {
  //             "X-Forwarded-Proto": ["{http.request.scheme}"],
  //             "X-Real-Ip": ["{http.request.remote.host}"]
  //           }
  //         }
  //       },
  //       "upstreams": [{
  //         "dial": upstream
  //       }]
  //     }];
  //   }
  //   try {
  //     const response = await axios({
  //       method: 'PATCH',
  //       url: 'http://localhost:2019/config/apps/http/servers/' + id,
  //       data: newServer,
  //     });
  //     console.log(response);
  //     await Caddy.updateOne({ _id: id }, { host, port, handler, root, upstream });
  //     res.redirect('/admin/caddies')
  //   } catch (error) {
  //     console.log(error);
  //     res.send(error.message);
  //   }
  // }
  const caddies = await Caddy.find();
  const oldServers = {};
  for (let index = 0; index < caddies.length; index++) {
    const caddy = caddies[index];
    oldServers[caddy._id] = {
      listen: [":" + caddy.port],
      routes: [{
        match: [{
          host: caddy.host.split('|'),
        }]
      }],
    }
    if (caddy.handler == 'file_server') {
      oldServers[caddy._id].routes[0].handle = [{
        "handler": "vars",
        "root": caddy.root
      }, {
        "handler": "file_server",
        "hide": ["./Caddyfile"]
      }];
    } else {
      oldServers[caddy._id].routes[0].handle = [{
        "handler": "reverse_proxy",
        "headers": {
          "request": {
            "set": {
              "X-Forwarded-Proto": ["{http.request.scheme}"],
              "X-Real-Ip": ["{http.request.remote.host}"]
            }
          }
        },
        "upstreams": [{
          "dial": caddy.upstream
        }]
      }];
    }
  }
  const newServer = {};
  newServer[caddy._id] = {
    listen: [":" + port],
    routes: [{
      match: [{
        host: host.split('|'),
      }]
    }]
  }
  if (handler == 'file_server') {
    newServer[caddy._id].routes[0].handle = [{
      "handler": "vars",
      "root": root
    }, {
      "handler": "file_server",
      "hide": ["./Caddyfile"]
    }];
  } else {
    newServer[caddy._id].routes[0].handle = [{
      "handler": "reverse_proxy",
      "headers": {
        "request": {
          "set": {
            "X-Forwarded-Proto": ["{http.request.scheme}"],
            "X-Real-Ip": ["{http.request.remote.host}"]
          }
        }
      },
      "upstreams": [{
        "dial": upstream
      }]
    }];
  }

  const servers = { ...oldServers, ...newServer };
  const obj = {
    "apps": {
      "http": {
        servers
      }
    }
  };
  // try {
  //   const response = await axios({
  //     method: 'PUT',
  //     url: 'http://localhost:2019/config/apps/http/servers/' + caddy._id,
  //     data: newServer[caddy._id],
  //   });
  //   console.log(response);
  //   res.redirect('/admin/caddies');
  // } catch (error) {
  //   console.log(error);
  //   res.send(error.message);
  // }
  try {
    const response = await axios({
      method: 'POST',
      url: 'http://localhost:2019/load',
      data: obj,
    });
    console.log(response);
    res.redirect('/admin/caddies')
  } catch (error) {
    console.log(error);
    res.send(error.message);
  }
```

**Comment by bookyo** [comment] 2022-03-23 11:02
```
const response = await axios({
       method: 'PUT',
       url: 'http://localhost:2019/config/apps/http/servers/' + caddy._id,
       data: newServer[caddy._id],
     });
```
same error:
```
2|caddyser | {"level":"error","ts":1648019767.4574378,"logger":"admin.api","msg":"request error","error":"loading new config: loading http app module: http: invalid configuration: server 623ac93708d92b379582f3ad: listener address repeated: tcp/:443 (already claimed by server '623ac70258a9be37ad185243')","status_code":500}
```
i use pm2 manager caddy binary.
```
 2  │ caddyserver        │ fork     │ 3    │ online    │ 0%       │ 19.2mb   │
```

**Comment by bookyo** [comment] 2022-03-23 11:04
i use caddy binary inside my code source folder and save config in my source folder.
this is my pm2 config:
```
{
      name: "caddyserver",
      script: "./caddy/caddy",
      args: "run --environ --resume",
      instances: 1,
      exec_mode: "fork",
      exec_interpreter: "",
      error_file: "./logs/caddyserver-error.log",
      out_file: "./logs/caddyserver-out.log",
      env_production: {
        XDG_DATA_HOME: "./",
        XDG_CONFIG_HOME: "./",
      }
    },

```

**Comment by bookyo** [comment] 2022-03-23 11:09
This error is thrown if both domains I create are binding to the same port, I've tried both port 80 and port 443, but if 
```
match: [{
           host: hostArr,
         }] 
```
can work fine with multiple hosts which binding same port at the same time.

**Closed** 2022-03-23 11:42 UTC
Labels: needs info

**Comment by francislavoie** [comment] 2022-03-23 13:21
That's right, only one server can listen to a port at a time. For multiple domains, you need to configure routes in the same server, which match on the domain/host you want.
