### ISSUE TITLE
pb.proto warning

### ISSUE THREAD

**Issue by dijiwiz** [caddyserver/caddy#3525] opened 2020-06-26 23:44 UTC
I was upgrading to v2.1 and the build seemed to go fine.

When I attempted to print up the version to confirm I was shown this warning message:

2020/06/26 17:58:17 WARNING: proto: file "pb.proto" is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

v2.1.0 h1:MC4d65RCVaEKy1iOFjsD51mybOwS8qdEVBi7ESDhUfE=

It seems to run fine but thought that may be of interest to the project.

**Comment by Mohammed90** [comment] 2020-06-27 00:08
According to dgraph-io/dgraph#5290, this is due to upgrading the github.com/golang/protobuf package and can be fixed by downgrading it. Needs further digging to understand the nuance of what's going on there. Nonetheless, the fix seems simple.

**Comment by dijiwiz** [comment] 2020-06-27 00:17
Thank you!

**Comment by Mohammed90** [comment] 2020-06-27 00:21
I'll keep it open. We need to resolve it by inspecting our dependency graph and pick appropriate packages version.

The error originates from [github.com/dgraph-io/dgraph](https://github.com/dgraph-io/dgraph/blob/master/protos/pb.proto), which is in our dep graph due to github.com/smallstep/nosql. 
```bash
$ go mod why github.com/dgraph-io/badger
# github.com/dgraph-io/badger
github.com/caddyserver/caddy/v2/modules/caddypki/acmeserver
github.com/smallstep/nosql
github.com/smallstep/nosql/badger/v1
github.com/dgraph-io/badger
```

**Comment by linquize** [comment] 2020-06-27 16:17
c9049bdc24cf35a1c2a4871401428cd08daf1f7d causes the issue.

**Comment by mholt** [comment] 2020-06-27 16:32
That's weird, those are just patch updates. There should be no breaking changes in those.

**Comment by francislavoie** [comment] 2020-06-27 16:37
I think `github.com/smallstep/nosql v0.3.1` is to blame.

Technically it's not a breaking change in isolation for that lib to update its protobuf dependency, but the problem is that we also depend on CEL which also uses protobuf, but a version from a different repo.

I think those weren't marked as conflicting dependencies by the go mod dependency solver so we have two different versions pulled in of protobuf now.

I'm just thinking out loud based on the evidence I think is apparent but I can't say for sure, I don't know how go mod does its dep resolution, just making guesses here.

I think #3526 is related.

**Comment by Mohammed90** [comment] 2020-06-28 01:46
Sorry, my investigative skills we're subpar. It isn't coming from dgraph. dgraph experienced the same issue because they have their own `pb.proto` and depend on `badger` which also has `pb.proto`. We're seeing it from badger. I think this is because our `go.sum` has multiple versions of badger, which is transitive from `github.com/smallstep/nosql`, who also see the same in their `go.sum`.

https://github.com/caddyserver/caddy/blob/c9049bdc24cf35a1c2a4871401428cd08daf1f7d/go.sum#L168-L173

**Comment by Mohammed90** [comment] 2020-06-28 01:58
Perhaps golang/protobuf#1122 is loosely related

**Comment by mholt** [comment] 2020-06-29 18:05
@Mohammed90 Thanks for the investigation. Downgrading nosql is fine for now.

I'm still trying to understand the crux of the origin of the problem. I won't have much time to dig into this particular issue for a while since I'm busy working on the website backend. Is this due to a combination of our own dependencies, or is the problem upstream in another dependency?

**Comment by Mohammed90** [comment] 2020-06-29 21:19
There's nothing for us to do in our codebase, neither in smallstep/nosql. It's just the mere dependency on badger. It's resolved in badger as of PR dgraph-io/badger#1293. So to resolve it from the root, smallstep/nosql should depend on a commit dgraph-io/badger@809725940698806f4e6e828ee936a11ac05b8e62 or any commit after it. 

If someone can convince dgraph-io/badger to do a point release just for that, that'd be great for everyone.

**Comment by mholt** [comment] 2020-06-29 21:40
Alright, cool. We'll make sure this gets out in a 2.1.1 release soon.

**Closed** 2020-06-30 17:53 UTC
Labels: bug

**Comment by mvdan** [comment] 2020-09-14 16:38
For what it's worth, I'm fixing this upstream at https://github.com/dgraph-io/badger/pull/1519, which should remove the warning when a Go binary includes both badger v1 and v2.

**Comment by dijiwiz** [comment] 2021-01-01 17:46
It's back! I tried to compile the new 2.3.0 code and am getting the same message.

It had gone away on the 2.2 branch.

**Comment by francislavoie** [comment] 2021-01-01 17:50
@dijiwiz make sure to use the latest version of Go when building.

**Comment by mholt** [comment] 2021-01-01 18:57
Yeah it's not showing up for me.

**Comment by dijiwiz** [comment] 2021-01-01 19:12
I am using Go 1.5.6. I blew off my go.sum and module directory and did a go mod tidy and rebuilt. It works now.

Previously I had updated the go.mod version and ran a go mod tidy. 

Thanks for the help and the program. Happy new year!

**Comment by TristonianJones** [comment] 2021-03-31 15:54
This may or may not be helpful, but [cel-go v0.7.*](https://github.com/google/cel-go/releases) supports the latest version of the Golang protobuf API. I notice that the CEL dependency is at v0.6.0. Perhaps a version bump of CEL will help?

**Comment by mvdan** [comment] 2021-03-31 16:11
In case anyone is confused, the latest v2 release is from September 2020, and my fix went in a few weeks later, so right now using the latest v1 and v2 tags still gets you the warning. They haven't responded to [my comments](https://github.com/dgraph-io/badger/pull/1519#issuecomment-765678556), so I think v2 just isn't maintained anymore. If you're still building v1 together with v2, the only fixes seem to be either pulling the last v2 commit, or jumping to v3 directly.

**Comment by mvdan** [comment] 2021-07-20 09:16
> pulling the last v2 commit

In hindsight, that's not actually possible, as there's no v2 branch. If you pull a commit from master shortly after the latest v2 release, and including my proto fix, then it's likely that you're also pulling in unrelated changes or stuff from v3. So that wouldn't really be running "badger v2", but rather "badger at random master commit".

The protobuf library in Go started panicking on this namespace conflict since March, and it's really starting to bite me at work. I've [posted one more ping](https://github.com/dgraph-io/badger/pull/1519#issuecomment-883229923) to beg that they backport the commit and do a bugfix release. Upvotes or supporting comments are welcomed, if you're feeling the conflict pain and would like to see it happen. Otherwise, it seems like I'm the only one bothering them with this fatal bug :)

**Comment by mholt** [comment] 2021-07-20 19:41
Yay, looks like they might finally be on it.

**Comment by mvdan** [comment] 2021-07-22 09:30
They finally did it! Tears of joy!

**Comment by ThinkChaos** [comment] 2021-08-16 22:54
Can we get a release with that fixes this please?
v2.4.3's dependency graph still uses badger v2.2007.2 which has the issue.

**Comment by francislavoie** [comment] 2021-08-16 22:57
@ThinkChaos badger is an indirect dependency, we're waiting for https://github.com/smallstep/nosql/issues/12 to totally resolve this.

**Comment by ThinkChaos** [comment] 2021-08-16 22:59
Ah sorry I missed that! This issue should probably stay open then.

**Comment by ThinkChaos** [comment] 2021-08-17 00:04
I opened https://github.com/smallstep/nosql/pull/13 to bump their dependency.
In the mean time anyone can add `--with github.com/smallstep/nosql=github.com/ThinkChaos/nosql@master` to their `xcaddy` invocation to bypass the issue.
