### ISSUE TITLE
redir directive code html does not redirect using HTML document 

### ISSUE THREAD

**Issue by nomuus** [caddyserver/caddy#4940] opened 2022-08-08 21:10 UTC
## Version

Currently using Caddy 2.5.2 for Linux AMD64:

```v2.5.2 h1:eCJdLyEyAGzuQTa5Mh3gETnYWDClo1LjtQm2q9RNZrs=```

## Configuration
`Caddyfile` configuration:
```
(test_config) {
    redir /html https://www.example.com/ html
    redir /301 https://www.example.com/ permanent
    redir /302 https://www.example.com/ temporary
    redir /permanent https://www.example.com/ permanent
    redir /temporary https://www.example.com/ temporary

    respond /test_html_redirect_200 200 {
        body `<!DOCTYPE html>
<html>
	<head>
		<title>Redirecting...</title>
		<script>window.location.replace("https://www.example.com");</script>
		<meta http-equiv="refresh" content="0; URL='https://www.example.com'">
	</head>
	<body>Redirecting to <a href="https://www.example.com">https://www.example.com</a>...</body>
</html>
`
        close
    }

    respond /test_html_redirect_301 301 {
        body `<!DOCTYPE html>
<html>
	<head>
		<title>Redirecting...</title>
		<script>window.location.replace("https://www.example.com");</script>
		<meta http-equiv="refresh" content="0; URL='https://www.example.com'">
	</head>
	<body>Redirecting to <a href="https://www.example.com">https://www.example.com</a>...</body>
</html>
`
        close
    }

    respond /test_html_redirect_302 302 {
        body `<!DOCTYPE html>
<html>
	<head>
		<title>Redirecting...</title>
		<script>window.location.replace("https://www.example.com");</script>
		<meta http-equiv="refresh" content="0; URL='https://www.example.com'">
	</head>
	<body>Redirecting to <a href="https://www.example.com">https://www.example.com</a>...</body>
</html>
`
        close
    }

}

http://localhost {
    import test_config
}
```

## Details

After reviewing issue [#3979](https://github.com/caddyserver/caddy/issues/3979) and associated fix, it appears that the [redir](https://caddyserver.com/docs/caddyfile/directives/redir) directive is not redirecting as documented using HTML or script. Rather the redirect makes use of a `302` response code where the `200` code may be more appropriate. In prior versions, it's possible that `200` could have been the default response code. (`3xx` response code may meet expected behavior but if the `Location` header is omitted.)

According to the [syntax documentation](https://caddyserver.com/docs/caddyfile/directives/redir#syntax):

> `html` to use an HTML document to perform the redirect (useful for redirecting browsers but not API clients)

This supposes that any browser would be redirected using a script defined by [`metaRedir` const](https://github.com/caddyserver/caddy/blob/v2.5.2/caddyconfig/httpcaddyfile/builtins.go#L569).

The observed behavior is that the browser will not redirect from the HTML `meta` tag or the script.  Rather the browser will redirect based on the `Location` header in conjunction with the `302` response code. This behavior can be observed in a variety ways, for example:

- To determine if a script redirect is occuring, Chromium's browser developer tools can be used to set an *Event Listener Breakpoint* on *Script*. If the script-based redirect is successful then the page should pause at `<script>window.location.replace`.
- Alternatively, another simple test could be to add `alert('Script executed');` within the script tag of `metaRedir` prior to the `window.location.replace`. If the script-based redirect is successful then the browser will display an alert box then redirect after closing it.

The current behavior of Caddy 2.5.2 functions similar to specifying a code of `temporary` for the `redir` directive.  The following are all functionally equivalent while using a web browser:

- `redir <matcher> <to> temporary`

- `redir <matcher> <to> html`

- `redir <matcher> <to> 302`

## Suggestions

Based on observations of web applications implementing HTML/script redirection, the response code for HTML or script redirections should be `200` instead of `3xx`. Chromium appears to ignore the `Location` header if it is present and proceeds to execute the HTML/script code.

*Alternatively*, Chromium appears to execute the HTML/script code with a `3xx` response code but only if the `Location` header is removed from the response. It has not been confirmed which behavior is "RFC" standard behavior.

The expected behavior can be demonstrated and observed using the [`metaRedir` const](https://github.com/caddyserver/caddy/blob/v2.5.2/caddyconfig/httpcaddyfile/builtins.go#L569). value with the `respond` directive in the examples provided in the test configuration:

- `/test_html_redirect_200` will respond with a `200` and uses the redirect text from `metaRedir`.
- `/test_html_redirect_301` will respond with a `301` and uses the redirect text from `metaRedir` without a `Location` header.
- `/test_html_redirect_302` will respond with a `302` and uses the redirect text from `metaRedir` without a `Location` header.

**Comment by mholt** [comment] 2022-08-08 21:31
I guess that's true, we should emit a 200 status code and probably no Location header. I didn't know anyone actually used this feature anymore tbh :sweat_smile:

This will more properly adhere to documentation so that browsers (or any other client which evaluates `<meta>` tags and/or JS) redirect but not other clients (based on status code + Location header). I don't _really_ understand what the use case is for this but I guess it helps in some cases?

**Comment by mholt** [comment] 2022-08-09 17:12
@nomuus I've pushed a fix for this; hopefully it is the intended behavior now (and doesn't break anyone; don't think it should though, since we are now conforming to docs).

**Closed** 2022-08-09 17:12 UTC
Labels: bug

**Comment by nomuus** [comment] 2022-08-10 21:58
Cheers!

**Comment by T313C0mun1s7** [comment] 2022-08-16 00:10
I have this in use and my server is auto-updating. I just confirmed that includes Caddy as I have the current version. In addition the reason I found this issue is because I have a monitoring script in place that runs every 15 minutes and it tells be the status codes. I noticed that on the one redirect I had set to use the html method I was getting a 302 status and not a 200 status. All my other redirects are perm so they are status 301. This one stood out like a sore thumb. 

How can I get a notification when Caddy v2.5.3 hits the repos? I am using AlmaLinux release 8.6, the upstream would be Redhat Enterprise Linux 8.6.

**Comment by francislavoie** [comment] 2022-08-16 00:16
@T313C0mun1s7 you can click Watch on github to get notified on releases, but for packages, I assume you might be using COPR https://copr.fedorainfracloud.org/coprs/g/caddy/caddy/ so you can watch that for updates.

**Comment by mholt** [comment] 2022-08-16 00:17
@T313C0mun1s7 We're actually targeting 2.6 straightaway at this point, we've made enough progress with new features that 2.6 pre-releases are imminent! (One major feature left but hopefully won't take too long.)

GitHub has subscription options for releases if you click "Watch" in the top-right. You can customize them to just be notified of releases if you want.

You could also just download the latest CI artifacts if you want a build right now. For example, here's the assets for the latest tests currently: https://github.com/caddyserver/caddy/actions/runs/2862495458
