### ISSUE TITLE
follow websocket headers' names as they defined in spec

### ISSUE THREAD

**Issue by akosyakov** [caddyserver/caddy#4197] opened 2021-06-08 08:34 UTC
Many servers out there follow literally to web socket headers as they defined in https://datatracker.ietf.org/doc/html/rfc6455#section-4.2.1 If I read it correctly only values of `Upgrade` and `Connection` fields are defined like ASCII case-insensitive value. Switching from nginx to caddy broke many use cases for us: https://github.com/gitpod-io/gitpod/issues/4047#issuecomment-856566526

**Comment by francislavoie** [comment] 2021-06-08 08:43
Caddy passes through the `Upgrade` header exactly as provided by the client.

https://github.com/caddyserver/caddy/blob/76913b19ff053bc5b0848ce4d0bbf73698f30d93/modules/caddyhttp/reverseproxy/reverseproxy.go#L524

**Comment by francislavoie** [comment] 2021-06-08 08:45
Scratch that, the value does get lowercased:

https://github.com/caddyserver/caddy/blob/76913b19ff053bc5b0848ce4d0bbf73698f30d93/modules/caddyhttp/reverseproxy/reverseproxy.go#L824

So yes, it is "case insensitive". Caddy is spec compliant here. I'd call this a bug in your application.

**Comment by francislavoie** [comment] 2021-06-08 08:48
Sounds like a duplicate of https://github.com/caddyserver/caddy/issues/3888.

**Closed** 2021-06-08 08:47 UTC
Labels: needs info

**Comment by akosyakov** [comment] 2021-06-08 08:51
Our application is using caddy to proxy web socket connection to different servers (on different runtimes like java for instance). Such servers expect `Sec-WebSocket-*` (uppercase S after Web), but caddy is giving `Sec-Websocket` (lowercase s after web). We are not in control of fixing all kind of servers for different languages.

**Comment by francislavoie** [comment] 2021-06-08 08:53
We're also not in control of changing how Go's `http.Header` behaves. HTTP header fields are case insensitive, so it's a bug to rely on specific case for a header.
