### ISSUE TITLE
Local CA does not refresh intermediate certificate

### ISSUE THREAD

**Issue by DblK** [caddyserver/caddy#5617] opened 2023-07-04 07:03 UTC
hi,

First, I'd to say that I love Caddy! You make my life easier for a couple of things!

### 1a. Operating system and version

```
FriendlyWrt 21.02.3, r16554-1d4dea6d4f
```

### 1b. Caddy version (run `caddy version` or paste commit SHA)

I built caddy with [this link](https://caddyserver.com/download?package=github.com/aksdb/caddy-cgi/v2) for `arm64`.
```
v2.6.4 h1:2hwYqiRwk1tf3VruhMpLcYTg+11fCdr8S3jhNAdnPy8=
```

### 2a. What happens (briefly explain what is wrong)

Certificate with local CA does not refresh before expiration end.

### 2b. Why it's a bug (if it's not obvious)

It serves one time an expired intermediate certificate and on next query it's sending a new one.

### 2c. Log output

```
2023/07/04 12:19:05.567	warn	tls	stapling OCSP	{"error": "no OCSP stapling for [power.example.com]: no OCSP server specified in certificate", "identifiers": ["power.example.com"]}
2023/07/04 12:19:05.567	debug	tls.cache	added certificate to cache	{"subjects": ["power.example.com"], "expiration": "2023/07/04 23:48:09.000", "managed": true, "issuer_key": "example.com", "hash": "644e14fa46b543729749b880e027694bc7ace4d9e37fbcd81af36eadb8737e14", "cache_size": 4, "cache_capacity": 10000}
2023/07/04 12:19:05.567	debug	events	event	{"name": "cached_managed_cert", "id": "4b82d65b-e077-46a5-b1db-0edb20e59779", "origin": "tls", "data": {"sans":["power.example.com"]}}

{"level":"info","ts":1688473193.345026,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["power.example.com", ....]}
```

### 2d. Workaround(s)

Have a service to query the endpoint on a minute basis to avoid ssl issue with real queries.  
But I do not do it because it adds traffic on machine for nothing.

## 3. Tutorial (minimal steps to reproduce the bug)

```Caddyfile
{
	skip_install_trust
	admin off

	pki {
		ca example.com {
			name "Example.com Local Authority"
		}
	}
	storage file_system {
		root /etc/caddy/config
	}
}

(tls-internal) {
	tls {
		issuer internal {
			ca example.com
		}
	}
}

power.example.com {
	import tls-internal
	reverse_proxy 10.10.10.10:8080
}
```

Example of date on generated certificate:
```
Issued On	Tuesday, 4 July 2023 at 05:48:08
Expires On	Tuesday, 4 July 2023 at 17:48:08
```

- Install the Root Certificate on your machine
- Go to https://power.example.com to trigger issuing certificate
- Wait for 12 hours
- Go to https://power.example.com and see the expired certificate
- Go again and see the new certificate

I only changed the domain name since it's locally resolved by my internal dns and I override a possible existing domain that I do not want to pay for ^^.

**Comment by francislavoie** [comment] 2023-07-04 08:32
Thanks for opening an issue! We'll look into this.

It's not immediately clear to us what is going on, so we'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by DblK** [comment] 2023-07-04 12:26
Initial comment updated with your template ;)

**Comment by mholt** [comment] 2023-07-05 16:21
Thanks; will look into this soon! Catching up from a lot after the holiday.

**Comment by mholt** [comment] 2023-07-05 17:43
@DblK Are you using a web browser or curl?

If a web browser, please use curl to verify: `curl -v "https://power.example.com"` because browsers do funky things that don't reflect reality.

If this is a bug in Caddy, you'll see a TLS alert from curl where the intermediate's date is invalid. If it works in curl but not the browser, then it's a browser bug (which we've seen many times before).

**Comment by DblK** [comment] 2023-07-06 16:34
I waited for the 12 hours, and did `curl` before and after expiration and everything goes well.
Seems to be a browser issue...

However the [documentation](https://caddyserver.com/docs/caddyfile/directives/tls#internal) states that we should not change the `12h` lifetime.
Since you said, browser are not used to short-lived certs, what should be the default to set? `90d` like Let's encrypt or a lower value?

Anyways, thanks for helping me out!

**Comment by mholt** [comment] 2023-07-06 16:40
Thanks for verifying!

Yeah I've seen this before too. It's definitely a browser bug. I reported this years ago but it was received with hostility and burned me out so I don't care to pursue it anymore: https://bugs.chromium.org/p/chromium/issues/detail?id=1210965

Curl always works. Browsers don't always work. I guess they're OK with that.

**Closed by mholt** 2023-07-06 16:40 UTC
Labels: needs info :mailbox_with_no_mail:
