### ISSUE TITLE
[RC2] Panic when using basicauth

### ISSUE THREAD

**Issue by Kalagon** [caddyserver/caddy#3253] opened 2020-04-10 16:03 UTC
Hey,
I'm encountering an issue with basicauth in RC2.
Whenever the basic auth is required, caddy panics and the connection is dropped. Caddy does recover and serve other paths fine, as long as no basicauth is involved. It doesn't matter which hash algorithm is used. The hashes are generated using `caddy hash-password`.
The issue did not occur in RC1.

The log output is
```
2020/04/10 15:57:46 http2: panic serving <redacted>: runtime error: invalid memory address or nil pointer dereference
goroutine 2772 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc0005dc050, 0xc000955f8e, 0xc0006b4000)
	net/http/h2_bundle.go:5713 +0x16b
panic(0x144d380, 0x2470800)
	runtime/panic.go:969 +0x166
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc000803200, 0x192e1e0, 0xc0005dc050, 0xc0005bda00)
	github.com/caddyserver/caddy/v2@v2.0.0-rc.2/modules/caddyhttp/server.go:203 +0x932
net/http.serverHandler.ServeHTTP(0xc0007e77a0, 0x192e1e0, 0xc0005dc050, 0xc0005bcc00)
	net/http/server.go:2807 +0xa3
net/http.initALPNRequest.ServeHTTP(0x19335a0, 0xc0009b24b0, 0xc000720380, 0xc0007e77a0, 0x192e1e0, 0xc0005dc050, 0xc0005bcc00)
	net/http/server.go:3381 +0x8d
net/http.(*http2serverConn).runHandler(0xc0006b4000, 0xc0005dc050, 0xc0005bcc00, 0xc000b6ab40)
	net/http/h2_bundle.go:5720 +0x8b
created by net/http.(*http2serverConn).processHeaders
	net/http/h2_bundle.go:5454 +0x4e1
```

**Comment by mholt** [comment] 2020-04-10 16:05
Thanks for the report, but is already fixed. Duplicate of #3248 and #3250. You can get the latest build artifacts from CI to confirm!

**Closed by mholt** 2020-04-10 16:05 UTC

**Comment by Kalagon** [comment] 2020-04-10 16:09
Ah nice, didn't connect those dots. Thanks for the quick work and reply!
