### ISSUE TITLE
do not auto-retry failed Let's encrypt

### ISSUE THREAD

**Issue by My1** [caddyserver/caddy#3251] opened 2020-04-10 11:54 UTC
when Lets encrypt fails I think it is unwise to immediately retry it, as caddy just goes in does it 5 times and hits ratelimit which is definitely not really a good thing.

**Comment by mholt** [comment] 2020-04-10 14:03
Thanks for opening an issue! We'll look into this.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by My1** [comment] 2020-04-10 14:15
very simply speaking I started caddy but forgot to run the port forwarding therefore acme failed, and caddy went to retry immediately.

OS is windows 8.1 x64 
caddy is 1.0.4

caddy config
~~~
https://domain.tld {
root c:\htdocs
browse /
tls {
protocols tls1.2
}
}
~~~

cmd log
~~~
C:\Users\My1\Downloads\Caddy>caddy -conf="certs.txt"
Activating privacy features...

Your sites will be served over HTTPS automatically using Let's Encrypt.
By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
  https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Please enter your email address to signify agreement and to be notified
in case of issues. You can leave it blank, but we don't recommend it.
  Email address: EMAIL@domain.tld
2020/04/10 13:50:07 [INFO] acme: Registering account for EMAIL@domain.tld
2020/04/10 13:50:07 [INFO] [domain.tld] acme: Obtaining bundled SAN certificate
2020/04/10 13:50:08 [INFO] [domain.tld] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/3875179099
2020/04/10 13:50:08 [INFO] [domain.tld] acme: Could not find solver for: tls-alpn-01
2020/04/10 13:50:08 [INFO] [domain.tld] acme: use http-01 solver
2020/04/10 13:50:08 [INFO] [domain.tld] acme: Trying to solve HTTP-01
2020/04/10 13:50:11 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/3875179099
2020/04/10 13:50:12 [INFO] Unable to deactivate the authorization: https://acme-v02.api.letsencrypt.org/acme/authz-v3/3875179099
2020/04/10 13:50:13 [INFO] [domain.tld] acme: Obtaining bundled SAN certificate
2020/04/10 13:50:13 [INFO] [domain.tld] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/3875180139
2020/04/10 13:50:13 [INFO] [domain.tld] acme: Could not find solver for: tls-alpn-01
2020/04/10 13:50:13 [INFO] [domain.tld] acme: use http-01 solver
2020/04/10 13:50:13 [INFO] [domain.tld] acme: Trying to solve HTTP-01
2020/04/10 13:50:19 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/3875180139
2020/04/10 13:50:19 [INFO] Unable to deactivate the authorization: https://acme-v02.api.letsencrypt.org/acme/authz-v3/3875180139
2020/04/10 13:50:20 [INFO] [domain.tld] acme: Obtaining bundled SAN certificate
2020/04/10 13:50:21 [INFO] [domain.tld] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/3875181697
2020/04/10 13:50:21 [INFO] [domain.tld] acme: Could not find solver for: tls-alpn-01
2020/04/10 13:50:21 [INFO] [domain.tld] acme: use http-01 solver
2020/04/10 13:50:21 [INFO] [domain.tld] acme: Trying to solve HTTP-01
2020/04/10 13:50:24 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/3875181697
2020/04/10 13:50:25 [INFO] Unable to deactivate the authorization: https://acme-v02.api.letsencrypt.org/acme/authz-v3/3875181697
2020/04/10 13:50:26 [INFO] [domain.tld] acme: Obtaining bundled SAN certificate
2020/04/10 13:50:26 [INFO] [domain.tld] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/3875182777
2020/04/10 13:50:26 [INFO] [domain.tld] acme: use tls-alpn-01 solver
2020/04/10 13:50:26 [INFO] [domain.tld] acme: Trying to solve TLS-ALPN-01
2020/04/10 13:50:27 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/3875182777
2020/04/10 13:50:27 [INFO] Unable to deactivate the authorization: https://acme-v02.api.letsencrypt.org/acme/authz-v3/3875182777
2020/04/10 13:50:28 [INFO] [domain.tld] acme: Obtaining bundled SAN certificate
2020/04/10 13:50:29 [INFO] [domain.tld] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/3875183194
2020/04/10 13:50:29 [INFO] [domain.tld] acme: use tls-alpn-01 solver
2020/04/10 13:50:29 [INFO] [domain.tld] acme: Trying to solve TLS-ALPN-01
2020/04/10 13:50:30 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/3875183194
2020/04/10 13:50:30 [INFO] Unable to deactivate the authorization: https://acme-v02.api.letsencrypt.org/acme/authz-v3/3875183194
2020/04/10 13:50:31 [INFO] [domain.tld] acme: Obtaining bundled SAN certificate
2020/04/10 13:50:32 failed to obtain certificate: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:
rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url:
~~~

**Comment by mholt** [comment] 2020-04-10 14:18
@My1 Hm, thanks for the info. Does this happen with Caddy 2? (Use the latest builds from CI artifacts)

Equivalent Caddyfile to get you started:

```
https://domain.tld {
    root C:\htdocs
    file_server browse
}
```

**Comment by My1** [comment] 2020-04-10 14:21
> Use the latest builds from CI artifacts

not sure how to get to those here, on gitlab they were immediately visible, but I found no CI option on the caddy github page

**Comment by mholt** [comment] 2020-04-10 14:26
Yeah, GitHub needs to improve on that...

If you go to the commit page there's a little CI icon, usually a green checkmark, a red X, or a yellow circle -- click it, and go to Details, then you should see 3 artifacts: https://github.com/caddyserver/caddy/actions/runs/75279456

Or just click the Actions tab on any page in this project, find the most recent Cross Platform that is passing, and it will take you to a page with the artifacts.

**Comment by My1** [comment] 2020-04-10 14:43
okay it doesnt seem to retry immediately but wait a minute before.

I also switched to staging for this as I dont wanna hit anything again

~~~
C:\Users\My1\Downloads\caddy_v2_Windows_999ab22>caddy run --adapter caddyfile -config="caddyconf.txt"
2020/04/10 14:37:43.694 ←[34mINFO←[0m   using provided configuration    {"config_file": "caddyconf.txt", "config_adapter": "caddyfile"}
2020/04/10 14:37:43.699 ←[34mINFO←[0m   admin   admin endpoint started  {"address": "localhost:2019", "enforce_origin": false, "origins": ["localhost:2019"]}
2020/04/10 14:37:43.701 ←[34mINFO←[0m   http    server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS {"server
_name": "srv0", "https_port": 443}
2020/04/10 14:37:43.701 ←[34mINFO←[0m   http    enabling automatic HTTP->HTTPS redirects        {"server_name": "srv0"}
2020/04/10 14:37:43.704 ←[34mINFO←[0m   tls     cleaned up storage units
2020/04/10 14:37:43.705 ←[34mINFO←[0m   http    enabling automatic TLS certificate management   {"domains": ["domain.tld"]}
2020/04/10 14:37:43.710 ←[34mINFO←[0m   autosaved config        {"file": "C:\\Users\\My1\\AppData\\Roaming\\Caddy\\autosave.json"}
2020/04/10 14:37:43.711 ←[34mINFO←[0m   serving initial configuration
2020/04/10 16:37:43 [INFO][cache:0xc000487d10] Started certificate maintenance routine
2020/04/10 16:37:43 [INFO][domain.tld] Obtain certificate; acquiring lock...
2020/04/10 16:37:43 [INFO][domain.tld] Obtain: Lock acquired; proceeding...
2020/04/10 16:37:44 [INFO][domain.tld] Waiting on rate limiter...
2020/04/10 16:37:44 [INFO][domain.tld] Done waiting
2020/04/10 16:37:44 [INFO] [domain.tld] acme: Obtaining bundled SAN certificate given a CSR
2020/04/10 16:37:45 [INFO] [domain.tld] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/48513968
2020/04/10 16:37:45 [INFO] [domain.tld] acme: Could not find solver for: tls-alpn-01
2020/04/10 16:37:45 [INFO] [domain.tld] acme: use http-01 solver
2020/04/10 16:37:45 [INFO] [domain.tld] acme: Trying to solve HTTP-01
2020/04/10 16:37:55 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/48513968
2020/04/10 16:37:55 [INFO] Unable to deactivate the authorization: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/48513968
2020/04/10 16:37:55 [ERROR] acme: Error -> One or more domains had a problem:
[domain.tld] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Fetching http://domain.tld/.well-known/acme-challenge/-e6W4YKEievXxYPmmsmIN6oMvAkO_z
Yv-qkDaaoOCY4: Error getting validation data, url:
 (challenge=http-01 remaining=[tls-alpn-01])
2020/04/10 16:37:57 [INFO] [domain.tld] acme: Obtaining bundled SAN certificate given a CSR
2020/04/10 16:37:58 [INFO] [domain.tld] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/48513989
2020/04/10 16:37:58 [INFO] [domain.tld] acme: use tls-alpn-01 solver
2020/04/10 16:37:58 [INFO] [domain.tld] acme: Trying to solve TLS-ALPN-01
2020/04/10 16:37:58 http: TLS handshake error from 127.0.0.1:56543: EOF
2020/04/10 16:37:58 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/48513989
2020/04/10 16:37:59 [INFO] Unable to deactivate the authorization: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/48513989
2020/04/10 16:37:59 [ERROR] acme: Error -> One or more domains had a problem:
[domain.tld] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Error getting validation data, url:
 (challenge=tls-alpn-01 remaining=[])
2020/04/10 16:38:01 [ERROR] attempt 1: [domain.tld] Obtain: [domain.tld] acme: Error -> One or more domains had a problem:
[domain.tld] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Error getting validation data, url:
 - retrying in 1m0s (17.3005632s/720h0m0s elapsed)...

-----> here I hit ctrl+C

2020/04/10 14:38:13.472 ←[34mINFO←[0m   shutting down   {"signal": "SIGINT"}
2020/04/10 16:38:13 [INFO][domain.tld] Obtain: Releasing lock
2020/04/10 16:38:13 [INFO][cache:0xc000487d10] Stopped certificate maintenance routine
2020/04/10 16:38:13 [ERROR] Unable to clean up lock: remove C:\Users\My1\AppData\Roaming\Caddy\locks\cert_acme_domain.tld_acme-staging-v02.api.letsencrypt.org-
directory.lock: Das System kann die angegebene Datei nicht finden. (lock=cert_acme_domain.tld_acme-staging-v02.api.letsencrypt.org-directory storage=FileStorag
e:C:\Users\My1\AppData\Roaming\Caddy)
2020/04/10 16:38:13 [ERROR] domain.tld: obtaining certificate: context canceled
2020/04/10 14:38:13.477 ←[34mINFO←[0m   shutdown done   {"signal": "SIGINT"}
~~~

**Comment by mholt** [comment] 2020-04-10 14:45
Ah good, that's all as expected, it looks like it is working!

> okay it doesnt seem to retry immediately but wait a minute before.

That's due to Caddy 2's exponential backoff.

> I also switched to staging for this as I dont wanna hit anything again

Fun fact, Caddy 2 will switch to staging for you when it retries, so you won't have to worry (as much -- it's not perfect but it mostly works) about hitting rate limits. Still, manually switching to the staging endpoint is never a bad idea.

I will close this since this is apparently fixed in Caddy 2.

**Closed by mholt** 2020-04-10 14:45 UTC
