### ISSUE TITLE
Subject is missing in internal tls issued certificates 

### ISSUE THREAD

**Issue by aduzsardi** [caddyserver/caddy#3558] opened 2020-07-07 14:27 UTC
When using internal tls for https the subject is missing in the issued certificate , and chrome/chromium throws an error even if i import the CA in the trust store

**Caddy version v2.1.1**

**Caddy file**
```
https://staging.prodigycj.lan {
	reverse_proxy 10.0.1.6:8000
	tls internal {
		on_demand
	}
}
```

**Certificate details**

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            26:f0:9a:d0:2b:ac:fc:40:f7:44:8c:ea:d4:8d:1c:34
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN = Caddy Local Authority - ECC Intermediate
        Validity
            Not Before: Jul  7 13:22:20 2020 GMT
            Not After : Jul  8 01:23:20 2020 GMT
        Subject: 
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:ec:8c:39:f3:6f:b8:b2:f3:d7:9b:71:c6:28:2d:
                    4e:b5:23:e4:04:2c:76:ac:f2:3d:28:22:1d:10:97:
                    cc:51:a6:5c:79:94:b0:29:f5:fa:d2:0f:9b:9d:85:
                    0e:02:92:b1:2a:87:57:a5:79:1c:a7:ee:8b:c6:a2:
                    fa:64:24:64:fb
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Subject Key Identifier: 
                0A:E8:8F:00:78:B1:3B:6F:E9:9B:8D:7E:89:91:CB:7D:19:54:4D:00
            X509v3 Authority Key Identifier: 
                keyid:62:46:D0:03:6A:D3:3B:2E:83:04:52:A2:56:52:BF:B0:3D:01:88:3D

            X509v3 Subject Alternative Name: 
                DNS:staging.prodigycj.lan
    Signature Algorithm: ecdsa-with-SHA256
         30:46:02:21:00:d6:92:2e:92:05:69:3d:fe:c9:ec:49:30:76:
         cb:73:78:79:d9:dd:7c:6d:c5:fd:50:4b:32:70:30:2d:b2:6b:
         1e:02:21:00:8a:1a:90:2f:c2:40:3d:62:ab:09:e4:4b:41:9b:
         d5:51:0c:c8:56:f9:c4:51:26:4c:4b:6f:71:cb:02:5c:bf:08

```

**Comment by mholt** [comment] 2020-07-07 14:56
This is a relatively new behavior of Chrome. Duplicate of https://github.com/caddyserver/caddy/issues/3535 and fixed on master.

**Closed by mholt** 2020-07-07 14:56 UTC

**Comment by aduzsardi** [comment] 2020-07-09 07:38
Building from master seems to fix the issue with chrome and chromium but the subject is still missing in the issued certificate

Can this be fixed without hardcoding the common name in the code like they did in #3535 ?

**Comment by mholt** [comment] 2020-07-09 11:52
@aduzsardi CommonName has been deprecated for 20 years. Even Chrome hasn't supported CommonName for several years.

**Comment by aduzsardi** [comment] 2020-07-09 11:56
I don't know about that , i never seen a public certificate without a CN=whateverdomain.tld until now :)
so be it deprecated it's still used

**Comment by mholt** [comment] 2020-07-09 13:56
This is already being discussed in #3535, please don't repeat the same unrelated conversation in multiple issues.
