### ISSUE TITLE
Caddyfile doesn't work as expected randomly

### ISSUE THREAD

**Issue by mpmc** [caddyserver/caddy#4204] opened 2021-06-13 19:41 UTC
Is this a bit of an odd one. I've spent the last few days tinkering with this and it's nearly drove me [potty](https://www.merriam-webster.com/dictionary/potty)!

I'm currently using the following Caddyfile - I know some of you will wince at this but I thought, hey why not see if I can.
```
{
	debug
}
(web_root) {
	root * /var/www/
}

# This is for on demand tls without using external scripting.
# It's ugly but it works - sometimes!
127.0.0.1:80 {
	file_server browse 
	import web_root

	# Rewrite a domain query into a path request and only if /.
	@domain_query {
		path /
		query domain=*
	}
	rewrite @domain_query /domain/{query.domain}/

	@domain_exists {
		path_regexp domain \/domain\/(www\.)?([^\.\\\/].{1,})\/
		file {re.domain.2}/
	}
	
	handle @domain_exists {
		respond 200
	}
	respond 404
}

:443 {
}
```
Even though it's REALLY UGLY it does work sometimes! As you can see test.com exists and the folder is in /var/www/test.com whereas test4.com does not. 
```
mark@mark-desktop2:~$ curl -kv http://127.0.0.1/?domain=test.com
*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET /?domain=test.com HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: Caddy
< Date: Sun, 13 Jun 2021 19:00:20 GMT
< Content-Length: 0
< 
* Connection #0 to host 127.0.0.1 left intact
mark@mark-desktop2:~$ curl -kv http://127.0.0.1/?domain=test.com4
*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET /?domain=test.com4 HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Server: Caddy
< Date: Sun, 13 Jun 2021 19:00:21 GMT
< Content-Length: 0
< 
* Connection #0 to host 127.0.0.1 left intact

```
But restarting caddy with the same file? The same requests give an unexpected result. It now says test4.com and test.com exist?! Only test.com should return OK here but Caddy has other ideas.
```
mark@mark-desktop2:~$ curl -kv http://127.0.0.1/?domain=test.com
*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET /?domain=test.com HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: Caddy
< Date: Sun, 13 Jun 2021 19:11:54 GMT
< Content-Length: 0
< 
* Connection #0 to host 127.0.0.1 left intact
mark@mark-desktop2:~$ curl -kv http://127.0.0.1/?domain=test.com4
*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET /?domain=test.com4 HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: Caddy
< Date: Sun, 13 Jun 2021 19:11:55 GMT
< Content-Length: 0
< 
* Connection #0 to host 127.0.0.1 left intact


sudo caddy run --watch
2021/06/13 19:11:50.175	INFO	using adjacent Caddyfile
2021/06/13 19:11:50.176	WARN	input is not formatted with 'caddy fmt'	{"adapter": "caddyfile", "file": "Caddyfile", "line": 11}
2021/06/13 19:11:50.176	INFO	admin	admin endpoint started	{"address": "tcp/localhost:2019", "enforce_origin": false, "origins": ["localhost:2019", "[::1]:2019", "127.0.0.1:2019"]}
2021/06/13 19:11:50.176	INFO	http	server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS	{"server_name": "srv0", "https_port": 443}
2021/06/13 19:11:50.176	INFO	http	enabling automatic HTTP->HTTPS redirects{"server_name": "srv0"}
2021/06/13 19:11:50.176	INFO	http	server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server	{"server_name": "srv1", "http_port": 80}
2021/06/13 19:11:50.177	INFO	tls.cache.maintenance	started background certificate maintenance	{"cache": "0xc00031ae00"}
2021/06/13 19:11:50.177	DEBUG	http	starting server loop	{"address": "[::]:443", "http3": false, "tls": true}
2021/06/13 19:11:50.177	DEBUG	http	starting server loop	{"address": "[::]:80", "http3": false, "tls": false}
2021/06/13 19:11:50.177	INFO	tls	cleaning storage unit	{"description": "FileStorage:/root/.local/share/caddy"}
2021/06/13 19:11:50.177	INFO	tls	finished cleaning storage units
2021/06/13 19:11:50.177	INFO	autosaved config (load with --resume flag)	{"file": "/root/.config/caddy/autosave.json"}
2021/06/13 19:11:50.177	INFO	serving initial configuration
2021/06/13 19:11:50.177	INFO	watcher	watching config file for changes	{"config_file": "Caddyfile"}
2021/06/13 19:11:54.236	DEBUG	http.handlers.rewrite	rewrote request	{"request": {"remote_addr": "127.0.0.1:43024", "proto": "HTTP/1.1", "method": "GET", "host": "127.0.0.1", "uri": "/?domain=test.com", "headers": {"User-Agent": ["curl/7.74.0"], "Accept": ["*/*"]}}, "method": "GET", "uri": "/domain/test.com/?domain=test.com"}
2021/06/13 19:11:55.452	DEBUG	http.handlers.rewrite	rewrote request	{"request": {"remote_addr": "127.0.0.1:43026", "proto": "HTTP/1.1", "method": "GET", "host": "127.0.0.1", "uri": "/?domain=test.com4", "headers": {"User-Agent": ["curl/7.74.0"], "Accept": ["*/*"]}}, "method": "GET", "uri": "/domain/test.com4/?domain=test.com4"}
```

Like I said previously I've been trying this out for the past few days, doing all sorts to figure out why it's pot luck whether it works or not. At this point I'm pretty sure it's a bug somewhere - perhaps #4202? . The fmt warning is due to me adding a line break before `file_server browse` (to test if it's some cache or not).

Any direction or assistance as to what is going here would be gratefully received.

**Comment by mholt** [comment] 2021-06-15 01:44
So that we can reproduce this, what is the folder structure in `/var/www/`?

**Comment by mpmc** [comment] 2021-06-15 01:58
> 
> 
> So that we can reproduce this, what is the folder structure in `/var/www/`?

it's just a single dir called /test.com/ so, /var/www/test.com/ nothing else, the tree all owned by root with 755. Caddy running using sudo.

**Comment by mholt** [comment] 2021-06-15 19:33
@mpmc What version of Caddy are you using?

**Comment by mholt** [comment] 2021-06-15 19:55
Anyway, the nondeterminism is because the order these matchers is executed isn't defined:

```
	@domain_exists {
		path_regexp domain \/domain\/(www\.)?([^\.\\\/].{1,})\/
		file {re.domain.2}/
	}
```

In my debugging, I found that sometimes the `file` matcher was running before the `path_regexp` matcher. This is because in the underlying JSON representation, they are objects:

```
"match": [
	{
		"file": {
			"try_files": [
				"{http.regexp.domain.2}/"
			]
		},
		"path_regexp": {
			"name": "domain",
			"pattern": "\\/domain\\/(www\\.)?([^\\.\\\\\\/].{1,})\\/"
		}
	}
]
```

And object keys aren't ordered (in Go, at least). If the file matcher runs first, it won't have the results of the regexp yet, so it will be empty string.

/cc @francislavoie or @whitestrake  - can you think of another way to write this config?

**Comment by mholt** [comment] 2021-06-15 20:05
I think this is a weird way to do it, but here's my suggestion: guarantee that the regex matcher runs first. Replace the `handle @domain_exists` part of your config with this:

```
@domain_in_path path_regexp domain \/domain\/(www\.)?([^\.\\\/].{1,})\/
handle @domain_in_path {
	@domain_exists file {re.domain.2}/
	handle @domain_exists {
		respond 200
	}
}
```

I'll close this as I'm not sure there's anything actionable here, but feel free to continue discussion if perhaps we can clarify documentation or something like that. Or if anyone finds a better way to write this, feel free to share.

**Closed by mholt** 2021-06-15 20:05 UTC

**Comment by francislavoie** [comment] 2021-06-15 20:08
Yep - that's how I'd do it too, regexp in a separate matcher first. We've seen plenty of examples like that on the forums as well over the past year.

**Comment by mpmc** [comment] 2021-06-15 23:55
Thanks folks. Good to know i'm not completely mad.. yet.
