### ISSUE TITLE
caddy_http_requests_in_flight metric slowly rising

### ISSUE THREAD

**Issue by SteffenDE** [caddyserver/caddy#4009] opened 2021-02-03 09:42 UTC
Hello everyone,

I'm monitoring caddy with the `/metrics` endpoint and noticed that there is an increase in the number that `caddy_http_requests_in_flight` is reporting over time. I think this number should return to zero when there are no requests in flight, but it doesn't:

<img width="1652" alt="image" src="https://user-images.githubusercontent.com/4116351/106727566-e8b85500-660b-11eb-9d61-1d88032cef93.png">

The used query is `avg(avg_over_time(caddy_http_requests_in_flight{handler="[[handler]]", server="[[server]]"}[1m]))`.

Maybe someone knows what's causing this. Thank you all for the great work on caddy!

**Comment by francislavoie** [comment] 2021-02-03 12:11
FYI @hairyhenderson

**Comment by mholt** [comment] 2021-02-03 15:56
@SteffenDE Can you provide any more information about your server? What do your usage patterns look like? How often do you do config reloads? What does your config look like? How busy is your server? What are your clients like? What version of Caddy are you using? (I do want answers to all those questions...)

Resource leaks at this point would be pretty unlikely, but certainly possible of course. If there is one, it's probably in some less-used corner of the code base.

**Comment by hairyhenderson** [comment] 2021-02-03 16:28
@SteffenDE do you mind posting a view of `sum(caddy_http_requests_in_flight{handler="[[handler]]", server="[[server]]"})`?

The only thing I can think of is a missing idle timeout, but that's set to 5mins now.

**Comment by SteffenDE** [comment] 2021-02-03 17:24
> @SteffenDE Can you provide any more information about your server? What do your usage patterns look like? How often do you do config reloads? What does your config look like? How busy is your server? What are your clients like? What version of Caddy are you using? (I do want answers to all those questions...)
> 
> Resource leaks at this point would be pretty unlikely, but certainly possible of course. If there is one, it's probably in some less-used corner of the code base.

Whoops, I really forgot the most important things here. So:
```
$ caddy version
v2.3.0 h1:fnrqJLa3G5vfxcxmOH/+kJOcunPLhSBnjgIvjXV/QTA=
```
The server is running in Docker on Ubuntu 20.04 and is typically used Mondays through Fridays heavily from 08:00 until in the afternoon, as it serves a Moodle for a school. The config looks like this:
```
moodle.domain {
    root * /datapool/www/moodle_base/moodle
    file_server

    @blocked {
        path /.git/*
    }
    respond @blocked 403

    import logging.snippet moodle

    php_fastcgi 127.0.0.1:9000 {
        env SERVER_SOFTWARE Apache
    }

    tls myemail@mydomain.xyz {
        dns cloudflare mytoken
    }
}
```
The Dockerfile used to build looks like this:
```
FROM caddy:2.3.0-builder AS builder
RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare

FROM caddy:2.3.0-alpine
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```
The particular server is not really that busy, usually serving around 5 requests/s, with max up to 40 req/s today. At night most requests are just regular health checks.
Clients are a wild bunch of browsers accessing the Moodle instance as well as some people using the Moodle app, but nothing special here.
This is a screenshot of some more metrics that I collect. The request pattern here looks a bit strange as this particular server is also requested by a python script every 6 minutes for an api, so the graph looks a bit spiky:

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/4116351/106782438-73b84000-664a-11eb-8731-5dff3789125f.png">

I've got another school that is served by 4 load balanced caddy servers (same config, only for Moodle, so simple reverse_proxy with fastcgi as above) and there I'm also seeing this happen:

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/4116351/106781172-0eb01a80-6649-11eb-81ea-a0d91f46bbc8.png">
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/4116351/106781261-28516200-6649-11eb-8420-6a856aa1e8d1.png">

The full config here:
```
# Caddyfile
# Global configs
{
    http_port 80
    https_port 443
    email mymail

    storage redis {
        host          "10.100.16.5"
        port          6379
        db            1
        key_prefix    "caddytls"
        value_prefix  "caddy-storage-redis"
        timeout       5
        tls_enabled   "false"
        aes_key       "key",
    }

    servers :443 {
        listener_wrappers {
            proxy_protocol {
                timeout 5s
                allow 10.100.16.0/21
            }
            tls
        }
        protocol {
            experimental_http3
        }
    }
}

import vhosts/*.cf

# vhosts/moodle.cf
moodle.domainA, moodle.domainB {
    redir https://moodle.domainC{uri}

    tls myemail@mydomain.xyz {
        dns cloudflare mytoken
    }
}

moodle.domainC {
    root * /mnt/moodle/moodle
    file_server

    @blocked {
        path /.git/*
    }
    respond @blocked 403

    import logging.snippet moodle

    php_fastcgi 127.0.0.1:9000 {
        env SERVER_SOFTWARE Apache
    }

    tls myemail@mydomain.xyz {
        dns cloudflare mytoken
    }
}

# vhosts/prometheus.cf
:8080 {
    metrics /metrics

    import logging.snippet prometheus
}

# vhosts/logging.snippet
log {
    output file /var/log/{args.0}.log {
        roll_size 10MiB
        roll_keep 10
        roll_keep_for 336h
    }
    format filter {
         wrap json
         fields {
              request>remote_addr ip_mask {
                  ipv4 24
                  ipv6 32
              }
              common_log delete
         }
    }
}
```
The Dockerfile used here is similar, just with some more plugins:
```
FROM caddy:2.3.0-builder AS builder
RUN xcaddy build \
       --with github.com/caddy-dns/cloudflare \
       --with github.com/gamalan/caddy-tlsredis \
       --with github.com/francislavoie/caddy2-proxyprotocol@1326994

FROM caddy:2.3.0-alpine
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```
Some more graphs for this particular load-balanced setup:

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/4116351/106784085-3fde1a00-664c-11eb-9132-9755e20f2a39.png">

When restarting caddy, the value drops back to zero again for some time until it starts to climb again.

> @SteffenDE do you mind posting a view of `sum(caddy_http_requests_in_flight{handler="[[handler]]", server="[[server]]"})`?
> 
> The only thing I can think of is a missing idle timeout, but that's set to 5mins now.

<img width="941" alt="image" src="https://user-images.githubusercontent.com/4116351/106779992-d4924900-6647-11eb-8513-590bfd6b0a05.png">
Here are all current values for the metric:
<img width="982" alt="image" src="https://user-images.githubusercontent.com/4116351/106782147-1de39800-664a-11eb-906d-661e4b38c92b.png">

I hope this helps. If you need any more information I'll happily provide it.

**Comment by hairyhenderson** [comment] 2021-02-03 17:31
@SteffenDE thanks - as for the metric, I was looking for a graph rather than just a single value 😉.

The code for the requests-in-flight _seems_ correct - after the request is finished being handled, the gauge is decremented. It's done with a `defer` so I can't think of situations where it would fail to be decremented.

All that to say - I think the value that that metric is returning is correct. I'm not sure why you'd do an `avg(avg_over_time())` though - is there a reason for that?

**Comment by SteffenDE** [comment] 2021-02-03 19:19
> @SteffenDE thanks - as for the metric, I was looking for a graph rather than just a single value 😉.
> 
> The code for the requests-in-flight _seems_ correct - after the request is finished being handled, the gauge is decremented. It's done with a `defer` so I can't think of situations where it would fail to be decremented.
> 
> All that to say - I think the value that that metric is returning is correct. I'm not sure why you'd do an `avg(avg_over_time())` though - is there a reason for that?

Oh, well there you go:

<img width="1654" alt="image" src="https://user-images.githubusercontent.com/4116351/106797266-acf9ab80-665c-11eb-8512-9a41f0f04039.png">

and here from the load-balanced setup (sum of 4 other caddy servers):

<img width="1657" alt="image" src="https://user-images.githubusercontent.com/4116351/106797378-ce5a9780-665c-11eb-9195-4ccaaa11ee83.png">

I've copied the `avg(avg_over_time())` from [this public dashboard](https://grafana.com/grafana/dashboards/13460), I'm also not sure why the original author used this.

**Comment by SteffenDE** [comment] 2021-02-03 19:23
Some more information:
I do not think that the metric is correct. Normally I'd expect this to go back to zero when there aren't any active requests. From the load balancer stats I can see that the number of open connections goes back to basically zero at least during the night, so there shouldn't be any open connections any more during that time:

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/4116351/106797890-7ff9c880-665d-11eb-86fa-c7eec1e14758.png">

(First graph shows open connections, second graph new connections / second)

**Comment by mholt** [comment] 2021-02-03 19:45
I'm mobile so this is off the cuff but what if you disable http 3?

**Comment by SteffenDE** [comment] 2021-02-03 19:51
> I'm mobile so this is off the cuff but what if you disable http 3?
> 
> Ps. Thank you very much for the details!!

I'll try this, but I can already say that the single server setup does not have HTTP/3 enabled, so I do not think that this is the cause.

**Comment by SteffenDE** [comment] 2021-02-03 19:57
Maybe this has something todo with it:
I'm seeing many error messages with the following content:
```
{"level":"error","ts":1612362166.442285,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"http2: stream closed"}
```
<img width="1634" alt="image" src="https://user-images.githubusercontent.com/4116351/106801671-52fbe480-6662-11eb-952f-a77b9e83a84d.png">

**Comment by francislavoie** [comment] 2021-02-03 20:12
Do you have as many of those errors as you do "requests in flight"? Do the timestamps roughly align for when it jumps up?

**Comment by SteffenDE** [comment] 2021-02-03 20:53
I think you're right. There are about 30000 entries in the log with "stream closed", way more than the increase in the metric. And I also cannot really see a connection to the timestamps.

**Comment by mholt** [comment] 2021-02-04 00:48
@SteffenDE If you open the profiling endpoint at `http://localhost:2019/debug/pprof` (from that machine, of course), what are the numbers on the index page? If any of them are exceedingly high, maybe attach a dump of the linked page.

Oh, and if you're using Prometheus already, it is probably exporting that data for you? So that data might already be in your dashboards, but more presentable. I'm only guessing, but @hairyhenderson would know.

**Comment by mholt** [comment] 2021-02-04 03:05
Also, I just looked through the full config (thanks for posting that). I know this might not be feasible, but how much are you able to help narrow down whether it might be one of the third-party modules you have installed? Redis or proxy protocol... not sure if you can disable either but that might tell us very quickly whether this issue is even in the right repo.

The debug endpoint I mentioned in my last comment should also shed light if they have stack traces, but I'm not sure it's guaranteed depending on the situation. Disabling those modules (somehow...) one at a time would be a pretty surefire test.

**Comment by SteffenDE** [comment] 2021-02-04 10:48
> @SteffenDE If you open the profiling endpoint at `http://localhost:2019/debug/pprof` (from that machine, of course), what are the numbers on the index page? If any of them are exceedingly high, maybe attach a dump of the linked page.
> 
> Oh, and if you're using Prometheus already, it is probably exporting that data for you? So that data might already be in your dashboards, but more presentable. I'm only guessing, but @hairyhenderson would know.

<img width="245" alt="image" src="https://user-images.githubusercontent.com/4116351/106881470-df97b880-66dd-11eb-8565-6e90eddf36f0.png">

Nothing that I'd call "exceedingly high", but I'll attach the stack dump anyway. This machine currently reports 40 requests in flight as baseline when nothing happens. I also quickly removed the machine from the load balancer, so there were no requests during that time, but the metric still reported 40.

[goroutine.txt](https://github.com/caddyserver/caddy/files/5925116/goroutine.txt)

> Also, I just looked through the full config (thanks for posting that). I know this might not be feasible, but how much are you able to help narrow down whether it might be one of the third-party modules you have installed? Redis or proxy protocol... not sure if you can disable either but that might tell us very quickly whether this issue is even in the right repo. Edit: Derp, probably proxy_protocol has more to do with active requests than storage. So if you can disable proxy_protocol for a short time to test, that'd be worthwhile.
> 
> The debug endpoint I mentioned in my last comment should also shed light if they have stack traces, but I'm not sure it's guaranteed depending on the situation. Disabling those modules (somehow...) one at a time would be a pretty surefire test.

I also thought about this, but as I'm only using these plugins with the load balanced setup and also experience this with the single server (I've included the Dockerfile here: https://github.com/caddyserver/caddy/issues/4009#issuecomment-772680853), I'm quite sure that this is not the issue here.

**Comment by SteffenDE** [comment] 2021-02-04 11:09
Here an image where the node is removed from the load balancer for quite some time. Caddy reports zero requests (all handlers), but requests in flight are still reported as 40:

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/4116351/106884315-6ef29b00-66e1-11eb-9812-64b8e3d3ee04.png">

The only other "server" in caddy-language is the one that provides the prometheus /metrics endpoint. There it looks as expected:

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/4116351/106884451-9cd7df80-66e1-11eb-95f2-4097ca430740.png">

**Comment by mholt** [comment] 2021-02-04 15:56
Thanks for all the juicy details!! And we really appreciate your help in this investigation.

There seems to be a lot of goroutines and allocations in the FastCGI client -- what's your PHP backend like? You said it's Moodle right? It looks like it's holding connections open.

You might try setting read and write timeouts: https://caddyserver.com/docs/caddyfile/directives/php_fastcgi

Incidentally, [the FastCGI transport is _not_ efficient](https://github.com/caddyserver/caddy/issues/3803) -- it was a miracle I found an open source pure Go implementation of it at all, way back in like 2014, which has since disappeared -- and it needs a refactoring. However, first, the cause of connections being kept open to the FastCGI responder should be identified, because that's not normal. If the backend is holding them open, that is certainly one possibility.

**Comment by SteffenDE** [comment] 2021-02-04 17:25
> There seems to be a lot of goroutines and allocations in the FastCGI client -- what's your PHP backend like? You said it's Moodle right? It looks like it's holding connections open.

Right, Caddy talks to a php-fpm container that executes the Moodle scripts. The compose project looks like this:
```yaml
version: '3.3'

services:
  caddy:
    image: registry.gitlab.com/steffend/jvg-moodle/caddy
    restart: always
    network_mode: host
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./caddy:/var/www
      - /var/log:/var/log
      - /mnt/moodle:/mnt/moodle:rshared
      - /mnt/moodle_files:/mnt/moodle_files:rshared
    command: caddy run --config /var/www/Caddyfile
    cap_add:
      - NET_BIND_SERVICE
  php:
    image: registry.gitlab.com/steffend/jvg-moodle/php-fpm
    volumes:
      - ./php/php.ini:/opt/bitnami/php/etc/conf.d/custom.ini
      - ./php/www.conf:/opt/bitnami/php/etc/php-fpm.d/www.conf
      - /mnt/moodle:/mnt/moodle:rshared
      - /mnt/moodle_files:/mnt/moodle_files:rshared
    ports:
     - 127.0.0.1:9000:9000
    restart: always
```

The php container is based on the bitnami php-fpm container with some programs added that Moodle needs for converting submissions:
```Dockerfile
FROM bitnami/php-fpm:7.3-prod

RUN install_packages ghostscript unoconv autoconf build-essential \
 && pecl install redis \
 && echo "extension=redis.so" >> /opt/bitnami/php/etc/php.ini

CMD [ "php-fpm", "-F", "--pid", "/opt/bitnami/php/tmp/php-fpm.pid", "-y", "/opt/bitnami/php/etc/php-fpm.conf" ]
```

> You might try setting read and write timeouts: https://caddyserver.com/docs/caddyfile/directives/php_fastcgi

In fact I did not set these on purpose, as there are already limits set in the php-fpm configuration (although they are set quite high as there are some people uploading files over a slow connection):

```
root@moodle-web-9630683:~/moodle# cat php/php.ini
upload_max_filesize = 4G
post_max_size = 4G
default_socket_timeout = 360
max_input_time = 1800
max_execution_time = 1800
```
This should mean that the maximum time that a connection between caddy and the php-fpm container is open is 30 minutes. I can try to set the limits in the caddy file to 30 minutes too to see if that makes a difference.

> However, first, the cause of connections being kept open to the FastCGI responder should be identified, because that's not normal.

I guess you're on the right track here: for testing purposes I restarted the php container and voilà:

![image](https://user-images.githubusercontent.com/4116351/106928789-dc1f2400-6713-11eb-92c5-7592954001d2.png)

Does this mean that caddy does not realize that a client disconnected? Because from the load balancer I know that there aren't that many open connections to caddy. I'd expect the metric to decrease as soon as the request is done, i.e. either it is successfully served or the client disconnected for other reasons. But in the latter case it seems like the request stays in an "open" state. I do not think that caddy is waiting for a response from php, as this *should* time out after `max_execution_time` seconds and by no later than that, the request should be done...

<hr>

Off Topic:

> Incidentally, the FastCGI transport is not efficient

This may be true, but what's much less efficient most of the time are the php scripts. Kind of weird to need four machines to serve 80 req/s... (Off Topic: I'm running four nodes, with caddy + php, 4x2 vCPUs, as this is cheaper than using a beefier machine with this use case)
I know that one can use fastcgi for other languages too, I used to run caddy 1 with a python fastcgi-wsgi wrapper, but I guess most people that use the php_fastcgi directive actually use php and I've never seen caddy being a bottleneck there.

**Comment by mholt** [comment] 2021-02-08 19:05
@SteffenDE Very interesting! Thanks again for the detailed update. I think we're making progress.

> This should mean that the maximum time that a connection between caddy and the php-fpm container is open is 30 minutes. I can try to set the limits in the caddy file to 30 minutes too to see if that makes a difference.

Yes, please do. I'm interested to know if that helps regardless of the php-fpm config.

> Does this mean that caddy does not realize that a client disconnected?

To be honest, a lot of the fcgi transport code is foreign to me, as I haven't read the spec in detail nor did I implement it myself like I did most of the higher-level reverse proxy code or the HTTP transport. So I do not know. It would not surprise me if there was an obscure bug in this code, then; but it's also been in use in many production environments for 5+ years. (It is definitely due for a rewrite though!)

**Comment by SteffenDE** [comment] 2021-02-11 19:21
I‘ve kept an eye on this for a couple of days now and setting the timeouts in the php_fastcgi directive solves this problem 👍🏻

**Comment by mholt** [comment] 2021-02-11 20:02
That's great news! For some reason the connection is being kept open to the backend (at least in some cases). That could be a misconfiguration either the client or the backend -- or I suppose it could be in Caddy, but we haven't had any reports of that being the case. I suppose if you dig in and prove that it's something in Caddy that's not closing the connection, I wouldn't be *very* surprised (the whole transport is in need of a rewrite anyway, like I said) -- but I would be a little surprised, since you'd think everyone would be having this problem, which isn't so.

Sounds like setting the timeout is the easiest way to solve this when it does happen though! Thanks for following up!

**Closed by mholt** 2021-02-11 20:02 UTC
