### ISSUE TITLE
Caddy does not recognize a Caddyfile created from PowerShell

### ISSUE THREAD

**Issue by michaelgrigoryan25** [caddyserver/caddy#4359] opened 2021-09-24 14:13 UTC
Environment: Windows 10, latest version
Caddy version: v2.2.0 h1:sMUFqTbVIRlmA8NkFnNt9l7s0e+0gw+7GPIrhty905A=

Hi, I do not know why but when I created my Caddyfile in PowerShell with the following command
```powershell
$null > Caddyfile
```

and used the config below

```caddyfile
http://localhost:5000 {
	reverse_proxy localhost:3000
}

http://localhost:5001 {
	reverse_proxy localhost:3001
}
```

Caddy threw this error:

```
run: adapting config using caddyfile: ./Caddyfile:2: unrecognized directive:
Did you mean to define a second site? If so, you must use curly braces around each site to separate their configurations.
```

but after I created a file with the normal Windows context action(e.g. `New>Text Document`) and used the same config with the same filename, everything seemed to work fine.

**Comment by Mohammed90** [comment] 2021-09-24 17:10
I'm suspecting the issue is because you write $null to the beginning of the file. How are you adding the rest of the config afterwards? Do you have the same issue when creating the file with: `New-Item -ItemType "file" -Name "Caddyfile"` ?

**Comment by michaelgrigoryan25** [comment] 2021-09-24 17:21
> How are you adding the rest of the config afterwards?

I am just running `caddy run` from the directory where `Caddyfile` is present. Also tried running it with the `--config` flag.

> Do you have the same issue when creating the file with: New-Item -ItemType "file" -Name "Caddyfile" ?

After trying, I can surely say that the issue does not exist when creating the file with the command that you mentioned.

**Comment by mholt** [comment] 2021-09-24 17:24
I think the problem is having an invalid character in the Caddyfile.

Since this doesn't appear to be a bug, I'll close the issue, but feel free to continue discussion if needed.

**Comment by michaelgrigoryan25** [comment] 2021-09-24 17:25
Sure, thank you!

**Closed by mholt** 2021-09-24 17:24 UTC
Labels: needs info

**Comment by francislavoie** [comment] 2021-09-24 18:04
Another couple things:

>  Caddy version: v2.2.0 h1:sMUFqTbVIRlmA8NkFnNt9l7s0e+0gw+7GPIrhty905A=

Please upgrade to v2.4.5! That's a pretty old version at this point.

Also, for next time, we prefer usage questions to be asked on our community forums https://caddy.community, to keep the Github issue board focused on bugs and feature requests.

**Comment by michaelgrigoryan25** [comment] 2021-09-24 18:10
Sure @francislavoie. I posted it on GitHub, because I thought that it was an issue with Caddy. I will upgrade to v2.4.5. Thanks!
