### ISSUE TITLE
Caddy crashed when generating certificate

### ISSUE THREAD

**Issue by johanobergman** [caddyserver/caddy#5394] opened 2023-02-24 21:12 UTC
Caddy crashed when trying to generate a certificate. Not sure what went wrong, but we have a number of domains that point to us and some of them can have a lot of bad DNS config. I'm not sure if this domain `difbtf.se` was the reason for the crash but it has a lot of DNS records that don't point to us.

Caddy version `v2.6.1 h1:EDqo59TyYWhXQnfde93Mmv4FJfYe00dO60zMiEt+pzo=` on Ubuntu 22.04.

```
Feb 21 16:27:07 klubben-online-1 caddy[835]: {"level":"error","ts":1676993227.6915717,"logger":"http.acme_client","msg":"challenge failed","identifier":"difbtf.se","challenge_type":"http-01","problem":{"type":"","title":"","detail":"","instance":"","subproblems":[]}}
Feb 21 16:27:07 klubben-online-1 caddy[835]: {"level":"error","ts":1676993227.691596,"logger":"http.acme_client","msg":"validating authorization","identifier":"difbtf.se","problem":{"type":"","title":"","detail":"","instance":"","subproblems":[]},"order":"https://acme.zerossl.com/v2/DV90/order/wXEqfSek4YE1dFnaFerWZQ","attempt":1,"max_attempts":3}
Feb 21 16:27:07 klubben-online-1 caddy[835]: {"level":"error","ts":1676993227.6916168,"logger":"tls.renew","msg":"could not get certificate from issuer","identifier":"difbtf.se","issuer":"acme.zerossl.com-v2-DV90","error":"HTTP 0  - "}
Feb 21 16:27:07 klubben-online-1 caddy[835]: {"level":"info","ts":1676993227.6923947,"logger":"tls.renew","msg":"releasing lock","identifier":"difbtf.se"}
Feb 21 16:27:07 klubben-online-1 caddy[835]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 21 16:27:07 klubben-online-1 caddy[835]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8a4c34]
Feb 21 16:27:07 klubben-online-1 caddy[835]: goroutine 26848963 [running]:
Feb 21 16:27:07 klubben-online-1 caddy[835]: github.com/caddyserver/certmagic.(*Config).renewCert.func2({0x1de8c58, 0xc000dc6930})
Feb 21 16:27:07 klubben-online-1 caddy[835]:         github.com/caddyserver/certmagic@v0.17.1/config.go:821 +0xc14
Feb 21 16:27:07 klubben-online-1 caddy[835]: github.com/caddyserver/certmagic.doWithRetry({0x1de8c20, 0xc001d766c0}, 0xc00106bc20, 0xc000a33720)
Feb 21 16:27:07 klubben-online-1 caddy[835]:         github.com/caddyserver/certmagic@v0.17.1/async.go:106 +0x1cb
Feb 21 16:27:07 klubben-online-1 caddy[835]: github.com/caddyserver/certmagic.(*Config).renewCert(0xc0017ee370, {0x1de8c20, 0xc001d766c0}, {0xc00187a590, 0x9}, 0x0, 0x0)
Feb 21 16:27:07 klubben-online-1 caddy[835]:         github.com/caddyserver/certmagic@v0.17.1/config.go:860 +0x58b
Feb 21 16:27:07 klubben-online-1 caddy[835]: github.com/caddyserver/certmagic.(*Config).RenewCertAsync(...)
Feb 21 16:27:07 klubben-online-1 caddy[835]:         github.com/caddyserver/certmagic@v0.17.1/config.go:690
Feb 21 16:27:07 klubben-online-1 caddy[835]: github.com/caddyserver/certmagic.(*Config).renewDynamicCertificate.func3({0x1de8c20, 0xc001d766c0}, 0xc001bcbbd0?)
Feb 21 16:27:07 klubben-online-1 caddy[835]:         github.com/caddyserver/certmagic@v0.17.1/handshake.go:664 +0x2ac
Feb 21 16:27:07 klubben-online-1 caddy[835]: created by github.com/caddyserver/certmagic.(*Config).renewDynamicCertificate
Feb 21 16:27:07 klubben-online-1 caddy[835]:         github.com/caddyserver/certmagic@v0.17.1/handshake.go:699 +0x1293
Feb 21 16:27:07 klubben-online-1 systemd[1]: caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 21 16:27:07 klubben-online-1 systemd[1]: caddy.service: Failed with result 'exit-code
```

Caddy config:
```
{
	# Enable debug log to catch certificate errors.
	debug

	on_demand_tls {
		ask http://localhost:8000/api/caddy/domain
		interval 2m
		burst 20
	}
}

(dns_challenge) {
	issuer acme {
		email "johan@..."
		propagation_delay "60s"
		propagation_timeout "15m0s"
		dns glesys {
			project "..."
			api_key "..."
		}
	}
}

(server) {
	root * {args.0}

	request_body {
		max_size 40MB
	}

	@notStatic not file
	reverse_proxy @notStatic {args.1} {
		lb_try_duration 30s
		lb_try_interval 1s
	}

	file_server {
		hide index.php
	}

	encode zstd gzip

	# Cache build for 60 days.
	@static {
		file
		path /build/*
	}
	header @static Cache-Control max-age=5184000
}

# Redirect www to naked for the root domain.
www.klubbenonline.se {
	redir https://klubbenonline.se{uri}
}

# Main domains.
klubbenonline.se {
	import server /home/forge/klubbenonline.se/current/public localhost:8000
}

# Subdomains using wildcard certificate with Glesys DNS module.
# https://caddyserver.com/docs/caddyfile/patterns#wildcard-certificates
*.klubbenonline.se, *.preview.klubbenonline.se {
	tls {
		import dns_challenge
	}

	import server /home/forge/klubbenonline.se/current/public localhost:8000
}

staging.klubbenonline.se {
	import server /home/forge/staging.klubbenonline.se/current/public localhost:8001
}

*.staging.klubbenonline.se, *.preview.staging.klubbenonline.se {
	tls {
		import dns_challenge
	}

	import server /home/forge/staging.klubbenonline.se/current/public localhost:8001
}

# Custom domains, uses Caddy on demand certificates.
https:// {
	tls {
		on_demand
	}

	# Redirect www domains to the naked domain.
	@www header_regexp www Host ^www\.(.*)$
	redir @www https://{re.www.1}{uri} 301

	import server /home/forge/klubbenonline.se/current/public localhost:8000
}
```

**Comment by mholt** [comment] 2023-02-24 21:14
Please upgrade to the latest version. It has already been fixed :innocent: 

Duplicate of #5082 and #5200

**Closed by mholt** 2023-02-24 21:14 UTC

**Comment by johanobergman** [comment] 2023-02-24 21:16
Sorry about that - will upgrade!
