### ISSUE TITLE
--envfile does not handle quotes strings

### ISSUE THREAD

**Issue by chaychoong** [caddyserver/caddy#4686] opened 2022-04-08 05:46 UTC
# How to test

Caddyfile
```
http://{$BASE_URL} {
    log

    handle {
        root * /usr/share/caddy/html
        try_files {path} /index.html
        file_server
    }
}
```

test1.env
```
BASE_URL="test.com"
```

test2.env
```
BASE_URL=test.com
```

Run command
```
caddy run --config /etc/caddy/Caddyfile --adapter caddyfile --envfile /etc/caddy/.env
```

# Possible solutions

1. Implement something similar to this: https://github.com/joho/godotenv/blob/master/godotenv.go#L292
2. Just use godotenv

**Comment by francislavoie** [comment] 2022-04-08 06:21
We're generally wary of pulling in additional dependencies, but looks like https://github.com/joho/godotenv is just a single file of code, no external dependencies. So I'd be okay with using it, and it would we mean we could rely on a better-tested implementation than rolling our own.

PRs welcome!

**Comment by mholt** [comment] 2022-04-13 17:41
Should be fixed in 30b6d1f47a35d00fca7cff0daa2ff59a98c5a85e - thanks!

**Closed by mholt** 2022-04-13 17:41 UTC
Labels: feature, good first issue

**Comment by coolaj86** [comment] 2023-03-16 17:15
I just ran into this as well.

```sh
caddy version
v2.6.4 h1:2hwYqiRwk1tf3VruhMpLcYTg+11fCdr8S3jhNAdnPy8=
```

My env file looks like

```sh
DUCKDNS_API_TOKEN='xxxxxxxx'
```

The DuckDNS URL in the logs had `%27`s on either end of the token. I took out the quotes and then it went from KO to OK.

Regression?

**Comment by mholt** [comment] 2023-03-16 17:18
No, but the quotes have to be `"`

**Comment by coolaj86** [comment] 2023-03-16 17:18
It looks like https://github.com/caddyserver/caddy/commit/30b6d1f47a35d00fca7cff0daa2ff59a98c5a85e only handles the string interpolation quotes for expanding variables, not the literal quotes for exact strings.

**Comment by coolaj86** [comment] 2023-03-16 17:23
> No, but the quotes have to be "

That's not to spec: https://dotenv-linter.github.io/#/checks/quote_character

The true spec for `dotenv` is the subset of the Posix shell for environment files, but dotenv-linter is probably the next best thing for practical use cases.

**Comment by mholt** [comment] 2023-03-16 17:27
I can probably add `'` support easily enough then -- for now. Kind of an as-needed complexity.

**Comment by coolaj86** [comment] 2023-03-16 17:29
That would be awesome.

What would you require in order to pull in (or copy) a dependency?

I've been wanting to write one of these parsers for a long time - kinda annoyed that most existing projects, including joho's godotenv don't actually follow the rules - one of them was saying that they want theirs to be "ini" compatible rather than posix compatible.

I know the actual rules quite well. I'm confident that I could provide a single file that obeys them exactly.

**Comment by mholt** [comment] 2023-03-16 19:14
@coolaj86 Please test #5437 when you have a chance.

> What would you require in order to pull in (or copy) a dependency?

Hard to say for sure. It needs to be shown to add considerable value for a significant number of users and incur minimal maintenance cost and dependency bloat.
