### ISSUE TITLE
Stub Status

### ISSUE THREAD

**Issue by DzigaV** [caddyserver/caddy#4885] opened 2022-07-13 10:40 UTC
Hi folks, first of all, thank you for Caddy. I can't wait to say goodbye to our hand-rolled certificate stack 😀

All I'm really missing from Caddy are simple top-line metrics. I've been following this issue: [Prometheus metrics are redundant and slow](https://github.com/caddyserver/caddy/issues/4644) and I'm itching to disable Prometheus metrics entirely and take the performance win.

They don't do anything for me. I need a whole monitoring stack (perhaps including various ugly third-party agents) just to get basic information. Yet at the same time, they don't provide the actionable insight I need when responding to an incident. For that, I'll need to pipe detailed logs to an analyser.

I'm sure there are several global metrics people might find useful, like total open connections and so on. But frankly, I'd happy with a simple per-upstream cumulative request count, which could be added to the existing /reverse_proxy/upstreams endpoint.

I guess my feature request boils down to two things:

- A "metrics off" global option
- Add "total_requests" to each server in /reverse_proxy/upstreams

Interested to hear if anyone else is thinking along the same lines as me.

**Comment by francislavoie** [comment] 2022-07-13 13:38
By total requests, do you mean since Caddy was started? Or do you mean total being currently processed?

**Comment by DzigaV** [comment] 2022-07-13 14:50
> By total requests, do you mean since Caddy was started? Or do you mean total being currently processed?

Since started. I know in-flight requests are already available in /reverse_proxy/upstreams

To summarise my approach, I like low-overhead (CPU and cognitive) metrics that let me understand what's flowing through the system. RPS and error rate, basically.

Then I need to get super detailed to actually solve the problem. JSON logs piped to a socket will fit he bill nicely there.

Prometheus metrics are a halfway house that I just find uncomfortable and wasteful. I understand they're very popular and increasingly "standard", so I wanted to gauge whether my feedback resonated with any other Caddy users.

**Comment by francislavoie** [comment] 2022-07-13 15:44
Frankly, I think we should just focus on having one way of producing metrics. Having more than one way will complicate things.

So basically I'm thinking of that aspect as a duplicate of https://github.com/caddyserver/caddy/issues/4140.

Wanting to turn off metrics is probably valid though, but I think if the performance issues currently existing are resolved, it'll be so minimal that it won't matter.

**Comment by hairyhenderson** [comment] 2022-07-13 21:06
@DzigaV I'd recommend reading about [what Prometheus is](https://prometheus.io/docs/introduction/overview/) before making comparisons to commercial monitoring solutions. I hope you'll see you're making a false equivalence.

> Is parsing a 200KB text protocol dump a good way to for users to find their RPS or error rate?

In my experience, yes. And more than just RPS/errors. Network is cheap, disk is cheap, and gzip compression does wonders for the Prometheus text format.

> And that's without considering whether it was all worth generating in the first place

The implication that metrics exposed via the `/metrics` endpoint are "expensive" to generate  is, in general, false. Performance bugs happen, but that's not really material to your complaints.

> That question doesn't even need an answer, it's so absurd. But that's the direction the industry has taken.

I would urge you to take a step back and try to consider why the industry has adopted Prometheus. I promise you that it's not because of "absurdity".

There's a cost to observability, yes. But in my experience the benefits far outweigh the cost.

I'd like to understand a bit more about what you mean by this:

> I need a whole monitoring stack (perhaps including various ugly third-party agents) just to get basic information.

What "ugly third-party agents" are you referring to? You don't need an agent to scrape Prometheus-format metrics. All you need is a single process, with a few lines of configuration.
You _can_ use an agent to forward metrics to other Prometheus-compatible endpoints, though. I'm partial to the open-source [Grafana Agent](https://github.com/grafana/agent), but I'm probably biased 😉.


I think your frustration lies mainly with the performance bug that's already been filed. I sympathize, and for the part that my code had to play in that bug, I apologize.

Given that there are already issues that cover the two things you're asking for, I suggest that this issue can probably be closed.

**Comment by DzigaV** [comment] 2022-07-14 08:17
> Is parsing a 200KB text protocol dump a good way to for users to [extract an interger]

> In my experience, yes

I feel old.

That said, I await Caddy v27 with some enthusiasm:

Caddy's metrics are now structured! This means that the information in a message is not simply an opaque string or byte slice. Instead, data remains strongly typed and is keyed by individual field names until it is time to encode the message and write it out.

Compare traditional unstructured metrics—like the archaic Prometheus format—commonly used with traditional HTTP servers:

> HELP caddy_http_requests_total Counter of HTTP(S) requests made.
> TYPE caddy_http_requests_total counter
> caddy_http_requests_total{handler="encode",server="srv0"} 1

This format "has structure" but is not "structured": it can only be used to measure HTTP requests. There is no (efficient) way to encode it differently, because it is an opaque string of bytes. It is also missing a lot of information. It does not even include the Host header of the request or the upstream that handled it! This metrics format is only useful when hosting a single site, and for getting the most basic of information about requests.

Now compare an equivalent structured metrics message from Caddy, encoded as JSON and formatted nicely for display.

😘

**Closed** 2022-07-14 08:25 UTC
Labels: feature, discussion

**Comment by francislavoie** [comment] 2022-07-14 08:51
The snark really isn't necessary.

It's not the Caddy project's place or goal to innovate in the metrics/observability space. We leave that to other projects who have the time and expertise to do it.

If someone comes up with a structured metrics standard that is consumed by popular tools, we might reconsider.

**Comment by hairyhenderson** [comment] 2022-07-14 14:13
I'd just like to point out that Prometheus-format metrics _are_ structured. The format may not be JSON, but that doesn't mean it's not "structured". Read and understand the Prometheus docs before making strange judgements like that.
