### ISSUE TITLE
Caddy Server Running for 3-4 weeks, and then all requests fail

### ISSUE THREAD

**Issue by ScottPierce** [caddyserver/caddy#5647] opened 2023-07-22 15:49 UTC
I've been running a Caddy server now for ~2 months. In that time, the server has gotten stuck twice, pegs the CPU, and requires a restart in order to fix it. During that time, the server is non-responsive. The server seems to run well for about 3 or so weeks, and then this happens. A simple restart fixes it.

I'm running it on Google Compute Engine on a pretty low end config, with ~1 GB of memory.

I'm redirecting ~1000 domains, but the traffic is pretty low.

Here is my Caddyfile:
```
{
        email {$EMAIL}

        on_demand_tls {
                ask {$TLS_ASK_URL}
        }

        # Global log configuration
        log {
                output stdout
        }
}

:80 {
        route {
                respond /ping 200
                redir https://{host}{uri}
        }
}

:443 {
        tls {
                on_demand
        }
        route {
                rewrite * /redirect/handle?host={http.request.host}&path={path}
                reverse_proxy /* https://{$REVERSE_PROXY_HOST} {
                        header_up Host {$REVERSE_PROXY_HOST}
                }
        }
}
```

Here is my Dockerfile:
```
FROM caddy:2.6.4-alpine as cpr-redirect-server

COPY Caddyfile /etc/caddy/Caddyfile

```

<img width="577" alt="image" src="https://github.com/caddyserver/caddy/assets/871169/9027eeea-558c-450b-a3de-63f2d0745c29">

I'm not sure how to go about debugging this. Please advise.

**Comment by mholt** [comment] 2023-07-25 02:33
That's odd. First thing to do would be to grab a CPU profile while it's unresponsive. At `localhost:2019/debug/pprof` on the server you can access links to collect a CPU profile (if you add `?seconds=10` or something to the URL it'll take a profile over time).

Without a profile we'll just be guessing. A goroutine dump could be useful too.

Is there a particular request that triggers this behavior?

**Comment by ScottPierce** [comment] 2023-07-25 21:02
No request in particular. So far it just seems to happen after a certain amount of time.

Is there any way to grab the dump externally? I assume not, as I assume that wouldn't be secure. Since it's running externally on a docker-container host, I'm not sure if I have the ability to access it from localhost.

Is there a way I can expose this externally under a different endpoint? I've noticed that bots will preemptively call `/debug/pprof` on some of my other servers, looking for holes. If I can hide it behind a secret uuid endpoint, that'd allow me to access it easily the next time this happens.

**Comment by mholt** [comment] 2023-07-26 03:54
> I assume not, as I assume that wouldn't be secure. 

The debug/pprof endpoint does not actually have security sensitive information, it just so happens that we stuck it on the admin listener since that made the most sense... you could in theory open up the admin endpoint if you can't get into localhost... as long as you either enable authentication OR specify a listener that is still internal-only.

Use the `admin` global option to set the listener address to something that's still an internal interface and then you won't need authentication (probably): https://caddyserver.com/docs/caddyfile/options#admin

**Comment by ScottPierce** [comment] 2023-07-26 05:07
I should mention, the `respond /ping 200` won't even respond when this happens. Why would this other endpoint respond?

**Comment by mholt** [comment] 2023-07-26 05:31
Really depends on the nature of the bug.  Give it a few minutes to respond and see what happens.

In the meantime, could you post the logs here, and also enable debug logging (`debug` in your global options)? That will give us more insight.

For example, if you get a flood of requests, you're simply getting DoS'ed. A firewall or CDN can help with that.

**Comment by francislavoie** [comment] 2023-08-21 01:30
Have you updated to the latest version? Has this problem happened again?

**Comment by ScottPierce** [comment] 2023-08-21 01:31
Yes, I was on the latest version, 2.6.4 at the time, and this has happened again. It's due to happen again in another week or so.

Has another release come out? Is there any reason to think it will do something?

**Comment by francislavoie** [comment] 2023-08-21 01:37
Yes, please upgrade to the latest version, v2.7.4. See https://github.com/caddyserver/caddy/releases. You can subscribe to be notified for releases by clicking Watch then choose Custom to only get alerts for releases.

I don't think we'll learn anything from letting it "fail" on an older version. We've fixed _lots_ of issues since, and without more evidence, it's impossible to rule out that it hasn't already been fixed.

**Comment by ScottPierce** [comment] 2023-08-21 02:24
Just updated and released 2.7.4. Should I change anything about my caddy file to allow debugging?

**Comment by mholt** [comment] 2023-08-22 15:05
If you put 'debug' in your global options it will give more logs. That and a profile would be helpful!

**Comment by ScottPierce** [comment] 2023-08-23 18:34
So I should make our global options:

```
{
        debug

        email {$EMAIL}

        on_demand_tls {
                ask {$TLS_ASK_URL}
        }

        # Global log configuration
        log {
                output stdout
        }
}
```

?

**Comment by mholt** [comment] 2023-08-23 18:57
Yep :+1:

**Comment by ScottPierce** [comment] 2023-08-23 19:42
I'll do this as soon as the new version fails in production again.

**Comment by Dinfangion** [comment] 2023-09-01 18:38
Hi,
I don't have the requested additional info as asked above.
But just posting to confirm that the problem exists.
I'm running the same version as mentioned by Scott, on 4 caddy webservers.
Rocky 8 linux, 4 cpu with normally a load of 1 or 2.
After 32 days with some hours difference, suddenly a cpu user time of more than 60% for caddy,  a load more than 4, no memory issues, and established tcp over 1100, and a respons time of more then 200 seconds.
A restart was necessary.

**Comment by ScottPierce** [comment] 2023-09-01 18:47
@Dinfangion What version? `2.6.4` or `2.7.4`?

**Comment by Dinfangion** [comment] 2023-09-01 18:55
@ScottPierce caddy 2.6.4, rocky 8.8

**Comment by francislavoie** [comment] 2023-09-01 18:57
Please use the latest version.

**Comment by Dinfangion** [comment] 2023-09-01 19:01
And to make my report complete, 
I compiled it with this plugin https://github.com/lindenlab/caddy-s3-proxy .

**Comment by mholt** [comment] 2023-09-01 20:25
When this happens can you post a profile? :2019/debug/pprof has links to goroutine + heap profiles; those would be most helpful.

Alternatively, minimal instructions to reproduce the issue would be needed. Thanks!

**Comment by Dinfangion** [comment] 2023-09-12 12:24
"Alternatively, minimal instructions to reproduce the issue would be needed."
=> 119054 GET requests per hour during 32 days should do it

Caddyfile:

`{
    order s3proxy last
}

:8888 {
    log {
        output file /web/logs/caddy/caddy.log
        format json
        }
    uri strip_prefix /bucketname
    s3proxy {
        region "regionname"
        bucket "bucketname"
        endpoint "https://endpointname"
        force_path_style
    }
}`

![caddy-file-descriptors](https://github.com/caddyserver/caddy/assets/25172314/b5aa7ad4-cc87-4dd8-ba58-d665484b27ef)
![caddy-cpu](https://github.com/caddyserver/caddy/assets/25172314/9bc65a6a-717d-4c38-9f8f-8ec6a28a6a36)
![caddy-cpu-load](https://github.com/caddyserver/caddy/assets/25172314/cfdc288c-c1bf-4222-96aa-0764004b828d)
![caddy-established-tcp](https://github.com/caddyserver/caddy/assets/25172314/45eb262c-b24a-45c4-b9db-3c2585a43300)
![caddy-networkinerface](https://github.com/caddyserver/caddy/assets/25172314/d0d6866f-5b58-405e-9c40-8cf881ea30c9)

**Comment by francislavoie** [comment] 2023-09-12 13:12
@Dinfangion got any logs from around that time? Without logs I don't think there's much we can do.

**Comment by mholt** [comment] 2023-09-12 14:09
Thanks for the charts.

I believe it is happening, which is about all I can glean from charts, though.

> 119054 GET requests per hour during 32 days should do it

We'd have to reproduce these requests :sweat: 

What we _really need_ is either a way to reproduce it or a profile captured during the event. Debug logs may be helpful too -- especially with #5793 -- but the profile will tell us where in the code the CPU use is coming from. Logs mainly add context.

My first reply above has some instructions for grabbing a profile. This can also be done on a regular basis if you don't want to supervise it. Just dump the profiles somewhere and after it happens, go find the profile that happened during the event. That would be very helpful!

**Comment by Dinfangion** [comment] 2023-09-14 14:16
Hi, 
No extra logs from then.
I upgraded 4 production servers to caddy v2.7.4, after a sanity test and loadtest on non-production.
Let's wait and see what happens.

**Comment by ScottPierce** [comment] 2023-09-15 14:12
Confirmed that 2.7.4 has the same issue:
<img width="569" alt="image" src="https://github.com/caddyserver/caddy/assets/871169/51280615-2880-4c0d-a971-3af50813e623">

I'm right in the middle of a crunch right though, so I didn't have time to change anything to get more data. I server restart fixed me, like usual.

**Comment by ScottPierce** [comment] 2023-09-15 14:14
So my server lasted 25-26 days this time.

**Comment by mholt** [comment] 2023-09-15 14:35
Until we get a profile there's nothing we can do to help, other than guess.

**Comment by ScottPierce** [comment] 2023-09-15 14:39
>just load the debug endpoint and download the profile (see above). When this happens, none of the endpoints function. i.e. I have a simple ping endpoint that won't return when this happens

```
:80 {
        route {
                respond /ping 200
                redir https://{host}{uri}
        }
}
```

**Comment by mholt** [comment] 2023-09-15 15:08
It's worth an HTTP request to find out -- let it run as long as it needs to. You can set the number of seconds to a low value.

**Comment by Dinfangion** [comment] 2023-09-15 15:41
I'm going to try and break it in non-production as I received votes against debug mode in production.
@ScottPierce Are you using standard Caddy without plugins?
Can you share your traffic profile so I can also take that in to account? You said something about low traffic.
number of GET requests/hour or second, and network traffic Mb/sec
( our very low traffic non-production setup never had the problem )

**Comment by mholt** [comment] 2023-09-15 17:18
@Dinfangion Thanks. FYI you can get a profile without enabling debug mode. Just use the endpoint I mentioned, it works on all Caddy instances that don't have the admin endpoint explicitly disabled. If you can (re)load a config through the CLI or API, you can capture a profile.

Anyway, you should be able to do this in production already.

**Comment by Dinfangion** [comment] 2023-10-18 18:52
It happened again on production on 17/10/2023.
Caddy v2.7.4.

The best clue that we got from all the logfiles is:
**kernel: TCP: out of memory -- consider tuning tcp_mem**


what we already tune:

common__sysctl:
- name: 'net.core.somaxconn'
value: 2048
- name: 'net.ipv4.ip_local_port_range'
value: '1024 62000'
- name: 'net.ipv4.tcp_max_tw_buckets'
value: 524288
- name: 'net.ipv4.tcp_tw_reuse'
value: 1


what we should also tune:

net.core.netdev_max_backlog = 30000
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 87380 67108864


what we currently have:

net.core.netdev_max_backlog = 1000
net.core.rmem_max = 212992
net.core.wmem_max = 212992
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_rmem = 4096 87380 6291456
net.ipv4.tcp_wmem = 4096 16384 4194304

I also ran:
curl -o caddy-debug.prof http://localhost/:2019/debug/pprof/profile
curl -o caddy-heap.prof http://localhost/:2019/debug/pprof/heap
Still have to look at those results.



              total        used        free      shared  buff/cache   available
Mem:          63888       11925       45616        3156        6345       48133
Swap:          3999           0        3999

load average: 6.40, 6.05, 5.54

System load: User: 41.24, Nice: 0.00, System: 56.96, Total: 98.2, IOWait: 0.00, Steal: 0.00, Idle: 1.80
	
![cpu-mem-traffic_23-10-17](https://github.com/caddyserver/caddy/assets/25172314/f95cc430-830f-4eca-afe3-6dc7eb64032b)
![cpu-mem-traffic_23-10-17](https://github.com/caddyserver/caddy/assets/25172314/39c46a94-2661-48f4-8940-47502e4caf50)


%Cpu0  : 43.8 us, 55.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  1.2 hi,  0.0 si,  0.0 st
%Cpu1  : 41.2 us, 57.5 sy,  0.0 ni,  0.0 id,  0.0 wa,  1.2 hi,  0.0 si,  0.0 st
%Cpu2  : 39.2 us, 59.5 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  1.3 si,  0.0 st
%Cpu3  : 41.8 us, 58.2 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  63888.5 total,  45590.4 free,  11941.2 used,   6356.9 buff/cache
MiB Swap:   4000.0 total,   4000.0 free,      0.0 used.  48109.2 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                     
4025435 caddy     20   0 3054364   1.8g  35816 S 270.9   2.8   2426:19 caddy    

 ss -an | grep ESTA | wc -l
1168

**Comment by francislavoie** [comment] 2023-10-18 18:55
Yes, please share those profiles. You can use `go tool pprof -web /path/to/profile` to generate an SVG which can also be shared.

**Comment by Dinfangion** [comment] 2023-10-18 19:51
pprof output
![pprof001-debug](https://github.com/caddyserver/caddy/assets/25172314/d23c9359-ca6c-4839-9046-42ec620740ef)
![pprof001-heap](https://github.com/caddyserver/caddy/assets/25172314/daf0821f-d040-45be-b8a7-e05aa734025d)

**Comment by Dinfangion** [comment] 2023-10-18 19:52
pprof output heap
![pprof001-heap](https://github.com/caddyserver/caddy/assets/25172314/daf0821f-d040-45be-b8a7-e05aa734025d)

**Comment by francislavoie** [comment] 2023-10-18 21:09
Okay so from that, it looks like the S3Proxy gets stuck in a crazy write loop which is taking up 75% of the time in syscalls. The rest of the time looks to be in the Go runtime/scheduler and GC. This seems like a bug with the S3Proxy plugin, not with Caddy.

**Comment by mholt** [comment] 2023-10-18 22:25
Thank you for the profile @Dinfangion.

Indeed, Francis is right. That is a bug in the [caddy-s3-proxy](https://github.com/lindenlab/caddy-s3-proxy) plugin and should be reported there.

@ScottPierce If it's alright, I'll close this issue as not actionable until we get a profile from you. We can reopen at that point.

**Closed by mholt** 2023-10-18 22:25 UTC
Labels: needs info :mailbox_with_no_mail:
