### ISSUE TITLE
Using both gzip and minify causes a Content Encoding Error when viewed in browser

### ISSUE THREAD

**Issue by makeworld-the-better-one** [caddyserver/caddy#2797] opened 2019-10-10 00:10 UTC
## 1. Which version of Caddy are you using (`caddy -version`)?

Caddy v1.0.3 (h1:i9gRhBgvc5ifchwWtSe7pDpsdS9+Q0Rw9oYQmYUTw1w=)

## 2. What are you trying to do?

Both gzip and minify files.

## 3. What is your Caddyfile?
```text
domain.tld {
    root /var/www
    gzip
    minify
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

I ran Caddy with the default systemd file provided by you guys.

## 6. What did you expect to see?

The webpage being served, an index.html file.

## 7. What did you see instead (give full error messages and/or log)?

The "Content Encoding Error" page on Firefox

## 8. Why is this a bug, and how do you think this should be fixed?

You should be able to both gzip and minify files without any issues.

## 9. What are you doing to work around the problem in the meantime?

Don't use minify, which is what I am doing now.

## 10. Please link to any related issues, pull requests, and/or discussion.

Maybe #448?

**Comment by mholt** [comment] 2019-10-10 00:13
Since it works without the minify plugin, I believe this is an issue with the minify plugin, and not with Caddy. Try opening your issue here: https://github.com/hacdias/caddy-minify

**Comment by francislavoie** [comment] 2019-10-10 00:14
Duplicate of https://github.com/hacdias/caddy-minify/issues/23

**Closed by mholt** 2019-10-10 00:13 UTC
