### ISSUE TITLE
Feature: support multiple Caddyfiles like docker do with Dockerfile

### ISSUE THREAD

**Issue by mindon** [caddyserver/caddy#4800] opened 2022-05-19 03:34 UTC
merge multiple Caddyfiles into one is NOT fun, it will be great if caddy supports multiple Caddyfiles with their own namespace

working scene ( or something like docker do)

1. caddy start website A under directory a/ with a Caddyfile only for A,
2. caddy start website B under directory b/ with a Caddyfile only for B,
3. caddy start more ... and their Caddyfile config won't conflict
4. and caddy stop only stop current directory website, when there's none else, then stop caddy

**Comment by francislavoie** [comment] 2022-05-19 06:42
This request sounds fundamentally incompatible with how Caddy was designed. 

Under the hood, there's a single JSON config; the Caddyfile adapter produces that JSON config. It's not possible to stop just part of the config. You need to remove what you want to stop from the config entirely then reload Caddy with the updated config.

Also I'm not sure I understand what you mean by "and their Caddyfile won't conflict". What conflicts are you talking about?

This sounds like the [XY problem](https://en.wikipedia.org/wiki/XY_problem). What are you actually trying to do? What's your current config?

I'll close this, because it doesn't really make sense as-is.

Please ask your usage questions on the [Caddy community forums](https://caddy.community). Don't forget to fill out the help topic template so we can help you!

**Closed by francislavoie** 2022-05-19 06:42 UTC

**Comment by mindon** [comment] 2022-05-19 07:05
@francislavoie  thanks for your quick reply.

maybe it could be implemented by keep the whole config as a virtual one in memory or a default Caddyfile.all, start or stop to merge/unmerge current Caddyfile from the virtual config in memory, then reload. 

here you will see what i mean "conflict part" -- the global options in each Caddyfile.

btw, manage multiple websites' config in one file may be some kind of unsafe operation, and it's mess.

**Comment by francislavoie** [comment] 2022-05-19 07:09
That's not how the Caddyfile works. It's an adapter that generates JSON config. The Caddyfile is not kept in memory, and there's no plans to do so.

I'm still not clear what your problem is, you haven't clearly explained it. Like I said, please open a topic on the forums and fill out the template, so we better understand.

**Comment by mindon** [comment] 2022-07-14 03:53
A simple tool **cadder** to implement such a feature, providing convenient `cadder start|stop|reload` for only current directory **Caddyfile** or **caddy.json**, without merging all configs into one
https://gist.github.com/mindon/5db9f76585bde39b2a714c44084e3894
