### ISSUE TITLE
HTTP/3 Support for upstream proxies 

### ISSUE THREAD

**Issue by joshughes** [caddyserver/caddy#5452] opened 2023-03-22 02:35 UTC
Many cloud providers are beginning to support http/3 on their load balancers. There are many cases where http/3 connections to upstreams could be beneficial such as less reliable networks. It would be an interesting feature for caddy to support http3 as a target protocol for upstream servers. Even more interesting if this could be negotiated like browser decide to upgrade to http/3 use the alt-svc header on an upstream to perform this upgrade. 

There are some complications like firewall rules and other things where TCP 443 may be open but UDP 443 may not. But in any case being able to explicitly tell caddy to try http3 on a reverse proxy upstream with a configuration flag would be pretty interesting, useful in many cases, and a differentiator as this currently does not exist in anything that could be found currently. 

POC of a http 1.1 to http3 upstream can be seen at https://github.com/AeroNotix/go-quic-proxy

**Comment by francislavoie** [comment] 2023-03-22 03:09
Duplicate of https://github.com/caddyserver/caddy/issues/5086.

Thanks for the reasoning, it would be helpful if you could add a comment to that issue.

**Closed** 2023-03-22 03:10 UTC
