### ISSUE TITLE
Different headers on HTTP/2 and HTTP/3

### ISSUE THREAD

**Issue by JeDaYoshi** [caddyserver/caddy#5592] opened 2023-06-23 04:56 UTC
Running on `v2.7.0-beta.2`, but pretty sure this issue has been present for a while.

While not *really* a critical issue, I figured I might as well raise it up since I've not noticed anyone else do it.

There is a difference as to how headers are handled on HTTP/1.1 and HTTP/2, and HTTP/3.
While it seems like on the first two the headers are sorted out alphabetically (plus `Content-Length` and `Date` added on the bottom), on HTTP/3 I'm guessing they are added in "incoming order", plus additionally:

- If serving a static file, HTTP/3 is missing a `Date` header which is present on HTTP/2.
- If reverse proxying, `Date` is present on both.

HTTP/3 run:
```
* using HTTP/3
> GET / HTTP/3
> Host: xxx
> User-Agent: curl/8.1.2
> Accept: */*
> 
< HTTP/3 200 
< x-frame-options: SAMEORIGIN
< last-modified: Mon, 12 Jun 2023 00:00:00 GMT
< x-robots-tag: none
< x-content-type-options: nosniff
< content-type: text/html; charset=utf-8
< strict-transport-security: max-age=31536000; preload
< cache-control: public, max-age=600
< referrer-policy: same-origin
< content-length: 1238
< accept-ranges: bytes
```

HTTP/2 run:
```
* using HTTP/2
> GET / HTTP/2
> Host: xxx
> User-Agent: curl/8.1.2
> Accept: */*
> 
< HTTP/2 200 
< accept-ranges: bytes
< alt-svc: h3=":443"; ma=2592000
< cache-control: public, max-age=600
< content-type: text/html; charset=utf-8
< last-modified: Mon, 12 Jun 2023 00:00:00 GMT
< referrer-policy: same-origin
< strict-transport-security: max-age=31536000; preload
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< x-robots-tag: none
< content-length: 1238
< date: Fri, 23 Jun 2023 04:45:10 GMT
```

It is intentional that the `Server` header is missing in these, too, as I've removed it with my Caddy config for that host.
All of these logs are not in full, but removed content to not make this very long. Issue is reproducible regardless.

This is also visible on 404's:

HTTP/3 run:
```
* using HTTP/3
> GET / HTTP/3
> Host: xxx
> User-Agent: curl/8.1.2
> Accept: */*
> 
< HTTP/3 404 
< server: Caddy
```

HTTP/2 run:
```
* using HTTP/2
> GET / HTTP/2
> Host: xxx
> User-Agent: curl/8.1.2
> Accept: */*
> 
< HTTP/2 404 
< alt-svc: h3=":443"; ma=2592000
< server: Caddy
< content-length: 0
< date: Fri, 23 Jun 2023 04:51:40 GMT
```

This one is on another server, running a pretty much "default" setting, just serving `file_server` on a root directory.

**Comment by mholt** [comment] 2023-06-23 05:08
Thanks for opening an issue! We'll look into this.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_ **using the latest version of Caddy.** This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

This should be the latest version of Caddy:

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Instructions -- please heed otherwise we cannot help you (help us help you!)

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222) Please enable debug and access logs.
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by JeDaYoshi** [comment] 2023-06-23 05:14
Ah well, here we go.

## 1. Environment

### 1a. Operating system and version

```
Debian 12, applies to other OSes
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

This should be the latest version of Caddy:

```
v2.7.0-beta.2 h1:jaS1odoRuDR2W8igaKgVGvVjhTNt8xfoz3YPC4bcenA=
(also happens on a clean release of caddy)
```

## 2. Description

### 2a. What happens

HTTP and HTTP/3 headers are different (ordered differently, with `file_server` it has different results with a `Date` header missing, or both `Content-Length` or `Date` missing)

### 2b. Why it's a bug

While not as important, I believe they should be consistent between the protocols, also consistent between `file_server` and `reverse_proxy`, which it currently isn't.

## 3. Tutorial (minimal steps to reproduce the bug)

Just run a Caddy server, a basic config works. (I'm using Caddyfile's in here, but not sure if it's relevant or not.)
Run `curl --http3 -v https://host` and `curl --http2 -v https://host` to notice the difference in responses.

A basic config such [as any from the docs](https://caddyserver.com/docs/quick-starts/static-files#caddyfile) do the trick, as long as it does HTTP/2 and HTTP/3.

**Comment by WeidiDeng** [comment] 2023-06-23 11:46
I noticed this problem before, since http3 won't set `Content-Type` header unless set explicitly which has led to a [problem](https://github.com/caddyserver/caddy/issues/5059#issuecomment-1253013498), 404 html code instead of page because in the absence of `Content-Type`, browser typically interpret data as raw text.

http3 support is provided by [quic-go](https://github.com/quic-go/quic-go), while http2 is provided by [stdlib](https://github.com/golang/net/blob/master/http2/server.go#L2551) @marten-seemann is more qualified to known where to set these extra headers `Content-Length`, `Content-Type`, `Date` automatically added by stdlib. `Alt-Svc` should be absent however, as it's used to indicate alternative address to connect to (usually used to tell browser how to connect to http3).

**Comment by mholt** [comment] 2023-06-23 21:32
Thanks for providing the additional info @JeDaYoshi ! That's helpful.

I'll take a look into this if I have time, I think Weidi has a better handle on HTTP/3 stuff for now :)

**Comment by marten-seemann** [comment] 2023-06-23 21:38
Which version are you using? quic-go added content type sniffing in February this year: https://github.com/quic-go/quic-go/pull/3715.

**Comment by WeidiDeng** [comment] 2023-06-23 21:43
That 404 error is from September last year. And content type sniffing is not available last year.

**Comment by WeidiDeng** [comment] 2023-06-25 08:17
I created a [pr](https://github.com/quic-go/quic-go/pull/3915) that will hopefully reduce the difference with h3 and stdlib response writers. Automatically adding `Content-Length` is not done for now, because it's too many changes for one commit. h3 also [doesn't support trailers](https://github.com/quic-go/quic-go/issues/2266) right now.

**Comment by WeidiDeng** [comment] 2023-07-15 00:38
All except automatic `Content-Length` are fixed in upstream.

Trailers are still in the works.

**Closed by WeidiDeng** 2023-07-15 00:38 UTC
Labels: upstream :arrow_up:, needs info :mailbox_with_no_mail:

**Comment by mholt** [comment] 2023-07-15 16:02
Thanks, Weidi!
