### ISSUE TITLE
Content-Length doesn't work in caddy2 gzip option open

### ISSUE THREAD

**Issue by Erchoc** [caddyserver/caddy#4902] opened 2022-07-22 10:20 UTC
like #2892, the caddy v2.5.2 I used, but when I config `file_server` and `gzip`, the `response.header` doesn't `contnet-length` field.
![image](https://user-images.githubusercontent.com/19908809/180419272-cc7a412c-bd3c-4365-a4b4-c95e08397b67.png)

**Comment by mholt** [comment] 2022-07-22 19:38
I believe the problem is we do not know the Content-Length because the body is compressed while it is being streamed to the client. In other words, the headers have already been written by the time the body has been compressed.

Unless we buffer the response in memory, I do not know a way to set this header for dynamically-compressed content. Ideas welcomed.

Note that Content-Length is an optional header: https://www.rfc-editor.org/rfc/rfc9110.html#name-content-length - and specifically can be omitted if the server does not know the length before sending headers.

Closing, as I don't think this is actually a bug/problem, as we are compliant with spec. Feel free to continue discussion though.

**Closed by mholt** 2022-07-22 19:38 UTC
