### ISSUE TITLE
Debian / Ubuntu / Raspian install currently broken due to certificate issues

### ISSUE THREAD

**Issue by schnittchen** [caddyserver/caddy#4795] opened 2022-05-17 16:07 UTC
These steps https://caddyserver.com/docs/install#debian-ubuntu-raspbian
fail at the step `sudo apt update` with

```
Get:5 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease [7,491 B]
Err:5 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABA1F9B8875A6661
Reading package lists...
W: GPG error: https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABA1F9B8875A6661
E: The repository 'https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease' is not signed.
```

Note that the missing key ABA1F9B8875A6661 is not the one imported in a previous step.

Failed on Ubuntu 20.04 LTS, but probably affects other deb-based distros and versions as well.

**Comment by francislavoie** [comment] 2022-05-17 16:12
Duplicate of https://github.com/caddyserver/dist/issues/83

**Closed by francislavoie** 2022-05-17 16:12 UTC
