### ISSUE TITLE
caddyfile: users specifying default route first

### ISSUE THREAD

**Issue by greenpau** [caddyserver/caddy#4065] opened 2021-03-15 20:09 UTC
Seeing users specifying default routes first and only then more specific routes. Please see below.

```
auth.myhome.net {
  route /* {
    import auth
    redir https://auth.myhome.net/auth/oauth2/azure 302
  }

  route /auth* {
```

Would it make sense to:
* detect the default route and place it last?
* detect multiple default routes?

**Comment by francislavoie** [comment] 2021-03-15 20:35
That's already automatic; the Caddyfile adapter sorts directives based on the length of their path matchers (except within `route` blocks themselves, because that overrides any ordering). See the `caddy adapt` output, you'll see that they're sorted.

Really, users should stop using `/*` and instead omit the matcher altogether. It's more efficient because it avoids Caddy having to do a tautological comparison (paths always start with `/` so it's useless to do that comparison).

**Comment by francislavoie** [comment] 2021-03-15 20:41
I'll close this because I don't see anything actionable. Let me know if I misunderstood.

**Closed by francislavoie** 2021-03-15 20:41 UTC
Labels: invalid

**Comment by greenpau** [comment] 2021-03-15 21:22
> That's already automatic; 

@francislavoie , the `route /*` is not getting re-order. Otherwise, this [comment](https://github.com/greenpau/caddy-auth-portal/issues/99#issuecomment-799580249) would not have helped.

**Comment by francislavoie** [comment] 2021-03-15 21:31
I can't replicate:

```
$ cat Caddyfile 
:8888

route /* {
	respond "Should be last"
}

route /foo* {
	respond "Should be second"
}

route /foobar* {
	respond "Should be first"
}

$ caddy adapt
2021/03/15 21:31:12.369	INFO	using adjacent Caddyfile
{"apps":{"http":{"servers":{"srv0":{"listen":[":8888"],"routes":[{"match":[{"path":["/foobar*"]}],"handle":[{"handler":"subroute","routes":[{"handle":[{"body":"Should be first","handler":"static_response"}]}]}]},{"match":[{"path":["/foo*"]}],"handle":[{"handler":"subroute","routes":[{"handle":[{"body":"Should be second","handler":"static_response"}]}]}]},{"match":[{"path":["/*"]}],"handle":[{"handler":"subroute","routes":[{"handle":[{"body":"Should be last","handler":"static_response"}]}]}]}]}}}}}
```

Please give a reproducible example.
