### ISSUE TITLE
caddy file_server breaks with file names containing specific characters

### ISSUE THREAD

**Issue by glowinthedark** [caddyserver/caddy#4098] opened 2021-03-30 21:45 UTC
Caddy file_server throws a HTTP 404 error with a folder containing special characters such as `name {WHATEVER}`.

## Steps to reproduce

1. Create a folder named e. g. `'some folder {VERY SPECIAL}'`
2. Navigate to the folder using the `file_server` plugin (`Caddyfile` provided below).

## Expected behaviour
Caddy is able to traverse the folder.

## Actual behaviour
HTTP status 404 is returned

> Notes: The path appears to be properly escaped and is displayed in the web browser address bar as `/some%20folder%20%7BSPECIAL%7D/`.

#### Curl output

```
❯ curl -vv http://ron/usb0/backup/tmp/some%20folder%20%7BSPECIAL%7D/
*   Trying 192.168.1.100...
* TCP_NODELAY set
* Connected to ron (192.168.1.100) port 80 (#0)
> GET /usb0/backup/tmp/some%20folder%20%7BSPECIAL%7D/ HTTP/1.1
> Host: ron
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Server: Caddy
< Date: Tue, 30 Mar 2021 21:50:44 GMT
< Content-Length: 0
<
* Connection #0 to host ron left intact
* Closing connection 0
```

#### Details:
File system: EXT4
Also reproducible on MacOS with the APFS file system

#### /etc/caddy/Caddyfile

```caddy
http:// {
	root * /media

	file_server browse {
		root /media
		hide .git
		index ''
	}
	
@plist {
	path *.plist
}
header @plist Content-Type application/xml
```

#### Output of `locale`

```sh
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

## NOTE:
It's the problem specifically with curly brackets `{}` since other special characters are not causing this behaviour, for example a folder named `<#%$" !/` is traversed correctly and is url escaped as `<%23%25$"%20%21/`.

**Comment by francislavoie** [comment] 2021-03-30 22:43
I think this is a duplicate of https://github.com/caddyserver/caddy/issues/4027, which has been fixed on the master branch (not in a tagged release yet). Please try a build from commit https://github.com/caddyserver/caddy/commit/5bf0a55df499e189424103d87d93960395d3172f or after to confirm!

**Comment by glowinthedark** [comment] 2021-03-31 15:10
@francislavoie: confirming it's not reproducible with the latest `master` branch (as of e68dbe9)

**Closed** 2021-03-31 15:16 UTC
