### ISSUE TITLE
[feature] Metrics should exist and have a value

### ISSUE THREAD

**Issue by erikschul** [caddyserver/caddy#6659] opened 2024-10-23 20:25 UTC
I was surprised to find that metrics were missing, and @mohammed90 noted that 
> They’ll show up when you have traffic flowing

This is problematic, because it will show up in Grafana as "no data", which is not correct, since the server is live, and the correct data is, for example, that zero requests have been served.

As a feature request, I would like all metrics to be available.

I understand that this interferes a bit with dynamic configuration.
Perhaps a server that only lives for a short time (like 10 seconds) is a niche use case that should then opt-out of server-specific metrics.
But the server can still increment global metrics, e.g. requests served, failures, upstreams_healthy, upstreams_failing, etc.

**Comment by erikschul** [comment] 2024-10-23 20:26
IIUC, the current implementation of metrics needs major rework? https://github.com/caddyserver/caddy/issues/4644
and has issues architecturally, with performance, with missing metrics, and with dynamic configuration?

**Comment by hairyhenderson** [comment] 2024-10-23 21:00
> This is problematic, because it will show up in Grafana as "no data", which is not correct, since the server is live, and the correct data is, for example, that zero requests have been served.

HTTP metrics are not intended to tell you whether your webserver is running or not - there are other metrics for that.

Metrics like this have labels (i.e. `method="GET"`). It's impossible to initialize such metrics to zero, because there's no way to know which sets of labels will be used...

From your description, these metrics are working as designed.

> But the server can still increment global metrics, e.g. requests served, failures, upstreams_healthy, upstreams_failing, etc.

these metrics aren't global though - configuration changes affect how these metrics are presented...

I'm going to close this for now. If you can come up with a substantive feature request that makes sense in the context of Prometheus metrics idioms, feel free to edit and re-open.

**Closed by hairyhenderson** 2024-10-23 21:00 UTC

**Comment by erikschul** [comment] 2024-10-23 21:50
For perspective, when I tested envoy recently it had ~1800 metrics. One commenter mentioned having 18k metrics.
I'm not sure if envoy's approach is idiomatic though.
I'll return if I have some concrete use cases.
