### ISSUE TITLE
Config reload fails when admin endpoint is a socket

### ISSUE THREAD

**Issue by bones-was-here** [caddyserver/caddy#5056] opened 2022-09-20 19:47 UTC
I've been using this Caddyfile global configuration, which was working at e289ba6187ddd50afc86feb85246a14298673a69 but is no longer working in 2.6.0 (Caddy's official package for Debian).
```
{
	admin unix//run/caddy/admin.sock
}
```
The goal is to support zero downtime config reloads without exposing Caddy's config to any process on the system that might send some json to 127.0.0.1.  Partly in case some other service gets compromised, and partly because we have human SSH user accounts on the system which don't have sysadmin (sudo) access and should not be able to reconfigure the main web server.

`/run/caddy` has mode `0750` and `caddy:caddy` ownership.  

Log:
```
systemd[1]: Reloading Caddy.
caddy[3372028]: {"level":"info","ts":1663700361.6707227,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
caddy[3371872]: {"level":"info","ts":1663700361.6808317,"logger":"admin.api","msg":"received request","method":"POST","host":"","uri":"/load","remote_ip":"@","remote_port":"","headers":{"Accept-Encoding":["gzip"],"Cache-Control":["must-revalidate"],"Content-Length":["20327"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]}}
caddy[3371872]: {"level":"error","ts":1663700361.6862683,"logger":"admin.api","msg":"request error","error":"loading config: loading new config: starting caddy administration endpoint: listen unix /run/caddy/admin.sock: bind: address already in use","status_code":400}
caddy[3372028]: Error: sending configuration to instance: caddy responded with error: HTTP 400: {"error":"loading config: loading new config: starting caddy administration endpoint: listen unix /run/caddy/admin.sock: bind: address already in use"}
systemd[1]: caddy.service: Control process exited, code=exited, status=1/FAILURE
```

Relatedly I also needed this addition to the packaged `/lib/systemd/system/caddy.service` to make Caddy start reliably with the socket admin endpoint (loaded via systemd drop-in config):
```
[Service]
# bones_was_here: 2.5.2 fails to start if the admin endpoint socket still exists!
ExecStartPre=rm -f /run/caddy/admin.sock
```

**Comment by bones-was-here** [comment] 2022-09-20 20:22
If it's hard to cleanly re-use the same file, the socket path could point to a directory instead of a file.  This would allow each process to create its own socket file in that directory so multiple can exist during a handover.

**Comment by mholt** [comment] 2022-09-20 20:52
Thanks for the report.

How can I reproduce it?

I cannot with this Caddyfile:

```
{
	debug
	admin unix//home/matt/Desktop/admin.sock
}
```

and then running Caddy with it, and then running `caddy reload`, works just fine.

Still, now that you mention it, I somehow missed that SO_REUSEPORT does not work for unix sockets (even though it's an SO, "socket option")... (That's kind of ironic that a unix socket option does not work for unix sockets.)

But it works for me? How can I see what you're seeing?

**Comment by bones-was-here** [comment] 2022-09-20 21:09
There's certainly a few quirks in the naming of some network stuff in go, when was the last time you connected to a system by _dialling_ it :)

**Comment by bones-was-here** [comment] 2022-09-20 21:16
Are you reloading an unchanged config?  If i remove `--force` from the `ExecReload=/usr/bin/caddy reload --config /etc/caddy/Caddyfile --force` line then it succeeds, but if I actually change the config then it fails again.

**Comment by mholt** [comment] 2022-09-20 21:25
@bones-was-here Ah, okay it happens only as a systemd service.

If you follow my steps above (without systemd, just a plain config file like that and run `caddy run` then `caddy reload`) does it work for you?

Trying to narrow down if systemd is the culprit here.

**Comment by bones-was-here** [comment] 2022-09-20 21:41
I can reproduce it without systemd, compiled with go 1.19.1 on my PC (debian testing).  Caddyfile:
```
{
        debug
        admin unix//home/bones/tmp/admin.sock
}
```
`./caddy run --config Caddyfile`  
Startup looks OK, socket file has been created.  
`./caddy reload --config Caddyfile`  
Succeeds, logging that config is unchanged.  
`./caddy reload --config Caddyfile --force`  
`ERROR   admin.api       request error   {"error": "loading config: loading new config: starting caddy administration endpoint: listen unix /home/bones/tmp/admin.sock: bind: address already in use", "status_code": 400}`

**Comment by mholt** [comment] 2022-09-20 21:44
Huh, I'm stumped then. For me it only happens as a systemd service.

I mean, I presume this has to do with our recent use of SO_REUSEPORT, but I'm surprised I can't reproduce it except with systemd.

**Comment by bones-was-here** [comment] 2022-09-20 21:54
It logs `INFO    admin.api       received request` before hitting the error, so I guess at that point you would know if the config has been parsed and is OK to run?  In which case it _should_ be safe to just delete the socket file before starting the new listener on it?  That should also work for when the system hard reboots and at next startup the socket file still exists.

**Comment by mholt** [comment] 2022-09-20 23:03
That would disconnect the current API request. We need to close the old listener while the new one is already running on the same socket...

**Comment by mholt** [comment] 2022-09-21 14:32
Currently working on a fix. It involves copying the file descriptor and closing the old one. I *think* it works in some testing I've done, but still doing more testing and polishing of the implementation.

**Comment by mholt** [comment] 2022-09-21 17:40
@bones-was-here Could you please give #5063 a try and confirm that it works for you? When the CI is finished there will be build artifacts if you want to just download one of those. Or you can build from that branch, either way.

**Comment by bones-was-here** [comment] 2022-09-21 18:17
I like that approach.  It looks like you fixed the problem with config reloads, but initial startup is now failing when the socket file _doesn't_ exist (opposite to before):  
`Error: loading initial config: loading new config: starting caddy administration endpoint: no such file or directory`

Creating any file is enough to "kick start" it, eg `touch /home/bones/tmp/admin.sock`, and that file gets replaced with the proper socket, and then config reloads work.

**Comment by mholt** [comment] 2022-09-21 18:39
@bones-was-here Interesting! So, I thought I tested that case because `test.sock` did not appear on my linux desktop. Even though my other test, `admin.sock`, did.

Turns out `test.sock` only appeared in `ls` in the terminal for some reason.

Gotta love Linux... I'm lookin' for a new distro + desktop btw.

Anyway, I pushed a fix or that. Thanks for letting me know I can't trust my OS. :sweat_smile: 

I will merge this momentarily. Thank you for verifying!

**Closed** 2022-09-21 18:55 UTC
Labels: bug, in progress

**Comment by bones-was-here** [comment] 2022-09-21 19:00
If your requirements for a DE include showing unix sockets on the desktop, KDE plasma seems to have that working :P.  
I stopped putting files on the desktop long ago, I wanted them to stay in specific spots but they'd move around when switching computers or monitors.

**Comment by mholt** [comment] 2022-09-21 19:01
Heh, I don't use the desktop often except when I'm actively working with a file and need really quick, easy access to it.

The weird thing is it did show my `admin.sock` file but not my `test.sock` file. :man_shrugging:

v2.6.1 going out in a few minutes, FYI
