### ISSUE TITLE
Feature request: Placeholders in reverse_proxy directive when defining SRV upstreams

### ISSUE THREAD

**Issue by yehudacohen** [caddyserver/caddy#3723] opened 2020-09-15 03:31 UTC
Hi @francislavoie and Caddy team,

Francis, in [this comment](https://caddy.community/t/proxy-upstream-placeholders/8085/12) in the community forums, you mention that there is one situation broken with using placeholders in Caddyfiles for reverse_proxy upstreams and that is with SRV records. You also mention that you probably won't implement a solution for this without someone showing that they have a use case for this.

I believe I have such a use case:
I have a fleet of containerized micro-backends per customer. Each of these micro-backends has a public alias `customer-id.public-domain.com`. Each of these micro-backends also registers a private domain name as an SRV record `customer-id.private.domain`. 

The reason for this is that there can be a hundred or more micro-backends per backend instance and there aren't enough network interfaces on the hardware to support giving each micro-backend a separate IP address.

When a request comes in from a client, the reverse proxy needs to translate the incoming hostname to the corresponding internal SRV name, resolve that SRV name, and proxy traffic to the corresponding container.

Is there any chance you might support this use-case?

**Comment by francislavoie** [comment] 2020-09-15 03:40
Could you give an example Caddyfile to show what you're trying to have work? We need to make sure we're on the same page here.

Thanks

**Comment by yehuda-elementryx** [comment] 2020-09-15 04:04
I haven't ever written a Caddyfile or used Caddy before this, so forgive me if this is invalid, but I think it should get the idea across:
```
http://:2020

handle * {
	header Host "public-domain.com" "internal.domain"

	reverse_proxy {
		to "srv+http://{header.host}"
	}
}
```
Basically, first replace the request's host header with the private host. Then reverse proxy requests to that host. Does that make sense?

**Comment by francislavoie** [comment] 2020-09-15 04:29
Hmm, I think so. I think it might look more like this if I'm understanding correctly:

```
reverse_proxy srv+http://{host} {
    header_up Host "public-domain.com" "internal.domain"
}
```

I'm not sure if it'll be possible, but I'll look into it.

**Comment by yehuda-elementryx** [comment] 2020-09-15 04:31
Great thanks! Wasn't sure whether the header_up sub-directive would be applied before the upstream was resolved in your configuration.

**Comment by francislavoie** [comment] 2020-09-15 05:13
Ah, I misunderstood that then, that wouldn't happen first with `header_up`.

Is the subdomain always a second level? If so then I think the upstream should be:

```
srv+http://{labels.2}.internal.domain
```

Another question - what port would this proxy to?

Essentially, the problem is the parsing step for the address, so I want to make sure we have a proper usecase for tests.

**Comment by yehuda-elementryx** [comment] 2020-09-15 05:28
Not sure what you mean by is the subdomain always a second level, but there are some use cases with `customer-id.dev.public-domain.com` that point to `customer-id.dev.private.domain` if that makes sense.

It would proxy to whatever port the srv record pointed it to. For example if the srv record read: 
`service-id.internal.domain. 3600	IN	SRV	10 20 5000 10.0.0.20.` it would resolve to 10.0.0.20:5000

**Comment by francislavoie** [comment] 2020-09-15 05:34
Right - sorry, totally forgot SRV records include the port.

**Comment by yehuda-elementryx** [comment] 2020-09-15 05:47
Great, thanks @francislavoie , is JSON config usage for reverse_proxy documented somewhere? That would probably be okay for now.

**Comment by francislavoie** [comment] 2020-09-15 05:51
The best way to get started with JSON config is to write what you want in Caddyfile then use the `caddy adapt` command to convert it to JSON. In this case, just don't use a placeholder for the upstream before adapting, then put the placeholder in the JSON after. Also note that placeholders need to be in their long form in the JSON (the short form is a Caddyfile shortcut - see the list in the Caddyfile Concepts doc page)

**Comment by yehuda-elementryx** [comment] 2020-09-15 12:41
Great, thanks Francis, if you'd like any help with a pull request to get this into caddyfile syntax as well I may have some cycles in the next month depending on what's required here.

**Comment by mholt** [comment] 2022-09-14 04:28
I think this may be resolved now? Caddy's reverse proxy recently upgraded the SRV upstreams support to a first-class feature, rather than hacking it into the scheme, so I believe this should work now.

Feel free to reopen if I am mistaken!

**Closed by mholt** 2022-09-14 04:28 UTC
Labels: feature
