### ISSUE TITLE
http 1.0 requests are not supported

### ISSUE THREAD

**Issue by chentiangang** [caddyserver/caddy#5201] opened 2022-11-11 09:35 UTC
Caddyfile:
{
  http_port 18080
  http_port 28080
}

192.168.0.103:28080 {

    reverse_proxy {
        to 192.168.0.103:38080 192.168.0.103:48080
    }

    log {
        output file ./access.log
    }
}

log:

2022/11/11 09:25:53.095	INFO	http.log.access	handled request	{"request": {"remote_ip": "192.168.0.100", "remote_port": "55460", "proto": "HTTP/1.0", "method": "POST", "host": "", "uri": "/api/v1/get_process_monitor_list", "headers": {"Connection": ["keep-alive"], "Content-Type": ["text/plain; charset=utf-8"], "User-Agent": ["python-requests/2.28.1"], "Accept-Encoding": ["gzip, deflate"], "Accept": ["*/*"], "Content-Length": ["134"]}}, "user_id": "", "duration": 0.000005539, "size": 0, "status": 0, "resp_headers": {"Server": ["Caddy"]}}

**Comment by francislavoie** [comment] 2022-11-11 09:38
Thanks for opening an issue! We'll look into this.

It's not immediately clear to us what is going on, so we'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by WeidiDeng** [comment] 2022-11-14 00:32
> 2022/11/11 09:25:53.095 INFO http.log.access handled request {"request": {"remote_ip": "192.168.0.100", "remote_port": "55460", "proto": "HTTP/1.0", "method": "POST", "host": "", "uri": "/api/v1/get_process_monitor_list", "headers": {"Connection": ["keep-alive"], "Content-Type": ["text/plain; charset=utf-8"], "User-Agent": ["python-requests/2.28.1"], "Accept-Encoding": ["gzip, deflate"], "Accept": ["_/_"], "Content-Length": ["134"]}}, "user_id": "", "duration": 0.000005539, "size": 0, "status": 0, "resp_headers": {"Server": ["Caddy"]}}

From the log, host is empty and you seem to use python request. Caddy handles request by matching request host. What is your python request file, can you share it?

**Comment by mholt** [comment] 2022-11-14 03:36
@WeidiDeng is right... My understanding is that Caddy can support HTTP 1.0 at the protocol layer but 1.0 does not require a Host header I think. So if Caddy is configured to match on a Host header then it won't handle it. But you can remove host matching from the config and it should still work.

Why are you using HTTP 1.0?

**Comment by WeidiDeng** [comment] 2022-11-14 06:47
From golang http.readRequest function (used by http.Server and http.ReadRequest)

<img width="562" alt="image" src="https://user-images.githubusercontent.com/28780594/201592636-d8fa5f0b-dbd3-44dc-a766-a8a505cc29ec.png">

So golang stdlib does parse Host from either request line or from header field. In http1.0 Host is optional (either from request line or header), without client code to reproduce it, we cannot help it.

**Closed** 2022-11-14 08:48 UTC
Labels: needs info :mailbox_with_no_mail:

**Comment by Saklad5** [comment] 2022-11-17 17:01
For the record, GnuPG seems to make HTTP/1.0 requests when refreshing public keys. I have no idea why.

Does Caddy officially support HTTP/1.0, or should this not be relied upon?

**Comment by mholt** [comment] 2022-11-17 18:31
It should work, but note that HTTP/1.0 features are extremely limited (by protocol spec, not server problem). For example, any Host matching won't work. So make sure your config doesn't use any host matcher.

**Comment by Saklad5** [comment] 2022-11-17 18:33
Duly noted. I’m probably just going to try fixing anything that uses HTTP/1.0, rather than trying to accommodate it.

**Comment by mholt** [comment] 2022-11-17 18:34
Yes, sounds good. HTTP/1.0 is a relic of the past.

**Comment by Saklad5** [comment] 2022-11-17 20:20
> Yes, sounds good. HTTP/1.0 is a relic of the past.

I'd argue HTTP/1.1 is too. Actually, is it possible to disable HTTP/1.0 outright? I may as well force people's hands.

**Comment by mholt** [comment] 2022-11-17 20:36
@Saklad5 The `protocol` matcher can match HTTP/1.0 specifically:

https://github.com/caddyserver/caddy/blob/ee7c92ec9b57c671c9091ff993b1a24251020c25/modules/caddyhttp/matchers.go#L1136

And you can reject the request in a way of your choosing then!

I am not entirely sure what HTTP/1.0 supports, but it's not much. You might just want to close the connection (`abort` directive, if using the Caddyfile) or return `400`.

**Comment by Saklad5** [comment] 2022-11-17 20:39
> I am not entirely sure what HTTP/1.0 supports, but it's not much. You might just want to close the connection (`abort` directive, if using the Caddyfile) or return `400`.

`abort` sounds like the best option. Unfortunately, I think the status code dedicated to deprecating HTTP versions was actually added in HTTP/1.1.
