### ISSUE TITLE
[Feature request] Mirror http request

### ISSUE THREAD

**Issue by sinawic** [caddyserver/caddy#6706] opened 2024-11-23 14:38 UTC
hi,
i tried achieving a configuration in which i can mirror all the http requests received by caddy to a remote http server listening on an `ip:port`
just exactly same functionality as `nginx mirror module`.

https://nginx.org/en/docs/http/ngx_http_mirror_module.html

in which you can send the exact copy of received request to an `ip:port` also proxying the request to the upstream server, all done in one request.

eventually i want to get same functionality as this nginx config file:

https://raw.githubusercontent.com/sinawic/4yt/refs/heads/master/nginx/http-logs/nginx.conf

thanks in advance

**Comment by mholt** [comment] 2024-11-23 15:03
Thanks for the request!

This is a duplicate of https://github.com/caddyserver/caddy/issues/4211.

Closing, but feel free to continue discussion if needed. :+1:

**Closed by mholt** 2024-11-23 15:03 UTC
Labels: duplicate :paperclips:

**Comment by sinawic** [comment] 2024-11-24 06:32
hi, thanks for the quick response @mholt 
sorry i didn't come up to this issue on my searches.
actually im a youtube content creator that is focused on reverse proxies
and im doing a playlist for caddy now
and i am trying to show and compare functionalities of different technologies.

and my main requirement is actually logging remotely through http requests
on logging docs
https://caddyserver.com/docs/caddyfile/directives/log#net
we don't seem to have http as log listeners with `net` as the output for logs
which i have implemented in `nginx` and `kong`

using `mirror` i wanted to try implement that but also i wasn't able to implement such thing too.

so i have to wait or there's no chance implementing it this soon?

**Comment by francislavoie** [comment] 2024-11-24 06:38
As written on the other issue, we have no plans to implement it right now, the community can write a plugin if they need it. It doesn't require anything special from Caddy itself to do. It's not been a feature in high enough demand for us to prioritize it.
