### ISSUE TITLE
Site stuck at loading and errors in Caddy.log

### ISSUE THREAD

**Issue by MarcS1975** [caddyserver/caddy#6156] opened 2024-03-08 08:23 UTC
Massive problems with one of my sites when using Caddy as reverse proxy. Works fine with Nginx but Caddy logs errors:

`duration=0.027873268error=writing: H3_REQUEST_CANCELLEDlevel=errorlogger=http.handlers.reverse_proxymsg=aborting with incomplete responserequest.client_ip=xxx.xxxx.xxx.xxxrequest.headers.Accept=["*/*"]request.headers.Accept-Encoding=["gzip, deflate, br, zstd"]request.headers.Accept-Language=["en-GB,en-US;q=0.9,en;q=0.8,de;q=0.7,it-IT;q=0.6,it;q=0.5"]request.headers.Cookie=[]request.headers.Dnt=["1"]request.headers.Sec-Ch-Ua=[""Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122""]request.headers.Sec-Ch-Ua-Mobile=["?0"]request.headers.Sec-Ch-Ua-Platform=[""Windows""]request.headers.Sec-Fetch-Dest=["script"]request.headers.Sec-Fetch-Mode=["no-cors"]request.headers.Sec-Fetch-Site=["same-origin"]request.headers.User-Agent=["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"]request.headers.X-Forwarded-For=["xxx.xxx.xxx.xxx"]request.headers.X-Forwarded-Host=["Domain"]request.headers.X-Forwarded-Proto=["https"]request.host=Domainnamerequest.method=GETrequest.proto=HTTP/3.0request.remote_ip=xxx.xxx.xxx.xxxrequest.remote_port=62336request.tls.cipher_suite=4865request.tls.proto=h3request.tls.resumed=truerequest.tls.server_name=Domainnamerequest.tls.version=772request.uri=/dist/core-common.js?v=2e903e75-8ts=1709885823.9857714upstream=xxxx:port`

My Caddyfile is simple:

```
# ––––––––––––––––––––––––––––––––––––––––––––
#  Caddyfile 05-03-24 
# ––––––––––––––––––––––––––––––––––––––––––––
#
{
        email <me@email.com>
}
https://MYDomain:443 {
        reverse_proxy MyhostIP:port
}

```

**Comment by mohammed90** [comment] 2024-03-08 08:34
Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by MarcS1975** [comment] 2024-03-08 09:04
## 1. Environment
Docker container
`services:
  caddy:
    image: caddy:2.7.6
    restart: unless-stopped
    ports:
      - "89:80"
      - "448:443"
      - "448:443/udp"
    volumes:
      - /srv/xxx/Caddy/Caddyfile:/etc/caddy/Caddyfile
      - /srv/xxx/Caddy/site:/srv
      - /srv/xxx/Caddy/caddy_data:/data
      - /srv/xxx/Caddy/caddy_config:/config

#volumes:
#  caddy_data:
#  caddy_config:
`

### 1a. Operating system and version

```
docker-ce 5:25.0.4-1~debian.11~bullseye
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
v2.7.6 h1:w0NymbG2m9PcvKWsrXO6EEkY9Ru4FJK8uQbYcev1p3A=
```

## 2. Description

### 2a. What happens (briefly explain what is wrong)
see above


### 2b. Why it's a bug (if it's not obvious)
see above



### 2c. Log output
see above



### 2d. Workaround(s)
use Nginx



## 3. Tutorial (minimal steps to reproduce the bug)

- launch caddy
- access web URL
- loading is extremely slow
- after a while, caddy log fills with the above error message

**Comment by mohammed90** [comment] 2024-03-08 09:11
Thank you, but the provided info is not enough. I need more logs. I also need a replication with `curl`. Is the shared config the complete config?

I just noticed your log mentions HTTP/3. Do you have port 443 open for UDP? This is very critical for HTTP/3.

**Comment by MarcS1975** [comment] 2024-03-08 09:24
- Port 443 is open for ALL
- The rest of the logs is just a repetition of the same error.
- Yes thats the whole Caddyfile

Whay would you like me to do with Curl?

**Comment by MarcS1975** [comment] 2024-03-08 09:43
I can send you full curl output but is there a tool that I can use to remove senssitive data like iPs, domains etc?

**Comment by mholt** [comment] 2024-03-08 10:20
"Aborting with incomplete response" generally just means the client closed the connection early or similar.

I don't know of a tool that can automatically detect and remove "sensitive" info but you could use jq to manipulate JSON I guess.

**Comment by mholt** [comment] 2024-03-08 10:21
What is the client experience when this error happens?

**Comment by MarcS1975** [comment] 2024-03-08 11:29
The client is stuck like a website waiting for more data. The page is
visible but frozen.

**Comment by MarcS1975** [comment] 2024-03-08 15:38
If it helps, I had added this to the Caddyfile when the problem started. I removed all entries below again but the problem (as described above) still stays. THe below must have triggered something that remains broken.

```
[header]{
	# disable FLoC tracking
	Permissions-Policy interest-cohort=()

	# enable HSTS
	Strict-Transport-Security max-age=31536000;

	# disable clients from sniffing the media type
	X-Content-Type-Options nosniff

	# clickjacking protection
	X-Frame-Options DENY
}
```

**Comment by francislavoie** [comment] 2024-03-08 15:41
That's invalid syntax, `[header]` is not a thing. You shouldn't have brackets around the directive name.

Caddy would have emitted an error on startup about this config problem. Please share your logs.

**Comment by MarcS1975** [comment] 2024-03-08 23:03
As I said. The problem is that when I removed the lines the error
persisted. The logs are posted above.

**Comment by mohammed90** [comment] 2024-03-09 09:53
> so I had added this to the Caddyfile when the problem started

Let's take a step back. Please describe the exact steps you took before and after, what happened when, and the logs for each step.

**Comment by MarcS1975** [comment] 2024-03-09 14:36
1) Setup Caddy file as above (1 domain reverse proxy entry) -> worked fine
2) I added the lines above (to turn on HSTS) which have syntax errors (Yes
I realise that they are wrong) -> Caddy stopped working, website
stuck/frozen -> Log files as above
3) I removed the erroneous lines and went back to original Caddyfile ->
error persists -> same log file entries

**Comment by mohammed90** [comment] 2024-03-09 16:21
You have to be more generous with the information. For instance, "Docker" is not the operating system. What is the host system? Did the Caddy version change at any point in time? When you say "Port 443 is open for ALL", do you mean because you did that in the docker-compose file? When you say it's stuck in the browser, what do you see in the Network tab of the devtools of the browser?

**Comment by MarcS1975** [comment] 2024-03-09 16:37
My Docker runs on a Debian 12 Linux host.
Port 443 is open because I opened it on the firewall for all protocols and
on docker via compose. I have been running Nginx for a very long time on
this system without issues.
Caddy did not change version.
Sorry I did not check the network tab of the browser.

**Comment by MarcS1975** [comment] 2024-03-10 02:11
So I added a few more domains. Very simple Caddyfile and they all create the same Caddy error. Log file below. I think there is something really really wrong inside Caddy because my servers work flawlessly with NGINX. Caddyfile is below the Log.

`duration=0.005875815error=writing: H3_REQUEST_CANCELLEDlevel=errorlogger=http.handlers.reverse_proxymsg=aborting with incomplete responserequest.client_ip=193.148.16.4request.headers.Accept=["image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8"]request.headers.Accept-Encoding=["gzip, deflate, br, zstd"]request.headers.Accept-Language=["en-GB,en;q=0.9"]request.headers.Dnt=["1"]request.headers.Referer=["https://MYdomainam.com/"]request.headers.Sec-Ch-Ua=[""Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122""]request.headers.Sec-Ch-Ua-Mobile=["?0"]request.headers.Sec-Ch-Ua-Platform=[""Windows""]request.headers.Sec-Fetch-Dest=["image"]request.headers.Sec-Fetch-Mode=["no-cors"]request.headers.Sec-Fetch-Site=["same-origin"]request.headers.User-Agent=["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"]request.headers.X-Forwarded-For=["193.148.16.4"]request.headers.X-Forwarded-Host=["MYdomainam.com"]request.headers.X-Forwarded-Proto=["https"]request.host=MYdomainam.comrequest.method=GETrequest.proto=HTTP/3.0request.remote_ip=193.148.16.4request.remote_port=11683request.tls.cipher_suite=4865request.tls.proto=h3request.tls.resumed=falserequest.tls.server_name=MYdomainam.comrequest.tls.version=772request.uri=/wp-content/uploads/2024/01/MYdomain-Am-preserving-value.jpgts=1710035928.6820567upstream=xxx.xxx.1.xxx:8888
add duration=0.005875815
add error=writing: H3_REQUEST_CANCELLED
add level=error
add logger=http.handlers.reverse_proxy
add msg=aborting with incomplete response
request=
add client_ip=193.148.16.4
headers=
add Accept=[ "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8" ]
add Accept-Encoding=[ "gzip, deflate, br, zstd" ]
add Accept-Language=[ "en-GB,en;q=0.9" ]
add Dnt=[ "1" ]
add Referer=[ "https://MYdomainam.com/" ]
add Sec-Ch-Ua=[ ""Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122"" ]
add Sec-Ch-Ua-Mobile=[ "?0" ]
add Sec-Ch-Ua-Platform=[ ""Windows"" ]
add Sec-Fetch-Dest=[ "image" ]
add Sec-Fetch-Mode=[ "no-cors" ]
add Sec-Fetch-Site=[ "same-origin" ]
add User-Agent=[ "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" ]
add X-Forwarded-For=[ "193.148.16.4" ]
add X-Forwarded-Host=[ "MYdomainam.com" ]
add X-Forwarded-Proto=[ "https" ]
add host=MYdomainam.com
add method=GET
add proto=HTTP/3.0
add remote_ip=193.148.16.4
add remote_port=11683
tls=
add cipher_suite=4865
add proto=h3
add resumed=false
add server_name=MYdomainam.com
add version=772
add uri=/wp-content/uploads/2024/01/MYdomain-Am-preserving-value.jpg
add ts=1710035928.6820567
add upstream=xxx.xxx.1.xxx:8888`

Caddyfile:

`# ––––––––––––––––––––––––––––––––––––––––––––
#  Caddyfile 05-03-24 Nginx Z44
# ––––––––––––––––––––––––––––––––––––––––––––
#
#
{
        email <myemail>
}
#
https://abc.domain124.abc:443 {
        reverse_proxy xxx.xxx.xxx.xxx:p1
}
#
#
https://domain2.com:443 {
        reverse_proxy xxx.xxx.xxx.xxx:p2
}
#https://domain124.abc:443 {
#       reverse_proxy xxx.xxx.xxx.xxx:p3
#}
https://xyz.domain124.abc:443 {
        reverse_proxy xxx.xxx.xxx.xxx:p4
}
`

**Comment by MarcS1975** [comment] 2024-03-10 02:27
When I call a new url which is defined in the caddyfile the following error goes into the log:

New log entry
```
error=no information found to solve challenge for identifier: mysubdomain.mydomain.xyzhost=mysubdomain.mydomain.xyzlevel=errorlogger=httpmsg=looking up info for HTTP challengeremote_addr=172.71.142.69:13700ts=1710037462.248043user_agent=Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)
add error=no information found to solve challenge for identifier: mysubdomain.mydomain.xyz
add host=mysubdomain.mydomain.xyz
add level=error
add logger=http
add msg=looking up info for HTTP challenge
add remote_addr=172.71.142.69:13700
add ts=1710037462.248043
add user_agent=Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)
```

**Comment by MarcS1975** [comment] 2024-03-10 02:30
seriously I think Caddy is not ready for release. I have such a simple Caddyfile and Nginx runs flawlessly so it cannot be due to by setup

**Comment by francislavoie** [comment] 2024-03-10 02:47
If you come in with a negative attitude, how do you expect us to want to help you?

Caddy is _definitely_ production ready, it's used by very large companies. Look at the star count, _clearly_ tens of thousands of people (at _least_) think it has value.

We've repeatedly asked you to clarify, but each time you omitted or redacted information such that we're left in the dark. Your logs are in a weird format, clearly they've been altered in some way since Caddy doesn't emit them like that.

This isn't worth our time as this point so I'll close this.

**Closed by francislavoie** 2024-03-10 02:47 UTC
Labels: needs info :mailbox_with_no_mail:

**Comment by MarcS1975** [comment] 2024-03-10 04:20
typical french attitude

**Comment by MarcS1975** [comment] 2024-03-10 04:23
I spent my time debugging your faulty beta product and you just feel hurt in your pride. Grow up man!

**Comment by mholt** [comment] 2024-03-14 04:35
@MarcS1975 Ooookay that behavior is not tolerated here, byeeee :wave:
