### ISSUE TITLE
log output file does not work

### ISSUE THREAD

**Issue by noqqe** [caddyserver/caddy#3359] opened 2020-05-06 07:26 UTC
Hi,

with Caddy2 logging to a local file does not work :( 

```yaml
version: '3.0'
services:

  cajir:
    image: caddy:latest
    ports:
      - '9999:80'
    volumes:
      - './Caddyfile:/etc/caddy/Caddyfile'
```
and the corresponding Caddyfile

```
localhost:80 {
  log {
    output file /var/log/access.log
  }
}
```

When attached to the running container there is nothing to be found. The file permissions should be fine. 

```
/ # ls -lah /var/log/
total 8K
drwxr-xr-x    2 root     root        4.0K Apr 23 06:25 .
drwxr-xr-x    1 root     root        4.0K Apr 23 06:25 ..
/ # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
   11 root      0:00 /bin/sh
   17 root      0:00 ps aux
```
Logging on startup shows:

```
cajir_1  | {"level":"info","ts":1588749531.5937614,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
cajir_1  | {"level":"info","ts":1588749531.6153986,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["[::1]:2019","127.0.0.1:2019","localhost:2019"]}
cajir_1  | {"level":"info","ts":1588749531.6156926,"logger":"http","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
cajir_1  | {"level":"info","ts":1588749531.6157525,"logger":"tls","msg":"cleaned up storage units"}
cajir_1  | {"level":"info","ts":1588749531.6159644,"msg":"autosaved config","file":"/config/caddy/autosave.json"}
cajir_1  | {"level":"info","ts":1588749531.6159844,"msg":"serving initial configuration"}
cajir_1  | 2020/05/06 07:18:51 [INFO][cache:0xc000671c20] Started certificate maintenance routine
cajir_1  | {"level":"info","ts":1588749545.500123,"logger":"http.log.access","msg":"handled request","request":{"method":"GET","uri":"/","proto":"HTTP/1.1","remote_addr":"192.168.2.1:35752","host":"localhost:9999","headers":{"User-Agent":["curl/7.64.0"],"Accept":["*/*"]}},"common_log":"192.168.2.1 - - [06/May/2020:07:19:05 +0000] \"GET / HTTP/1.1\" 0 0","duration":0.000010665,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
```

Im using caddy:latest (ID 8015a88eb81d). 

Any thoughts on this?

**Comment by mholt** [comment] 2020-05-06 16:04
Thanks for using Caddy!

Weird, it works for me... can you try without Docker?

Here's a template that will help make the issue more reproducible:

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by hairyhenderson** [comment] 2020-05-06 20:38
@noqqe you're telling Caddy to log to a file `/var/log/access.log`, but you've pasted the console output from `docker-compose up`. If you want the logs to be displayed on the console, I think the default `output stderr` is what you want instead.

**Comment by mholt** [comment] 2020-06-05 19:44
Closing due to inactivity

**Closed by mholt** 2020-06-05 19:44 UTC
Labels: needs info
