### ISSUE TITLE
Cloudsmith Package Hosting Failing - 402 Payment Required

### ISSUE THREAD

**Issue by wyattconsulting** [caddyserver/caddy#6218] opened 2024-04-03 21:13 UTC
![Screenshot from 2024-04-03 15-11-18](https://github.com/caddyserver/caddy/assets/59403431/606680f5-64de-4117-949a-2ebf8613ee97)

**Comment by igordeveloper** [comment] 2024-04-03 21:46
Same problem here.

![Screenshot from 2024-04-03 18-46-01](https://github.com/caddyserver/caddy/assets/1105648/216518fc-2c05-4376-96c6-81722e9b759e)

**Comment by wyattconsulting** [comment] 2024-04-03 21:48
Thanks @igordeveloper for confirming...I always feel silly opening issues like this.

**Comment by igordeveloper** [comment] 2024-04-03 21:49
> Thanks @igordeveloper for confirming...I always feel silly opening issues like this.

This error is ocurring with many people.

**Comment by compuguy** [comment] 2024-04-03 22:36
I can confirm it as well. Getting the same `402 Payment Required` error.

**Comment by sbusso** [comment] 2024-04-03 22:41
same here
<img width="1203" alt="image" src="https://github.com/caddyserver/caddy/assets/346/0f2384cf-7993-40cf-be2b-1c86fb89197c">

**Comment by sbusso** [comment] 2024-04-03 22:47
using github as an alternative: https://github.com/caddyserver/caddy/releases/tag/v2.7.6

```sh
wget https://github.com/caddyserver/caddy/releases/download/v2.7.6/caddy_2.7.6_linux_amd64.deb
sudo  dpkg -i caddy_2.7.6_linux_amd64.deb
```

**Comment by francislavoie** [comment] 2024-04-03 23:24
Duplicate of https://github.com/caddyserver/dist/issues/115

**Closed by francislavoie** 2024-04-03 23:24 UTC

**Comment by ASoldo** [comment] 2024-04-03 23:36
> using github as an alternative: https://github.com/caddyserver/caddy/releases/tag/v2.7.6
> 
> ```shell
> wget https://github.com/caddyserver/caddy/releases/download/v2.7.6/caddy_2.7.6_linux_amd64.deb
> sudo  dpkg -i caddy_2.7.6_linux_amd64.deb
> ```

This fixed issue for me rn! Tnx!

**Comment by mholt** [comment] 2024-04-04 04:05
As noted in the linked issue, our generously-allotted, bandwidth quota donated by Cloudsmith was spent in just 3 days. For now, we're asking Cloudsmith to not raise our allocation any further (as they have already multiplied it a few times over the course of several years!) and until we find a better solution we're asking anyone using the Cloudsmith repos in CI to download from GitHub releases or to compile from source instead.

**Comment by mholt** [comment] 2024-04-11 20:02
Cloudsmith informs me that they have been able to implement some measures, so that's good.
