### ISSUE TITLE
version 1.0.3,1.0.2 bug.   ./caddy  -version show unknown

### ISSUE THREAD

**Issue by whatlly** [caddyserver/caddy#2733] opened 2019-08-30 02:35 UTC
## 3. What is your Caddyfile?
```text
paste entire Caddyfile here - DO NOT REDACT ANYTHING (except credentials)
```

**Comment by mholt** [comment] 2019-08-30 03:55
Duplicate of #2715

**Closed by mholt** 2019-08-30 03:55 UTC
