### ISSUE TITLE
Debian sources at https://dl.cloudsmith.io/public/caddy/stable/deb/debian are down

### ISSUE THREAD

**Issue by barcovanrhijn** [caddyserver/caddy#6214] opened 2024-04-03 13:15 UTC
The sources url used in caddy-stable_dep.txt has gone down. 

This makes it impossible to upgrade Caddy or update other Debian/Ubuntu packages without removing Caddy as a source. 

The offending url is https://dl.cloudsmith.io/public/caddy/stable/deb/debian

**Comment by renchap** [comment] 2024-04-03 13:32
The repository as a whole seems to no longer be accessible.

```
E: Failed to fetch https://dl.cloudsmith.io/public/caddy/stable/deb/debian/dists/any-version/InRelease  402  Payment Required [IP: 2600:9000:2117:6c00:e:f4d2:20c0:93a1 443]
E: The repository 'https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease' is no longer signed.
```

According to the message, the Cloudsmith account has been disabled because of a billing issue?

**Comment by francislavoie** [comment] 2024-04-03 13:34
Duplicate of https://github.com/caddyserver/dist/issues/115

**Closed by francislavoie** 2024-04-03 13:34 UTC
