### ISSUE TITLE
caddy cannot obtaine Certificate on 4th-level domain

### ISSUE THREAD

**Issue by QGB** [caddyserver/caddy#5306] opened 2023-01-15 09:09 UTC
Caddy/2.6.2

```log

2023/01/15 08:36:02.987 INFO    tls.obtain      obtaining certificate   {"identifier": "four4.yourIPHEX.nip.io"}
2023/01/15 08:36:02.987 DEBUG   events  event   {"name": "cert_obtaining", "id": "************", "origin": "tls", "data": {"identifier":"four4.yourIPHEX.nip.io"}}
2023/01/15 08:36:02.991 DEBUG   tls.obtain      trying issuer 1/2       {"issuer": "acme-v02.api.letsencrypt.org-directory"}
2023/01/15 08:36:03.600 DEBUG   http.acme_client        http request    {"method": "GET", "url": "https://acme-staging-v02.api.letsencrypt.org/directory", "headers": {"User-Agent":["Caddy/2.6.2 CertMagic acmez (linux; amd64)"]}, "response_headers": {"Cache-Control
":["public, max-age=0, no-cache"],"Content-Length":["830"],"Content-Type":["application/json"],"Date":["Sun, 15 Jan 2023 08:36:03 GMT"],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]}, "status_code": 200}
2023/01/15 08:36:03.784 DEBUG   http.acme_client        http request    {"method": "HEAD", "url": "https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce", "headers": {"User-Agent":["Caddy/2.6.2 CertMagic acmez (linux; amd64)"]}, "response_headers": {"Cache-C
ontrol":["public, max-age=0, no-cache"],"Date":["Sun, 15 Jan 2023 08:36:03 GMT"],"Link":["<https://acme-staging-v02.api.letsencrypt.org/directory>;rel=\"index\""],"Replay-Nonce":["========11111========="],"Server":["nginx"],"Strict-Transpo
rt-Security":["max-age=604800"],"X-Frame-Options":["DENY"]}, "status_code": 200}
2023/01/15 08:36:03.982 DEBUG   http.acme_client        http request    {"method": "POST", "url": "https://acme-staging-v02.api.letsencrypt.org/acme/new-acct", "headers": {"Content-Type":["application/jose+json"],"User-Agent":["Caddy/2.6.2 CertMagic acmez (linux;
amd64)"]}, "response_headers": {"Boulder-Requester":["87654321"],"Cache-Control":["public, max-age=0, no-cache"],"Content-Length":["267"],"Content-Type":["application/json"],"Date":["Sun, 15 Jan 2023 08:36:03 GMT"],"Link":["<https://acme-staging-v02.api.letsencryp
t.org/directory>;rel=\"index\"","<https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf>;rel=\"terms-of-service\""],"Location":["https://acme-staging-v02.api.letsencrypt.org/acme/acct/87654321"],"Replay-Nonce":["===========2222222===="],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]}, "status_code": 201}
2023/01/15 08:36:04.206 DEBUG   http.acme_client        http request    {"method": "POST", "url": "https://acme-staging-v02.api.letsencrypt.org/acme/new-order", "headers": {"Content-Type":["application/jose+json"],"User-Agent":["Caddy/2.6.2 CertMagic acmez (linux;
 amd64)"]}, "response_headers": {"Boulder-Requester":["87654321"],"Cache-Control":["public, max-age=0, no-cache"],"Content-Length":["357"],"Content-Type":["application/json"],"Date":["Sun, 15 Jan 2023 08:36:04 GMT"],"Link":["<https://acme-staging-v02.api.letsencry
pt.org/directory>;rel=\"index\""],"Location":["https://acme-staging-v02.api.letsencrypt.org/acme/order/87654321/6540867703"],"Replay-Nonce":["============3333333========="],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Fra
me-Options":["DENY"]}, "status_code": 201}
2023/01/15 08:36:04.393 DEBUG   http.acme_client        http request    {"method": "POST", "url": "https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/4957727313", "headers": {"Content-Type":["application/jose+json"],"User-Agent":["Caddy/2.6.2 CertMagic acm
ez (linux; amd64)"]}, "response_headers": {"Boulder-Requester":["87654321"],"Cache-Control":["public, max-age=0, no-cache"],"Content-Length":["823"],"Content-Type":["application/json"],"Date":["Sun, 15 Jan 2023 08:36:04 GMT"],"Link":["<https://acme-staging-v02.api
.letsencrypt.org/directory>;rel=\"index\""],"Replay-Nonce":["=======44444444444444======"],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]}, "status_code": 200}
2023/01/15 08:36:04.393 DEBUG   http.acme_client        no solver configured    {"challenge_type": "dns-01"}
2023/01/15 08:36:04.393 INFO    http.acme_client        trying to solve challenge       {"identifier": "four4.yourIPHEX.nip.io", "challenge_type": "http-01", "ca": "https://acme-staging-v02.api.letsencrypt.org/directory"}
2023/01/15 08:36:04.394 DEBUG   http.acme_client        waiting for solver before continuing    {"identifier": "four4.yourIPHEX.nip.io", "challenge_type": "http-01"}
2023/01/15 08:36:04.394 DEBUG   http.acme_client        done waiting for solver {"identifier": "four4.yourIPHEX.nip.io", "challenge_type": "http-01"}
2023/01/15 08:36:04.583 DEBUG   http.acme_client        http request    {"method": "POST", "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/4957727313/R8_eAQ", "headers": {"Content-Type":["application/jose+json"],"User-Agent":["Caddy/2.6.2 CertMa
gic acmez (linux; amd64)"]}, "response_headers": {"Boulder-Requester":["87654321"],"Cache-Control":["public, max-age=0, no-cache"],"Content-Length":["193"],"Content-Type":["application/json"],"Date":["Sun, 15 Jan 2023 08:36:04 GMT"],"Link":["<https://acme-staging-
v02.api.letsencrypt.org/directory>;rel=\"index\"","<https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/4957727313>;rel=\"up\""],"Location":["https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/4957727313/R8_eAQ"],"Replay-Nonce":["===========555555555555======"],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]}, "status_code": 200}
2023/01/15 08:36:04.583 DEBUG   http.acme_client        challenge accepted      {"identifier": "four4.yourIPHEX.nip.io", "challenge_type": "http-01"}
2023/01/15 08:36:04.975 INFO    http    served key authentication       {"identifier": "four4.yourIPHEX.nip.io", "challenge": "http-01", "remote": "3.142.74.186:12798", "distributed": false}
2023-01-15 16:36:04.975558115 +0800 CST m=+84676.554602516 write error: error getting log file info: stat /root/access.log: permission denied
2023/01/15 08:36:04.984 INFO    http    served key authentication       {"identifier": "four4.yourIPHEX.nip.io", "challenge": "http-01", "remote": "35.91.203.83:28564", "distributed": false}
2023-01-15 16:36:04.984424285 +0800 CST m=+84676.563468691 write error: error getting log file info: stat /root/access.log: permission denied
2023/01/15 08:36:05.019 DEBUG   http.acme_client        http request    {"method": "POST", "url": "https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/4957727313", "headers": {"Content-Type":["application/jose+json"],"User-Agent":["Caddy/2.6.2 CertMagic acm
ez (linux; amd64)"]}, "response_headers": {"Boulder-Requester":["87654321"],"Cache-Control":["public, max-age=0, no-cache"],"Content-Length":["823"],"Content-Type":["application/json"],"Date":["Sun, 15 Jan 2023 08:36:04 GMT"],"Link":["<https://acme-staging-v02.api
.letsencrypt.org/directory>;rel=\"index\""],"Replay-Nonce":["===============66666666======"],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]}, "status_code": 200}
2023/01/15 08:36:05.186 INFO    http    served key authentication       {"identifier": "four4.yourIPHEX.nip.io", "challenge": "http-01", "remote": "23.178.112.107:60008", "distributed": false}
2023-01-15 16:36:05.186759162 +0800 CST m=+84676.765803579 write error: error getting log file info: stat /root/access.log: permission denied
2023/01/15 08:36:05.458 DEBUG   http.acme_client        http request    {"method": "POST", "url": "https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/4957727313", "headers": {"Content-Type":["application/jose+json"],"User-Agent":["Caddy/2.6.2 CertMagic acm
ez (linux; amd64)"]}, "response_headers": {"Boulder-Requester":["87654321"],"Cache-Control":["public, max-age=0, no-cache"],"Content-Length":["782"],"Content-Type":["application/json"],"Date":["Sun, 15 Jan 2023 08:36:05 GMT"],"Link":["<https://acme-staging-v02.api
.letsencrypt.org/directory>;rel=\"index\""],"Replay-Nonce":["=========7777777777======"],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]}, "status_code": 200}
2023/01/15 08:36:05.458 INFO    http.acme_client        authorization finalized {"identifier": "four4.yourIPHEX.nip.io", "authz_status": "valid"}
2023/01/15 08:36:05.458 INFO    http.acme_client        validations succeeded; finalizing order {"order": "https://acme-staging-v02.api.letsencrypt.org/acme/order/87654321/6540867703"}
2023/01/15 08:36:06.412 DEBUG   http.acme_client        http request    {"method": "POST", "url": "https://acme-staging-v02.api.letsencrypt.org/acme/finalize/87654321/6540867703", "headers": {"Content-Type":["application/jose+json"],"User-Agent":["Caddy/2.6.2 Cert
Magic acmez (linux; amd64)"]}, "response_headers": {"Boulder-Requester":["87654321"],"Cache-Control":["public, max-age=0, no-cache"],"Content-Length":["467"],"Content-Type":["application/json"],"Date":["Sun, 15 Jan 2023 08:36:06 GMT"],"Link":["<https://acme-stagin
g-v02.api.letsencrypt.org/directory>;rel=\"index\""],"Location":["https://acme-staging-v02.api.letsencrypt.org/acme/order/87654321/6540867703"],"Replay-Nonce":["==========88888888======="],"Server":["nginx"],"Strict-Transport-Security":["max-
age=604800"],"X-Frame-Options":["DENY"]}, "status_code": 200}
2023/01/15 08:36:06.600 DEBUG   http.acme_client        http request    {"method": "POST", "url": "https://acme-staging-v02.api.letsencrypt.org/acme/cert/fada14389b54ae630291baca7e74bb0ba17f", "headers": {"Content-Type":["application/jose+json"],"User-Agent":["Cad
dy/2.6.2 CertMagic acmez (linux; amd64)"]}, "response_headers": {"Cache-Control":["public, max-age=0, no-cache"],"Content-Length":["4196"],"Content-Type":["application/pem-certificate-chain"],"Date":["Sun, 15 Jan 2023 08:36:06 GMT"],"Link":["<https://acme-staging-
v02.api.letsencrypt.org/directory>;rel=\"index\""],"Replay-Nonce":["========9999999999======="],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]}, "status_code": 200}
2023/01/15 08:36:06.600 INFO    http.acme_client        successfully downloaded available certificate chains    {"count": 1, "first_url": "https://acme-staging-v02.api.letsencrypt.org/acme/cert/fada14389b54ae630291baca7e74bb0ba17f"}
2023/01/15 08:36:06.601 INFO    http    waiting on internal rate limiter        {"identifiers": ["four4.yourIPHEX.nip.io"], "ca": "https://acme-v02.api.letsencrypt.org/directory", "account": ""}
2023/01/15 08:36:06.601 INFO    http    done waiting on internal rate limiter   {"identifiers": ["four4.yourIPHEX.nip.io"], "ca": "https://acme-v02.api.letsencrypt.org/directory", "account": ""}
2023/01/15 08:36:07.196 DEBUG   http.acme_client        http request    {"method": "HEAD", "url": "https://acme-v02.api.letsencrypt.org/acme/new-nonce", "headers": {"User-Agent":["Caddy/2.6.2 CertMagic acmez (linux; amd64)"]}, "response_headers": {"Cache-Control":
["public, max-age=0, no-cache"],"Date":["Sun, 15 Jan 2023 08:36:07 GMT"],"Link":["<https://acme-v02.api.letsencrypt.org/directory>;rel=\"index\""],"Replay-Nonce":["=========AAA====="],"Server":["nginx"],"Strict-Transport-Security":["m
ax-age=604800"],"X-Frame-Options":["DENY"]}, "status_code": 200}
2023/01/15 08:36:07.403 DEBUG   http.acme_client        http request    {"method": "POST", "url": "https://acme-v02.api.letsencrypt.org/acme/new-order", "headers": {"Content-Type":["application/jose+json"],"User-Agent":["Caddy/2.6.2 CertMagic acmez (linux; amd64)"
]}, "response_headers": {"Boulder-Requester":["916253017"],"Cache-Control":["public, max-age=0, no-cache"],"Content-Length":["247"],"Content-Type":["application/problem+json"],"Date":["Sun, 15 Jan 2023 08:36:07 GMT"],"Link":["<https://acme-v02.api.letsencrypt.org/
directory>;rel=\"index\"","<https://letsencrypt.org/docs/rate-limits>;rel=\"help\""],"Replay-Nonce":["=============bbbbbb========"],"Retry-After":["1433"],"Server":["nginx"]}, "status_code": 429}
2023/01/15 08:36:07.403 ERROR   tls.obtain      could not get certificate from issuer   {"identifier": "four4.yourIPHEX.nip.io", "issuer": "acme-v02.api.letsencrypt.org-directory", "error": "HTTP 429 urn:ietf:params:acme:error:rateLimited - Error creating new order
 :: too many certificates already issued for \"nip.io\". Retry after 2023-01-15T09:00:00Z: see https://letsencrypt.org/docs/rate-limits/"}
2023/01/15 08:36:07.403 DEBUG   tls.obtain      trying issuer 2/2       {"issuer": "acme.zerossl.com-v2-DV90"}
2023/01/15 08:36:26.038 DEBUG   http.acme_client        http request    {"method": "HEAD", "url": "https://acme.zerossl.com/v2/DV90/newNonce", "headers": {"User-Agent":["Caddy/2.6.2 CertMagic acmez (linux; amd64)"]}, "response_headers": {"Access-Control-Allow-Orig
in":["*"],"Cache-Control":["max-age=0, no-cache, no-store"],"Content-Type":["application/octet-stream"],"Date":["Sun, 15 Jan 2023 08:36:25 GMT"],"Link":["<https://acme.zerossl.com/v2/DV90>;rel=\"index\""],"Replay-Nonce":["====ccccccc======"],"Server":["nginx"],"Strict-Transport-Security":["max-age=15724800; includeSubDomains"]}, "status_code": 200}
^C2023/01/15 08:36:28.581       INFO    shutting down   {"signal": "SIGINT"}
2023/01/15 08:36:28.583 WARN    exiting; byeee!! 👋     {"signal": "SIGINT"}
2023/01/15 08:36:28.583 DEBUG   http    servers shutting down with eternal grace period
2023/01/15 08:36:28.584 INFO    tls.cache.maintenance   stopped background certificate maintenance      {"cache": "0xc000558f50"}
2023/01/15 08:36:28.586 WARN    http.acme_client        HTTP request failed; retrying   {"url": "https://acme.zerossl.com/v2/DV90/newOrder", "error": "performing request: Post \"https://acme.zerossl.com/v2/DV90/newOrder\": context canceled"}
2023/01/15 08:36:28.586 ERROR   tls.obtain      could not get certificate from issuer   {"identifier": "four4.yourIPHEX.nip.io", "issuer": "acme.zerossl.com-v2-DV90", "error": "[four4.yourIPHEX.nip.io] creating new order: attempt 1: https://acme.zerossl.com/v2/DV90/
newOrder: context canceled (ca=https://acme.zerossl.com/v2/DV90)"}
2023/01/15 08:36:28.586 DEBUG   events  event   {"name": "cert_failed", "id": "3fe8d5fd-a774-4366-8902-1db78b607b41", "origin": "tls", "data": {"error":{},"identifier":"four4.yourIPHEX.nip.io","issuers":["acme-v02.api.letsencrypt.org-directory","acme.zerossl.com-v2
-DV90"],"renewal":false}}
2023/01/15 08:36:28.586 INFO    tls.obtain      releasing lock  {"identifier": "four4.yourIPHEX.nip.io"}
2023/01/15 08:36:28.586 ERROR   tls.obtain      unable to unlock        {"identifier": "four4.yourIPHEX.nip.io", "lock_key": "issue_cert_four4.yourIPHEX.nip.io", "error": "remove /home/qgb/.local/share/caddy/locks/issue_cert_four4.yourIPHEX.nip.io.lock: no such file
or directory"}
2023/01/15 08:36:28.586 ERROR   tls     job failed      {"error": "four4.yourIPHEX.nip.io: obtaining certificate: [four4.yourIPHEX.nip.io] Obtain: [four4.yourIPHEX.nip.io] creating new order: attempt 1: https://acme.zerossl.com/v2/DV90/newOrder: context canceled (ca=
https://acme.zerossl.com/v2/DV90)"}
2023/01/15 08:36:28.586 INFO    admin   stopped previous server {"address": "localhost:2019"}
2023/01/15 08:36:28.586 INFO    shutdown complete       {"signal": "SIGINT", "exit_code": 0}
qgb@:~$ ^C

````

**Comment by mohammed90** [comment] 2023-01-15 09:20
Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by QGB** [comment] 2023-01-15 10:36
@mohammed90 Do your have a public ipv4 server?。you may reproduce the problem by command

`caddy reverse-proxy --to http://captive.apple.com --from https://four4.yourIPHEX.nip.io:443 --debug`

**Comment by mohammed90** [comment] 2023-01-15 10:40
Reporting a bug requires the information requested in the template shared in the prior comment. Nonetheless, I took a preliminary look at the reported domain and there aren't any DNS records for it. We can attribute failure to that. If you have contrary evidence, please provide it. Meanwhile, this report appears invalid.

**Closed** 2023-01-15 10:40 UTC
Labels: invalid :question:

**Comment by QGB** [comment] 2023-01-15 10:44
@mohammed90  you need to replace your ip to url . like https://four4.8-8-8-8.nip.io:443

**Comment by mohammed90** [comment] 2023-01-15 10:47
> @mohammed90  you need to replace your ip to url . like https://four4.8-8-8-8.nip.io:443 

Can you pretty please fill out the template? With accurate, unredacted details if you don't mind. IP addresses and DNS FQDN are not secret.


Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by francislavoie** [comment] 2023-01-15 17:27
I don't think you can reliably use `nip.io` domains with ACME issuers. That domain is subject to rate limits, and since a lot of people use it in place of a real domain, it gets a lot of hits.

Use a real domain name, or get a free domain name from a service like DuckDNS instead.
