### ISSUE TITLE
v2: DNS providers

### ISSUE THREAD

**Issue by lpellegr** [caddyserver/caddy#3122] opened 2020-03-06 19:39 UTC
Congratulations on the awesome work and progress you made on version 2 of Caddy.

With Caddy v1 there is a plugin called dnsproviders to use caddy and issue certificates, for instance, behind a Cloudflare protected host:

https://github.com/caddyserver/dnsproviders

Is there a solution to this use case with the current version of Caddy v2 or is it something you plan to add later?

**Comment by mholt** [comment] 2020-03-06 20:24
Thanks! Not yet. Duplicate of #2855

**Closed by mholt** 2020-03-06 20:24 UTC
