### ISSUE TITLE
v2 basicauth - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tribor** [caddyserver/caddy#3258] opened 2020-04-12 15:59 UTC
I'm trying to use basicauth for a folder but get an exception while accessing the folder.
Tested with version v2.0.0-rc.2 on
* hardware centos7 server (kernel 3.10.0-1062.12.1.el7.x86_64) 
* also with docker `caddy/caddy:latest`

/etc/caddy # cat Caddyfile
```
:2015
root * /usr/share/caddy
basicauth /secret/* {
	Bob JDJhJDEwJEVCNmdaNEg2Ti5iejRMYkF3MFZhZ3VtV3E1SzBWZEZ5Q3VWc0tzOEJwZE9TaFlZdEVkZDhX
}
```

/etc/caddy #  caddy  validate
```
2020/04/12 15:33:08.678	INFO	using adjacent Caddyfile
2020/04/12 15:33:08 [INFO][cache:0xc0005c42d0] Started certificate maintenance routine
2020/04/12 15:33:08.703	INFO	http	server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server	{"server_name": "srv0", "http_port": 80}
2020/04/12 15:33:08 [INFO][cache:0xc0005c42d0] Stopped certificate maintenance routine
Valid configuration
```

/etc/caddy # caddy  reload
`2020/04/12 15:33:13.498	INFO	using adjacent Caddyfile`

/etc/caddy # caddy  version
`v2.0.0-rc.2 h1:7NOaxYrsnQ5D3rcLGn2UnLZHLfBpgrfM/JNTLhjCJ1c=`

/etc/caddy #  curl localhost:2015/secret/foo (on hardware server)
```
2020/04/12 17:41:29 http: panic serving [::1]:42190: runtime error: invalid memory address or nil pointer dereference
goroutine 23 [running]:
net/http.(*conn).serve.func1(0xc00048c000)
	net/http/server.go:1772 +0x139
panic(0x144d380, 0x2470800)
	runtime/panic.go:975 +0x3e3
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc000125d40, 0x192e2e0, 0xc00014c700, 0xc000416300)
	github.com/caddyserver/caddy/v2@v2.0.0-rc.2/modules/caddyhttp/server.go:203 +0x932
net/http.serverHandler.ServeHTTP(0xc00014c0e0, 0x192e2e0, 0xc00014c700, 0xc000416100)
	net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc00048c000, 0x19334e0, 0xc0004472c0)
	net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
	net/http/server.go:2933 +0x35c
curl: (52) Empty reply from server
```
Note: the output is much longer when trying to do the same in the docker container

```
/etc/caddy #  free -m
              total        used        free      shared  buff/cache   available
Mem:           7640        1653         298         400        5688        5283
Swap:          2043          12        2031

```

**Comment by mholt** [comment] 2020-04-12 16:06
Duplicate of #3248, #3250, #3253, #3254 

Already fixed, please download the latest CI artifacts or build from master.

**Closed by mholt** 2020-04-12 16:06 UTC

**Comment by francislavoie** [comment] 2020-04-12 16:20
CI artifacts are available here: https://github.com/caddyserver/caddy/actions/runs/75970632
