### ISSUE TITLE
Docker version is still v2.7.2

### ISSUE THREAD

**Issue by neil-lcv-cs** [caddyserver/caddy#5741] opened 2023-08-13 09:10 UTC
Hi,

Please update the Docker images on DockerHub:
```sh
docker exec -it caddy ash
/srv # caddy version
v2.7.2 h1:QqThyoyUFAv1B7A2NMeaWlz7xmgKqU49PXBX08A+6xg=
```
(I am using the `2-builder` tag)

**Comment by mohammed90** [comment] 2023-08-13 09:56
Duplicate of caddyserver/caddy-docker#307

**Closed by mohammed90** 2023-08-13 09:56 UTC
