### ISSUE TITLE
Tls self_signed - Not working correctly since a few versions

### ISSUE THREAD

**Issue by magikstm** [caddyserver/caddy#2502] opened 2019-03-05 02:01 UTC
## 1. Which version of Caddy are you using (`caddy -version`)?

Caddy 0.11.5 (non-commercial use only)

## 2. What are you trying to do?

Use tls self_signed for a local development Caddy server.

## 3. What is your Caddyfile?

    :2021 {
    root C:\sites\1
    log “” access2019.log “{remote} | {>User-Agent} | {user} | {when} | {method} | {uri} | {proto} | {status} | {size} | {latency_ms}”

    gzip
    on startup php_cgi2.bat &
    fastcgi / 127.0.0.1:6545 php
    tls self_signed
    }

## 4. How did you run Caddy (give the full command and describe the execution environment)?

I'm using Windows 7 x64.

I typed "caddy" in cmd in the folder containing caddy.exe.

## 5. Please paste any relevant HTTP request(s) here.

N/A

## 6. What did you expect to see?

Server starting and running normally.

## 7. What did you see instead (give full error messages and/or log)?

> 2019/03/04 19:39:27 self-signed: certificate has no names

## 8. Why is this a bug, and how do you think this should be fixed?

It doesn't respect docs here:
https://caddyserver.com/docs/tls

It worked correctly with Caddy 0.11.1.

## 9. What are you doing to work around the problem in the meantime?

I commented this line:
> tls self_signed

## 10. Please link to any related issues, pull requests, and/or discussion.

https://caddy.community/t/tls-self-signed-windows-7-x64-caddy-0-11-5/5299

**Comment by mholt** [comment] 2019-03-09 00:46
Thanks for the report. I could reproduce it. This one might require a change in CertMagic to fix fully.

**Comment by STaRDoGG** [comment] 2019-03-29 14:36
Any word on a fix for this? I just upgraded from 0.11.1 to 0.11.5 and have run into the same issue.

**Comment by francislavoie** [comment] 2019-03-29 14:53
@STaRDoGG see PR #2531, it's a work in progress.

**Comment by linquize** [comment] 2019-04-20 15:41
Should this issue be fixed in 1.0.0? Many users use self sign cert for development purpose

**Comment by mholt** [comment] 2019-04-20 19:40
I'll get around to it soon. It's not a blocker for 1.0, and I'm currently redesigning how self-signed certs are managed.

**Comment by magikstm** [comment] 2019-11-10 17:56
Is this issue still considered for Caddy 1.x?

I tested with Caddy 1.0.3 and I still have the issue.

**Comment by mholt** [comment] 2019-11-11 21:25
It will probably be worked on more for Caddy 2, tbh. Caddy 2 is really close to being "done" (for an initial stable release).

**Comment by sergeevabc** [comment] 2020-02-03 15:42
Agggrrrhh. What’s the proper way to get HTTPS working on localhost with Caddy2?

```
localhost, localhost:80, localhost:443
tls self_signed
file_server browse
encode zstd gzip
```
outputs
```
run: adapting config using caddyfile: parsing caddyfile tokens for 'tls':
Caddyfile:2 - Error during parsing: single argument must be an email address
```

**Comment by mholt** [comment] 2020-02-03 15:49
There is no `self_signed` in Caddy 2. I have a call today with a company to discuss implementing something better than it over the next few months, so just hang tight.

**Comment by mholt** [comment] 2020-03-07 20:17
Anyone interested in this please follow #3125 and try it out ASAP, it will be the successor to the v1 `self_signed` feature. Thanks!

**Closed by mholt** 2020-03-07 20:17 UTC
Labels: bug

**Comment by sergeevabc** [comment] 2020-03-07 21:03
@mholt, how is one supposed to try it if there is no binary attached?

**Comment by mholt** [comment] 2020-03-07 21:04
For now, just clone the branch and run go build from the cmd/caddy folder.

**Comment by francislavoie** [comment] 2020-03-07 21:44
@sergeevabc you should also be able to try it with one of the CI build artifacts: https://dev.azure.com/mholt-dev/Caddy/_build/results?buildId=927&view=artifacts&type=publishedArtifacts

**Comment by sergeevabc** [comment] 2020-03-07 22:35
I managed to download Caddy2’s binary thanks to @francislavoie, but not sure how to proceed with configuration, because I do not and never will use JSON for configuration. ```Caddyfile``` looks as follows
```
localhost:80
file_server browse
encode zstd gzip
```
I tried adding ```issuer internal```, but with no success. What should I add there?

**Comment by francislavoie** [comment] 2020-03-07 22:43
If you read the PR, you'll see that Caddyfile support isn't ready yet for this feature. In the meantime, you can easily convert your Caddyfile config to JSON with the `caddy adapt` command and go from there.
