### ISSUE TITLE
Constantly reloading of Caddyfile with "--watch"

### ISSUE THREAD

**Issue by ueffel** [caddyserver/caddy#5538] opened 2023-05-17 11:11 UTC
caddy version: v2.7.0-beta.1

As a result of #5521 running caddy per `caddy run --watch`

1. the log gets very spammy. Every second, there is a line like this:
  
   ```plain
   2023/05/17 12:46:42.285	INFO	using provided configuration	{"config_file": "Caddyfile", "config_adapter": ""}
   2023/05/17 12:46:43.291	INFO	using provided configuration	{"config_file": "Caddyfile", "config_adapter": ""}
   2023/05/17 12:46:44.287	INFO	using provided configuration	{"config_file": "Caddyfile", "config_adapter": ""}
   ```
2. Even relatively easy Caddyfiles are not always byte-equal after loading, which is why it is reloaded very often even though there are no changes. This line is the culprit https://github.com/caddyserver/caddy/blob/v2.7.0-beta.1/cmd/main.go#L224
   Example Caddyfile:
   ```caddy-d
   {
   	log {
   		format console {
   			time_format wall_milli
   			time_local
   			level_format upper
   		}
   	}
   }
   
   (config) {
   	root .
   	file_server browse
   }
   
   http://:80 {
   	import config
   }
   
   :443 {
   	tls internal
   	import config
   }
   ```

   lastCfg contents:
   ```json
   {"logging":{"logs":{"default":{"encoder":{"format":"console","level_format":"upper","time_format":"wall_milli","time_local":true}}}},"apps":{"http":{"servers":{"srv0":{"listen":[":443"],"routes":[{"handle":[{"handler":"vars","root":"."},{"browse":{},"handler":"file_server","hide":[".\\Caddyfile",".\\Caddyfile:22 (import config)"]}]}]},"srv1":{"listen":[":80"],"routes":[{"handle":[{"handler":"vars","root":"."},{"browse":{},"handler":"file_server","hide":[".\\Caddyfile:17 (import config)"]}]}]}}},"tls":{"automation":{"policies":[{"issuers":[{"module":"internal"}]}]}}}}
   ```
   
   newCfg contents:
   ```json
   {"logging":{"logs":{"default":{"encoder":{"format":"console","level_format":"upper","time_format":"wall_milli","time_local":true}}}},"apps":{"http":{"servers":{"srv0":{"listen":[":443"],"routes":[{"handle":[{"handler":"vars","root":"."},{"browse":{},"handler":"file_server","hide":[".\\Caddyfile:22 (import config)",".\\Caddyfile"]}]}]},"srv1":{"listen":[":80"],"routes":[{"handle":[{"handler":"vars","root":"."},{"browse":{},"handler":"file_server","hide":[".\\Caddyfile:17 (import config)"]}]}]}}},"tls":{"automation":{"policies":[{"issuers":[{"module":"internal"}]}]}}}}
   ```
   
   The difference is in `file_server`s hide field. The json array does not always seems to have the same order.

I don't really like the changes in #5521. Rereading the config every second is very inefficient. Isn't there a more efficient way like keeping track of all modification times of imported config files and the Caddyfile itself or using filesystem watchers (e.g https://github.com/fsnotify/fsnotify)?

**Comment by francislavoie** [comment] 2023-05-17 12:37
🤣 lovely. The problem is that maps in Go don't keep items ordered deterministically when iterating through their entries. Slices are ordered through. So the solution will be to sort the Hide slice after filling it with entries from the map.

Well I guess the good news from these changes is that we'll hear about more of the non-deterministic parts of the config adapter. We've fixed many of them previously because they often cause unit test failures, but I guess we didn't try this combination of snippets plus file_server in our tests, we haven't seen this one yet.

I agree with you that the `--watch` solution isn't ideal, but there's a lot of trouble with implementing fsnotify. We would need to wire up the Caddyfile adapter to collect all the file paths it visited including preserving `import` globs to later be watched, and I don't think we can watch globs with fsnotify on all platform-specific implementations. It's why we hadn't done it earlier, and why that feature request stayed open a long time. We figured this solution would be good enough to fulfill the ask in a reasonably simple way, even if it's inefficient. `--watch` is meant as a development tool and shouldn't be kept on 24/7 and especially not on a production server.

**Comment by mholt** [comment] 2023-05-17 15:27
Also, this seems weird to me:

> .\\Caddyfile:22 (import config)

I don't think that should be in the "hide" slice in the first place; probably a bug.

Thanks for the report @ueffel :blush:

**Comment by francislavoie** [comment] 2023-05-17 15:36
> Also, this seems weird to me `.\Caddyfile:22 (import config)`

I agree, but that's part of the "file" handling from snippets; tokens have a file and line number that they're sourced from, and since a snippet isn't actually a file, we needed some way to track that. Comes from https://github.com/caddyserver/caddy/commit/8bc05e598da0068358a2876c45f92f2c77455341#diff-98917d2db5db8a35380961b3fd2b791be869ed57a466e9245fda3f3f3b36e4a2R434

**Comment by mholt** [comment] 2023-05-17 20:00
I went ahead and pushed a commit that makes the list deterministic. That might happen to be enough to resolve the issue for you, @ueffel -- you're welcome to try it.

But I think we still need to fix the `hide` list, which I'm working on.

**Comment by ueffel** [comment] 2023-05-17 21:04
Thx! Issue 2. in the OP seems to be fixed in ca14b6edd95671e7f0731eea91c138cdca760577.

**Comment by mholt** [comment] 2023-05-17 21:07
@ueffel Thanks for verifying. I believe issue 1 should be fixed in https://github.com/caddyserver/caddy/commit/5ebb7d496da765fd0263161cd306ecf86b609485 already :thinking:

**Comment by ueffel** [comment] 2023-05-17 21:47
https://github.com/caddyserver/caddy/blob/ca14b6edd95671e7f0731eea91c138cdca760577/cmd/main.go#LL114-L117 begs to differ 😇

**Comment by mholt** [comment] 2023-05-17 22:13
Oops, silly me, there's another call to `LoadConfig` in the loop. Should be fixed now. :smiley:

**Closed** 2023-05-17 22:13 UTC
Labels: bug :lady_beetle:
