### ISSUE TITLE
experimental_http3 - "panic" when configuring a unix domain socket server

### ISSUE THREAD

**Issue by thx1111** [caddyserver/caddy#4901] opened 2022-07-22 06:28 UTC
caddy 2.5.1

With:
```
experimental_http3
strict_sni_host on
```
Also, explicitly setting `bind` and `host` directives.

Configuring a unix domain socket server, "/run/caddy/serve.sock", seems to trigger this, such that:
```
$ sudo caddy start --config /etc/caddy/Caddyfile
...
INFO    http    enabling experimental HTTP/3 listener   {"addr": "/run/caddy/serve.sock"}
panic: interface conversion: interface {} is nil, not *caddy.sharedQuicListener

goroutine 1 [running]:
github.com/caddyserver/caddy/v2.ListenQUIC({0xc000486f45, 0x15}, 0xc00051e000)
        github.com/caddyserver/caddy/v2/listeners.go:104 +0x1e5
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*App).Start(0xc00012cdc0)
        github.com/caddyserver/caddy/v2/modules/caddyhttp/app.go:355 +0x898
github.com/caddyserver/caddy/v2.run.func4(0xc00017a960)
        github.com/caddyserver/caddy/v2/caddy.go:447 +0xd5
github.com/caddyserver/caddy/v2.run(0xc0003f4900?, 0x1)
        github.com/caddyserver/caddy/v2/caddy.go:463 +0x533
github.com/caddyserver/caddy/v2.unsyncedDecodeAndRun({0xc0003f4000, 0x88d, 0x900}, 0x1)
        github.com/caddyserver/caddy/v2/caddy.go:282 +0x112
github.com/caddyserver/caddy/v2.changeConfig({0x561abe2cc267, 0x4}, {0x561abe2d7734, 0x7}, {0xc0000ed600, 0x88d, 0x900}, 0x1)
        github.com/caddyserver/caddy/v2/caddy.go:173 +0x4a5
github.com/caddyserver/caddy/v2.Load({0xc0000ed600, 0x88d, 0x900}, 0x0?)
        github.com/caddyserver/caddy/v2/caddy.go:114 +0x205
github.com/caddyserver/caddy/v2/cmd.cmdRun({0xc0002aa060?})
        github.com/caddyserver/caddy/v2/cmd/commandfuncs.go:213 +0x765
github.com/caddyserver/caddy/v2/cmd.Main()
        github.com/caddyserver/caddy/v2/cmd/main.go:84 +0x40d
main.main()
        github.com/caddyserver/caddy/v2/cmd/caddy/main.go:37 +0x17
start: caddy process exited with error: exit status 2
```
Alternatively, `caddy` may be started without `experimental_http3`, and then, enabling `experimental_http3`, and running `caddy reload`, the UDP configuration may just fail, sort of silently, with `caddy` still running:
```
$ sudo caddy reload --config /etc/caddy/Caddyfile
...
INFO    using provided configuration    {"config_file": "/etc/caddy/Caddyfile", "config_adapter": ""}
reload: sending configuration to instance: performing request: Post "http://%20/load": EOF
```
whereupon, checking for a `caddy` udp socket, there is none.  That last line, "reload: sending ...", is not normal output from `caddy reload`.

Otherwise, the configuration works fine without `experimental_http3`.  I have seen some simpler configurations working with `experimental_http3`.

**Comment by mholt** [comment] 2022-07-22 19:48
Thanks for the report.

Note that HTTP/3 + Strict Host Matching is not supported (yet) due to limitations upstream: https://github.com/caddyserver/caddy/issues/4294

It's not immediately clear to me what is going on in this case, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Instructions -- please heed otherwise we cannot help you (help us help you!)

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by mholt** [comment] 2022-09-13 23:07
Closing due to inactivity and lack of sufficient information to troubleshoot.

**Closed by mholt** 2022-09-13 23:07 UTC
Labels: needs info
