### ISSUE TITLE
caddy for arm64 crashes on Realtek RTD1295

### ISSUE THREAD

**Issue by deamen** [caddyserver/caddy#3593] opened 2020-07-22 02:57 UTC
The caddy arm64 crashes when I execute caddy:

> ./caddy
> SIGILL: illegal instruction
> PC=0x427e70 m=0 sigcode=1
> 
> goroutine 1 [running, locked to thread]:
> github.com/klauspost/cpuid.getProcFeatures(0xfaafa0, 0x400010aa50, 0x11dabff, 0xc, 0x4000093e18, 0x421ea4, 0x216e6c0, 0x421ea0, 0x4000093e28, 0x51a5c, ...)
>         github.com/klauspost/cpuid@v1.3.0/cpuid_arm64.s:15 fp=0x4000093dd0 sp=0x4000093dd0 pc=0x427e70
> github.com/klauspost/cpuid.addInfo(0x216e6c0)
>         github.com/klauspost/cpuid@v1.3.0/detect_arm64.go:42 +0x20 fp=0x4000093e00 sp=0x4000093dd0 pc=0x4231a0
> github.com/klauspost/cpuid.Detect()
>         github.com/klauspost/cpuid@v1.3.0/cpuid.go:289 +0x70 fp=0x4000093e20 sp=0x4000093e00 pc=0x421f30
> github.com/klauspost/cpuid.init.0()
>         github.com/klauspost/cpuid@v1.3.0/cpuid.go:272 +0x24 fp=0x4000093e30 sp=0x4000093e20 pc=0x421ea4
> runtime.doInit(0x20d4720)
>         runtime/proc.go:5420 +0x9c fp=0x4000093e70 sp=0x4000093e30 pc=0x51a5c
> runtime.doInit(0x20e9620)
>         runtime/proc.go:5415 +0x58 fp=0x4000093eb0 sp=0x4000093e70 pc=0x51a18
> runtime.doInit(0x20e6820)
>         runtime/proc.go:5415 +0x58 fp=0x4000093ef0 sp=0x4000093eb0 pc=0x51a18
> runtime.doInit(0x20e6940)
>         runtime/proc.go:5415 +0x58 fp=0x4000093f30 sp=0x4000093ef0 pc=0x51a18
> runtime.doInit(0x20d3a60)
>         runtime/proc.go:5415 +0x58 fp=0x4000093f70 sp=0x4000093f30 pc=0x51a18
> runtime.main()
>         runtime/proc.go:190 +0x1b8 fp=0x4000093fd0 sp=0x4000093f70 pc=0x44828
> runtime.goexit()
>         runtime/asm_arm64.s:1148 +0x4 fp=0x4000093fd0 sp=0x4000093fd0 pc=0x74604
> 
> r0      0x216e6c0
> r1      0x4000092380
> r2      0x4000093e00
> r3      0x3
> r4      0xfaafa0
> r5      0x0
> r6      0x11dabff
> r7      0xd9
> r8      0xf
> r9      0x4
> r10     0x0
> r11     0xd
> r12     0x1
> r13     0x802aaaa00aaaa
> r14     0xf8
> r15     0x0
> r16     0x34
> r17     0x68
> r18     0x0
> r19     0xd0
> r20     0x4000093ca8
> r21     0x40001283a0
> r22     0x4000002000
> r23     0x0
> r24     0x0
> r25     0x0
> r26     0x20d4748
> r27     0x216e748
> r28     0x4000000180
> r29     0x4000093dc8
> lr      0x4231a0
> sp      0x4000093dd0
> pc      0x427e70
> fault   0x0
>

**Comment by mholt** [comment] 2020-07-22 03:00
This is a known bug, duplicate of https://github.com/caddyserver/caddy/issues/3537.

It will be fixed in the next release. In the meantime, please build from source.

**Closed by mholt** 2020-07-22 03:00 UTC
