### ISSUE TITLE
http3 post request with body failed

### ISSUE THREAD

**Issue by majc08149** [caddyserver/caddy#3429] opened 2020-05-19 11:14 UTC
http3 post request with body always failed . 
caddy version:2.0.0
 I use curl http3 client, command line like: 
`curl --http3  -H "Content-Type:application/json"  -X POST  -v  "https://192.168.94.48:8080/g/demo-def-t2-server/9.0/testField1k" -d "{"name":"mmm"}"`

caddy file :
`{
  http_port 8081
	debug
	experimental_http3
}

:8080 {
	tls cert/hsiarserver.pem cert/hsiarserver.key {
	 #load cert 
	 #cert
	}
	
	log logs access.log "{remote} {when} {method} {uri} {proto} {status} {size} {>User-Agent} {latency} || {request} || BODY: {request_body}"
	encode gzip
	reverse_proxy {
	  to http://192.168.36.61:8001
	  transport http {
	  	keepalive 30s
	  	keepalive_idle_conns 100 
	  	read_buffer 1MB
	  	write_buffer 1MB
	  }
	}
}`

the curl result is :+1: 

[root@sundl-hs majc]# curl --http3  -H "Content-Type:application/json"  -X POST  -v  "https://192.168.94.48:8080/g/demo-def-t2-server/9.0/testField1k" -d "{"name":"mmm"}"
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 192.168.94.48:8080...
* Sent QUIC client Initial, ALPN: h3-27h3-25h3-24h3-23
* Connected to 192.168.94.48 (192.168.94.48) port 8080 (#0)
* h3 [:method: POST]
* h3 [:path: /g/demo-def-t2-server/9.0/testField1k]
* h3 [:scheme: https]
* h3 [:authority: 192.168.94.48:8080]
* h3 [user-agent: curl/7.70.0-DEV]
* h3 [accept: */*]
* h3 [content-type: application/json]
* h3 [content-length: 10]
* Using HTTP/3 Stream ID: 0 (easy handle 0x1d9b950)
> POST /g/demo-def-t2-server/9.0/testField1k HTTP/3
> Host: 192.168.94.48:8080
> user-agent: curl/7.70.0-DEV
> accept: */*
> content-type:application/json
> content-length: 10
> 
* upload completely sent off: 10 out of 10 bytes
* Empty reply from server
* Connection #0 to host 192.168.94.48 left intact
curl: (52) Empty reply from server

please help me !

**Comment by mholt** [comment] 2020-05-19 15:16
What is the result if you do the same request without http3?

**Comment by majc08149** [comment] 2020-05-20 01:00
> What is the result if you do the same request without http3?
Use http1.1 , I  can get the right result. command like:
curl   -H "Content-Type:application/json"  -X POST  -v  "https://192.168.94.48:8080/g/demo-def-t2-server/9.0/testField1k" -d "{"name":"mmm"}"

**Comment by mholt** [comment] 2020-05-20 05:00
Hm, okay, thanks.

It's not immediately clear to me what is going on, so I'll need your help to understand it better. There's not quite enough info here for me to see what you're seeing yet.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by majc08149** [comment] 2020-05-20 08:03
## 1. Environment
### 1a. Operating system and version
Server:  windows 7
Client:  CentOS Linux release 8.1.1911 (Core)
### 1b. Caddy version (run `caddy version` or paste commit SHA)
D:\caddy\caddy-master\cmd\caddy>caddy.exe version
v2.0.0 h1:pQSaIJGFluFvu8KDGDODV8u4/QRED/OPyIR+MWYYse8=
### 1c. Go version (if building Caddy from source; run `go version`)
C:\Users\majc08149>go version
go version go1.14.2 windows/amd64
### 1d. curl version 
curl --version
curl 7.70.0-DEV (x86_64-pc-linux-gnu) libcurl/7.70.0-DEV BoringSSL zlib/1.2.11 quiche/0.3.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS HTTP3 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
## 2. Description
### 2a. What happens (briefly explain what is wrong)
When I config http3, use curl send post request with body, response an empty body. the same environment send http1.1 post request，I can get the right body
### 2b. Why it's a bug (if it's not obvious)
Use http1.1 such as:
curl  -H "Content-Type:application/json" -v  "https://192.168.94.48:8080/g/demo-def-t2-server/9.0/testField1k" -d '{"name":"mmm"}' -k
result is :
*   Trying 192.168.94.48:8080...
* Connected to 192.168.94.48 (192.168.94.48) port 8080 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: [NONE]
*  start date: May 20 07:34:21 2020 GMT
*  expire date: May 20 19:35:21 2020 GMT
*  issuer: CN=Caddy Local Authority - ECC Intermediate
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> POST /g/demo-def-t2-server/9.0/testField1k HTTP/1.1
> Host: 192.168.94.48:8080
> User-Agent: curl/7.70.0-DEV
> Accept: */*
> Content-Type:application/json
> Content-Length: 14
> 
* upload completely sent off: 14 out of 14 bytes
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
_**< HTTP/1.1 404 Not Found
< Alt-Svc: h3-27=":8080"; ma=2592000
< Content-Length: 155
< Content-Type: text/html
< Date: Wed, 20 May 2020 07:44:55 GMT
< Server: Caddy
< Server: hsiar/V1.2.0-1
< 
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>hsiar/V1.2.0-1</center>
</body>
</html>
* Connection #0 to host 192.168.94.48 left intact**_
but use http3 such as
curl --http3 -H "Content-Type:application/json" -X POST -v "https://192.168.94.48:8080/g/demo-def-t2-server/9.0/testField1k" -d "{"name":"mmm"}"
result is :
*   Trying 192.168.94.48:8080...
* Sent QUIC client Initial, ALPN: h3-27h3-25h3-24h3-23
* Connected to 192.168.94.48 (192.168.94.48) port 8080 (#0)
* h3 [:method: POST]
* h3 [:path: /g/demo-def-t2-server/9.0/testField1k]
* h3 [:scheme: https]
* h3 [:authority: 192.168.94.48:8080]
* h3 [user-agent: curl/7.70.0-DEV]
* h3 [accept: */*]
* h3 [content-type: application/json]
* h3 [content-length: 14]
* Using HTTP/3 Stream ID: 0 (easy handle 0x6b4530)
> POST /g/demo-def-t2-server/9.0/testField1k HTTP/3
> Host: 192.168.94.48:8080
> user-agent: curl/7.70.0-DEV
> accept: */*
> content-type:application/json
> content-length: 14
> 
* upload completely sent off: 14 out of 14 bytes
* **_Empty reply from server
* Connection #0 to host 192.168.94.48 left intact
curl: (52) Empty reply from server_**

the italic text part is different, http3 no response body return

### 2c. Log output
ts=1589954061.6446605 level=info msg="handled request" requestError="unsupported value type" common_log="192.168.194.73 - - [20/May/2020:13:54:21 +0800] \"POST /g/demo-def-t2-server/9.0/testField1k HTTP/3\" 0 0" duration=0.007 size=0 status=0 resp_headersError="unsupported value type"
### 2d. Workaround(s)

### 2e. Relevant links

## 3. Tutorial (minimal steps to reproduce the bug)
Step 1：
Use the caddyfile such as：

{
  http_port 8081
	debug
	experimental_http3
	local_certs
}

:8080 {
	tls  cert/caddyserver.crt cert/caddyserver.key {
	}
	log {
	 output file  logs/access.log
	 format logfmt 
	 level  DEBUG
  }
	encode gzip
	reverse_proxy {
	  to http://192.168.36.61:8001
	  transport http {
	  	keepalive 30s
	  	keepalive_idle_conns 100 
	  	read_buffer 1MB
	  	write_buffer 1MB
	  }
	}
}
Step 2:
Run caddy ,commands:
Caddy.exe run
Step 3
Send curl request As described at the beginning
curl --http3 -H "Content-Type:application/json" -X POST -v "https://192.168.94.48:8080/g/demo-def-t2-server/9.0/testField1k" -d "{"name":"mmm"}"

**Comment by mholt** [comment] 2020-05-20 16:18
Thanks, but -- sorry, it's really hard to read your post. Can you go back and use proper markdown formatting to make it readable? Enclose code/output in code blocks, etc.

**Comment by majc08149** [comment] 2020-05-21 01:22
> Thanks, but -- sorry, it's really hard to read your post. Can you go back and use proper markdown formatting to make it readable? Enclose code/output in code blocks, etc.

## 1. Environment
### 1a. Operating system and version
Server:  windows 7， Caddy runs on this machine
Client:  CentOS Linux release 8.1.1911 (Core)，curl runs  on this machine
### 1b. Caddy version (run `caddy version` or paste commit SHA)
D:\caddy\caddy-master\cmd\caddy>caddy.exe version
v2.0.0 h1:pQSaIJGFluFvu8KDGDODV8u4/QRED/OPyIR+MWYYse8=
### 1c. Go version (if building Caddy from source; run `go version`)
C:\Users\majc08149>go version
go version go1.14.2 windows/amd64
### 1d. curl version 
curl --version
curl 7.70.0-DEV (x86_64-pc-linux-gnu) libcurl/7.70.0-DEV BoringSSL zlib/1.2.11 quiche/0.3.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS HTTP3 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
## 2. Description
### 2a. What happens (briefly explain what is wrong)
Using caddy as a reverse proxy server,and upstream is a web server, which can return a 404 page. When configuring caddy to support http3, Using curl to send http3's
Post request with body, Return empty reply package.  But the same environment using curl to send http1.1's Post request with body，I can get the correct 404 page
### 2b. Why it's a bug (if it's not obvious)
Send using the following command :
curl  -H "Content-Type:application/json" -v  "https://192.168.94.48:8080/g/demo-def-t2-server/9.0/testField1k" -d '{"name":"mmm"}' -k
return correct results:
< HTTP/1.1 404 Not Found
< Alt-Svc: h3-27=":8080"; ma=2592000
< Content-Length: 155
< Content-Type: text/html
< Date: Wed, 20 May 2020 07:44:55 GMT
< Server: Caddy
< Server: hsiar/V1.2.0-1
< 
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>hsiar/V1.2.0-1</center>
</body>
</html>


but Send using the following command :
curl --http3 -H "Content-Type:application/json" -X POST -v "https://192.168.94.48:8080/g/demo-def-t2-server/9.0/testField1k" -d "{"name":"mmm"}"
Return error results, Nothing came back，display following:
Empty reply from server
curl: (52) Empty reply from server

### 2c. Log output
ts=1589954061.6446605 level=info msg="handled request" requestError="unsupported value type" common_log="192.168.194.73 - - [20/May/2020:13:54:21 +0800] \"POST /g/demo-def-t2-server/9.0/testField1k HTTP/3\" 0 0" duration=0.007 size=0 status=0 resp_headersError="unsupported value type"

## 3. Tutorial (minimal steps to reproduce the bug)
###Create a config file:
{
  http_port 8081
	debug
	experimental_http3
	local_certs
}

:8080 {
	tls  cert/caddyserver.crt cert/caddyserver.key {
	}
	log {
	 output file  logs/access.log
	 format logfmt 
	 level  DEBUG
  }
	encode gzip
	reverse_proxy {
	  to http://192.168.36.61:8001
	  transport http {
	  	keepalive 30s
	  	keepalive_idle_conns 100 
	  	read_buffer 1MB
	  	write_buffer 1MB
	  }
	}
}
###Open terminal and run Caddy:
Run caddy ,commands:
Caddy.exe run
###Make an HTTP request:

curl  -H "Content-Type:application/json" -v  "https://192.168.94.48:8080/g/demo-def-t2-server/9.0/testField1k" -d '{"name":"mmm"}' -k

curl --http3 -H "Content-Type:application/json" -X POST -v "https://192.168.94.48:8080/g/demo-def-t2-server/9.0/testField1k" -d "{"name":"mmm"}"

**Comment by ggjjlldd** [comment] 2020-05-21 05:05
i am a co-worker with @majc08149 , i find problem  reason and code. But I do not know how to modify? @mholt 

I paste problem code ：
file->net/http/transfer.go:371

`	if t.BodyCloser != nil {
		if err := t.BodyCloser.Close(); err != nil {
			return err
		}
	}
`
the function BodyCloser.Close() call quic-go->http3->body.go Close() like :
`
func (r *body) Close() error {
	// quic.Stream.Close() closes the write side, not the read side
	if r.isRequest {
		return r.str.Close()
	}
	r.requestDone()
	r.str.CancelRead(quic.ErrorCode(errorRequestCanceled))
	return nil
}

`

this call quic-go->stream.go function 👍 
`
func (s *stream) Close() error {
	if err := s.sendStream.Close(); err != nil {
		return err
	}
	return nil
}
`

the function  s.sendStream.Close() will call func (s *sendStream) Close() error , this function call 
s.ctxCancel() to cancel context.
so the request reverseproxy will be canceled.

please help me how to fix this bug? @mholt

**Comment by ggjjlldd** [comment] 2020-05-21 07:42
### the reason

when I debug this problem , I found **reason**:
I paste problem code ：

```
Breakpoint reached: send_stream.go:322
Stack: 
	github.com/lucas-clemente/quic-go.(*sendStream).Close at send_stream.go:322
	github.com/lucas-clemente/quic-go.(*stream).Close at stream.go:132
	github.com/lucas-clemente/quic-go/http3.(*body).Close at body.go:99
	net/http.(*transferWriter).writeBody at transfer.go:375
	net/http.(*Request).write at request.go:685
	net/http.(*persistConn).writeLoop at transport.go:2280
	runtime.goexit at asm_amd64.s:1373
```

**send_stream.go** function:

```
func (s *sendStream) Close() error {
	s.mutex.Lock()
	if s.closedForShutdown {
		s.mutex.Unlock()
		return nil
	}
	if s.canceledWrite {
		s.mutex.Unlock()
		return fmt.Errorf("close called for canceled stream %d", s.streamID)
	}
	
	s.ctxCancel() // this is problem.the context canceled, So i can not get response from back server
	
	s.finishedWriting = true
	s.mutex.Unlock()

	s.sender.onHasStreamData(s.streamID) // need to send the FIN, must be called without holding the mutex
	return nil
}
```

**Comment by ggjjlldd** [comment] 2020-05-21 07:42
> ### the reason
> when I debug this problem , I found **reason**:
> I paste problem code ：
> 
> ```
> Breakpoint reached: send_stream.go:322
> Stack: 
> 	github.com/lucas-clemente/quic-go.(*sendStream).Close at send_stream.go:322
> 	github.com/lucas-clemente/quic-go.(*stream).Close at stream.go:132
> 	github.com/lucas-clemente/quic-go/http3.(*body).Close at body.go:99
> 	net/http.(*transferWriter).writeBody at transfer.go:375
> 	net/http.(*Request).write at request.go:685
> 	net/http.(*persistConn).writeLoop at transport.go:2280
> 	runtime.goexit at asm_amd64.s:1373
> ```
> 
> **send_stream.go** function:
> 
> ```
> func (s *sendStream) Close() error {
> 	s.mutex.Lock()
> 	if s.closedForShutdown {
> 		s.mutex.Unlock()
> 		return nil
> 	}
> 	if s.canceledWrite {
> 		s.mutex.Unlock()
> 		return fmt.Errorf("close called for canceled stream %d", s.streamID)
> 	}
> 	
> 	s.ctxCancel() // this is problem.the context canceled, So i can not get response from back server
> 	
> 	s.finishedWriting = true
> 	s.mutex.Unlock()
> 
> 	s.sender.onHasStreamData(s.streamID) // need to send the FIN, must be called without holding the mutex
> 	return nil
> }
> ```

please help me to bug fix!!!

**Comment by mholt** [comment] 2020-05-21 18:48
Thanks for looking into it more @ggjjlldd -- I see that much more discussion has happened over in https://github.com/lucas-clemente/quic-go/issues/2551, so to avoid repeating ourselves I will close this issue.

If you are able to reproduce the problem without reverse proxy, that will be helpful. 

It seems that you think the problem is:

> the function s.sendStream.Close() will call func (s *sendStream) Close() error , this function call
> s.ctxCancel() to cancel context.
> so the request reverseproxy will be canceled.

I think this is expected though; if the client closes their connection, the upstream connection will also be closed.

**Closed by mholt** 2020-05-21 18:48 UTC
Labels: needs info

**Comment by mholt** [comment] 2020-06-05 19:44
This is apparently fixed in https://github.com/lucas-clemente/quic-go/issues/2551!
