### ISSUE TITLE
log does not log to console

### ISSUE THREAD

**Issue by vRobM** [caddyserver/caddy#3671] opened 2020-08-20 07:51 UTC
According to the docs, the log module invoked with no parameters from CLI should display access logs in the console.

I can't seem to get it to do so with any log output directives.

Since I mainly use it in interactive mode I'd like to see the output friendliness cleaned up and actual access logs visible.

**Comment by francislavoie** [comment] 2020-08-20 08:08
Thanks for opening an issue! We'll look into this.

It's not immediately clear to us what is going on, so we'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by francislavoie** [comment] 2020-08-23 18:46
Closing this until more information is provided.

**Closed by francislavoie** 2020-08-23 18:46 UTC
Labels: needs info

**Comment by vRobM** [comment] 2020-08-23 20:11
You can write your tests to check for any 200 messages after a connection is made and should be output to the log.
check the stdout, stderr, console and file logging options.

what else do you _actually_ need?

**Comment by mholt** [comment] 2020-08-23 20:27
Believe it or not, the information we ask for in the bug report template is actually helpful and required to troubleshoot problems. We don't know what your command looks like, what your config looks like, what your requests look like, or anything. Right now with the information provided we'd have to make so many assumptions it'd be pointless because, remember, every feature that we ship "worked for us" so if it doesn't work for you we need to be convinced.

**Comment by vRobM** [comment] 2020-08-23 20:37
Ohh I believe you Matt, point is I already mentioned everything I did was in interactive mode, meaning straight from CLI.

I didn't see anyone respond with, I just ran it and I see connection requests, here's my command.

`$ ~/caddyv2 version
2020/08/23 16:31:50 WARNING: proto: file "pb.proto" is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

v2.1.1 h1:X9k1+ehZPYYrSqBvf/ocUgdLSRIuiNiMo7CvyGUQKeA=
`

`~/caddyv2 file-server --browse --listen log` should do it, yet nothing prints in console after initial messages when clients are connecting.

**Comment by francislavoie** [comment] 2020-08-23 20:38
You didn't use the `--access-log` flag. https://caddyserver.com/docs/command-line#caddy-file-server

**Comment by vRobM** [comment] 2020-08-23 21:10
You're right, apparently I was attempting to run Caddyfile directives in CLI.
confusing why they would be different.

I see the output is in JSON. Is there a plan to improve the output formatting of the INFO message for human readability? (add some new lines and tabs?)

**Comment by mholt** [comment] 2020-08-26 16:38
@vRobM 

> I see the output is in JSON. Is there a plan to improve the output formatting of the INFO message for human readability? (add some new lines and tabs?)

You can customize which log encoder is used to change the format of the log entries. Generally logs don't have newlines because it makes it hard to read. If you run caddy interactively on the terminal the default log format has colors and tabs for readability. If you run it non-interactively its default is pure JSON to make it easy for machines to parse.

**Comment by KempWatson** [comment] 2021-04-07 22:13
This may explain a lot of weirdness i'm seeing on the Caddy console output:

```
2021/04/07 21:52:36.731 [34mINFO[0m   http    enabling automatic HTTP->HTTPS redirects        {"server_name": "srv0"}
2021/04/07 21:52:36.732 [34mINFO[0m   http    enabling experimental HTTP/3 listener   {"addr": ":443"}
2021/04/07 21:52:36.733 [34mINFO[0m   http    enabling automatic TLS certificate management   {"domains": ["*.pathology.network", "*.pathology.cloud", "pathology.asia", "bingli.tw", "tuberculosis.asia", "www.tuberculosis.asia"]}
2021/04/07 21:52:36.737 [34mINFO[0m   tls     cleaned up storage units
2021/04/07 21:52:37.046 [34mINFO[0m   tls.obtain      acquiring lock  {"identifier": "bingli.tw"}
2021/04/07 21:52:37.049 [31mERROR[0m  tls     job failed      {"error": "bingli.tw: obtaining certificate: invalid character '\\x00' looking for beginning of value"}
2021/04/07 21:52:37.484 [34mINFO[0m   autosaved config        {"file": "C:\\Users\\Administrator\\AppData\\Roaming\\Caddy\\autosave.json"}
2021/04/07 21:52:37.484 [34mINFO[0m   serving initial configuration
```

I'm guessing some of that is colour and formatting codes... but why show this on the basic Windows terminal, which by default does not support this? And if the default console output, why I am getting JSON, by default or even when I explicitly set logs to stdout and console? It's an awful mess.

Also, note that I can't get domain "bingli.tw" to acquire a cert... could this be an issue with China? A secondary question here is that Caddy tries to check in with Google - which is blocked in China...

Caddy 1 was just so sweet and simple in comparison to Caddy 2, which has been nothing but headaches. Caddy's greatness was not auto-SSL, which everybody will have soon, but the simple, not-trying-to-do-it-all mentality. Now it's turning into a kitchen-sink NGINX competitor, and I see fewer advantages to Caddy every time I check in. There's a thousand NGINX kiddies for every Caddy kid... what is the long-term advantage of Caddy? It's become HARD.

**Comment by francislavoie** [comment] 2021-04-07 23:42
@KempWatson install the new Windows Terminal and you won't have this problem https://www.microsoft.com/en-ca/p/windows-terminal/9n0dx20hk701?rtc=1&activetab=pivot:overviewtab

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
