### ISSUE TITLE
Missing linux/amd64 os/arch for Caddy 2.7.5

### ISSUE THREAD

**Issue by jonnyt** [caddyserver/caddy#5885] opened 2023-10-12 16:54 UTC
Hello,

When pulling caddy:2.7.5 we see `no matching manifest for linux/amd64 in the manifest list entries`

And sure enough it's not listed here: https://hub.docker.com/_/caddy/tags?page=1&name=2.7.5.

Just wondering if we should be patient or if there was some issue in the process that publishes the images.

Thanks!

**Comment by francislavoie** [comment] 2023-10-12 17:58
Duplicate of https://github.com/caddyserver/caddy-docker/issues/324#issuecomment-1758956763

**Closed by francislavoie** 2023-10-12 17:58 UTC
