### ISSUE TITLE
Support default values for placeholders 

### ISSUE THREAD

**Issue by dunglas** [caddyserver/caddy#3974] opened 2021-01-14 08:58 UTC
#3682 introduced support for env var defaults in `Caddyfile`, which is awesome! It would be nice to support default values in `env.*` placeholders too.

For instance, I have the following use case:

```
    mercure {
        # Transport to use (default to Bolt)
        transport_url {$MERCURE_TRANSPORT_URL:bolt://mercure.db}
     }
```

The `MERCURE_TRANSPORT_URL` env var may contain sensitive data (such as passwords). Using runtime env var would be a bit more secure than the current situation where the content of the password is stored in the internal config, but it's currently not possible (AFAIK) because it's not possible to set a default value for these env vars.

**Comment by mholt** [comment] 2021-01-14 18:17
I think this is a duplicate of #1793.

**Closed** 2021-01-16 18:38 UTC
Labels: duplicate, feature request, good first issue
