### ISSUE TITLE
Docker caddy:2.7.5-builder only published for 3 platforms

### ISSUE THREAD

**Issue by serfriz** [caddyserver/caddy#5886] opened 2023-10-12 19:12 UTC
Hello, I am trying to build my own custom Caddy image with some additional modules, and the build process fails because caddy:2.7.5-builder hasn't been pushed to [DockerHub](https://hub.docker.com/layers/library/caddy/2.7.5-builder/images/sha256-eba60e558fae5eb5237067ab66dcea5b0c12a3860210e548c2d702c8181969c8?context=explore) for the linux/amd64 platform (other platforms are also missing: armv7, arm64, s390x, etc). The updated builder was pushed with the tags "2.7" and "latest" for all platforms, but my GitHub Actions build process is configured to use specific 2.7.x versions. Thank you!

**Comment by francislavoie** [comment] 2023-10-12 19:56
Duplicate of https://github.com/caddyserver/caddy-docker/issues/324#issuecomment-1758956763

**Closed by francislavoie** 2023-10-12 19:56 UTC
