### ISSUE TITLE
How do I configure the logging request body in Caddyfile

### ISSUE THREAD

**Issue by karllao** [caddyserver/caddy#5518] opened 2023-05-04 11:28 UTC
I tried to use request_body, but this does not work and only headers are recorded in the log
caddy v2.6.4

```
mysite.xyz {
    reverse_proxy 127.0.0.1:3320
    log {
        output file /var/log/caddy/access.log
        format json
        request_body
    }
}
```

**Comment by IndeedNotJames** [comment] 2023-05-04 12:00
Duplicate of #1015

@francislavoie's response from https://github.com/caddyserver/caddy/issues/1015#issuecomment-1035087612 still applies, as far as I am aware.

**Closed by IndeedNotJames** 2023-05-04 12:00 UTC
Labels: question :grey_question:
