### ISSUE TITLE
Incorrect behavior when encode directive is used

### ISSUE THREAD

**Issue by ArabCoders** [caddyserver/caddy#5031] opened 2022-09-10 16:27 UTC
Hello,

I've noticed that when we use `encode gzip zstd` directive, the `Accept-Ranges` header is removed even when the response is not compressed at all. For example, 

# Incorrect behavior

Issuing this request i expect the `Accept-Ranges` header to be present in the response

```bash
(user@localhost) ~ http -h 'https://dev.example.com/api/browse/download/media/videos/3.mp4' Authorization:"Bearer testapikey"

# Request headers

GET /api/browse/download/media/videos/3.mp4 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Bearer testapikey
Connection: keep-alive
Host: dev.example.com
User-Agent: HTTPie/2.6.0

# Response Headers

HTTP/1.1 200 OK
Cache-Control: public, max-age=1694361074
Content-Disposition: inline; filename="3.mp4"
Content-Length: 2659699
Content-Type: video/mp4
Date: Sat, 10 Sep 2022 15:51:14 GMT
Expires: Fri, 07 Jul 2023 15:51:14 GMT
Last-Modified: Fri, 13 Oct 2017 00:31:34 GMT
Pragma: public
Server: Caddy
X-Real-Size: 2659699
X-Request-Id: NflSKPf5MYRY3A-H26yzv
```
As you can see from the request/response cycle, no `Accept-Ranges`  header is present. 

## Caddy logs

```json
[
    {
        "level": "debug",
        "ts": 1662825074.4811828,
        "logger": "http.handlers.rewrite",
        "msg": "rewrote request",
        "request": {
            "remote_ip": "10.0.0.2",
            "remote_port": "59699",
            "proto": "HTTP/1.1",
            "method": "GET",
            "host": "dev.example.com",
            "uri": "/api/browse/download/media/videos/3.mp4",
            "headers": {
                "Accept-Encoding": [
                    "gzip, deflate"
                ],
                "Accept": [
                    "*/*"
                ],
                "Connection": [
                    "keep-alive"
                ],
                "Authorization": [],
                "User-Agent": [
                    "HTTPie/2.6.0"
                ]
            },
            "tls": {
                "resumed": false,
                "version": 772,
                "cipher_suite": 4865,
                "proto": "http/1.1",
                "server_name": "dev.example.com"
            }
        },
        "method": "GET",
        "uri": "index.php"
    },
    {
        "level": "debug",
        "ts": 1662825074.481457,
        "logger": "http.reverse_proxy.transport.fastcgi",
        "msg": "roundtrip",
        "request": {
            "remote_ip": "10.0.0.2",
            "remote_port": "59699",
            "proto": "HTTP/1.1",
            "method": "GET",
            "host": "dev.example.com",
            "uri": "index.php",
            "headers": {
                "X-Forwarded-Proto": [
                    "https"
                ],
                "X-Forwarded-Host": [
                    "dev.example.com"
                ],
                "User-Agent": [
                    "HTTPie/2.6.0"
                ],
                "Accept-Encoding": [
                    "gzip, deflate"
                ],
                "Accept": [
                    "*/*"
                ],
                "X-Forwarded-For": [
                    "10.0.0.2"
                ],
                "Authorization": []
            },
            "tls": {
                "resumed": false,
                "version": 772,
                "cipher_suite": 4865,
                "proto": "http/1.1",
                "server_name": "dev.example.com"
            }
        },
        "dial": "php_fpm:9000",
        "env": {
            "SERVER_PROTOCOL": "HTTP/1.1",
            "SSL_CIPHER": "TLS_AES_128_GCM_SHA256",
            "HTTP_X_FORWARDED_HOST": "dev.example.com",
            "HTTP_AUTHORIZATION": "Bearer testapikey",
            "REQUEST_SCHEME": "https",
            "SCRIPT_NAME": "/index.php",
            "HTTPS": "on",
            "AUTH_TYPE": "",
            "SERVER_NAME": "dev.example.com",
            "SCRIPT_FILENAME": "/opt/app/public/index.php",
            "HTTP_ACCEPT_ENCODING": "gzip, deflate",
            "HTTP_X_FORWARDED_FOR": "10.0.0.2",
            "REMOTE_ADDR": "10.0.0.2",
            "HTTP_X_FORWARDED_PROTO": "https",
            "REQUEST_METHOD": "GET",
            "DOCUMENT_ROOT": "/opt/app/public/",
            "HTTP_ACCEPT": "*/*",
            "HTTP_HOST": "dev.example.com",
            "REQUEST_URI": "/api/browse/download/media/videos/3.mp4",
            "SSL_PROTOCOL": "TLSv1.3",
            "GATEWAY_INTERFACE": "CGI/1.1",
            "REMOTE_IDENT": "",
            "CONTENT_TYPE": "",
            "SERVER_SOFTWARE": "Caddy/v2.5.2",
            "DOCUMENT_URI": "index.php",
            "X_REQUEST_ID": "NflSKPf5MYRY3A-H26yzv",
            "CONTENT_LENGTH": "",
            "PATH_INFO": "",
            "QUERY_STRING": "",
            "REMOTE_PORT": "59699",
            "REMOTE_HOST": "10.0.0.2",
            "REMOTE_USER": "",
            "SERVER_PORT": "443",
            "HTTP_USER_AGENT": "HTTPie/2.6.0"
        }
    },
    {
        "level": "debug",
        "ts": 1662825074.546504,
        "logger": "http.handlers.reverse_proxy",
        "msg": "upstream roundtrip",
        "upstream": "php_fpm:9000",
        "duration": 0.065128102,
        "request": {
            "remote_ip": "10.0.0.2",
            "remote_port": "59699",
            "proto": "HTTP/1.1",
            "method": "GET",
            "host": "dev.example.com",
            "uri": "index.php",
            "headers": {
                "Accept": [
                    "*/*"
                ],
                "X-Forwarded-For": [
                    "10.0.0.2"
                ],
                "Authorization": [],
                "X-Forwarded-Proto": [
                    "https"
                ],
                "X-Forwarded-Host": [
                    "dev.example.com"
                ],
                "User-Agent": [
                    "HTTPie/2.6.0"
                ],
                "Accept-Encoding": [
                    "gzip, deflate"
                ]
            },
            "tls": {
                "resumed": false,
                "version": 772,
                "cipher_suite": 4865,
                "proto": "http/1.1",
                "server_name": "dev.example.com"
            }
        },
        "headers": {
            "Expires": [
                "Fri, 07 Jul 2023 15:51:14 GMT"
            ],
            "X-Real-Size": [
                "2659699"
            ],
            "Pragma": [
                "public"
            ],
            "Content-Length": [
                "2659699"
            ],
            "Content-Type": [
                "video/mp4"
            ],
            "Last-Modified": [
                "Fri, 13 Oct 2017 00:31:34 GMT"
            ],
            "Cache-Control": [
                "public, max-age=1694361074"
            ],
            "Content-Disposition": [
                "inline; filename=\"3.mp4\""
            ],
            "Accept-Ranges": [
                "bytes"
            ]
        },
        "status": 200
    }
]
```

# Correct behavior

Issuing this request with the header `Accept-Encoding` set to `None` the expected `Accept-Ranges` shows up

```bash
(user@localhost) ~ http -h 'https://dev.example.com/api/browse/download/media/videos/3.mp4' Authorization:"Bearer testapikey" Accept-Encoding: None

# Request headers

GET /api/browse/download/media/videos/3.mp4 HTTP/1.1
Accept: */*
Accept-Encoding: None
Authorization: Bearer testapikey
Connection: keep-alive
Host: dev.example.com
User-Agent: HTTPie/2.6.0

# Response Headers

HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: public, max-age=1694361125
Content-Disposition: inline; filename="3.mp4"
Content-Length: 2659699
Content-Type: video/mp4
Date: Sat, 10 Sep 2022 15:52:05 GMT
Expires: Fri, 07 Jul 2023 15:52:05 GMT
Last-Modified: Fri, 13 Oct 2017 00:31:34 GMT
Pragma: public
Server: Caddy
X-Real-Size: 2659699
X-Request-Id: XAH4-Cyc4F2EhdYRTdVeS
```
## Caddy logs

```json
[
    {
        "level": "debug",
        "ts": 1662825125.099057,
        "logger": "http.handlers.rewrite",
        "msg": "rewrote request",
        "request": {
            "remote_ip": "10.0.0.2",
            "remote_port": "2335",
            "proto": "HTTP/1.1",
            "method": "GET",
            "host": "dev.example.com",
            "uri": "/api/browse/download/media/videos/3.mp4",
            "headers": {
                "Accept-Encoding": [
                    "None"
                ],
                "Accept": [
                    "*/*"
                ],
                "Connection": [
                    "keep-alive"
                ],
                "Authorization": [],
                "User-Agent": [
                    "HTTPie/2.6.0"
                ]
            },
            "tls": {
                "resumed": false,
                "version": 772,
                "cipher_suite": 4865,
                "proto": "http/1.1",
                "server_name": "dev.example.com"
            }
        },
        "method": "GET",
        "uri": "index.php"
    },
    {
        "level": "debug",
        "ts": 1662825125.0992594,
        "logger": "http.reverse_proxy.transport.fastcgi",
        "msg": "roundtrip",
        "request": {
            "remote_ip": "10.0.0.2",
            "remote_port": "2335",
            "proto": "HTTP/1.1",
            "method": "GET",
            "host": "dev.example.com",
            "uri": "index.php",
            "headers": {
                "User-Agent": [
                    "HTTPie/2.6.0"
                ],
                "X-Forwarded-Proto": [
                    "https"
                ],
                "X-Forwarded-Host": [
                    "dev.example.com"
                ],
                "Accept-Encoding": [
                    "None"
                ],
                "Accept": [
                    "*/*"
                ],
                "X-Forwarded-For": [
                    "10.0.0.2"
                ],
                "Authorization": []
            },
            "tls": {
                "resumed": false,
                "version": 772,
                "cipher_suite": 4865,
                "proto": "http/1.1",
                "server_name": "dev.example.com"
            }
        },
        "dial": "php_fpm:9000",
        "env": {
            "PATH_INFO": "",
            "REMOTE_ADDR": "10.0.0.2",
            "REMOTE_PORT": "2335",
            "X_REQUEST_ID": "XAH4-Cyc4F2EhdYRTdVeS",
            "HTTP_X_FORWARDED_HOST": "dev.example.com",
            "CONTENT_LENGTH": "",
            "SERVER_SOFTWARE": "Caddy/v2.5.2",
            "HTTPS": "on",
            "HTTP_X_FORWARDED_PROTO": "https",
            "REQUEST_SCHEME": "https",
            "DOCUMENT_URI": "index.php",
            "HTTP_HOST": "dev.example.com",
            "SCRIPT_NAME": "/index.php",
            "SERVER_PORT": "443",
            "HTTP_AUTHORIZATION": "Bearer testapikey",
            "AUTH_TYPE": "",
            "SERVER_PROTOCOL": "HTTP/1.1",
            "REQUEST_URI": "/api/browse/download/media/videos/3.mp4",
            "SCRIPT_FILENAME": "/opt/app/public/index.php",
            "HTTP_ACCEPT_ENCODING": "None",
            "REMOTE_HOST": "10.0.0.2",
            "SERVER_NAME": "dev.example.com",
            "SSL_PROTOCOL": "TLSv1.3",
            "SSL_CIPHER": "TLS_AES_128_GCM_SHA256",
            "GATEWAY_INTERFACE": "CGI/1.1",
            "REMOTE_IDENT": "",
            "CONTENT_TYPE": "",
            "REQUEST_METHOD": "GET",
            "DOCUMENT_ROOT": "/opt/app/public/",
            "HTTP_ACCEPT": "*/*",
            "HTTP_USER_AGENT": "HTTPie/2.6.0",
            "QUERY_STRING": "",
            "REMOTE_USER": "",
            "HTTP_X_FORWARDED_FOR": "10.0.0.2"
        }
    },
    {
        "level": "debug",
        "ts": 1662825125.1613717,
        "logger": "http.handlers.reverse_proxy",
        "msg": "upstream roundtrip",
        "upstream": "php_fpm:9000",
        "duration": 0.062165963,
        "request": {
            "remote_ip": "10.0.0.2",
            "remote_port": "2335",
            "proto": "HTTP/1.1",
            "method": "GET",
            "host": "dev.example.com",
            "uri": "index.php",
            "headers": {
                "X-Forwarded-Host": [
                    "dev.example.com"
                ],
                "Accept-Encoding": [
                    "None"
                ],
                "Accept": [
                    "*/*"
                ],
                "X-Forwarded-For": [
                    "10.0.0.2"
                ],
                "Authorization": [],
                "User-Agent": [
                    "HTTPie/2.6.0"
                ],
                "X-Forwarded-Proto": [
                    "https"
                ]
            },
            "tls": {
                "resumed": false,
                "version": 772,
                "cipher_suite": 4865,
                "proto": "http/1.1",
                "server_name": "dev.example.com"
            }
        },
        "headers": {
            "Cache-Control": [
                "public, max-age=1694361125"
            ],
            "Accept-Ranges": [
                "bytes"
            ],
            "Last-Modified": [
                "Fri, 13 Oct 2017 00:31:34 GMT"
            ],
            "Pragma": [
                "public"
            ],
            "X-Real-Size": [
                "2659699"
            ],
            "Expires": [
                "Fri, 07 Jul 2023 15:52:05 GMT"
            ],
            "Content-Length": [
                "2659699"
            ],
            "Content-Type": [
                "video/mp4"
            ],
            "Content-Disposition": [
                "inline; filename=\"3.mp4\""
            ]
        },
        "status": 200
    }
]
```

As you can see from both examples, `Content-Length` and `X-Real-Size` are exactly the same, which means there are no encoding happening, however Caddy still removes `Accept-Ranges` header even when no encoding is happening. leading to some clients assuming no resume support for the download. As expected removing the directive `encode` directive fixes the problem.

## Caddy config

```
https://dev.example.com {
	request_id
	header * X-Request-Id "{http.request_id}"
	encode gzip zstd

	route {
		root * /opt/app/public

		php_fastcgi php_fpm:9000 {
			env X_REQUEST_ID "{http.request_id}"
		}

		file_server
	}
}
```

**Comment by mholt** [comment] 2022-09-11 02:44
Thanks for the detailed report.

We delete the Accept-Encoding header whenever we initialize the encoding responseWriter:

https://github.com/caddyserver/caddy/blob/076a8b8095ad4e1a8f2ad770ce375612dcaf0288/modules/caddyhttp/encode/encode.go#L314

It's been years since I looked at this code, but apparently we do not always actually encode the response even if the responseWriter is initialized. :monocle_face: 

I can look at this next week; but this should hopefully give you a head start if you want to take a stab at a patch! It will be faster that way.

**Comment by mholt** [comment] 2022-09-11 03:28
PS. Did you know Caddy generates a request ID for you already? `{http.request.uuid}` -- no plugin needed.

**Comment by mholt** [comment] 2022-09-11 03:43
Is this something we can reproduce without the PHP backend? I'm trying to reproduce it with an HTML file using the `file_server` and it seems to work fine.

Also why is the response not compressed? Shouldn't it be?

**Comment by ArabCoders** [comment] 2022-09-11 09:38
Hi sorry about the delay in response i am away from my PC.

Yeah i i didn't know that the request uuid was bundled i think when i was migrating to caddy that was not available? not sure

About the bug, I think you need some sort of backend that add `Accept-Ranges: bytes` header and the request itself need to have `Accept-Encoding: gzip, deflate` to trigger the bug. Not sure if file_server directive triggers the bug but `php_fastcgi` does

```
$ caddy version
v2.5.2 h1:eCJdLyEyAGzuQTa5Mh3gETnYWDClo1LjtQm2q9RNZrs=
```

**Comment by ArabCoders** [comment] 2022-09-11 15:48
Hi sorry about being late, here is a working example of the bug even with just using `file_server`

# Caddy config example

```
{
	admin 127.0.0.1:20199
	debug
}

:7885 {
	root * ./assets
	log
	encode gzip zstd
	header Accept-Ranges Bytes
	file_server
}
```

# Bugged response.

```bash

$ http http://127.0.0.1:7885/test.txt -v

# Request Headers

GET /test.txt HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: 127.0.0.1:7885
User-Agent: HTTPie/2.6.0


# Response Headers

HTTP/1.1 200 OK
Content-Length: 8
Content-Type: text/plain; charset=utf-8
Date: Sun, 11 Sep 2022 15:41:20 GMT
Etag: "rfqliz8"
Last-Modified: Thu, 28 Jul 2022 15:25:47 GMT
Server: Caddy

i am foo
```

# Caddy Logs

```
2022/09/11 15:41:20.070 DEBUG   http.handlers.file_server       sanitized path join     {"site_root": "./assets", "request_path": "/test.txt", "result": "assets/test.txt"}
2022/09/11 15:41:20.071 DEBUG   http.handlers.file_server       opening file    {"filename": "assets/test.txt"}
2022/09/11 15:41:20.071 INFO    http.log.access handled request {"request": {"remote_ip": "127.0.0.1", "remote_port": "39604", "proto": "HTTP/1.1", "method": "GET", "host": "127.0.0.1:7885", "uri": "/test.txt", "headers": {"User-Agent": ["HTTPie/2.6.0"], "Accept-Encoding": ["gzip, deflate"], "Accept": ["*/*"], "Connection": ["keep-alive"]}}, "user_id": "", "duration": 0.000197791, "size": 8, "status": 200, "resp_headers": {"Server": ["Caddy"], "Etag": ["\"rfqliz8\""], "Content-Type": ["text/plain; charset=utf-8"], "Last-Modified": ["Thu, 28 Jul 2022 15:25:47 GMT"], "Content-Length": ["8"]}}
```

# None Bugged response.

As expected sending `Accept-Encoding: None` make the header appears

```bash
$ http http://127.0.0.1:7885/test.txt Accept-Encoding:None -v

#Request Headers

GET /test.txt HTTP/1.1
Accept: */*
Accept-Encoding: None
Connection: keep-alive
Host: 127.0.0.1:7885
User-Agent: HTTPie/2.6.0


# Response Headers

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 8
Content-Type: text/plain; charset=utf-8
Date: Sun, 11 Sep 2022 15:42:05 GMT
Etag: "rfqliz8"
Last-Modified: Thu, 28 Jul 2022 15:25:47 GMT
Server: Caddy

i am foo
```

# Caddy Logs

```
2022/09/11 15:42:05.782 DEBUG   http.handlers.file_server       sanitized path join     {"site_root": "./assets", "request_path": "/test.txt", "result": "assets/test.txt"}
2022/09/11 15:42:05.782 DEBUG   http.handlers.file_server       opening file    {"filename": "assets/test.txt"}
2022/09/11 15:42:05.783 INFO    http.log.access handled request {"request": {"remote_ip": "127.0.0.1", "remote_port": "47212", "proto": "HTTP/1.1", "method": "GET", "host": "127.0.0.1:7885", "uri": "/test.txt", "headers": {"User-Agent": ["HTTPie/2.6.0"], "Accept-Encoding": ["None"], "Accept": ["*/*"], "Connection": ["keep-alive"]}}, "user_id": "", "duration": 0.000168387, "size": 8, "status": 200, "resp_headers": {"Content-Type": ["text/plain; charset=utf-8"], "Last-Modified": ["Thu, 28 Jul 2022 15:25:47 GMT"], "Content-Length": ["8"], "Server": ["Caddy"], "Accept-Ranges": ["bytes"], "Etag": ["\"rfqliz8\""]}}
```

The problem appears deeper then i thought, it seems even `text/*` mime type aren't being compressed. as indicated by the responses, i didn't notice this for long time probably because the majority of my sites are behind CDN which does it.

**Comment by mholt** [comment] 2022-09-11 19:18
Content under 512 bytes won't be compressed because of diminishing returns. Compressed short content can be longer and less efficient. Can you please try with a large payload?

**Comment by mholt** [comment] 2022-09-11 19:31
Oh, and yeah, I don't think video content gets compressed. Look at the docs for the default value of the response matcher, which doesn't include video content types.

https://caddyserver.com/docs/caddyfile/directives/encode

**Comment by ArabCoders** [comment] 2022-09-11 19:31
> Content under 512 bytes won't be compressed because of diminishing returns. Compressed short content can be longer and less efficient. Can you please try with a large payload?

@mholt It seems encode module broken for me size does not influence the encoding at all it seems. i tried small to large 1gb files the exact problem on all responses.

```bash
$ http http://127.0.0.1:7886/json.txt --headers 

# request headers

GET /json.txt HTTP/1.1
User-Agent: HTTPie/2.6.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Host: 127.0.0.1:7886

# response headers

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 18678895
Content-Type: text/plain; charset=utf-8
Etag: "ri28ekb4cq7"
Last-Modified: Sun, 11 Sep 2022 19:20:44 GMT
Server: Caddy
X-Request-Id: 153a00bc-e44c-4e1c-8b74-244c0f4471e5
Date: Sun, 11 Sep 2022 19:25:44 GMT
```

# Caddy logs

```bash

2022/09/11 19:25:44.307 DEBUG   http.handlers.file_server       sanitized path join    {"site_root": "./assets", "request_path": "/json.txt", "result": "assets/json.txt"}
2022/09/11 19:25:44.307 DEBUG   http.handlers.file_server       opening file   {"filename": "assets/json.txt"}
2022/09/11 19:25:51.541 INFO    http.log.access handled request {"request": {"remote_ip": "127.0.0.1", "remote_port": "51570", "proto": "HTTP/1.1", "method": "GET", "host": "127.0.0.1:7886", "uri": "/json.txt", "headers": {"User-Agent": ["HTTPie/2.6.0"], "Accept-Encoding": ["gzip, deflate"], "Accept": ["*/*"], "Connection": ["keep-alive"]}}, "user_id": "", "duration": 7.23385354, "size": 14712832, "status": 200, "resp_headers": {"Etag": ["\"ri28ekb4cq7\""], "Content-Type": ["text/plain; charset=utf-8"], "Last-Modified": ["Sun, 11 Sep 2022 19:20:44 GMT"], "Accept-Ranges": ["bytes"], "Content-Length": ["18678895"], "Server": ["Caddy"], "X-Request-Id": ["153a00bc-e44c-4e1c-8b74-244c0f4471e5"]}}
```

**Comment by mholt** [comment] 2022-09-11 19:47
Interesting that the size reported in the logs is so different from the Content-Length. 🧐

Is it sending gzipped content without the Content-Encoding header?

But notice that the Accept-Ranges header is back.

**Comment by ArabCoders** [comment] 2022-09-11 19:52
> Interesting that the size reported in the logs is so different from the Content-Length. 🧐
> 
> Is it sending gzipped content without the Content-Encoding header?
> 
> But notice that the Accept-Ranges header is back.

Yeah sorry i am on my phone trying to do the tests and i hit the wrong node, i updated the post with the correct information now. The problem it seems the encode module even if the request is not being compressed it still remove the `Accept-Ranges` header

**Comment by ArabCoders** [comment] 2022-09-12 14:59
@mholt After reading [encode.go](https://github.com/caddyserver/caddy/blob/076a8b8095ad4e1a8f2ad770ce375612dcaf0288/modules/caddyhttp/encode/encode.go#L314) i think this line should be moved to to be around here](https://github.com/caddyserver/caddy/blob/076a8b8095ad4e1a8f2ad770ce375612dcaf0288/modules/caddyhttp/encode/encode.go#L126) if you agree I'll send PR

**Comment by mholt** [comment] 2022-09-12 17:18
That would delete the header even more often than it is now, as there's no guarantee we'll actually encode the response just by opening the writer.

**Comment by ArabCoders** [comment] 2022-09-12 17:20
> That would delete the header even more often than it is now, as there's no guarantee we'll actually encode the response just by opening the writer.

Hmmm, i must be reading the code wrong then, isn't the loop supposed to ONLY run when they are common encoding at 

https://github.com/caddyserver/caddy/blob/076a8b8095ad4e1a8f2ad770ce375612dcaf0288/modules/caddyhttp/encode/encode.go#L122 ?

**Comment by mholt** [comment] 2022-09-12 17:29
No, that just reads the Accept-Encoding header, i.e. doesn't say anything about whether the response is encodable.

After trying a few more times with your config and configuring requests and responses to be the same as what you have (i.e. video content, larger than 512 bytes, similar request and response headers) I cannot reproduce the behavior you're describing:

```
>$ curl -v --compressed "http://localhost:8081/video.mp4"
*   Trying 127.0.0.1:8081...
* Connected to localhost (127.0.0.1) port 8081 (#0)
> GET /video.mp4 HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.81.0
> Accept: */*
> Accept-Encoding: deflate, gzip, br, zstd
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 38939
< Content-Type: video/mp4
< Etag: "rhtl5xu1n"
< Last-Modified: Wed, 07 Sep 2022 03:17:57 GMT
< Server: Caddy
< Date: Mon, 12 Sep 2022 17:20:24 GMT
```

As you can see, the Accept-Ranges header is present.

I'd be curious what results you get when using `curl -v --compressed`. Do you get the same result?

Since I've been unable to reproduce this after multiple varied attempts, I'm going to close the issue, but feel free to continue discussion if there's more information to add. If this is later demonstrated to be a bug, we can reopen it.

**Comment by ArabCoders** [comment] 2022-09-12 17:35
> curl -v --compressed

I am honestly not why the bug is not happening to you, i used the same command as you 

```bash
$ curl -v --compressed http://localhost:7885/test.mkv
*   Trying 127.0.0.1:7885...
* Connected to localhost (127.0.0.1) port 7885 (#0)
> GET /test.mkv HTTP/1.1
> Host: localhost:7885
> User-Agent: curl/7.81.0
> Accept: */*
> Accept-Encoding: deflate, gzip, br, zstd
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 356519749
< Content-Type: video/x-matroska
< Etag: "ri2a6i5w9ged"
< Last-Modified: Sun, 11 Sep 2022 19:59:06 GMT
< Server: Caddy
< Date: Mon, 12 Sep 2022 17:31:52 GMT
<
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
* Failure writing output to destination
* Closing connection 0
```

for what is worth here is the list-module output

```bash
admin.api.load
admin.api.metrics
admin.api.pki
admin.api.reverse_proxy
caddy.adapters.caddyfile
caddy.config_loaders.http
caddy.listeners.http_redirect
caddy.listeners.tls
caddy.logging.encoders.console
caddy.logging.encoders.filter
caddy.logging.encoders.filter.cookie
caddy.logging.encoders.filter.delete
caddy.logging.encoders.filter.hash
caddy.logging.encoders.filter.ip_mask
caddy.logging.encoders.filter.query
caddy.logging.encoders.filter.regexp
caddy.logging.encoders.filter.rename
caddy.logging.encoders.filter.replace
caddy.logging.encoders.json
caddy.logging.writers.discard
caddy.logging.writers.file
caddy.logging.writers.net
caddy.logging.writers.stderr
caddy.logging.writers.stdout
caddy.storage.file_system
http
http.authentication.hashes.bcrypt
http.authentication.hashes.scrypt
http.authentication.providers.http_basic
http.encoders.gzip
http.encoders.zstd
http.handlers.acme_server
http.handlers.authentication
http.handlers.copy_response
http.handlers.copy_response_headers
http.handlers.encode
http.handlers.error
http.handlers.file_server
http.handlers.headers
http.handlers.map
http.handlers.metrics
http.handlers.push
http.handlers.request_body
http.handlers.reverse_proxy
http.handlers.rewrite
http.handlers.static_response
http.handlers.subroute
http.handlers.templates
http.handlers.tracing
http.handlers.vars
http.matchers.expression
http.matchers.file
http.matchers.header
http.matchers.header_regexp
http.matchers.host
http.matchers.method
http.matchers.not
http.matchers.path
http.matchers.path_regexp
http.matchers.protocol
http.matchers.query
http.matchers.remote_ip
http.matchers.vars
http.matchers.vars_regexp
http.precompressed.br
http.precompressed.gzip
http.precompressed.zstd
http.reverse_proxy.selection_policies.cookie
http.reverse_proxy.selection_policies.first
http.reverse_proxy.selection_policies.header
http.reverse_proxy.selection_policies.ip_hash
http.reverse_proxy.selection_policies.least_conn
http.reverse_proxy.selection_policies.random
http.reverse_proxy.selection_policies.random_choose
http.reverse_proxy.selection_policies.round_robin
http.reverse_proxy.selection_policies.uri_hash
http.reverse_proxy.transport.fastcgi
http.reverse_proxy.transport.http
http.reverse_proxy.upstreams.a
http.reverse_proxy.upstreams.srv
pki
tls
tls.certificates.automate
tls.certificates.load_files
tls.certificates.load_folders
tls.certificates.load_pem
tls.certificates.load_storage
tls.client_auth.leaf
tls.get_certificate.http
tls.get_certificate.tailscale
tls.handshake_match.remote_ip
tls.handshake_match.sni
tls.issuance.acme
tls.issuance.internal
tls.issuance.zerossl
tls.stek.distributed
tls.stek.standard

  Standard modules: 97

caddy.logging.encoders.formatted
caddy.logging.encoders.transform
dns.providers.cloudflare
http.handlers.webdav
layer4
layer4.handlers.echo
layer4.handlers.proxy
layer4.handlers.proxy_protocol
layer4.handlers.subroute
layer4.handlers.tee
layer4.handlers.throttle
layer4.handlers.tls
layer4.matchers.http
layer4.matchers.ip
layer4.matchers.proxy_protocol
layer4.matchers.ssh
layer4.matchers.tls
layer4.matchers.xmpp
layer4.proxy.selection_policies.first
layer4.proxy.selection_policies.ip_hash
layer4.proxy.selection_policies.least_conn
layer4.proxy.selection_policies.random
layer4.proxy.selection_policies.random_choose
layer4.proxy.selection_policies.round_robin
tls.handshake_match.alpn

  Non-standard modules: 25

  Unknown modules: 0
```

**Comment by mholt** [comment] 2022-09-12 17:36
Which version of Caddy are you using?

**Comment by ArabCoders** [comment] 2022-09-12 17:37
> Which version of Caddy are you using?
```
$ caddy version
v2.5.2 h1:eCJdLyEyAGzuQTa5Mh3gETnYWDClo1LjtQm2q9RNZrs=
```

**Comment by mholt** [comment] 2022-09-12 17:44
I think your best bet would be to add some debug logs or print statements in the encode module. Put one near the line that removes the header, put others in places that will help you find out why the header is being removed when it shouldn't. Also print the headers as they are _before_ the encode module changes them (but after the response is written).

**Comment by ArabCoders** [comment] 2022-09-12 17:46
> I think your best bet would be to add some debug logs or print statements in the encode module. Put one near the line that removes the header, put others in places that will help you find out why the header is being removed when it shouldn't. Also print the headers as they are _before_ the encode module changes them (but after the response is written).

This probably too much for me, I'll try using the official docker container to see if i can reproduce it and share the exact steps.

**Comment by ArabCoders** [comment] 2022-09-12 18:01
Ok i was able to reproduce it using the official docker container. here are the step I've taken

# Caddy config

```
{
        debug
}

:80 {
        root * /files
        log
        encode gzip zstd
        header Accept-Ranges Bytes
        file_server
}
```

Downloaded [mp4 file](https://user-images.githubusercontent.com/1621552/189723635-a1471099-2259-4293-b02a-4abd6d3af0b3.mp4), saved in to `./files/` path and run the following command

```bash
$ docker run --name caddy --rm -p 7885:80 -v $PWD/files:/files -v $PWD/Caddyfile:/etc/caddy/Caddyfile caddy:alpine
```

once the container is running i used the following command

```bash
$ curl -v --compressed http://localhost:7885/file.mp4
*   Trying 127.0.0.1:7885...
* Connected to localhost (127.0.0.1) port 7885 (#0)
> GET /file.mp4 HTTP/1.1
> Host: localhost:7885
> User-Agent: curl/7.81.0
> Accept: */*
> Accept-Encoding: deflate, gzip, br, zstd
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 3114374
< Content-Type: video/mp4
< Etag: "ri3yzk1ur2e"
< Last-Modified: Mon, 12 Sep 2022 17:52:32 GMT
< Server: Caddy
< Date: Mon, 12 Sep 2022 17:57:06 GMT
<
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
* Failure writing output to destination
* Closing connection 0
```

as you can see the header is missing, if it still not not reproducible for you, then i have to study up on golang building environment :-)

**Comment by ArabCoders** [comment] 2022-09-13 16:36
@mholt i have discovered that the bug does not manifest if you send a `HEAD` request, unless i understood wrong, isn't HEAD request supposed to mimic the `GET` request behavior minus the body part? ref [RFC2616]


[RFC2616]: https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#:~:text=The%20HEAD%20method%20is%20identical,response%20to%20a%20GET%20request.

**Comment by WeidiDeng** [comment] 2022-09-13 23:47
It's a indeed a bug, will be fixed soon.

**Closed** 2022-09-15 22:05 UTC
Labels: bug

**Comment by mholt** [comment] 2022-09-16 01:46
Thank you for the patch, @WeidiDeng !
