### ISSUE TITLE
Importing an empty file in Caddyfile throws an error.

### ISSUE THREAD

**Issue by mkucej** [caddyserver/caddy#5180] opened 2022-10-31 13:00 UTC
### 1a. Operating system and version

```
Ubuntu 22.04 5.15.0-52-generic x86_64 GNU/Linux
```

### 1b. Caddy version

```
Caddy v2.6.2 h1:wKoFIxpmOJLGl3QXoo6PNbYvGW4xLEgo32GPBEjWL8o=
```

### 2a. What happens (briefly explain what is wrong)

Importing an empty file in Caddyfile using `import` throws an error.

### 2b. Why it's a bug (if it's not obvious)

I am not sure if it is intended behavior, but I would expect Caddy to silently ignore the empty file.

### 2c. Log output

```
Oct 31 12:40:09 ubuntu-2gb-ash-1 systemd[1]: Reloading Caddy...
Oct 31 12:40:09 ubuntu-2gb-ash-1 caddy[83086]: {"level":"info","ts":1667220009.0981665,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
Oct 31 12:40:09 ubuntu-2gb-ash-1 caddy[83086]: Error: adapting config using caddyfile: /etc/caddy/Caddyfile:1 - Error during parsing: Could not read tokens while importing /etc/caddy/foo.conf: EOF
Oct 31 12:40:09 ubuntu-2gb-ash-1 systemd[1]: caddy.service: Control process exited, code=exited, status=1/FAILURE
Oct 31 12:40:09 ubuntu-2gb-ash-1 systemd[1]: Reload failed for Caddy.
```

### 2d. Workaround(s)

Add `' '` (whitespace), or `#` to the included configuration file.

### 2e. Relevant links

https://caddyserver.com/docs/caddyfile/directives/import

## 3. Tutorial (minimal steps to reproduce the bug)

Minimal Caddyfile:
```
import foo.conf

:80, :443 {
}
```

Failing foo.conf (0 bytes):
```
```

Passing foo.conf:
```
#
```

**Comment by mholt** [comment] 2022-11-09 05:19
Hmm, this is a tough one (and I swear we've seen this discussed in an issue before, but I can't find it right now), because we don't know whether EOF is a problem or not.

EOF could mean two things, and it's impossible to tell which:

- User is explicitly importing a file, so for the file to be empty, is unexpected, thus an error. (This is the conservative approach which is what we do currently.)
- User may intend for file to be empty and for the import to be a no-op. (But then why is the import there in the first place? This is the cavalier approach which is riskier in that it can hide problems, so we don't do that.)

I think the majority of me feels like this is working as intended. Sometimes if a storage device returns 0 bytes for a file, that means the file or disk is corrupted (or even simpler, that the file was left unintentionally blank) which is a legit problem, especially with an explicit import statement. We've seen this quite a bit with certificate automation.

So, like you, I'm not sure what is intended here, because I'm not sure what the user intended. Do you have a strong use case for an empty file being explicitly imported?

**Comment by mkucej** [comment] 2022-11-25 16:25
> Do you have a strong use case for an empty file being explicitly imported?

Not strong, not really. We encountered the error, when we were creating our conf file structure. We have a Caddyfile that we set up once, and then don't touch it. In it, we import various conf files that are frequently edited by another software to add and remove configurations as needed. These files can be empty, if no configuration is needed. We were surprised that the empty file was not valid. At the end of the day, it is not a big issue, because every conf file will contain comments to provide hints to admins.

> So, like you, I'm not sure what is intended here

The pro is you can catch some rare conditions, where empty file is invalid. I do not think it is Caddy's role to decide whether the file is corrupted. However, I don't know anything about the issue with empty files in certificate automation you mentioned - it might be a reason enough to outweigh all other points.

The con is an unnecessary error. Do not underestimate the amount of errors a Caddy newbie (like us) gets to see.

> we've seen this discussed in an issue before, but I can't find it right now

I could not find it either, so I thought I submit it for posterity. :-)

**Comment by mholt** [comment] 2022-11-29 16:48
I'll think on this and see if we can do something better. Thanks for the feedback!

**Comment by francislavoie** [comment] 2023-01-11 04:40
https://github.com/caddyserver/caddy/issues/5295 Was opened which revived the discussion.

I think what we'll do is change empty files to emit a warning instead of an error, so it will still work but still tell the user their file might be incorrectly empty.

**Comment by francislavoie** [comment] 2023-01-21 17:58
Closed by https://github.com/caddyserver/caddy/pull/5320

**Closed by francislavoie** 2023-01-21 17:58 UTC
Labels: bug :lady_beetle:, good first issue :baby_chick:
