### ISSUE TITLE
2.7.3 Is not release on Dockerhub (Causing Dependency issues with Modules)

### ISSUE THREAD

**Issue by mhmdksh** [caddyserver/caddy#5744] opened 2023-08-14 10:34 UTC
It seems that version 2.7.3 was not release on the official Dockerhub pages causing errors while building modules:

```
#0 5.956 go: added google.golang.org/protobuf v1.31.0
#0 5.961 2023/08/14 10:15:30 [INFO] exec (timeout=-2562047h47m16.854775808s): /usr/local/go/bin/go get -d -v github.com/caddy-dns/cloudflare github.com/caddyserver/caddy/v2@v2.7.2
#0 6.135 go: downloading github.com/caddy-dns/cloudflare v0.0.0-20230807034102-74f004e1c1ab
#0 6.213 go: github.com/caddy-dns/cloudflare@upgrade (v0.0.0-20230807034102-74f004e1c1ab) requires github.com/caddyserver/caddy/v2@v2.7.3, not github.com/caddyserver/caddy/v2@v2.7.2
#0 6.215 2023/08/14 10:15:30 [FATAL] exit status 1
------
failed to solve: process "/bin/sh -c xcaddy build     --with github.com/caddy-dns/cloudflare" did not complete successfully: exit code: 1
```

**Comment by mohammed90** [comment] 2023-08-14 11:11
Duplicate of caddyserver/caddy-docker#307. The publish to Docker Hub requires a manual step on Docker end. For you, you can resolve it by explicitly telling xcaddy the version to build as such:
```
xcaddy build  v2.7.3   --with github.com/caddy-dns/cloudflare
```

**Closed by mohammed90** 2023-08-14 11:11 UTC
