### ISSUE TITLE
Allow creating objects nested in empty config in configuration

### ISSUE THREAD

**Issue by RX14** [caddyserver/caddy#3501] opened 2020-06-16 15:00 UTC
If you POST a new complete http server configuration to `/config/apps/http/servers/foo`, but the configuration is empty such that no other server configurations exist, then the configuration fails with "invalid traversal path at: config/apps/http".

I don't think that the state of other servers should affect this, and the only workarounds I can think of are to maintain a dummy server with no listeners just to keep the "apps/http/servers" object existing, or to generate the entire caddy config at once (which isn't suitable for my usecase where only a single server is machine-managed). So it'd be nice to have this feature to avoid what I think are some pretty ugly workarounds.

**Comment by mholt** [comment] 2020-06-16 15:06
@RX14 Hmm, yeah, good question -- the problem is that Caddy doesn't know what the missing structures are. In other words, if your POST consists of:

```
{
	"listen": [":80"]
}
```

there's no way for Caddy to know that the surrounding structure needs to be:

```
{
	"apps": {
		"http": {
			"servers": {
				...
			}
		}
	}
}
```

because the config is modular and extensible. Caddy only knows the structure of the top-level object: https://caddyserver.com/docs/json/

In your case, just do `POST /config/` with the whole body (sans servers) and then it should be easy to add a server after that.

(Closing, but feel free to continue discussion!)

**Closed by mholt** 2020-06-16 15:06 UTC

**Comment by RX14** [comment] 2020-06-16 16:37
It's certainly really quite ugly having to add something like this to the docker container entrypoint:
```sh
(
    while ! curl --fail --silent http://localhost:2019/config/ > /dev/null; do
          sleep 1
    done

    curl --silent http://localhost:2019/config/apps -d '{"http": {"servers": {}}}' -H 'Content-Type: application/json'
) &
```

I'm not sure I have any stronger arguments for why this should be possible, as long as a technical solution can be found. I guess it's not unacceptable, in that there's workarounds, but that configuring caddy like this doesn't work by default is at least surprising to me.

Perhaps one solution is to tell the structure from the URL? If it's `/config/apps/http` then it's `{"apps": {"http": POST_BODY}}`, if it's `/config/admin/origins/0` then it's `{"admin": {"origins": [POST_BODY]}}`.

**Comment by mholt** [comment] 2020-06-16 19:51
> but that configuring caddy like this doesn't work by default is at least surprising to me.

Can you be more specific here? By "default", Caddy's config is a blank slate. What do you expect it to be? (Anything that's not a blank slate needs a way to be "turned off" which is usually trickier and less intuitive. For example, in v1 it served static files by default, but there was no way to disable that, making it frustrating and even risky.)

> Perhaps one solution is to tell the structure from the URL? If it's /config/apps/http then it's {"apps": {"http": POST_BODY}}, if it's /config/admin/origins/0 then it's {"admin": {"origins": [POST_BODY]}}.

What if it's `/config/foo/3/bar` -- is `3` an array or an object? It can be both. If it's an array, what do we do for the first two elements?

What if it's a bad path, i.e. `/config/apps/asdflkjasdflkjsdlkfj/sdflkjsdflkjsdlfkjsdlfkjsdlkfj` - obviously this is contrived, but the point is what if it's a path that should never be allowed to exist in the first place?

**Comment by RX14** [comment] 2020-06-16 20:20
> Can you be more specific here? By "default", Caddy's config is a blank slate. What do you expect it to be?

I don't expect the default config to be different at all, I just expect the API to work slightly differently.



> What if it's `/config/foo/3/bar` -- is `3` an array or an object? It can be both. If it's an array, what do we do for the first two elements?

It could be! But personally I think a heuristic is better than nothing here.



> What if it's a bad path, i.e. `/config/apps/asdflkjasdflkjsdlkfj/sdflkjsdflkjsdlfkjsdlfkjsdlkfj` - obviously this is contrived, but the point is what if it's a path that should never be allowed to exist in the first place?

The same as if you POSTed `{"apps": {"asdflkjasdflkjsdlkfj": {"sdflkjsdflkjsdlfkjsdlfkjsdlkfj": ...}}}` to `/load` I guess. There are already mechanisms in place to weed out bad configuration, no?

**Comment by mholt** [comment] 2020-06-16 22:03
> I just expectex the API to work slightly differently. And I still think it'd be nice if it worked that way.

By "work slightly differently" are you referring to filling in the missing properties so that the path becomes valid?

I'm open to seeing if this can work, but it has to work reliably 100% of the time. So, again, open to proposals here.
