### ISSUE TITLE
Building caddy (using xcaddy) with main branch throws an error

### ISSUE THREAD

**Issue by r3g-5z** [caddyserver/caddy#5301] opened 2023-01-12 23:09 UTC
Commit that seems to cause this is 798c4a3ba48b55e85867780ed399dc084c15b322 as that's when google/pprof was added

`panic: internal error: can't find reason for requirement on github.com/google/pprof@v0.0.0-20210407192527-94a9f03dee38`

Go version: `go version go1.19.4 linux/amd64` (Fedora 37) and `go version go1.19.5 linux/amd64` (Arch Linux)
Error happens on both distros

```
2023/01/12 22:07:54 [INFO] Temporary folder: /tmp/buildenv_2023-01-12-2207.4152728799
2023/01/12 22:07:54 [INFO] Writing main module: /tmp/buildenv_2023-01-12-2207.4152728799/main.go
package main

import (
        caddycmd "github.com/caddyserver/caddy/v2/cmd"

        // plug in Caddy modules here
        _ "github.com/caddyserver/caddy/v2/modules/standard"
        _ "github.com/Odyssey346/ListenCaddy"
)

func main() {
        caddycmd.Main()
}
2023/01/12 22:07:54 [INFO] Initializing Go module
2023/01/12 22:07:54 [INFO] exec (timeout=10s): /usr/bin/go mod init caddy
go: creating new go.mod: module caddy
go: to add module requirements and sums:
        go mod tidy
2023/01/12 22:07:54 [INFO] Pinning versions
2023/01/12 22:07:54 [INFO] exec (timeout=0s): /usr/bin/go get -d -v -ldflags -w -s -race -strictdups 2 -linkshared -aslr -buildmode=pie -linkmode=external -trimpath github.com/caddyserver/caddy/v2@master
go: downloading github.com/caddyserver/caddy/v2 v2.6.3-0.20230110050823-223cbe3d0b50
go: downloading github.com/caddyserver/caddy v1.0.6-0.20200303163406-891446d06340
go: downloading github.com/lucas-clemente/quic-go v0.31.0
go: downloading golang.org/x/sys v0.1.1-0.20221102194838-fc697a31fa06
go: downloading golang.org/x/term v0.1.0
go: downloading github.com/klauspost/cpuid/v2 v2.1.2
go: downloading golang.org/x/crypto v0.0.0-20221005025214-4161e89ecf1b
go: downloading golang.org/x/net v0.1.0
go: downloading github.com/onsi/ginkgo/v2 v2.2.0
go: downloading github.com/marten-seemann/qpack v0.3.0
go: downloading github.com/prometheus/common v0.33.0
go: downloading google.golang.org/protobuf v1.28.1
go: downloading golang.org/x/tools v0.1.12
go: downloading golang.org/x/text v0.4.0
go: downloading golang.org/x/mod v0.6.0-dev.0.20220419223038-86c51ed26bb4
go: downloading github.com/google/pprof v0.0.0-20210407192527-94a9f03dee38
go: added github.com/beorn7/perks v1.0.1
go: added github.com/caddyserver/caddy/v2 v2.6.3-0.20230110050823-223cbe3d0b50
go: added github.com/caddyserver/certmagic v0.17.2
go: added github.com/cespare/xxhash/v2 v2.1.2
go: added github.com/go-task/slim-sprig v0.0.0-20210107165309-348f09dbbbc0
go: added github.com/golang/mock v1.6.0
go: added github.com/golang/protobuf v1.5.2
go: added github.com/google/pprof v0.0.0-20210407192527-94a9f03dee38
go: added github.com/google/uuid v1.3.0
go: added github.com/klauspost/cpuid/v2 v2.1.2
go: added github.com/libdns/libdns v0.2.1
go: added github.com/lucas-clemente/quic-go v0.31.0
go: added github.com/marten-seemann/qpack v0.3.0
go: added github.com/marten-seemann/qtls-go1-18 v0.1.3
go: added github.com/marten-seemann/qtls-go1-19 v0.1.1
go: added github.com/matttproud/golang_protobuf_extensions v1.0.1
go: added github.com/mholt/acmez v1.0.4
go: added github.com/miekg/dns v1.1.50
go: added github.com/onsi/ginkgo/v2 v2.2.0
go: added github.com/prometheus/client_golang v1.12.2
go: added github.com/prometheus/client_model v0.2.0
go: added github.com/prometheus/common v0.33.0
go: added github.com/prometheus/procfs v0.7.3
go: added go.uber.org/atomic v1.9.0
go: added go.uber.org/multierr v1.6.0
go: added go.uber.org/zap v1.23.0
go: added golang.org/x/crypto v0.0.0-20221005025214-4161e89ecf1b
go: added golang.org/x/exp v0.0.0-20220722155223-a9213eeb770e
go: added golang.org/x/mod v0.6.0-dev.0.20220419223038-86c51ed26bb4
go: added golang.org/x/net v0.1.0
go: added golang.org/x/sys v0.1.1-0.20221102194838-fc697a31fa06
go: added golang.org/x/term v0.1.0
go: added golang.org/x/text v0.4.0
go: added golang.org/x/tools v0.1.12
go: added google.golang.org/protobuf v1.28.1
2023/01/12 22:08:30 [INFO] exec (timeout=0s): /usr/bin/go get -d -v -ldflags -w -s -race -strictdups 2 -linkshared -aslr -buildmode=pie -linkmode=external -trimpath github.com/Odyssey346/ListenCaddy github.com/caddyserver/caddy/v2@master
go: downloading google.golang.org/genproto v0.0.0-20221027153422-115e99e71e1c
go: downloading github.com/smallstep/certificates v0.23.0
go: downloading go.step.sm/crypto v0.23.1
go: downloading github.com/spf13/cobra v1.6.0
go: downloading github.com/smallstep/nosql v0.5.0
go: downloading go.step.sm/cli-utils v0.7.5
go: downloading go.step.sm/linkedca v0.19.0
go: downloading google.golang.org/grpc v1.50.1
go: downloading github.com/slackhq/nebula v1.6.1
go: downloading github.com/inconshreveable/mousetrap v1.0.1
go: downloading github.com/urfave/cli v1.22.10
go: downloading filippo.io/edwards25519 v1.0.0
go: downloading github.com/jackc/pgx/v4 v4.17.2
go: downloading github.com/rs/xid v1.4.0
go: downloading github.com/sirupsen/logrus v1.9.0
go: downloading github.com/go-logfmt/logfmt v0.5.1
go: downloading github.com/dgraph-io/ristretto v0.1.0
go: downloading github.com/jackc/pgconn v1.13.0
go: downloading github.com/jackc/pgproto3/v2 v2.3.1
go: downloading github.com/jackc/pgtype v1.12.0
go: downloading github.com/golang/glog v1.0.0
panic: internal error: can't find reason for requirement on github.com/google/pprof@v0.0.0-20210407192527-94a9f03dee38

goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0xc000260648?, 0xc0004fcf90?}, {0xc0000366f0?, 0xc0002893b8?}})
        /usr/lib/go/src/cmd/go/internal/modget/get.go:1760 +0x114
cmd/go/internal/modget.(*resolver).updateBuildList(0xc000150100, {0xb2e7b0, 0xc00002a0a8}, {0x0, 0x0, 0x0})
        /usr/lib/go/src/cmd/go/internal/modget/get.go:1765 +0x597
cmd/go/internal/modget.(*resolver).applyUpgrades(0xc000150100, {0xb2e7b0, 0xc00002a0a8}, {0x0?, 0x2?, 0x472485?})
        /usr/lib/go/src/cmd/go/internal/modget/get.go:1312 +0x105
cmd/go/internal/modget.runGet({0xb2e7b0, 0xc00002a0a8}, 0xc000028498?, {0xc000024100, 0x2, 0x2})
        /usr/lib/go/src/cmd/go/internal/modget/get.go:351 +0x45e
main.invoke(0xe28fe0, {0xc0000240a0, 0x8, 0x8})
        /usr/lib/go/src/cmd/go/main.go:225 +0x34e
main.main()
        /usr/lib/go/src/cmd/go/main.go:179 +0x7d1
2023/01/12 22:08:43 [FATAL] exit status 2
```

**Comment by francislavoie** [comment] 2023-01-12 23:33
Weird. It works in CI for us, obviously.

Apparently there's some issues with this upstream https://github.com/golang/go/issues/56494

**Comment by r3g-5z** [comment] 2023-01-12 23:42
Definitely seems related :(

Was able to build with 817470dd66edb22015651971e39f8ef183d7bf9d at least.

**Comment by mholt** [comment] 2023-01-14 18:03
That's weird... I am not able to see that behavior either...

The panic is definitely coming from within `go get`. I'm going to close this since I'm not sure there's anything actionable for us to do, but feel free to continue discussion if needed.

**Closed by mholt** 2023-01-14 18:03 UTC
Labels: upstream :arrow_up:

**Comment by r3g-5z** [comment] 2023-01-14 18:25
No worries, I wasn't aware this is an upstream bug. Hope this gets solved soon. I even tried Fedora Rawhide but still no luck :(

**Comment by onodera-punpun** [comment] 2023-02-09 21:38
Running into the same issue with `xcaddy build v2.6.3 --with github.com/awoodbeck/caddy-validate-github`

**Comment by mholt** [comment] 2023-02-09 21:48
I get the error with that command too, @onodera-punpun -- unfortunately, this is [an upstream issue in the `go` command](https://github.com/golang/go/issues/56494), and I don't know that there's anything we can do about it. There are workarounds described in https://github.com/golang/go/issues/56494.

Based on user reports above, it seems like the order of dependencies in go.mod matters (which it shouldn't), and I wonder if the dependencies of the plugins (i.e. their go.mod files) matters; like maybe if they're targeting older versions of Caddy or even Go. I dunno.

**Comment by francislavoie** [comment] 2023-02-10 01:42
I did some investigating, that I outlined here https://github.com/golang/go/issues/56494#issuecomment-1425022660. I have no solution right now :grimacing:

**Comment by francislavoie** [comment] 2023-02-10 08:25
@excid3 @onodera-punpun FYI I've figured out that the issue can be fixed by the plugins bumping their Caddy dependency in their `go.mod` to Caddy v2.6.3 (i.e. latest right now) and running `go mod tidy`. That way, the plugins will sync its dependencies with Caddy's, and it should resolve the build issues. You'll have to reach out to the relevant plugin authors to get them to do so.

This problem really shouldn't have happened. Go's module system is still proving to not be quite robust enough. We keep running into little issues like this and it feels like there's rarely much we can do.

**Comment by excid3** [comment] 2023-02-10 13:51
Very interesting. Thanks for looking into this @francislavoie. 👍 

Are the caddy-dns modules updated?

**Comment by mholt** [comment] 2023-02-10 14:47
@excid3 The caddy-dns modules are independently maintained.

It's not clear to me which plugins need updating yet. For example, `xcaddy build --with github.com/mholt/caddy-ratelimit` works fine, even though that plugin doesn't target v2.6.3.

**Comment by mario-moreira** [comment] 2023-02-10 15:45
I have the same problem. I'm building caddy with this docker file:

```
FROM caddy:builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/godaddy

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

And I get the same error. This should be easy to reproduce. 

Is there any workaround I can do to keep using godaddy?

**Comment by mholt** [comment] 2023-02-10 15:52
@mario-moreira This is very convoluted but I was able to get your build to work with:

```
xcaddy build --with github.com/caddy-dns/godaddy --with github.com/caddyserver/caddy/v2=github.com/caddyserver/caddy/v2@v2.6.3
```

Do not ask me why. :man_shrugging:

**Comment by mario-moreira** [comment] 2023-02-10 15:59
@mholt yes, it worked. Problem solved for the moment. Thank you.

**Comment by mattvb91** [comment] 2023-03-10 10:26
> @mario-moreira This is very convoluted but I was able to get your build to work with:
> 
> ```
> xcaddy build \
>     --with github.com/caddy-dns/godaddy \
>     --with github.com/caddyserver/caddy/v2=github.com/caddyserver/caddy/v2@v2.6.4
> ```
> 
> Do not ask me why. man_shrugging

@mholt this was working fine until today. Can no longer build it again even with your fix:

```
#0 30.13 panic: internal error: can't find reason for requirement on github.com/google/pprof@v0.0.0-20210407192527-94a9f03dee38

```

**Comment by mholt** [comment] 2023-03-10 17:14
We are hoping the Go team fixes the bug ASAP.
