### ISSUE TITLE
Caddy doesn't strip gzip header

### ISSUE THREAD

**Issue by deepbluev7** [caddyserver/caddy#3546] opened 2020-07-03 23:39 UTC
When you are using caddy as a reverse proxy for a service, that serves gzip compressed content (in this case a matrix-synapse server with compressed: true on the specific listener) Caddy decompresses the content automatically and then serves it uncompressed. That in itself wouldn't be considered a bug in my opinion, however it does serve the `Content-Encoding: gzip` header without modifying it. Because of this the encoding header doesn't match the actual content. In my opinion it should either not decompress the body or remove the header.

The affected server seems to be a Caddy v1 server. Sadly the affected user didn't specify the exact version. I've worked around the issue in my client now, which is probably good anyway, but it would probably still be good, if Caddy v2 is still affected, if this behaviour could be adapted in some way, that matches the usual expectations better.

Thank you!

---

### 1a. Operating system and version

```
uname -a
Linux renner.dev 5.3.0-62-generic #56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
caddy -version 
Caddy v1.0.0 (h1:KI6RPGih2GFzWRPG8s9clKK28Ns4ZlVMKR/v7mxq6+c=)
```

### 1c. Go version (if building Caddy from source; run `go version`)

```
no idea, not built from source
```

### 2a. What happens (briefly explain what is wrong)

When caddy proxies gzipped requests, it decompresses them, but doesn't remove the gzip header (`Content-Encoding: gzip`).

### 2b. Why it's a bug (if it's not obvious)

The gzip header makes applications think they need to decompress the response, but it isn't compressed, so the decompression fails.

### 2c. Log output

```
none
```

### 2d. Workaround(s)

Let the application ignore the header, if decompression fails

## 3. Tutorial (minimal steps to reproduce the bug)

Set up a service using caddy as a reverse proxy, that can serve compressed content. Don't enable compression in caddy, but otherwise use it as a reverse proxy. You should get responses with curl, that have the gzip header but are not gzipped. I noticed it with a matrix-synapse server with `compress: true` in the config.

Sadly this is not my system and I have no control over it. I just noticed the issue and added a workaround to my matrix client. The actual owner doesn't care that much about the bug and it may even be fixed in caddy v2, but they don't want to further debug the issue :/

This bug is more here to document my issues instead of silently working around them. I don't think I can provide that many log or environment information easily.

**Comment by mholt** [comment] 2020-07-04 00:03
Thanks for opening an issue! We'll look into this.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by deepbluev7** [comment] 2020-07-05 21:52
I've extended the description as good as I could. Sadly it is not my system, so getting the necessary info is quite a bit of effort. I hope this helps!

(Btw, adding that template as an issue template may be helpful.)

**Comment by mholt** [comment] 2020-07-05 22:31
Oh, you're using Caddy 1.0. Caddy 1 is no longer actively developed. Please upgrade to Caddy 2 and let us know if the problem still occurs. But if you do, please fill out the whole template, so we can fix anything.

**Closed by mholt** 2020-07-05 22:31 UTC
Labels: needs info
